### ISSUE TITLE
Cоздать кастомную игру с двумя выбранными игроками.

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#1038]
Пользователям с расширенным доступом можем дать возможность создавать кастомные игры и выбрать двух противников, которые должны будут сражаться. Ребята получат инвайты на это событие, после того, как оба подтвердят участие, начнется игра.
К ней стоит приступить, когда будут готовы расширенные возможности по настройке игр: ограниченный набор языков и выбор конкретной задачи.

**Comment by Stonek79** [comment]
Беру в работу

**Comment by vtm9** [comment]
я думаю, что нынешняя система инвайтов вполне может с этим справится
пока закрою ПР
