### ISSUE TITLE
Сделать hash параметр в  url для того чтобы давать ссылку на список туниров

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#1060]
Сделать привязку hash параметров в url  к открывающимся табам

`http://localhost:4000/#tournaments`

чтобы можно было удобнее делиться ссылками и при перезагрузке страницы она сохраняла вкладку
 
пока есть три вкладки:

lobby, completedGames, tournaments

**Comment by avshukan** [comment]
Я только начинаю учить React и ещё не сделал ни одного пул-реквеста.
Хочу попробовать закрыть этот Issue. С кем можно консультироваться?
