### ISSUE TITLE
Находясь в команде на турнире переместиться в другую по 1 клику

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#1085]
Нельзя перейти в другую команду, нажав жоин, если находишься уже в другой команде
Сначала нужно нажать Leave потом Join
![image](https://user-images.githubusercontent.com/697178/145860531-20e1ff92-db23-4cbb-ac6d-b0f99e457ec7.png)

**Comment by vtm9** [comment]
это баг, надо пофиксить на беке
