### ISSUE TITLE
Добавить номера игроков на страницу турнира

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#1100]
На странице турнира перед началом есть список игроков, но не написан номер игрока.
Чтобы подсчитать колво игроков, нужно вручную по ним пройтись.
При этом в списке Indent Players номера игроков есть.
(у меня был скрин, но я не успел сохранить его)

**Comment by vtm9** [comment]
спасибо, уже работаем над этим

**Comment by vtm9** [comment]
думаю что мы это сделаем в реактовской версии, старая пока deprecated
