### ISSUE TITLE
Я больше не могу войти в какую-либо игру

### ISSUE THREAD

**Issue by Layerex** [hexlet-codebattle/codebattle#1110]
После нескольких игр я больше не могу ни принять инвайт, ни создать новую игру, ни зайти в игру с ботом. При попытке зайти в игру с ботом появляется сообщение как здесь: 

![screen](https://user-images.githubusercontent.com/59440032/173888386-813c832a-0fbe-4a5f-b677-49ee918440db.png)

Расширение показывает следующее:

![image](https://user-images.githubusercontent.com/59440032/173888484-f6babc49-e7c5-49a5-b767-917876d5d12a.png)

У того, с кем я играл (@kxyzd), такая же проблема.

**Comment by Layerex** [comment]
ID игры на скрине - 80632

![image](https://user-images.githubusercontent.com/59440032/173888933-e32a1925-b2e1-4375-82e6-65ac47f8a6fd.png)

[Страница игры](https://codebattle.hexlet.io/games/80632):

![image](https://user-images.githubusercontent.com/59440032/173889165-41d3767a-6cb9-4ca7-933d-4410250747f4.png)

**Comment by Layerex** [comment]
А сегодня всё заработало

**Comment by avshukan** [comment]
У меня на днях была такая же проблема.
Как вариант - добавить кнопку типа "выйти из всех игр"

**Comment by vtm9** [comment]
sorry, мы уже пофиксили это костылем, на подходе большой патч, который это все фиксит
