### ISSUE TITLE
Исправить баг с проверкой результатов

### ISSUE THREAD

**Issue by ic-it** [hexlet-codebattle/codebattle#1119]
Я выбился в топ 1, думаю вы заметите, что не так.
Писал этот текст:
```py
##############
# FIX IT !!! #
##############


class EzWin(int):
    def __init__(self): ...
    def __eq__(self, other): return True


def solution(*a, **kw):
    return EzWin()
```

Проблема заключается в том, что проверка на валидность ответа — сломана. 
Вариант решения: 
При проверке результата функции использовать что-то вроде:
`json.loads(json.dumps({"res": solution(*args)})).get("res")`

**Comment by vtm9** [comment]
привет, пофиксили, спасибо

**Comment by vtm9** [comment]
обновил рейтинг)

**Comment by ic-it** [comment]
Эх, уже не первое место XDD
