### ISSUE TITLE
Добавить бесконечный скролл для Completed Games на главной странице

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-codebattle/codebattle#1122]
У нас есть бесконечный скрол в completed_games в профиле пользователя (https://codebattle.hexlet.io/users/1), нужно сделать такой же на главной странице в разделе completed games
![image](https://user-images.githubusercontent.com/77053797/187164526-a21a6889-f2ec-46f1-9479-9e549220e385.png)

**Comment by CryFromTheHeart** [comment]
задача уже выполнена?  
![image](https://user-images.githubusercontent.com/67069570/188619503-48667e45-e419-4243-a1ca-f5ad5aa32b26.png)

**Comment by CryFromTheHeart** [comment]
не смог сделать

**Comment by Nesaq** [comment]
Я покупаюсь , отпишусь я если не смогу )

**Comment by Guryanov-Maksim** [comment]
Добавил ветку https://github.com/hexlet-codebattle/codebattle/tree/infinite-scroll, в котороя реализовал бесконечный скролл. Посмотри, пожалуйста, кто может.

**Comment by Guryanov-Maksim** [comment]
Если такая реализация подходит, то еще тесты добавлю.
