### ISSUE TITLE
Исправить url 

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-codebattle/codebattle#1123]
При заходе на главную страницу у нас показывается все три контейнера сразу(lobby, tournaments, completed_games)
после нажатия на lobby, в url подставляется #lobby hashTag. и показывается только лобби. Надо сделать так чтобы #lobby был по дефолту, если его нет в URL, то фронтенд сам его туда пририсовывает и показывает лобби по умолчанию
![image](https://user-images.githubusercontent.com/77053797/187402828-17291e32-e15b-4c9b-aa3e-cd8167619816.png)
![image](https://user-images.githubusercontent.com/77053797/187402844-e57235b9-a853-435d-97fc-3d9a0878f73c.png)

**Comment by kasapvictor** [comment]
Взял в работу
