### ISSUE TITLE
Алиасы и группировка import/export

### ISSUE THREAD

**Issue by kasapvictor** [hexlet-codebattle/codebattle#1126]
Пути не разбиты на группы и не имеют алиасов

- [ ] Настроить алиасы через `jsonconfig.js`
- [ ] Добавить и настроить правило в ESLint для группировки импортов

Пример как можно разбить на группы

<img width="539" alt="01-09-2022-11-31-34-PhpStorm" src="https://user-images.githubusercontent.com/73124371/187869943-a6b263b3-7959-4a50-bc72-8a874c99742e.png">

**Comment by acidmaksim** [comment]
@vtm9 чекни, пожалуйста правильно ли описана задача

**Comment by ReDBrother** [comment]
Не мы отказались от всякого рода группировок. Мы уже устали постоянно спорить куда к кому определять, еще когда думали по папкам раскидывать. У нас нет никакого формального разделения и не будет(

**Comment by kasapvictor** [comment]
Алиасы могут помочь решить споры, т.е группировать не по вложенности, а по типам

**Comment by vtm9** [comment]
в целом мне кажется это не то что сейчас супер актуально для проекта, но я не фронтендер.
Иногда при сильно спорных вопросах, мы открываем дискуссию в слаке и взвешиваем за и против.
Но ично мне кажется, что это не сильно важно. За фронтенд у нас отвечает @ReDBrother , и иногда помогает @imamatory 
Думаю решение принимать тут им

**Comment by imamatory** [comment]
Мне кажется, гораздо более полезным будет создание фасада для импортов т.е. index.js файлы в папках с компонентами и контейнерами, которые экспортируют все компоненты и позволяют импортировать из одной точки. Содержат примерно такой код
```
export { MyComp } from './MyComp/MyComp.js
...
```
И в компонентах при использовании можно импортировать все под и один импорт `import { A, B } from '../components'

**Comment by kasapvictor** [comment]
фасад хорошая идея но не спасет от вложенностей и не группирует импорты, вообще к этой задаче если добавить фасад то будет красота 😄 
это не супер актуально может быть, но воспринимать такое однозначно легче будет 😄
