### ISSUE TITLE
Починить убивалку контейнеров

### ISSUE THREAD

**Issue by solar05** [hexlet-codebattle/codebattle#1131]
Перестали подчищаться подвисшие докер образы, нужно разобраться почему

https://hexlet-ru.slack.com/archives/C09FRNPC4/p1662208313715069

**Comment by solar05** [comment]
Судя по названиям контейнеров, слетело проставление тегов, скорее всего из-за этого генсервер докеровский не видит контейнеры

**Comment by solar05** [comment]
После крупного апдейта вроде как все стабилизировалось, нужно будет еще понаблюдать, сохраняется ли баг

**Comment by vtm9** [comment]
thx
