### ISSUE TITLE
Поправить размер иконок достижений

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#1135]
<img width="236" alt="Screen Shot 2022-09-07 at 16 20 21" src="https://user-images.githubusercontent.com/24855537/188889136-696bd2b4-22ae-40b5-b8bf-be370ec2458b.png">

Увеличить и выровнять все размеры иконок. Эту плашку можно увидеть при наведении мышки на пользователей.

**Comment by semyonsurkov** [comment]
Взял в работу

**Comment by semyonsurkov** [comment]
Подскажите, пожалуйста, какой размер нужен? На сколько необходимо "увеличить"?

**Comment by MONDAYMIND** [comment]
Беру в работу

**Comment by ReDBrother** [comment]
> Ознакомился со структурой проекта и понял, что пока и такую простую задачу закрыть не смогу. Даже найдя в css - файлах нужные объекты. Вынужден на данный момент отказаться от выполнения этой задачи.

Всегда можно будет вместе засесть и посмотреть. Никто не ожидает, что вы будете сходу разбираться в громадных проектах, как этот. Без человека, который будет вашим гидом это очень тяжело и опасно)

**Comment by semyonsurkov** [comment]
> Всегда можно будет вместе засесть и посмотреть. Никто не ожидает, что вы будете сходу разбираться в громадных проектах, как этот. Без человека, который будет вашим гидом это очень тяжело и опасно)

Получается в следующий раз лучше писать в комментариях, если возникнут сложности?)

**Comment by ReDBrother** [comment]
В комментах, в слаке - везде)

**Comment by semyonsurkov** [comment]
Понял, спасибо!
