### ISSUE TITLE
Кнопка "Вызвать на дуэль" в общем чате

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#1136]
По нажатию на "create a game" в режиме "With a friend" мы можем вызывать на дуэль противников.
<img width="596" alt="Screen Shot 2022-09-07 at 15 26 08" src="https://user-images.githubusercontent.com/24855537/188890143-dc82053a-4129-45c0-be10-b93d43f35a55.png">

В лобби есть общий чат. Нужно добавить экшен, который откроет этот диалог и предзаполнить его (в селекторе будет выбранный соперник)

<img width="543" alt="Screen Shot 2022-09-07 at 15 27 38" src="https://user-images.githubusercontent.com/24855537/188890169-443bed9d-a3de-42bf-8cb3-c8d7ba1f20ff.png">

1) Добавить кнопку (Иконку скрещенных мечей, как в нотификациях в хедере) в чат, который открывает предзаполненный диалог. Можно повесить на каждое сообщение пользователей (На картинке, возле кнопки "ban")

<img width="90" alt="Screen Shot 2022-09-07 at 16 27 12" src="https://user-images.githubusercontent.com/24855537/188890610-9045bc5e-b4b8-46d0-b185-ac00df9b0483.png">

2) Она должна быть недоступна, если у вас уже есть активная или созданная игра в списке active games или если пользователь, это вы. Кнопку не нужно скрывать, а сделать ее disable.

**Comment by vtm9** [comment]
я думаю что это надо сделать не в чате, а в поповере игрока

**Comment by vtm9** [comment]
я думаю что это надо сделать не в чате, а в поповере игрока

**Comment by niyak93rus** [comment]
взял в работу

**Comment by CryFromTheHeart** [comment]
взял в работу
