### ISSUE TITLE
Safari — редактор кода не отображается

### ISSUE THREAD

**Issue by faciledictu** [hexlet-codebattle/codebattle#1143]
Safari version 15.6.1 on macOS 12.5.1

**Comment by faciledictu** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/104712148/189949875-eed400a4-ee72-45da-b245-9fc0724ac6c8.png">

**Comment by seth2810** [comment]
Кроме этого в лобби не работает кнопка присоединения к битве.
