### ISSUE TITLE
Задача split_names не проходит проверку тестами

### ISSUE THREAD

**Issue by LarendsD** [hexlet-codebattle/codebattle#1146]
Не проходит как и у меня, так и у бота:
![изображение](https://user-images.githubusercontent.com/84834138/190118642-40869528-f2c7-4162-8237-67edea853995.png)
Вывод тестов и у меня и у бота:
![изображение](https://user-images.githubusercontent.com/84834138/190118832-895cf121-cba7-43a1-be97-462811f09f39.png)

**Comment by ReDBrother** [comment]
@vtm9 Проверка 2.0 крашиться на не примитивных данных

**Comment by vtm9** [comment]
done
