### ISSUE TITLE
Верное решение не совпадает с условием задачи

### ISSUE THREAD

**Issue by kanigreg** [hexlet-codebattle/codebattle#1173]
![изображение](https://user-images.githubusercontent.com/41334863/197394197-16f91d06-d1c1-489d-9f1b-86c1a74e7653.png)

**Comment by solar05** [comment]
Привет! В задаче же написано, что нужно проверить, равен ли квадратный корень первого числа кубическому корню второго, а в решении числа возводятся в степень и проверяются на равенство, что не соответствует условию задачи.
