### ISSUE TITLE
Подключить i18n для javascript

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#118]
Нужно подключить [i18n](https://www.i18next.com/), чтобы слова в js коде при загрузке страницы (например, `joined channel`) менялись в соотвествии с языком пользователя.

**Comment by imamatory** [comment]
Я вижу реализацию так:
* Используется [i18next](https://www.i18next.com/).
* В сборку js подгружаются файлы локализации при помощи [i18next-po-loader](https://github.com/queicherius/i18next-po-loader)
* Текущая локализация прокидывается с бекенда с помощью [gon](https://github.com/khusnetdinov/phoenix_gon)

**Comment by PeresvetS** [comment]
Closed #145
