### ISSUE TITLE
Не работает привязка Discord в личном кабинете

### ISSUE THREAD

**Issue by kaziamov** [hexlet-codebattle/codebattle#1195]
![image](https://user-images.githubusercontent.com/99541755/209007770-cc253e09-b058-445f-9ff9-c60107abb877.png)

**Comment by MariaLishchuk** [comment]
Баг воспроизвелся
ПК
Google Chrome 108.0.5359.125 (Официальная сборка) (64 бит)
ОС Windows 10 19045.2364

**Comment by ReDBrother** [comment]
fixed
