### ISSUE TITLE
Убрать артефакт, возникающий при наведении на кнопку Sign in

### ISSUE THREAD

**Issue by Shamilist** [hexlet-codebattle/codebattle#1200]
![Наведение](https://user-images.githubusercontent.com/62985728/210764362-9ea1e725-b5b4-47fb-8a3d-d0a2a4bf1fcc.png)

**Comment by Shamilist** [comment]
Взял в работу.

**Comment by Shamilist** [comment]
Отправил PR

**Comment by mx3drive** [comment]
Артефакт остался:

 - Навести на "Sign in"

ОС:
Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎10.‎02.‎2023
Сборка ОС 22621.1265
Взаимодействие Windows Feature Experience Pack 1000.22638.1000.0

Браузер:
Яндекс Браузер Версия 23.1.4.778 (64-bit)

![image](https://user-images.githubusercontent.com/119818671/225050517-0da47e5a-af5f-4938-9231-413e19599691.png)

**Comment by kos342** [comment]
Артефакт остался
_Environment:_
Windows 11 Pro Version 22H2 OS build 22621.1555
Google Chrome Version 112.0.5615.121 (Official Build) (64-bit)

**Comment by Romul76** [comment]
Артефакт остался

Environment:
Windows 10 
Firefox 112.0.2 (64-bit)

**Comment by katrytikova** [comment]
Артефакт остался
Google Chrome 113.0.5672.126 (Официальная сборка), (arm64)
macOS Ventura 13.1
<img width="689" alt="Снимок экрана 2023-05-24 в 14 40 41" src="https://github.com/hexlet-codebattle/codebattle/assets/122362310/3750ebbc-3fa9-40bc-a7b8-b4421ac8601c">
