### ISSUE TITLE
no indent tabs for specific languages

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#1203]
Некоторые ЯП используют по стандарту пробелы в отступах, а не табы.

Например сейчас JS (Nodejs) содержит табы, если использовать отступы. 
Так не должно быть, потому что по по стандарту airbnb например используются 2 пробела.

**Comment by Guryanov-Maksim** [comment]
Привет! В принципе я могу добавить эту опцию аналогично. Вопрос в том, что делать с кодом, который приходить с бекенда при первой загрузке. Его нужно парсить и заменять табы на пробелы?

**Comment by fey** [comment]
по идее этот код должен иначально приходить верным

**Comment by Guryanov-Maksim** [comment]
Если так, то это облегчает задачу, звучит почти как copy/paste. @vtm9, что скажешь по поводу бекенда?

**Comment by solar05** [comment]
Поправил, теперь с бека код приходит без табов 👌

**Comment by Guryanov-Maksim** [comment]
Спасибо, я займусь фронтендом
