### ISSUE TITLE
Ошибка авторизации через Discord

### ISSUE THREAD

**Issue by GeeksterVALO** [hexlet-codebattle/codebattle#1215]
### Summary

При подтверждении авторизации через аккаунт Discord появляется ошибка

### Reproduction steps

```bash
1. Открыта страница логина https://codebattle.hexlet.io/session/new?locale=en&next=%2F
2. Нажать "Sign in with Discord"
3. На редиректе Discord нажать "Авторизовать"
```

### Expected result

Успешная авторизация через аккаунт Discord

### Actual result

URL: [https://codebattle.hexlet.io/auth/discord/callback?code=laiLxJ3N8kCyO6p1xPGEUtr6oQWwaD&state=ksz_HTiQkIkmFxdcqnJqO8Zg](https://vk.com/away.php?to=https%3A%2F%2Fcodebattle.hexlet.io%2Fauth%2Fdiscord%2Fcallback%3Fcode%3DlaiLxJ3N8kCyO6p1xPGEUtr6oQWwaD%26state%3Dksz_HTiQkIkmFxdcqnJqO8Zg&cc_key=)
`SOMETHING_WENT_WRONG, reason: %OAuth2.Error{reason: "Server responded with status: 401\n\nHeaders:\n\ndate: Mon, 23 Jan 2023 16:44:25 GMT\ncontent-type: application/json\ncontent-length: 27\nconnection: keep-alive\ncache-control: no-store\npragma: no-cache\nwww-authenticate: Basic error=\"invalid_client\", error_description=\"\"\nset-cookie: __dcfduid=320ee90e9b3d11edbdb10610cd934591; Expires=Sat, 22-Jan-2028 16:44:25 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/\nstrict-transport-security: max-age=31536000; includeSubDomains; preload\nvia: 1.1 google\nalt-svc: h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400\ncf-cache-status: DYNAMIC\nreport-to: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=aoGP0EtL%2FBl4nUkJW0xEOyV7Qi0xJZDYsc7e1hQMT4r6nZCVshR8m88TFj2p9cZmHG3d%2FGCuU%2FtiyuwPMUzcN7KZEimgI4agEGqemj0LfqhLijm8ZzEQpF%2FcLG9K\"}],\"group\":\"cf-nel\",\"max_age\":604800}\nnel: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\nx-content-type-options: nosniff\nset-cookie: __sdcfduid=320ee90e9b3d11edbdb10610cd934591b12f4e386c38d46df46930aa213483268006bc9d71eac423caf6ec5b7b224c2c; Expires=Sat, 22-Jan-2028 16:44:25 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/\nset-cookie: __cfruid=5c6e56e9bc9fcdf8f8482efa06af45587fec1402-1674492265; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None\nserver: cloudflare\ncf-ray: 78e1fe71fcbcb8be-AMS\n\nBody:\n\n%{\"error\" => \"invalid_client\"}\n"}`

![Screenshot (33)](https://user-images.githubusercontent.com/122525465/214102473-95902b4e-3cc3-402c-9c14-72efb45a64b5.png)

### Browsers

Chrome Версия 109.0.5414.75 (Официальная сборка), (64 бит)

### OS

Windows 10

**Comment by GeeksterVALO** [comment]
Ситуация воспроизвелась и на Firefox

**Comment by Shnitkin** [comment]
Баг воспроизвёлся и на
Microsoft Edge
Версия 109.0.1518.70 (Официальная сборка) (64-разрядная версия)
Windows 10

**Comment by 2KO1** [comment]
Баг воспроизвелся.
Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)
Opera Версия 94.0.4606.76

**Comment by AnnaTerekhina93** [comment]
Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
OS:
Windows 10 64-разрядная операционная система, процессор x64

**Comment by MariaLishchuk** [comment]
Баг воспроизвелся
ПК
Google Chrome 108.0.5359.125 (Официальная сборка) (64 бит)
ОС Windows 10 19045.2364

**Comment by Salivya** [comment]
Баг НЕ воспроизвелся, авторизация пройдена 

Safari Версия 16.1 (18614.2.9.1.12)
macOS Ventura Версия 13.0 (22A380)

  prerequisites:
    Открыта страница: https://codebattle.hexlet.io/session/new?locale=en&next=%2F
    Должен быть выполнен вход в аккаунт в Discord
  steps:
    - Нажимаем на кнопку sign in with Discord
    - Нажимаем на кнопку Авторизовать 
  expected-result: |
    Пользователь авторизован в приложении
