### ISSUE TITLE
Bug: Залипание текста сообщения в чате после отправки на странице "tournaments".

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1223]
### Summary

После написания сообщения в чате, при отправке кнопкой "Enter", сообщение отправляется в чат, а также остается в текстовом поле чата. При этом отправка сообщения через нажатие кнопки "Send" такой проблемы не вызывает.
![image](https://user-images.githubusercontent.com/102296858/215208173-2afdc6a1-df34-462f-8f95-0ab5ed15f933.png)

### Reproduction steps

```bash
- Авторизоваться в CodeBattle
- Перейти на страницу турниров (https://codebattle.hexlet.io/tournaments)
- Нажать кнопку "Show" рядом с любым турниром
- Написать сообщение в текстовое поле
- Нажать кнопку "Enter"
```

### Expected result

- Сообщение отправится в чат
- Сообщение пропадет из текстового поля

### Actual result

- Сообщение отправится в чат
- Сообщение не пропадет из текстового поля

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by denkrasotkin** [comment]
Воспроизводится ошибка на:
![safary comment](https://user-images.githubusercontent.com/121078808/217155783-2c7f811e-09b7-4ab4-b29c-8a1b6d09ad38.jpg)

Safary 16
macOS Ventura 13.2
