### ISSUE TITLE
Bug: Некорректное отображение номера строки в игре.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1228]
### Summary

При достижении количества строк 99, трехзначные номера строк в игре начинают некорректно отображаться, из-за слияния последней и предпоследней цифры.
Возможно связано с шириной столбца отображения цифр.

![image](https://user-images.githubusercontent.com/102296858/215268358-d332a081-95c3-492d-ac9e-619d506a71a3.png)

### Reproduction steps

```bash
- Начать игру (вне зависимости от авторизации пользователя)
- Зажать кнопку "Enter" до появления номеров строк с трехзначными числами
```

### Expected result

Номера строк отображены корректно

### Actual result

Номера строк отображены не корректно

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
 Разрешение дисплея 2560х1600

2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)
Разрешение дисплея 1920х1080

**Comment by vtm9** [comment]
Спасибо. Думаю надо попробовать обновить monaco и посмотреть что будет

**Comment by ReDBrother** [comment]
fixed
