### ISSUE TITLE
Bug: Отсутствие переноса символов отправленных подряд без пробелов в чате на главной странице "lobby".

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1229]
### Summary

В чате главной страницы, при введении подряд символов без пробелов и переносов на новую строку, сообщение автоматически не переносится на новую строку, из-за чего чтобы прочитать данное сообщение нужно двигать ползунок вправо.

![image](https://user-images.githubusercontent.com/102296858/215269088-946a5068-8970-4501-98df-fe3ed563f685.png)
![image](https://user-images.githubusercontent.com/102296858/215269104-5b2e5de8-fe31-4786-a25c-e6c9e34be092.png)

### Reproduction steps

```bash
- Авторизоваться в приложении CodeBattle
- Нажать на текстовое поле чата главной страницы "lobby"
- Ввести текст без пробелов, до момента выхода его за рамки текстового поля чата
```

### Expected result

Текст автоматически переносится на новую строку сохраняя границы чата.

### Actual result

Текст не переносится на новую строку и уходит за пределы границы чата.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Разрешение дисплея 2560х1600

2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)
Разрешение дисплея 1920х1080

**Comment by AnnaTerekhina93** [comment]
Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
OS:
Windows 10 64-разрядная операционная система, процессор x64

**Comment by denkrasotkin** [comment]
Ошибка воспроизводится на: 
Safary 16
macOS Ventura 13.2
![safary перенос](https://user-images.githubusercontent.com/121078808/217157051-f6f47696-630b-457b-88ac-3cf3bbdd890b.jpg)

**Comment by RemoSet** [comment]
Тест проходит. Ошибка не воспроизводится.

OS 22000.1219 Windows 11 Версия 21H2
Web browser Google Chrome Версия 108.0.5359.100
    
***
- Открыта главная страница, вкладка "LOBBY"
- Вводим текст без пробелов, до момента выхода его за рамки текстового поля чата
- Нажимаем кнопку "Send"
***
Текст автоматически переносится на новую строку сохраняя границы чата.

![issues 1229](https://user-images.githubusercontent.com/117320009/220281174-5377bacb-2df9-4675-ae0c-a039fa56c9c1.png)
