### ISSUE TITLE
Bug: Отсутствие переноса символов отправленных подряд без пробелов в чате игры.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1230]
### Summary

В чате игры, при введении подряд символов без пробелов и переносов на новую строку, сообщение автоматически не переносится на новую строку, из-за чего чтобы прочитать данное сообщение нужно двигать ползунок вправо.

![image](https://user-images.githubusercontent.com/102296858/215269634-2ff4273a-ef26-40a8-9c22-0a65ff35d475.png)
![image](https://user-images.githubusercontent.com/102296858/215269640-37096e2b-bcfa-4b92-8392-f1b6d670c7cd.png)

### Reproduction steps

```bash
- Начать игру
- Нажать на текстовое поле чата игры
- Ввести текст без пробелов, до момента выхода его за рамки текстового поля чата
```

### Expected result

Текст автоматически переносится на новую строку сохраняя границы чата.

### Actual result

Текст не переносится на новую строку и уходит за пределы границы чата.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Разрешение дисплея 2560х1600

2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)
Разрешение дисплея 1920х1080

**Comment by AnnaTerekhina93** [comment]
Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
OS:
Windows 10 64-разрядная операционная система, процессор x64
