### ISSUE TITLE
Bug: Не отображается аватар пользователя(авторизованного через email и password) в списке участников турнира.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1231]
### Summary

Если присоединиться к турниру, то на странице турнира, в списке игроков не отображаются аватары пользователей авторизованных через email и password. Аватары участников авторизованных через GitHub отображены корректно.

![image](https://user-images.githubusercontent.com/102296858/215272512-3ada621b-4fec-494b-892f-3872191a9a6b.png)

### Reproduction steps

```bash
- Авторизоваться в приложении CodeBattle
- Открыть меню
- Нажать кнопку "tournaments"
- Нажать кнопку "Show" у турнира к которому можно присоединиться
- Нажать кнопку "Join"
```

### Expected result

- Пользователь присоединился к турниру
- Иконка аватара в списке участников турнира отображена корректно

### Actual result

- Пользователь присоединился к турниру
- Иконка аватара в списке участников турнира отображена некорректно

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by denkrasotkin** [comment]
Иконки отображаются в виде знака вопроса. 
Safary 16
macOS Ventura 13.2
![safary icons](https://user-images.githubusercontent.com/121078808/217158080-0fffb5a9-13c4-4a50-be4d-e56b87c980f4.jpg)

**Comment by ReDBrother** [comment]
Добавим дефолтную иконку

**Comment by ReDBrother** [comment]
Убрали картинки вовсе)
