### ISSUE TITLE
Bug: Отсутствие перевода "Guide" на русский язык при смене языка отображения.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1234]
### Summary

На данный момент при смене языка имеется перевод задания, на мой взгляд также требуется перевод "Guide" для новичков, для более быстрого понимания интерфейса игрового процесса.

![image](https://user-images.githubusercontent.com/102296858/215860524-5a5dff5f-b9fe-4a8f-a032-f876570246d1.png)

### Reproduction steps

```bash
- Нажимаем кнопку "Try simple battle"
- Нажимаем кнопку "Show guide"
- Нажимая кнопку "Next" проверяем контент всех 8ми шагов "guide"
```

### Expected result

"Guide" отображен на русском языке при языковом "Select" = "RU"

### Actual result

"Guide" отображен на английском языке при языковом "Select" = "RU"/"EN"

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by AlenaSup** [comment]
Баг подтверждается:
![Снимок экрана (173)](https://user-images.githubusercontent.com/122166113/223185431-f90d4550-1a15-457e-8585-ab58349b703f.png)
Окружение: Windows 10 Pro Версия 21H2, Opera Browser версия 95.0.4635.46

**Comment by mx3drive** [comment]
Баг подтверждается:

- Нажимаю кнопку "Try simple battle"
- Выбираю язык RU из выпадающего списка
- Нажимаю "Show Gide" 
- Далее 8 раз нажимаю "Next" и есть только гайд на английском языке.

Выпуск	Windows 11 Домашняя для одного языка
Версия	22H2
Дата установки	‎10.‎02.‎2023
Сборка ОС	22621.1265
Взаимодействие	Windows Feature Experience Pack 1000.22638.1000.0
Яндекс Браузер Версия 23.1.4.778 (64-bit)

![image](https://user-images.githubusercontent.com/119818671/225039111-5274fe1a-9d21-4be8-b9b0-15ee3d4751a1.png)

**Comment by ReDBrother** [comment]
RU/EN переводит только текст задачи. Русской локализации всего интерфейса не будет
