### ISSUE TITLE
Bug: Нажатие кнопки "Х" 1ого шага "Guide" не сворачивает окно "Guide"

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1235]
### Summary

Нажатие кнопки "Х" 1ого шага "Guide" не сворачивает окно "Guide", а дублирует функцию кнопки "Next", при этом при наведении на кнопку "X" всплывает "tooltip" ="close"

![image](https://user-images.githubusercontent.com/102296858/215862153-e720db44-d279-4f0c-a7a8-26a6ce7c7876.png)

### Reproduction steps

```bash
- Нажимаем кнопку "Try simple battle
- Нажимаем кнопку "Show guide"
- Нажимаем кнопку "x"
```

### Expected result

Окно "guide" свернулось

### Actual result

Отображен 2ой шаг "guide", кнопка "x" на данном шаге дублирует кнопку "next"

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by 2KO1** [comment]
Также есть предложение касательно остальных шагов инструкции, при нажатии на "х" остальные шаги сворачиваются в круглую мигающую кнопку, и при этом, чтобы опять открыть шаг инструкции, нужно нажать на данную кнопку. В этот момент нажатие на кнопку "Show guide" не работает. Было бы хорошо, чтобы и нажатие на кнопку "Show guide", тоже открывало инструкцию на месте на котором она была свернута.

**Comment by AlenaSup** [comment]
Баг подтверждается:

https://user-images.githubusercontent.com/122166113/223186345-020c1181-6398-45c5-9f1b-0bd9ad64b51f.mp4

Окружение: Windows 10 Pro Версия 21H2, Opera Browser 95.0.4635.46
