### ISSUE TITLE
Bug: Некорректная работа кнопки "х2" в настройках проигрывателя истории игры.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1236]
### Summary

При просмотре истории игры, нажав на кнопку "х2" в настройках просмотра, кнопка начинает отображаться синим цветом совместно с кнопкой "copy history game url", при этом нажатие на "copy history game url" не подсвечивает ее синим цветом. Повторное нажатие кнопки "х2" возвращает серый цвет обеих кнопок.

![image](https://user-images.githubusercontent.com/102296858/215865278-b7d70a66-9c57-42c5-87c0-b2fdd0936c7b.png)

### Reproduction steps

```bash
- Нажимаем кнопку "Open History"
- Нажимаем на кнопку "Шестеренка" проигрывателя
- Нажимаем кнопку "x2"
- Нажимаем кнопку "Play"
- Нажимаем на кнопку "Шестеренка" проигрывателя
```

### Expected result

При нажатии на кнопку "х2" данная кнопка становится отображена синим цветом, при повторном нажатии и возвращении к обычной скорости кнопка становится вновь серой

### Actual result

При нажатии на кнопку "х2" данная кнопка становится отображена синим цветом вместе с кнопкой "copy history game url",  при повторном нажатии и возвращении к обычной скорости обе кнопки становится вновь серыми.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by 2KO1** [comment]
Ошибка вновь отображается

**Comment by vtm9** [comment]
сan't reproduce. Looks like fixed
