### ISSUE TITLE
Bug: Некорректное отображение тестового сообщения при принятии запроса на "Rematch"

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1237]
### Summary

При запросе на "Rematch" противнику приходит оповещение с вариантом выбора ответа "yes"/"no" при этом сам запрос находится в текстовом поле, которое не реагирует на введение и отправку сообщения.

![image](https://user-images.githubusercontent.com/102296858/215868310-ff279e93-531c-45d1-95fc-cfbac59257b6.png)
![image](https://user-images.githubusercontent.com/102296858/215868361-613dc14a-ab9f-4c55-88e1-27facc917c80.png)

### Reproduction steps

```bash
- Создаем игру с другом
- Противник  сдается до завершения времени
- Нажимаем кнопку "x"
- Нажимаем кнопку "Rematch"
```

### Expected result

Текстовое поле не поддается изменению и несет информирующий функционал

### Actual result

Текстовое поле поддается изменению

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by AllIzm** [comment]
Баг воспроизводится

**Browsers**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) 
Mozilla Firefox 110.0.1 (64-разрядный)

**OS**
ОС Windows 11 22H2

**Comment by ReDBrother** [comment]
Мы избавимся от инпута. Теперь будут только кнопки подтверждения/отмены рематча
