### ISSUE TITLE
Bug: Ошибка 429 при закрытии нажатием на кнопку "х"  только что созданной игры с другими пользователями.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1238]
### Summary

При создании игры с другими пользователями, в разделе "lobby" главной страницы есть возможность нажать на кнопку "х" рядом с кнопкой "Continue". При нажатии на данную кнопку возникает ошибка 429. При перезагрузке страницы игра больше не отображена.

![image](https://user-images.githubusercontent.com/102296858/215870901-179978e7-f16b-4926-8332-907ef1263d7b.png)

### Reproduction steps

```bash
- Нажимаем кнопку "Create a game"
- Выбираем "level" = "4"
- Выбираем "Game Type" = "With other users"
- Выбираем "Time control" = "8"
- Выбираем "Tags" = "strings, rest"
- После создания игры нажимаем на кнопку "х" рядом с кнопкой "Continue"
```

### Expected result

Игра отменена и более не отображена.

### Actual result

Возникает ошибка. После перезагрузки страницы игра отменена и более не отображена.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by Guryanov-Maksim** [comment]
Исправлено в пр 1217
