### ISSUE TITLE
Bug: Ошибка подбора задания при создании игры с определенными параметрами.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1240]
### Summary

При создании игры с данными параметрами, подбирается игра с другими параметрами, при этом в "lobby" отображается выбранный нами уровень сложности.

Скорее всего дело в отсутствии игры с такими параметрами и уровнем сложности, и подбор игнорирует уровень сложности, но при этом возможность создания такой игры присутствует.

Параметры игры:
- Выбираем "level" = "4"
- Выбираем "Game Type" = "With a bot"
- Выбираем "Time control" = "3"
- Выбираем "Tags" = "strings, collections"

![image](https://user-images.githubusercontent.com/102296858/215874461-e80a185e-0bb2-4411-bba0-e19d2629324a.png)
![image](https://user-images.githubusercontent.com/102296858/215874506-520d15e2-6dfd-41e7-b665-23e7243fb638.png)
![image](https://user-images.githubusercontent.com/102296858/215874557-451d0fee-eab2-4dda-9ad0-5a4a6998cec0.png)

### Reproduction steps

```bash
- Создать игру с указанными параметрами.
```

### Expected result

Созданная игра соответствует выбранным параметрам.

### Actual result

Созданная игра не соответствует выбранным параметрам.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by denkrasotkin** [comment]
ошибка воспроизводится :
Safary 16
macOS Ventura 13.2
![2](https://user-images.githubusercontent.com/121078808/217159253-689f15ba-a571-4c64-b298-04127a44e6ac.jpg)
![3](https://user-images.githubusercontent.com/121078808/217159258-2f1ebbbe-b003-4f5f-89ee-84ac289151e4.jpg)

**Comment by Salivya** [comment]
Баг воспроизвелся

Safari Версия 16.1 (18614.2.9.1.12)
macOS Ventura Версия 13.0 (22A380)

<img width="1280" alt="Снимок экрана 2023-04-03 в 15 31 50" src="https://user-images.githubusercontent.com/119805947/229514632-9f41a9d6-6acc-488c-87e8-c6b97a09dbe5.png">
<img width="1280" alt="Снимок экрана 2023-04-03 в 15 32 32" src="https://user-images.githubusercontent.com/119805947/229514673-124f9cf4-c473-4931-b8cb-5efe7e7acfb7.png">

**Comment by ReDBrother** [comment]
Нужно отфильтровать список тегов в зависимости от выбранного уровня. Для простоты сейчас скинули все теги в кучу

**Comment by Anastasia-Kim3** [comment]
Ошибка воспроизводится 
Browser: Версия 115.0.5790.111 (Официальная сборка), (64 бит)
OS: Windows 10 22H2 19045.3208
Current version: fd71526

![image](https://github.com/hexlet-codebattle/codebattle/assets/133269405/c9762ca7-2393-4e93-b666-53449e88c704)
![image](https://github.com/hexlet-codebattle/codebattle/assets/133269405/37b77b5f-2be0-4d09-a56a-8f7f70e55370)

**Comment by Helga1503** [comment]
Баг воспроизводится
Браузер yandex версия 23.9.2.888 (64-bit)
ОС Windows 22H2

![Безымянный_3](https://github.com/hexlet-codebattle/codebattle/assets/143843782/d187153b-a12e-47d3-b74f-f2f5928657ff)
![Безымянный_4](https://github.com/hexlet-codebattle/codebattle/assets/143843782/7969bb02-0a4b-4325-8912-6d8fe81030df)
