### ISSUE TITLE
Bug: Ошибка отображения значка(иконки) языка Typescript.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1241]
### Summary

Язык "Typescript" и "Node.js" отображены одним значком "Select" выбора языка в игре, кроме того аналогичная ситуация в "lobby" в списке игроков онлайн, при этом в профиле пользователя значек отображен корректно.

![image](https://user-images.githubusercontent.com/102296858/216046765-a71d7d28-1cb7-41dd-b685-a4a9fee95edc.png)
![image](https://user-images.githubusercontent.com/102296858/216045063-0bc37331-fe13-4b74-b75c-57a17f2f1e83.png)
![image](https://user-images.githubusercontent.com/102296858/216045105-dd986e7e-ec42-4f17-9e48-9cb8a2db12e1.png)

### Reproduction steps

```bash
- Создать игру
- Нажать на "Select" выбора языка программирования
```

### Expected result

Значек языка "Typescript" отображен корректно

### Actual result

Языки "Typescript" и "Node.js" отображены одним значком

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by ReDBrother** [comment]
Мы можем данные текущей игры синхронизировать с чатом.
Для этого компонент с иконкой должен проверять данные редакторов (redux toolkit store) и для участников игры приоритетом должен быть язык, выставленные редакторами кода.

**Comment by ReDBrother** [comment]
Скорее это фича)
Мы используем библиотеку бесплатных иконок fontAwesome, у которых нет иконки с typescript. Сейчас мы ограничены ею.
