### ISSUE TITLE
Bug: Отображение приглашения у противника, после его отмены/"Cancel" пользователем.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1243]
### Summary

При отмене отправленного приглашения на игру, данное приглашение остается отображаться. 
Кроме того, его возможно принять и игра начнется. Отмененное приглашение перестает отображаться у другого пользователя, в случае обновления страницы или перехода на другую страницу.

### Reproduction steps

```bash
- Авторизоваться в приложении "CodeBattle"
- Отправить приглашение в игру
- Нажать на кнопку "Invites"
- Нажать кнопку "Cancel"
```

### Expected result

 - Отображен "tooltip" = "No invites" у обоих игроков
 - Рядом с кнопкой "Invites" не отображается тег количества приглашений "1" у обоих игроков
 - Приглашения в игру не отображены у обоих игроков

### Actual result

- Отображение приглашения прекращается, лишь у игрока его отменившего
- У пользователя получившего приглашение, оно отображено и функционирует 

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by EEMinch** [comment]
**- summary:** 
Отображение приглашения у противника после его отмены пользователем

**- environment:**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) – _пользователь EEMinch_
Mozilla Firefox 110.0 (64-разрядный) - _пользователь Mee_
ОС Windows 10

**- steps-to-reproduce:**
1. Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем
2. Прокрутить главную страницу до общего чата
3. Кликнуть иконку «Challenge to a game» напротив сообщения желаемого игрока в чате
![image](https://user-images.githubusercontent.com/120366598/221676220-9146cd40-3cd2-4137-96ab-f37923d28b08.png)

4. В модальном окне выбрать сложность, time-limit, Task
![image](https://user-images.githubusercontent.com/120366598/221676382-8497c159-86f1-4101-807b-c780b534cdea.png)

5. Нажать "Create Invite"
6. В верхнем правом углу нажать на кнопку «INVITES»
7. В выпадающем нотисе нажать кнопку «Cancel»
![image](https://user-images.githubusercontent.com/120366598/221676489-f6d56d4a-2a9f-4b67-b7da-f18ffda7c286.png)

8. Перезагрузить страницу

**- expected-result:** 
Приглашения в игру не отображены у обоих пользователей, т.е. у кнопки «INVITES» не отображен тег количества приглашений.

**- actual-result:**
У обоих пользователей отображены теги приглашений, при этом кнопки «Cancel» у пригласившего и «Decline» - у приглашенного — не отрабатывают

![image](https://user-images.githubusercontent.com/120366598/221677051-102626a7-84bf-49c7-95f7-2faeedc89fc1.png)

![image](https://user-images.githubusercontent.com/120366598/221676657-85835a3b-dafe-4cc3-8372-3dae7c9aae50.png)
