### ISSUE TITLE
Bug: Ошибка отображения вкладки "Weekly" в "User rating".

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1245]
### Summary

При переключении на вкладку "Weekly" в "User rating" отображается список пользователей вкладки "Weekly", но сама вкладка не переключается, а остается в "Monthly".

![image](https://user-images.githubusercontent.com/102296858/216326011-64138c31-e5a8-4078-963e-f2a805da08dd.png)
![image](https://user-images.githubusercontent.com/102296858/216326051-d9454902-7899-46b5-ac36-4f9a02fadfad.png)
![image](https://user-images.githubusercontent.com/102296858/216326107-cf2e82f9-8c61-44ba-87dd-f0ab077dd63b.png)

### Reproduction steps

```bash
- Открываем меню нажатием на "аватар"
- Нажимаем кнопку "Users rating"
- Нажимаем на раздел "Monthly"
- Нажимаем на раздел "Weekly"
```

### Expected result

Корректное отображение названия вкладки "Weekly".

### Actual result

Некорректное отображение названия вкладки "Weekly".

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by denkrasotkin** [comment]
ошибки нет на: 
![rating](https://user-images.githubusercontent.com/121078808/217160016-d90cf071-b171-47e9-8822-3a2840df6fbf.jpg)

Safary 16
macOS Ventura 13.2
