### ISSUE TITLE
Bug: Возможность создания турниров с одинаковыми названиями.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1247]
### Summary

Существует возможность создания турниров с одинаковыми названиями.

![image](https://user-images.githubusercontent.com/102296858/216367595-e6038946-df29-4343-959b-caef73ecb549.png)

### Reproduction steps

```bash
- Авторизоваться в приложении "Codebattle"
- Создать турниры с одинаковыми названиями
```

### Expected result

Отображение ошибки при создании второго турнира с идентичным названием.

### Actual result

Турнир создается и отображается

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by 2KO1** [comment]
В дополнение, при создании турнира если прописать название турнира с маленькой буквы, то после создания, просматривая данный турнир, название будет отображаться с заглавной буквы.

**Comment by AavadaKedavra** [comment]
Воспроизводится 

 prerequisites:
    Открыта главная страница https://codebattle.hexlet.io/
    Пользователь авторизован
  test-data: |
    Login = AvadaKedavra; Password = password
    Name tournament 1 = test; Type = individual; Access_type = token; Level = elementary;
    Default language = js; Match timeout = 177;
    Name tournament 2 = test;
  steps:
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
    - Нажать 'Create'
    - Перейти во влкадку tournaments https://codebattle.hexlet.io/tournaments
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
  result: |
    Два турнира с одинаковым названием успешно созданы

**Comment by ReDBrother** [comment]
Добавить на бекенд фильтрацию названий турниров

**Comment by Makarova94** [comment]
- summary: |
    У пользователей есть возможность создавать турниры c одинаковым названием 
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
    - Открыть главную страницу сайта
    - Нажать на иконку профиля
    - Нажать на кнопку "Tournaments"
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
    - Нажать 'Create'
    - Нажать на кнопку "Tournaments"
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
   
  expected-result: |
     Отображается ошибка при создании второго турнира с идентичным названием
  actual-result: |
    Два турнира с одинаковым названием успешно созданы

**Comment by ElenaRedkina89** [comment]
summary: 
У пользователей есть возможность создавать турниры c одинаковым названием

environment: 
Chrome 117.0.5938.134 (Официальная сборка), (64 бит)
Windows 10 Pro
Codebattle Current version: ef4c0b9

steps-to-reproduce: 

-Открыть главную страницу сайта
-Нажать на иконку профиля
-Нажать на кнопку "Tournaments"
-Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
-Нажать 'Create'
-Нажать на кнопку "Tournaments"
-Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными

expected-result: 
Отображается ошибка при создании второго турнира с идентичным названием

actual-result: 
Два турнира с одинаковым названием успешно созданы
![Возможность создания турниров с одинаковыми названиями#1247](https://github.com/hexlet-codebattle/codebattle/assets/139364594/19e9ca17-7ad7-4ab2-8fd1-746a543d346b)

**Comment by Mimicry56** [comment]
Воспроизводится

**environment:**
OS Windows 11 SE
Google Chrome Версия 118.0.5993.118 (Официальная сборка), (64 бит)
Codebattle Current version: 9500f74

**prerequisites:**
Открыта главная страница codebattle.hexlet.io. Пользователь авторизован

**test-data:**
Name = test1
    Type = individual
    Access type = token
    Description = Test tournament
    Task strategy = game
    Task provider = level
    Level = elementary
    Players limit = 64
    Default language = js
    Match timeout sec = 177
    Break duration sec = 42
    
**steps:**
    - Нажать на вкладку 'TOURNAMENTS'
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму Create a new tournament
    - Заполнить поле 'Name'в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Type' значение в соответствии с тестовым значением
    - Заполнить поле 'Description' в соответствии с тестовым значением
    - Убрать галочку с 'Radiobutton' 'Use chat'
    - Заполнить поле 'Starts at' сегодняшней датой и временем
    - Выбрать в выпадающем списке 'Access type' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Task strategy' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Task provider' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Level значение' в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Players limit' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Default language' значение в соответствии с тестовым значением
    - Ввести числовое значение в поле 'Match timeout sec' в соответствии с тестовым значением
    - Ввести числовое значение в поле 'Break duration sec' в соответствии с тестовым значением
    - Нажать 'Create'
    - Перейти во вкладку tournaments https://codebattle.hexlet.io/tournaments
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
    
**expected-result:**
Второй турнир не создан, отображается сообщение с информацией 'турнир с текущем названием уже активен'

**result:**
Созданы два турнира с одинаковым названием

**Comment by 12ILib05** [comment]
summary: |
    Возможно создать новый турнир с уже существующим названием.

  requirement: |
    Пользователь не сможет создать новый турнир с уже существующим названием.

  environment: |
    Google Chrome 119.0.6045.160 (Официальная сборка) (64 бит)
    ОС Windows 10

  test-data: |
    Name = Мой_турнир
    Description = Этот турнир должен быть единственный и неповторимый
    Tags = #всякиетеги

  steps:
    - Открываем меню
    - Нажимаем «Tournaments»
    - Переходим к форме «Create a new tournament»
    - Заполняем поле «Name» в соответствии с тестовыми данными
    - Выбираем в выпадающем списке «Type» значение «individual» 
    - Заполняем поле «Description» в соответствии с тестовыми данными
    - Заполняем поле «Starts at» актуальной датой турнира
    - Выбираем в выпадающем списке «Access type» значение  «token»
    - Выбираем в выпадающем списке «Task strategy» значение  «game»
    - Выбираем в выпадающем списке «Task provider» значение  «tags»
    - Выбираем в выпадающем списке «Level значение «elementary»
    - Заполняем поле «Tags» в соответствии с тестовыми данными
    - Выбираем в выпадающем списке «Players limit' значение «2»
    - Выбираем в выпадающем списке «Default language' значение «php»
    - Вводим 190 в поле «Match timeout sec» 
    - Вводим 50 в поле «Break duration sec» 
    - Нажимаем «Create»
    - Проходим еще раз по шагам и создаем второй турнир с таким же названием
    
  expected-result: |
    Пользователь должен получить сообщение об ошибке.

  actual-result: |
   Создается второй турнир с названием, которое уже было использовано. Оба турнира отображаются в таблице.
![Турниры](https://github.com/hexlet-codebattle/codebattle/assets/133352264/f258be93-e394-4644-84e6-fd464448cefa)

**Comment by Retroman95** [comment]
summary:
Создание турнира с прошедшей датой

environment:
Google Chrome Версия 123.0.6312.59 (Официальная сборка), (64 бит)
Mozilla Firefox Версия 124.0.1 (64-разрядный)
ОС Windows 10 Pro 19045.3930

Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/85a7a93e3da39e9b4d05a460667cbcd4aeb7f695

Prerequisites:
    Открыта главная страница https://codebattle.hexlet.io/
    Пользователь авторизован
steps-to-reproduce:
    Name tournament 1 = test; Type = individual; Access_type = token; Level = elementary;
    Default language = js; Match timeout = 177;
    Name tournament 2 = test;
  steps:](steps-to-reproduce:)
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
    - Нажать 'Create'
    - Перейти во влкадку tournaments https://codebattle.hexlet.io/tournaments
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными

![баг одинаковые названия](https://github.com/hexlet-codebattle/codebattle/assets/46816641/150a215f-1f2a-447f-b1e4-56b4b16970f4)

**Comment by vtm9** [comment]
Мы решили что названия турниров могут повторяться. Например мы хотим проводить ежемесячные турниры с однаковым названием
