### ISSUE TITLE
Bug: Отсутствует сообщение об ошибке при попытке смены "Nickname" на уже используемый.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1248]
### Summary

при попытке смены "Nickname" на уже используемый, отсутствует сообщение об ошибке, кроме того возникает ошибка "422"

![image](https://user-images.githubusercontent.com/102296858/216587219-7241943a-ca6e-4523-8ae5-a0ec1641d95b.png)

### Reproduction steps

```bash
- Авторизоваться в приложении "CodeBattle"
- Открываем меню нажатием на "аватар"
- Нажимаем кнопку "Settings"
- Вводим в текстовое поле "Your name" существующий "Nickname"
- Нажимаем кнопку "Save"
```

### Expected result

Отображено сообщение об ошибке

### Actual result

Какие-либо изменения не отображены

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by MariaLishchuk** [comment]
Баг воспроизвелся
Nokia 5.4
Microsoft Edge 109.0.1518.70
Android 11
