### ISSUE TITLE
Bug: Не работает турнир "Type" = "stairway".

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1250]
### Summary

Данная ошибка возникает после создания турнира с данными параметрами:
    - Название турнира = "скрытый турнир"
    - "Select" "Type" = "stairway"
    - "Select" "Access Type" = "token"
    - "starts at(utc)" = "сегодня"
    - "Task pack name" = "test1"
    - "Default language" = "java"
    - "Match timeout in seconds" = "100"

![image](https://user-images.githubusercontent.com/102296858/216605967-bbaa63df-d994-4748-bfd3-ed9bdc4e321f.png)

После старта:
![image](https://user-images.githubusercontent.com/102296858/216606032-c718ffd2-e4eb-42e5-896c-0d8a623d62e8.png)
После обновления страницы:
![image](https://user-images.githubusercontent.com/102296858/216606118-8b092c94-4271-48c7-b26a-efec2686c2ff.png)
![image](https://user-images.githubusercontent.com/102296858/216606151-949d2c97-d2ca-4165-b5a1-304a25fb90eb.png)
https://video.drift.com/v/absnN23s09T/

Используемый Task pack:
![image](https://user-images.githubusercontent.com/102296858/216606247-a3f63f24-99f3-44a4-b93c-fdec88fa2f15.png)
![image](https://user-images.githubusercontent.com/102296858/216606274-602412ba-3dac-47e6-85d6-e904b7b7ca3e.png)

Другим пользователям он не виден, завершить его невозможно.
Возможно удалить. Возможно сделать публичным.

### Reproduction steps

```bash
- Открываем меню нажатием на "аватар"
    - Нажимаем кнопку "Tournaments"
    - В текстовое поле "Name" вводим название турнира
    - Выбираем "Select" "Type"
    - Выбираем "Select" "Access Type" 
    - Выбираем "starts at(utc)"
    - Выбираем "Task pack name"
    - Выбираем "Default language
    - Прописываем "Match timeout in seconds"
    - Нажимаем кнопку "Create"
    - Нажимаем кнопку "Join"
    - Нажимаем кнопку "Promote"
    - Нажимаем кнопку "Join"
    - Отправляем ссылку на турнир другому пользователю для подключения
    - Ожидаем подключения
    - Нажимаем кнопку "Start"
```

### Expected result

Корректная работа турнира

### Actual result

Некорректная работа турнира

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by 2KO1** [comment]
"Access Type" = "public" при тех же параметрах, аналогично.

**Comment by 2KO1** [comment]
Запуски одним пользователем(создателем), "Access Type" = "public/token"  , аналогичный результат.

**Comment by vtm9** [comment]
stairway турнир был закрыт, так как теперь есть arena + swiss
