### ISSUE TITLE
Bug: Нет выбора языков для главной страницы

### ISSUE THREAD

**Issue by tramvaichik** [hexlet-codebattle/codebattle#1251]
### Summary

Нет кнопки с выбором языка для главной страницы

### Reproduction steps

```bash
1. Открыть главную страницу игры
2. Перейти в настройки в личном кабинете
3. Выбрать язык страницы
```

### Expected result

В настройках в личном кабинете будет кнопка / выпадающий список с языками 

### Actual result

В настройках в личном кабинете нет кнопки / выпадающего списка с выбором языка для страницы

### Browsers

Firefox, Chrome, Microsoft Edge

### OS

Windows

**Comment by Goryaminskaya** [comment]
Summary
Нет кнопки с выбором языка на главной странице https://codebattle.hexlet.io/

Reproduction steps
1. Открыть главную страницу игры
2. Перейти в настройки в личном кабинете
3. Нажать кнопку "Settings"
4. Выбрать язык страницы
Expected result
В настройках в личном кабинете будет кнопка / выпадающий список с языками

Actual result
В настройках в личном кабинете нет кнопки с выбором языка для страницы

Browsers
Opera Версия 95.0.4635.46
Яндекс версия 23.1.3.949 (64-bit)

OS
Windows

**Comment by MashaMelon** [comment]
- summary: 
    Нет фукционала переключения языков на главной странице
  environment: 
    Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
    Opera Версия:94.0.4606.38
    Yandex Версия 22.11.3.818 (64-bit)
    Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)
  steps-to-reproduce: 
    Открыть главную страницу
    Переключить язык с английского на русский
  expected-result: 
    Весь контент, кроме имен собственных переведет на русский
  actual-result: 
    Нет возможности переключения языка

**Comment by ipsdv** [comment]
summary:
Нет фукционала переключения языков на главной странице
environment:
Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Opera Версия:94.0.4606.38
Yandex Версия 22.11.3.818 (64-bit)
Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)
steps-to-reproduce:
Открыть главную страницу
Переключить язык с английского на русский
expected-result:
Весь контент, кроме имен собственных переведет на русский
actual-result:
Нет возможности переключения языка

**Comment by Nackles999** [comment]
summary:
Нет функционала переключения языков на главной странице
environment: 
Google Chrome 109.0.5414.75 (Официальная сборка), (64 бит)
OC Windows 10 21H2 64-bit
steps-to-reproduce:
- Открыть главную страницу сайта 
- Переключить язык с английского на русский 
expected-result:
Весь контент будет на переведён на русский язык 
actual-result:
Нет возможности переключения языка

**Comment by Salivya** [comment]
summary:
Не реализован функционал переключения языка интерфейса на главной странице
environment:
Safari Версия 16.1 (18614.2.9.1.12)
macOS Ventura Версия 13.0 (22A380)
steps-to-reproduce:
- Открыть главную страницу: https://codebattle.hexlet.io/#lobby 
- Изменить язык с английского на русский
expected-result:
Интерфейс переведен на русский язык
actual-result:
Не реализована возможность переключения на русский язык 

_*программа во многом направлена на русскоязычную аудиторию, без русской адаптации проект чуть менее интересен для начинающих программистов без должного уровня английского_

**Comment by sddanilin** [comment]
- summary: |
    Нет возможности перевода сайта на русский язык.
  environment: |
    Яндекс Браузер 22.11.5.715 (64-bit)
    ОС Windows 10 22H2 
  steps-to-reproduce: |
    1. Открыть главную страницу сайта
    2. Переключить язык с английского на русский
  expected-result: |
    Страница должна полностью переводиться на русский язык.
  actual-result: |
    Отсутствие данной функции в настройка сайта.

**Comment by glazovanastasia** [comment]
summary: |
    Сайт не является мультиязычным

environment: |
    Google Chrome  Версия 113.0.5672.127 (Официальная сборка), (64 бит)
    ОС Windows 11 Pro

steps-to-reproduce: |
  1. Открыть сайт [CodeBattle](https://codebattle.hexlet.io/)
  2. Переключить язык сайта на русский
  
expected-result: |
    Весь текст сайта, за исключением никнеймов пользователей, имеет корректный перевод, не изменяя смысл

actual-result: |
    Отсутствует функция перевода языка сайта

**Comment by ReDBrother** [comment]
Русской локализации не будет
