### ISSUE TITLE
Bug: не меняется язык задачи

### ISSUE THREAD

**Issue by AnnaTerekhina93** [hexlet-codebattle/codebattle#1253]
### Summary

в турнире не меняется язык в описании задачи с русского на английский.

### Reproduction steps

```bash
1. начать игру
2. нажать кнопку для выбора языка задачи
```

### Expected result

Должна быть возможность сменить язык задачи с русского на английский.

### Actual result

Язык задачи только на русском языке. 

### Browsers

Chrome

### OS

Windows

**Comment by AnnaTerekhina93** [comment]
![2023-02-04_16-24-31](https://user-images.githubusercontent.com/120126809/216772213-d57b098b-016b-47fa-8931-1eaeba788a68.png)

**Comment by ReDBrother** [comment]
Тут автоматический перевод браузера сыграла злую шутку. Мы не можем это контролировать никак)
