### ISSUE TITLE
Bug: не исчезает текст отправленного сообщения 

### ISSUE THREAD

**Issue by AnnaTerekhina93** [hexlet-codebattle/codebattle#1254]
### Summary

Не исчезает текст отправленного сообщения в чате турнира
![2023-02-04_19-10-09] 
![2023-02-04_19-32-52](https://user-images.githubusercontent.com/120126809/216776130-40bf1639-fbf2-4299-ac3b-d5d242652a42.png)

### Reproduction steps

```bash
1. Создаем турнир
2. пишем в чат сообщение 
3. Отправляем
```

### Expected result

Сообщение отправилось и исчез текст отправленного сообщения из окна для ввода сообщения

### Actual result

Сообщение отправилось , текст отправленного сообщения не исчез из окна для ввода сообщения

### Browsers

Chrome

### OS

Windows

**Comment by MariaLishchuk** [comment]
Баг воспроизвелся
iPad
Safari 15.7
iPadOS 15.7
