### ISSUE TITLE
Bug: Одновременное отображение в списке "Intended players" и "Players" в "Tournament"

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1256]
### Summary

- При создании турнира и присоединении к нему мы попадаем в список "Intended players", после нажатия на кнопку "Promote", появляется возможность вступить в список "Players" и новые пользователи присоединяющиеся к турниру, сразу попадают в данный список, но люди находившиеся в списке "Intended players" вступающие в список "Players" отображены в двух списках одновременно. 
- Создатель турнира не может использовать "Promote" не вступив в список "Intended players".
- Есть возможность создателю турнира выйти из списка "Intended players" и попасть только в список "Players". Для этого нужно после вступления в список "Players" нажать кнопку "Leave", а потом снова нажать кнопку "Join".

![image](https://user-images.githubusercontent.com/102296858/216778655-17415fec-4b66-47a0-8a46-b3876d75f622.png)
![image](https://user-images.githubusercontent.com/102296858/216778659-b497cb0e-4a7c-4717-87ca-799374ba90e0.png)

### Reproduction steps

```bash
- Авторизоваться в приложении "Codebattle"
- Создаем турнир
- Нажимаем кнопку "Join"
- Нажимаем кнопку "Promote"
- Нажимаем кнопку "Join"
```

### Expected result

После вступления в список "Players", пользователь не отображен в списке "Intended players"

### Actual result

После вступления в список "Players", пользователь до этого находящийся в списке "Intended players", отображен сразу в двух списках одновременно.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by ReDBrother** [comment]
Мы избавились от промежуточного списка
