### ISSUE TITLE
Bug: Создание турнира прошедшей датой.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1258]
### Summary

Существует возможность создания турниров прошедшей датой, например 07.10.1994

### Reproduction steps

```bash
- Открываем меню нажатием на "аватар"
- Нажимаем кнопку "Tournaments"
- В текстовое поле "Name" вводим название турнира
- Выбираем "Select" "Type"
- Выбираем "Select" "Access Type" 
- Выбираем "starts at(utc)"
- Выбираем "Level"
- Выбираем "Default language
- Прописываем "Match timeout in seconds"
- Нажимаем кнопку "Create"
```

### Expected result

Отображена ошибка.
Турнир не создан.

### Actual result

Турнир создан.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by Anel1608** [comment]
steps:
 - Кликаем на свой Nickname
 - Выбираем "турниры"
 - Заполняем данные турнира
 - Дату указываем "16.02.2021 11:00"
 - Нажимаем "Создать"
  **Ожидаемый результат**
    Турнир не создан
**Фактический результат**
Создается турнир
**Браузеры**
1.  Яндекс Браузер Версия 23.1.2.931 (64-bit)
2.  Google Chrome Версия 110.0.5481.100 (Официальная сборка), (64 бит)
**ОС**
Windows 11 Версия 21H2 Сборка 22000.1516

**Comment by AllaLoginova** [comment]
**Баг актуален для окружения:**
Яндекс Версия 23.1.2 сборка 599
    iPhone SE iOS 16.12

**Шаги:**
1. Авторизоваться в мобильной версии
2. Кликнуть на свой Nickname
3. В выпавшем списке выбрать Tournaments
4. Заполнить форму создания нового турнира
5. В окне 'Starts at (UTC)' выбрать дату '2022-12-01'
6. Нажать кнопку "создать"

**Ожидаемый результат:**
Турнир не создан

**Фактический результат:**
Турнир создан

**Скрин бага:**

<img width="667" alt="баг на Iphon" src="https://user-images.githubusercontent.com/122536827/219933660-36f3b299-fb39-459b-81ca-669d63c6a79a.png">

**Comment by MashaMelon** [comment]
- summary: 
    Возможность создания турнира с прошедшей датой
  environment: 
    Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
    Opera Версия:94.0.4606.38
    Yandex Версия 22.11.3.818 (64-bit)
    Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)
  steps-to-reproduce: 
    Войти в личный кабинет
    Открыть страницу https://codebattle.hexlet.io/tournaments
    Создать турнир с прошедшей датой
    Нажать Create
  expected-result: 
    Появляется сообщение об ошибке
  actual-result: 
    Турнир успешно создан

**Comment by ipsdv** [comment]
summary:
Возможность создания турнира с прошедшей датой
environment:
Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Opera Версия:94.0.4606.38
Yandex Версия 22.11.3.818 (64-bit)
Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)
steps-to-reproduce:
Войти в личный кабинет
Открыть страницу https://codebattle.hexlet.io/tournaments
Создать турнир с прошедшей датой
Нажать Create
expected-result:
Появляется сообщение об ошибке
actual-result:
Турнир успешно создан

**Comment by Salivya** [comment]
summary:
Возможно создать турнир с прошедшей датой

environment:
Safari Версия 16.1 (18614.2.9.1.12)
macOS Ventura Версия 13.0 (22A380)

prerequisites:
Пользователь зарегестрирован в системе
Открыта страница https://codebattle.hexlet.io/tournaments

steps-to-reproduce:

- Заполнить поля создания турнира
- В поле Starts at (UTC) ввести любую прошедшую дату
- Нажать на кнопку Create

<img width="1280" alt="Снимок экрана 2023-04-03 в 16 21 29" src="https://user-images.githubusercontent.com/119805947/229523757-f345b575-8877-4dfe-8367-bbd17dfc38bb.png">

expected-result:
Турнир не создан

actual-result:
Турнир создан

<img width="1280" alt="Снимок экрана 2023-04-03 в 16 24 29" src="https://user-images.githubusercontent.com/119805947/229523835-b21278c1-ab90-4910-ab5e-9d97e1a440b5.png">

**Comment by AavadaKedavra** [comment]
Воспроизводится 

prerequisites: |
    Пользователь авторизован.
    Открыт сайт на вкладке tournaments https://codebattle.hexlet.io/#tournaments
  test-data: |
    Login1 = AvadaKedavra; Password = password
    Name = test1; Type = individual; Access_type = token; Level = elementary;
    Default language = js; Match timeout = 177;
  steps:
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму 'Create a new tournament' в соответствии с тестовыми данными
    - Указать прошедшую дату и время турнира
    - Нажать 'Create'
  result: | Турнир успешно создан

**Comment by face2face321** [comment]
Summary:
Создание турнира с прошедшей датой
environment:
Chrome Версия 113.0.5672.127 (Официальная сборка), (64 бит)
Windows 10
Prerequisites:
Пользователь авторизован
Открыта главная страница Codebattle
Reproduction steps:
 1. Нажимаем на иконку профиля
 2. Выбираем вкладку "Tournaments"
 3. Во вкладке Starts at (UTC) выбираем любую прошедшую дату
 4. Нажимаем кнопку "create"
Expected result:
Появляется ошибка с сообщением о некорректно выбранной дате
Actual result:
Турнир успешно создан
![445](https://github.com/hexlet-codebattle/codebattle/assets/127731960/30583065-3235-4b34-aa2f-c9f0f431bad3)

**Comment by anastasiya-breusova** [comment]
**summary:**
Создание турнира с прошедшей датой

**environment:**
Google Chrome Версия 109.0.5414.87 (Официальная сборка), (x86_64)
macOS Monterey Версия 12.6
Версия сайта - 764df7e

**steps-to-reproduce:**
1. Авторизоваться
2. Нажать на изображение учетной записи
3. Перейти в раздел "Tournament"
4. Зполнить все необхоимые поля в "Create a new tournament"
5. В поле "Starts at (UTC)" выбрать дату "01.01.2023 00:00"
6. Нажать на кнопку "Save"

**expected-result:**
Турнир не создан. Появится ошибка о некорректной дате старта

**actual-result:**
Турнир успешно создан. Турнир отображается в таблице турниров

**Comment by Makarova94** [comment]
- summary: |
    У пользователя есть возможность создать турнир с прошедшей датой
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
 - Открыть главную страницу сайта
    - Нажать на иконку профиля
    - Нажать на кнопку "Tournaments"
    - Заполнить форму 'Create a new tournament' Name -> Звезда  Starts at (UTC) -> 14.07.2020
    - Нажать 'Create'  
   
  expected-result: |
    Отображается ошибка при создании турнира с прошедшей датой  
  actual-result: |
  Турнир успешно создан. Турнир отображается в таблице турниров

**Comment by ElenaSimanina** [comment]
Баг актуален:
  
![Скриншот Начало турнира](https://github.com/hexlet-codebattle/codebattle/assets/135851722/a94a37f6-35e2-48ce-8010-fa328d7ec4f5)
summary: |
     Возможно создать турнир с прошедшей датой
  environment: |
     Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
     ОС Windows 10
  steps-to-reproduce: |
     1. Зайти на страницу сайта https://codebattle.hexlet.io/#lobby
     2. Авторизоваться
     3. Кликнуть на иконку со своим профилем
     4. Кликнуть на кнопку "Турниры"
     5. Создать турнир с названием Хекслет 123
     5. Выбрать дату 01.07.2022 г.
  expected-result: |
     Турнир не создан, появляется сообщение об ошибке
  actual-result: |
     Создан турнир со стартом 01.07.2022 г.

**Comment by Mimicry56** [comment]
Воспроизводится

**environment:**
OS Windows 11 SE
Google Chrome Версия 118.0.5993.118 (Официальная сборка), (64 бит)
Codebattle Current version: 9500f74

**prerequisites:**
Открыта главная страница codebattle.hexlet.io. Пользователь авторизован

**test-data:**
Name = test1
    Type = individual
    Access type = token
    Description = Test tournament
    Task strategy = game
    Task provider = level
    Level = elementary
    Players limit = 64
    Default language = js
    Match timeout sec = 177
    Break duration sec = 42
    
**steps:**
    - Нажать на вкладку 'TOURNAMENTS'
    - Нажать на гиперссылку 'Tournaments info'
    - Заполнить форму Create a new tournament
    - Заполнить поле 'Name'в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Type' значение в соответствии с тестовым значением
    - Заполнить поле 'Description' в соответствии с тестовым значением
    - Убрать галочку с 'Radiobutton' 'Use chat'
    - Заполнить поле 'Starts at' прошедшей датой и временем
    - Выбрать в выпадающем списке 'Access type' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Task strategy' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Task provider' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Level значение' в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Players limit' значение в соответствии с тестовым значением
    - Выбрать в выпадающем списке 'Default language' значение в соответствии с тестовым значением
    - Ввести числовое значение в поле 'Match timeout sec' в соответствии с тестовым значением
    - Ввести числовое значение в поле 'Break duration sec' в соответствии с тестовым значением
    - Нажать 'Create'
    
**expected-result:**
Турнир не создан, отображается сообщение о невозможности создать турнир с прошедшей датой и временем

**actual-result:**
Турнир успешно создан

**Comment by ReDBrother** [comment]
Дата старта является опциональной настройкой исключительно для таймера старта - на сам турнирный процесс он не влияет

**Comment by Retroman95** [comment]
summary:
Создание турнира с прошедшей датой

environment:
Google Chrome   Версия 123.0.6312.59 (Официальная сборка), (64 бит)
Mozilla Firefox Версия 124.0.1 (64-разрядный)
ОС Windows 10 Pro 19045.3930

Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/85a7a93e3da39e9b4d05a460667cbcd4aeb7f695

Prerequisites:
Пользователь авторизован
Открыта главная страница Codebattle

steps-to-reproduce: 
Открыть главную страницу сайта
Нажать на иконку профиля
Нажать на кнопку "Tournaments"
Заполнить форму 'Create a new tournament' Name -> My fancy tournament Starts at (UTC) -> 24.03.2024
Нажать 'Create'
![баг](https://github.com/hexlet-codebattle/codebattle/assets/46816641/4b288edb-ef11-4507-b5ac-addb9d3cf17a)
![баг 1](https://github.com/hexlet-codebattle/codebattle/assets/46816641/4abae647-f7c4-4a1a-b12e-827639c03d27)
