### ISSUE TITLE
Одновременное участие в обычной игре и игре турнира. Ошибка?

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1260]
### Summary

Если во время участия в игре, перейти на страницу "tournaments" и вступить в турнир(список Players), то при запуске турнира(Start), пользователь имеет возможность запустить игру турнира.

### Reproduction steps

```bash
- Нажимаем на кнопку "Create a game"
    - Выбираем "level"
    - Выбираем "game type"
    - Вводим "Nickname" противника
    - Нажимаем на "Nickname" противника
    - Выбираем "time control"
    - Нажимаем кнопку "Create invite"
    - Ждем согласия противника
    - Нажимаем на аватар
    - Нажимаем на кнопку "Tournaments"
    - Нажимаем кнопку "Show" у ранее созданного туринра
    - Нажимаем кнопку "Join"
    - Запускаем турнир
    - Нажимаем кнопку "Join"
```

### Expected result

?

### Actual result

Пользователь одновременно участвует в игре "with a friends" и в турнирной игре.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by 2KO1** [comment]
Возможно стоит сделать невозможным функцию попадания в список "Players" турнира во время игры с кем-либо.

**Comment by ReDBrother** [comment]
Пока оставим как есть, слишком много кейсов нужно решить.
