### ISSUE TITLE
Bug: Артефакт возникающий при наведении на кнопку "Sign in".

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1261]
### Summary

![image](https://user-images.githubusercontent.com/102296858/216840947-7c0a8a44-48c4-4886-9ff2-025a192fd1bf.png)
![image](https://user-images.githubusercontent.com/102296858/216840957-386056a2-9e70-4904-b781-2115c2129113.png)

### Reproduction steps

```bash
- Перейти на страницу веб-приложения "CodeBattle" по ссылке (https://codebattle.hexlet.io/)
- Навести курсор мыши на кнопку "Sin in"
- Перейти на страницу авторизации приложения (https://codebattle.hexlet.io/session/new?locale=en&next=%2F)
- Навести курсор мыши на кнопку "Sin in
```

### Expected result

Кнопка "Sign in" отображена корректно.

### Actual result

Кнопка "Sign in" отображена некорректно.

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by MariaLishchuk** [comment]
Баг воспроизводится
ПК
Microsoft Edge 109.0.1518.61 (Официальная сборка) (64 бит)
ОС Windows 10 19045.2364

**Comment by denkrasotkin** [comment]
https://github.com/hexlet-codebattle/codebattle/issues/1200
Данный артефакт встречался ранее.
Сейчас воспроизводится на OS Mac, Safary 15
![sign in](https://user-images.githubusercontent.com/121078808/217655805-4120dc64-8f72-4953-8f4e-622802f1f0ae.jpg)

**Comment by borizi** [comment]
Баг до сих пор воспроизводится.
Microsoft Edge
Версия 110.0.1587.41 (Официальная сборка) (64-разрядная версия)
Windows 11 Pro Сборка 22000.1574
![Артефакт у кнопки Sing in](https://user-images.githubusercontent.com/64551423/219372919-28a56dcf-eab9-406f-8d4a-dcdda0135d73.jpg)

**Comment by RemoSet** [comment]
А артефакт, это в мааааленькой черточке справа от кнопочки? очень сложно сразу понять из скринов, сразу и не увидишь

**Comment by 2KO1** [comment]
Да, все верно, синяя черточка справа кнопки "Sign in"

**Comment by RemoSet** [comment]
- Перейти на страницу  https://codebattle.hexlet.io/
- Навести курсор мыши на кнопку "Sin in"
***
OS 22000.1219 Windows 11 Версия 21H2
Web browser Google Chrome Версия 108.0.5359.100

![screen2](https://user-images.githubusercontent.com/117320009/219884059-a41c94d1-6b55-4dc1-a70e-0882b25222a5.png)

**Comment by Mayday4221** [comment]
Баг воспроизводится
ПК
ОС Windows 7 19045.2364   Google Chrome Версия 109.0.5414.120  (Официальная сборка), (64 бит)

**Comment by Goryaminskaya** [comment]
Перейти на страницу https://codebattle.hexlet.io/
Навести курсор мыши на кнопку "Sing in"

Браузер
Яндекс Версия 23.1.3.949 (64-bit)
Opera Версия 95.0.4635.46

**Comment by Germankhz** [comment]
Воспроизводится в браузере 

Brave  -> Version: 1.148.167 Chromium: 110.0.5481.104 (Official Build) (64bit)

**Comment by ValeriaStroeva** [comment]
Баг воспроизводится.

- summary: |
    При наведении на кнопку "Sign in" появляется черточка
  environment: |
    Google Chrome Версия 110.0.5481.177 (Официальная сборка), (arm64)
    OC macOS Ventura 13.1
  steps-to-reproduce: |
    - Зайти на главную страницу сайта
    - Навести курсор мыши на кнопку "Sing in"
  expected-result: |
    При наведении на кнопку "Sign in" её цвет меняется на красный
  actual-result: |
    При наведении на кнопку "Sign in" появляется черточка
    Ошибка изображена на скриншоте dash.png
<img width="1327" alt="dash" src="https://user-images.githubusercontent.com/74196783/224399586-90ee2b20-248d-4026-9230-b0fd7d561196.png">

**Comment by Romul76** [comment]
Воспроизвелось

Environment:
Windows 10
Firefox 112.0.2 (64-bit)

**Comment by katrytikova** [comment]
Артефакт остался
Google Chrome 113.0.5672.126 (Официальная сборка), (arm64)
macOS Ventura 13.1
firefox  	113.0.1
<img width="689" alt="Снимок экрана 2023-05-24 в 14 40 41" src="https://github.com/hexlet-codebattle/codebattle/assets/122362310/edd0a9eb-ee28-4324-b21d-72e7ed31e598">

**Comment by ReDBrother** [comment]
fixed
