### ISSUE TITLE
Bug: Некорректная работа кнопки "Cancel" в турнире.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1262]
### Summary

После запуска турнира кнопкой "Start", если нажать кнопку "Cancel", то у пользователя больше не отображается турнир и игра, но при этом пользователь продолжает находиться в игре все указанное, при создании турнира, время, из-за данной ошибки при попытке создать или поучаствовать в игре в этот момент отображается ошибка "already_in_a_game". Обновление страницы или выход из приложения не помогают. Ошибка распространяется на всех участников отмененного турнира.

### Reproduction steps

```bash
- Авторизоваться в приложении
- Создать турнир
- Присоединиться к турниру в список "Players"
- Нажать кнопку "Start"
- Нажать кнопку "Cancel"
- Нажать кнопку "Fight" рядом с ботом во вкладке "lobby" на главной странице приложения/создать игру с ботом
```

### Expected result

Турнир не отображен.
Пользователь успешно подключается к играм.
Пользователь успешно создает и участвует в играх.

### Actual result

Турнир не отображен.
При попытке участия в игре отображена ошибка "already_in_a_game".

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by ReDBrother** [comment]
Вроде пофиксили)
