### ISSUE TITLE
Bug: при запуске игры «With a friend» для решения дается не та задача, которая была установлена в настройках игры

### ISSUE THREAD

**Issue by MariaLishchuk** [hexlet-codebattle/codebattle#1265]
### Summary

При выборе конкретной задачи в настройках игры «With a friend» запускается игра по решению не той задачи, что была выбрана ранее

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/
2. С одного аккаунта нажать кнопку «Create a game»
3. Нажать кнопку «With a friend»
4. Ввести имя другого пользователя в окне «Choose opponent»
5. Выбрать значение «rect_area» в выпадающем меню «Choose task by name or tags»
6. Нажать кнопку «Create battle»
7. С аккаунта пользователя, приглашенного в игру, нажать кнопку с перекрещенными мечами
8. Нажать кнопку «Accept»
```

### Expected result

Начинается игра по решению задачи «rect_area»

### Actual result

Начинается игра по решению рандомной задачи

### Browsers

Chrome

### OS

Windows

**Comment by Marria22** [comment]
Баг все еще воспроизводится.

Браузер
Chrome Версия 110.0.5481.178 (Официальная сборка), (64 бит)

ОС
Windows 10 версия 22H2

**Comment by MariaSov** [comment]
Баг ещё воспроизводится.

Reproduction steps:

    - Нажать кнопку «Create a game»
    - Нажать кнопку «With a friend»
    - Выбрать имя пользователя из выпадающего списка в пункте «Choose opponent»
    - Выбрать игру «age_to_days» из выпадающего списка в пункте «Choose task by name or tags»
    - Нажать кнопку «Create battle»
    - С аккаунта пользователя, приглашённого в игру, нажать кнопку с перекрещёнными мечами
    - Нажать кнопку «Accept»

Браузер
Chrome Версия 112.0.5615.138 (Официальная сборка), (64 бит)

ОС
Выпуск	Windows 10 Pro
Версия	22H2
Сборка ОС	19045.2846
Взаимодействие	Windows Feature Experience Pack 120.2212.4190.0

Браузер
Chrome 
Version 112.0.5615.137 (Official Build) (arm64)

ОС
macOS 13.1 (22C65)

**Comment by ReDBrother** [comment]
fixed
