### ISSUE TITLE
Bug: не приходит оповещение в случае отклонения приглашения оппонентом вступить в игру

### ISSUE THREAD

**Issue by MariaLishchuk** [hexlet-codebattle/codebattle#1266]
### Summary

При отклонении пользователем приглашения вступить в игру у пользователя, создавшего игру, не отображается оповещение, что приглашение отклонено

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/
2. С одного аккаунта нажать кнопку «Create a game»
3. Нажать кнопку «With a friend»
4. Ввести имя другого пользователя в окне «Choose opponent»
5. Выбрать значение «rect_area» в выпадающем меню «Choose task by name or tags»
6. Нажать кнопку «Create battle»
7. С аккаунта пользователя, приглашенного в игру, нажать кнопку с перекрещенными мечами
8. Нажать кнопку «Decline»
```

### Expected result

У пользователя, создавшего игру, отображается оповещение «invitation has been declined»

### Actual result

У пользователя, создавшего игру, не отображается оповещение «invitation has been declined»

### Browsers

Safari

### OS

Mac

**Comment by MashaMelon** [comment]
summary:
Нет сообщения об отклонении игры от друга

environment:
Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Opera Версия:94.0.4606.38
Yandex Версия 22.11.3.818 (64-bit)
Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)

steps-to-reproduce:
Авторизоваться
Создать баттл (Game type - With a friend)

expected-result:
При отклонении баттла от друга, пользователь получает сообщение (например battle was canceled)

actual-result:
Пользователь не получает сообщение об отклонении игры

**Comment by ipsdv** [comment]
summary:
Нет сообщения об отклонении игры от друга

environment:
Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Opera Версия:94.0.4606.38
Yandex Версия 22.11.3.818 (64-bit)
Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)

steps-to-reproduce:
Авторизоваться
Создать баттл (Game type - With a friend)

expected-result:
При отклонении баттла от друга, пользователь получает сообщение (например battle was canceled)

actual-result:
Пользователь не получает сообщение об отклонении игры

**Comment by ipsdv** [comment]
summary:
- Нет сообщения об отклонении игры от друга

environment:
- Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
- Opera Версия:94.0.4606.38
- Yandex Версия 22.11.3.818 (64-bit)
- Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)

steps-to-reproduce:
1. Авторизоваться
2. Создать баттл (Game type - With a friend)

expected-result:
- При отклонении баттла от друга, пользователь получает сообщение (например battle was canceled)

actual-result:
- Пользователь не получает сообщение об отклонении игры

**Comment by ReDBrother** [comment]
Полноценной панели нотификаций нет.
