### ISSUE TITLE
Bug: невозможно отвязать аккаунт Github от аккаунта Codebattle

### ISSUE THREAD

**Issue by MariaLishchuk** [hexlet-codebattle/codebattle#1268]
### Summary

Невозможно отвязать аккаунт Github от аккаунта Codebattle, кнопка «Unlink Github» неактивна

![image](https://user-images.githubusercontent.com/121458283/217277291-87c55a85-444a-45fd-82e4-cf818e6917a9.png)

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/settings  
2. Нажать кнопку «Unlink Github»
3. Нажать на имя пользователя
4. Нажать кнопку «My profile»
```

### Expected result

Аккаунт Github отвязан, на странице пользователя перестает отображаться ссылка на него

### Actual result

Кнопка «Unlink Github» неактивна, при нажатии на нее ничего не происходит

### Browsers

Chrome

### OS

Windows

**Comment by tramvaichik** [comment]
Так же не работает в браузере FireFox, версия 109.0.1

**Comment by Goryaminskaya** [comment]
Summary
Кнопка «Unlink Github» неактивна
Reproduction steps
1. Перейти по ссылке https://codebattle.hexlet.io/settings  
2. Зайти в аккаунт, который привязан в Github
3. Нажать "Settings"
4. Нажать кнопку «Unlink Github»
Expected result
Аккаунт Github отвязан, на странице пользователя перестает отображаться ссылка на него
Actual result
Кнопка «Unlink Github» неактивна
Browsers
Яндекс 23.1.3.949 (64-bit)

OS
Windows

**Comment by polinatswet** [comment]
**Summary:** 
Проверка отключения Github от профиля пользователя Сodebattle
**Steps:**
1.  Авторизоваться с помощью Github
2. Открыть  https://codebattle.hexlet.io/settings
3.  Перейти в раздел Settings
4. Нажать кнопку Unlink Github

**Expected-result:**
 Кнопка Unlink Github активна, аккаунт Github отвязан,  пользователь может привязать другой аккаунт
 **Actual result:**
Нет возможности отключить профиль Github от профиля пользователя Сodebattle

**Browsers:** 
Google Chrome 110.0.5481.100
**OS** MacOS
<img width="1216" alt="Снимок экрана 2023-02-24 в 16 58 34" src="https://user-images.githubusercontent.com/120312860/221186826-a3a60bbb-24e2-4c59-ac34-4cb588d0bb28.png">

**Comment by Mayday4221** [comment]
Баг воспроизводится. 
OS Windows 7
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

  steps:
    1. Перейти по ссылке https://codebattle.hexlet.io/settings  
    2. Зайти в аккаунт, который привязан в Github
    3. Нажать "Settings"
    4. Нажать кнопку «Unlink Github»

  expected-result: 
    Аккаунт Github отвязан, на странице пользователя перестает отображаться ссылка на него

**Comment by Trouble666** [comment]
- summary: |
    Нет возможности отвязать аккаунт Github и Discord
  environment: |
    Opera GX LVL4 (core: 94.0.4606.69) Версия Chromium:108.0.5359.125
    Windows 10 64-bit
  steps-to-reproduce: |
    1. Быть авторизованным на сайте
    2. Перейти в раздел "Settings"
    3. Нажать на кнопки "Unlink Discord", "Unlink Github"
  expected-result: |
    Должно появиться сообщение о том, что операция прошла успешна
  actual-result: |
   Кнопки не кликабельны

![изображение_2023-03-14_201900311](https://user-images.githubusercontent.com/40794849/225114197-0ffb80fb-ead7-4856-ad80-b77d6749cfd1.png)

**Comment by Linsept** [comment]
![Снимок экрана 2023-06-08 020246](https://github.com/hexlet-codebattle/codebattle/assets/130752518/323473ae-4b3c-49cb-8429-674d71c6afa2)
  summary: |
    Отвязка Github от аккаунта Codebattle
  environment: |
    Google Chrome   49.0.2623 (Официальная сборка) (64 бит)
    ОС Windows 10 20h2
  steps-to-reproduce: |
    1. Зайти на сайта https://codebattle.hexlet.io
    2. Войти в профиль привязанный к Github
    3. Нажать на свой никнейм на верхней панели сайта
    4. В открывшемся окне нажать на кнопку "Settings"
    5. На открывшейся странице нажать на кнопку "UnLink Github"
  expected-result: |
    Аккаунт Codebattle успешно отвязан от Github
  actual-result: |
    Кнопка "Unlink Github" не активна

**Comment by ReDBrother** [comment]
Дубль от #1485
