### ISSUE TITLE
Bug: не воспроизводится видео-запись игры пользователя

### ISSUE THREAD

**Issue by MariaLishchuk** [hexlet-codebattle/codebattle#1269]
### Summary

При нажатии кнопки «Show» в истории игр пользователя отображена только обложка с аватарами и именами противников, видео-плеер не открывается

![image](https://user-images.githubusercontent.com/121458283/217278223-2cf15d4b-5b2b-4b57-8a3f-6aa99e30be5c.png)

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/
2. Нажать на имя пользователя «v.mozaykin»
3. Нажать кнопку «My profile»
4. Открыть вкладку «Completed games»
5. Нажать любую кнопку «Show»
6. Нажать кнопку «Play»
```

### Expected result

Открывается видео-плеер, воспроизводится виде-запись игры

### Actual result

Отображена только обложка с аватарами и именами противников, видео-плеер не открывается

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
fixed
