### ISSUE TITLE
Bug: игры в рамках чемпионата запускаются не с тем языком, что был выбран в настройках чемпионата

### ISSUE THREAD

**Issue by MariaLishchuk** [hexlet-codebattle/codebattle#1270]
### Summary

В играх, проходящих в рамках чемпионата, языком по умолчанию является язык, отличный от того, что был установлен в настройках чемпионата

![image](https://user-images.githubusercontent.com/121458283/217289768-f20b5461-c872-4789-a442-4a58729c63e5.png)
![image](https://user-images.githubusercontent.com/121458283/217287703-1add8361-35f1-4212-b296-cafcaa9bc9e4.png)

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/tournaments    
2. Ввести «Test 2» в поле «Name»
3. Установить значение «07.02.2023 19:36» в поле «Starts at (UTC)»
4. Выбрать «Python» в поле «Default language»
5. Ввести значение «777» в поле «Match timeout in seconds»
6. Нажать кнопку «Create»
7. Нажать кнопку «Join»
8. Нажать кнопку «Promote»
9. Нажать кнопку «Join»
10. Нажать кнопку «Start»
11. Нажать кнопку «Join»
```

### Expected result

Языком по умолчанию в играх в рамках чемпионата является «Python»

### Actual result

Языком по умолчанию в играх в рамках чемпионата является «JavaScript» 

### Browsers

Chrome

### OS

Windows

**Comment by Xtoseone** [comment]
воспроизводится до сих пор: при выборе языка например: python турнир начинается с JS для новых пользователей и с последнего выбранного в баттле


https://github.com/hexlet-codebattle/codebattle/assets/114728833/ef950164-6dfd-45f3-ae45-cf318ed94ab0

**Comment by vtm9** [comment]
в настройках чемпионата ставится дефолтный язык, если у пользователя уже выбран язык, то он будет выбран
