### ISSUE TITLE
Bug: "Send Feedback" button overley (mobile browser)

### ISSUE THREAD

**Issue by denkrasotkin** [hexlet-codebattle/codebattle#1271]
### Summary

When a completed game is opened, the "Send Feedback" button is overlaid on the "cb-slider-timeline".
It is not possible to scroll the slider to the selected position.

![наложение](https://user-images.githubusercontent.com/121078808/217547477-d2d83f79-ce47-4703-b62e-bd05e3a8d4a6.jpg)

### Reproduction steps

```bash
1. Open Google Chrome app
2. Go to https://codebattle.hexlet.io
3. Click on "Sign in" button
4. Pass Authorization #For example: Email=Plus@bk.com, Password=plusminus
5. Click on "Completed Games"
6. Choose any game, and click on "Show" button
7. See bug

Mobile model : Samsung SM-G970F
Browser: Chrome ver. 108.0.5359.128
```

### Expected result

It is possible to scroll the timeline slider to any position. Nothing is overlaid.

### Actual result

It is not possible to scroll the slider to the selected position.

**Comment by AllaLoginova** [comment]
**Наложение кнопки 'Send Feedback' на всплывающее окно кнопки временной шкалы при просмотре завершенной игры.**

**Шаги:**
1. Перейти в профиль игрока
2. Нажать кнопку "Завершенные игры"
3. Нажать кнопку просмотра любой завершенной игры

**Ожидаемый результат:**
Можно выбрать любое значение из выпадающего списка кнопки временной шкалы

**Фактический результат:**
Кнопка "Send Feedback" накладывается на всплывающее окно кнопки временной шкалы

**Окружающая среда:**
Google Chrome версия 109.0.5414.75 (Официальная сборка), 64 бит
    ОС Windows 7

**Скрин бага:**
![2023-02-19_09-05-45](https://user-images.githubusercontent.com/122536827/219923095-bce2b30d-2ab4-4a58-848c-2c277ce5a72c.png)

**Comment by Its-Kate** [comment]
Такой же Баг при использовании  Google Chrome версия 109.0.5414.75 (Официальная сборка), 64 бит
MacOS Monterey

**Comment by etibarovna** [comment]
summary:
Наслоение кнопки SendFeedback в мобильной версии 
environment:
Google Chrome
Android
Версия сайта – [764df7e](https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806)
steps-to-reproduce:
1. Авторизоваться на странице https://codebattle.hexlet.io/
2. Нажать кнопку create game
3. Перейти в саму игру
3. Открыть DevTools перевести в режим мобильного устройства
expected-result:
Все изображения, текст и кнопки в игре функциональны и удобно расположены
actual-result:
Кнопка SendFeedback наслаивается на Open history  Back to home, что затрудняет пользование этим функционалом

![image](https://github.com/hexlet-codebattle/codebattle/assets/129650700/ceee5b07-db1b-41ef-bbf7-10f4ec6bf614)

**Comment by YukKaji** [comment]
Summary
Кнопки загораживают полосу воспроизведения, а так же иконки не по центру.

Reproduction steps
1. Открыть сайт в мобильной версии
2. Нажать "completed games"
3. Нажать "show"

Expected result
Кнопки не загораживают полосу воспроизведения, иконки по центру.

Actual result
Кнопки загораживают полосу воспроизведения, иконки не по центру.

Browsers
Chrome

OS
Windows

![image](https://github.com/hexlet-codebattle/codebattle/assets/128067636/05011b39-5345-4fd5-9335-14c27777f0cc)

**Comment by ReDBrother** [comment]
Убрали плашку со странице истории игры
