### ISSUE TITLE
Bug: Overlay and distortion of elements in tournament lobby.

### ISSUE THREAD

**Issue by denkrasotkin** [hexlet-codebattle/codebattle#1273]
### Summary

Overlay and distortion of text, buttons and titles in the tournament lobby and chat.
Windows,Mac version OS doesn't have this bug.

![mobile](https://user-images.githubusercontent.com/121078808/217567279-82e51ee7-b2e5-4417-bab8-38a29ca59ff4.jpg)
![наложение2](https://user-images.githubusercontent.com/121078808/217567286-d6441200-ead4-47f8-b025-0d87c571f2bb.jpg)
![наложение3](https://user-images.githubusercontent.com/121078808/217567290-42e754e2-94c0-49dd-ac4b-85417ed6bd12.jpg)

### Reproduction steps

```bash
1. Open Google Chrome app
2. Go to https://codebattle.hexlet.io
3. Click on "Sign in" button
4. Pass Authorization #For example: Email=Plus@bk.com, Password=plusminus
5. Click on "Tournaments"
6. Choose any tournament, and click on "Show" button
7. See bug

Mobile model : Samsung SM-G970F
Browser: Chrome ver. 108.0.5359.128
```

### Expected result

All buttons, titles, texts and comments are displayed correctly, without distortion or overlap.

![normal](https://user-images.githubusercontent.com/121078808/217568200-891a6b27-5f29-402e-9fdb-b27f9ed27828.jpg)

### Actual result

The window for viewing and entering comments is very small. Overlay buttons on fields. Overlay and distortion of the title of the tournament.

**Comment by ReDBrother** [comment]
Fixed
