### ISSUE TITLE
Bug: Missing "Back" button

### ISSUE THREAD

**Issue by denkrasotkin** [hexlet-codebattle/codebattle#1274]
### Summary

There is no " Back" button to exit tournament lobby to the main lobby. 
In order to leave the tournament lobby, user must click on "Codebattle" button.
![no back](https://user-images.githubusercontent.com/121078808/217573647-10dc5c5f-2472-4674-8cf2-5dc545ca9102.jpg)

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io
2. Click on "Sign in" button
3. Pass Authorization #For example: Email=Plus@bk.com, Password=plusminus
4. Click on "Tournaments"
5. Choose any tournament, and click on "Show" button
6. See bug
```

### Expected result

Tournament lobby displays a "Back" button to go to the main or previous menu.

### Actual result

There is no button in the tournament lobby to go to the previous menu.

### Browsers

Chrome, Safari

### OS

Windows, Mac

**Comment by anastasiya-breusova** [comment]
**summary:**
Отсутствует кнопка "Back" из сетки турнира в список всех турниров

**environment:**
Google Chrome Версия 109.0.5414.87 (Официальная сборка), (x86_64)
macOS Monterey Версия 12.6
Версия сайта - 764df7e

**steps-to-reproduce:**
1. Авторизоваться
2. Нажать на изображение учетной записи
3. Перейти в раздел "Tournament"
4. В таблице выбрать турнирную сетку
5. Нажать на "Show"

**expected-result:**
В турнирной сетку присутствует кнопка возврата к списку всех турниров

**actual-result:**
В турнирной сетку отсутсвует кнопка возврата к списку всех турниров
<img width="1280" alt="Снимок экрана 2023-07-11 в 21 08 19" src="https://github.com/hexlet-codebattle/codebattle/assets/129413395/06294d5d-8536-4ea9-a01c-e6b1f4f5fd90">

**Comment by ReDBrother** [comment]
Fixed
