### ISSUE TITLE
Bug: There are no restrictions for writing a new task.

### ISSUE THREAD

**Issue by denkrasotkin** [hexlet-codebattle/codebattle#1276]
### Summary

The user has the opportunity to write Russian characters in the "description en" field
The user has the opportunity to write English characters in the "description ru" field
![task2](https://user-images.githubusercontent.com/121078808/217596286-5fa5410d-d124-4f80-89d8-1e8f0137f26f.jpg)

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io
2. Click on "Sign in" button
3. Pass Authorization #For example: Email=Plus@bk.com, Password=plusminus
4. Click on "account" icon
5. Click on "Tasks"
6. Click on "Create new task"
7. Write "test" in the "description ru" field,"тест" in the "description en" field,"test" in the "name" field,"test" in the "examples" field
8. Click on "Save"
9. See bug
```

### Expected result

After entering Russian characters in the "description en" field, an error pop-up window "only English characters" will appear.
After entering English characters in the "description ru" field, an error pop-up window "only Russian characters" will appear.

### Actual result

There are no restrictions on entering characters in different languages in the description

### Browsers

Chrome, Safari

### OS

Windows, Mac

**Comment by ReDBrother** [comment]
Создали новый таск билдер)
