### ISSUE TITLE
Bug: user rating differences

### ISSUE THREAD

**Issue by denkrasotkin** [hexlet-codebattle/codebattle#1277]
### Summary

The difference between the user rating in the lobby and in the chrome extension
![wrong rating](https://user-images.githubusercontent.com/121078808/217612287-7d13297d-8aa8-4e3f-8c5e-b0ce62f66059.jpg)

### Reproduction steps

```bash
1. Install chrome extension from https://chrome.google.com/webstore/search/codebattle?hl=ru
1. Go to https://codebattle.hexlet.io
2. Click on "Sign in" button
3. Pass Authorization #For example: Email=Plus@bk.com, Password=plusminus
4. Open chrome extension "Codebattle"
6. See bug
```

### Expected result

User ratings in the lobby and in the chrome extension are displayed the same

### Actual result

User rating in the lobby and in the chrome extension are displayed with different indicators

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Их невозможно держать в синхронизированном состоянии
