### ISSUE TITLE
Bug: Отображается нерелевантная область экрана при переключении шагов гайда во время боя (мобильная версия)

### ISSUE THREAD

**Issue by mootar** [hexlet-codebattle/codebattle#1281]
### Summary

Во время боя, пробного или под зареганным пользователем, при нажатии на кнопку гайд появляется окно с кнопкой Next 1/8. После третьего шага (кнопка будет выглядеть Next 3/8) при дальнейшем нажатии экран прокручивается до упора вверх. При этом вся область остаётся затемненной. Приходится вручную откручивать вниз до гайда, чтобы нажать на кнопку Next 4/8.
То же самое происходит вплоть до шага Next 7/8. Только последний шаг (Last 8/8) отображается корректно.
![guide_bug1 1](https://user-images.githubusercontent.com/26491495/218108349-c04938b9-0666-4d33-93cd-f72a1d0bf283.jpg)
![guide_bug1 2](https://user-images.githubusercontent.com/26491495/218108356-c3cfbbd9-2271-4c5e-b02d-dda87fe91e14.jpg)

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/
2. Нажать Try simple battle
3. Нажать Show guide
4. Нажать Next 1/8
5. Нажать Next 2/8
6. Нажать Next 3/8
```

### Expected result

Пошаговое переключение гайда центрирует видимую пользователем область на описываемом элемента.

### Actual result

Пошаговое переключение гайда (с 4 по 7 шаги) центрирует видимую пользователем область в верх страницы.

### Browsers

Chrome 110.0.5481.64

### OS

Android 11

### Device

Pixel 2 XL Build/RP1A.201005.004.A1

**Comment by ReDBrother** [comment]
Будь у нас 100 тысяч программистов и набор девайсов для тестирования мобильной версии, то мы бы пофиксили это  поведение для всех смартфонов)
На части мобильных девайсов скролл работает. Закрываем тикет
