### ISSUE TITLE
Bug: При создании игры, не все слова переводятся на русский язык

### ISSUE THREAD

**Issue by gomer51** [hexlet-codebattle/codebattle#1282]
### Summary

Bug: При создании игры, не все слова переводятся на русский язык

### Reproduction steps

```bash
1.Перейти по ссылке https://codebattle.hexlet.io/?_gl=1*1g31me9*_ga*ODU4NDk4Njg1LjE2NzU3NTU4MTE.*_ga_PM3R85EKHN*MTY3NjA2MDgyNi4zOS4xLjE2NzYwNjA4OTYuMC4wLjA.
2. нажать на клавишу "Создать игру"
3. В появившемся окне находим графу "Выберете задачу"
4. При выборе задачи, можно заметить, что не все задачи переведены.
```

### Expected result

1.Перейти по ссылке https://codebattle.hexlet.io/?_gl=1*1g31me9*_ga*ODU4NDk4Njg1LjE2NzU3NTU4MTE.*_ga_PM3R85EKHN*MTY3NjA2MDgyNi4zOS4xLjE2NzYwNjA4OTYuMC4wLjA.
2. нажать на клавишу "Создать игру"
3. В появившемся окне находим графу "Выберете задачу"
4. Все задачи переведены.

### Actual result

![IMG_0175 1](https://user-images.githubusercontent.com/121378161/218195212-f97a4ce1-14b1-48a5-a8ac-b87746648631.jpg)
как можно видеть на фото, фактический результат, частичный перевод текста.

### Browsers

Chrome

### OS

Windows

**Comment by vikahati** [comment]
![Снимок экрана от 2023-04-03 13-45-05](https://user-images.githubusercontent.com/122161886/229487782-cf7c4513-cb10-4c33-9a8c-c80c58e4dc3c.png)

1.Перейти по ссылке https://codebattle.hexlet.io/?_gl=1*1g31me9*_ga*ODU4NDk4Njg1LjE2NzU3NTU4MTE.*_ga_PM3R85EKHN*MTY3NjA2MDgyNi4zOS4xLjE2NzYwNjA4OTYuMC4wLjA.
2. нажать на клавишу "Создать игру"
3. В появившемся окне находим графу "Выберете задачу"
4. При выборе задачи, можно заметить, что не все задачи переведены.

Воспроизводится на Browser: Yandex;   OS: Linux

**Comment by ReDBrother** [comment]
У нас нет локализации на русский и мы не будем подобный игровой контент подгонять под автоматические переводчики. Максимум мы можем вводить описание задач.
