### ISSUE TITLE
Bug: Возможность написать в чат сообщение с неограниченным количеством символов (Feature: 1024 - message max limit)

### ISSUE THREAD

**Issue by BelBranco** [hexlet-codebattle/codebattle#1285]
### Summary

Возможность написать в чат сообщение с неограниченным количеством символов

![Hexlet Codebattle • Game for programmers 2023-02-12 22-40-06](https://user-images.githubusercontent.com/120272005/218339904-ef328eba-3ee9-48c4-b3a7-eedd9fb6c548.png)

### Reproduction steps

```bash
1. Перейти по ссылке  https://codebattle.hexlet.io/#lobby
2. Авторизоваться
3. На главной странице сайта в чате ввести текст в 151.380 символов
```

### Expected result

Ограничение на количество введенных символов в одном сообщении

### Actual result

Возможность ввести сообщение количеством 151.380 символов

### Browsers

Chrome Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

 Windows 10 Home 22H2

**Comment by BelBranco** [comment]
такая же проблема во всех чатах

**Comment by vikahati** [comment]
1. Перейти по ссылке  https://codebattle.hexlet.io/#lobby
2. Авторизоваться
3. На главной странице сайта в чате ввести текст в 151.380 символов

Воспроизводится на Browser: Yandex;   OS: Linux

**Comment by ReDBrother** [comment]
Поставим лимит в 1024 символа

**Comment by ElenaSimanina** [comment]
Всем привет) Видимо пока лимит не установлен) 
1. Зайти на страницу сайта https://codebattle.hexlet.io/#lobby
2. Авторизоваться
3. В поле для ввода сообщений набрать текст из 19296 символов 
Воспроизводится: Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
![Скриншот неограниченное количество символов](https://github.com/hexlet-codebattle/codebattle/assets/135851722/e0652b2b-a877-4a55-9ecc-ad45e8238670)
ОС Windows 10

**Comment by shaolanx** [comment]
Всем доброго времени суток. хочу исправить данный баг. Какие кол-вом символов ограничить? На мой взгляд 200 будет достаточно) Можно любым числом

**Comment by ReDBrother** [comment]
fixed
