### ISSUE TITLE
Bug: при отправки сообщения в "Feedback", текст просто исчезает

### ISSUE THREAD

**Issue by BelBranco** [hexlet-codebattle/codebattle#1288]
### Summary

При отправки сообщения в "Feedback", текст просто исчезает 

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/#lobby
2. Авторизоваться
3. Создать игру
4. В правом нижнем углу нажать "Send Feedback"
5. В открывшимся окне выбрать тип обратной связи
6. В поле "Message" написать текст сообщения
7. Нажать кнопку "Send Feedback"
```

### Expected result

Отображено уведомление о успешной отправки сообщения (или закрытие окна "Send Feedback" )

### Actual result

Текст просто исчезает

### Browsers

Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

 Windows 10 Home 22H2

**Comment by 21aLeX** [comment]
@ReDBrother привет, хотела взять задачу, но есть но. Вроде бы при отправке сообщения текст кнопки меняется на "Sent!", а если на нее еще раз нажать то она становиться зеленой. На 5 сек, можно увеличить время. По поводу закрытия окна, параметр "open" можно задать только при создании этого виджета, с помощью useState не получилось изменить открытость окна. Есть еще disabled, но тогда все полностью исчезает.(

**Comment by ReDBrother** [comment]
> @ReDBrother привет, хотела взять задачу, но есть но. Вроде бы при отправке сообщения текст кнопки меняется на "Sent!", а если на нее еще раз нажать то она становиться зеленой. На 5 сек, можно увеличить время. По поводу закрытия окна, параметр "open" можно задать только при создании этого виджета, с помощью useState не получилось изменить открытость окна. Есть еще disabled, но тогда все полностью исчезает.(

Привет! Давай ограничимся алертами. Нам нужен сигнал, что фидбек дошел/не дошел. Текст кнопки не совсем очевидный сигнал. В проекте уже есть стандарт таких flash сообщений, которые ключевые для приложения. Примерно выглядит так

<img width="804" alt="Screenshot 2023-07-03 at 19 43 27" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/579f444e-af8a-4765-817e-263e8192e650"> 

Закрывать пока ничего не нужно

**Comment by 21aLeX** [comment]
@ReDBrother  а где сейчас эти алерты есть? посмотреть чтоб.
И текст сообщения какой? Что то типо "Ваш фидбек доставлен"?

**Comment by ReDBrother** [comment]
> @ReDBrother а где сейчас эти алерты есть? посмотреть чтоб.

Я скинул скриншот, его можно наблюдать при регистрации/входа в аккаунт. В js приложении в целом его нет, но мы можем написать еще один рядом, как на скриншоте.

> И текст сообщения какой? Что то типо "Ваш фидбек доставлен"?
Да, в самый раз

**Comment by ReDBrother** [comment]
<img width="1214" alt="Screenshot 2023-07-07 at 16 36 13" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/fb981ca5-0944-4eaa-a710-9b31a9d9691d">

**Comment by 21aLeX** [comment]
Привет! Я сделаль..
![sent](https://github.com/hexlet-codebattle/codebattle/assets/26786537/d4236707-9f67-4e48-b1e5-451f00095cf9)
![notSent](https://github.com/hexlet-codebattle/codebattle/assets/26786537/bc29c413-b5d9-46aa-9e82-d98314d62b5b)
По коду, как то так -
const FeedbackWidget = () => {
  const currentUserName = useSelector(currentUserNameSelector);

  const sendToServer = (payload, success, error) => fetch('/api/v1/feedback', {
    method: 'POST',
    headers: {
      'Content-type': 'application/json',
      'x-csrf-token': window.csrf_token,
    },
    body: JSON.stringify(payload),
  })
    .then(success)
    .catch(error);

  const notificationStyles = notification => cn({
    'alert-success row mb-0 rounded-0 alert-info alert-dismissible fade show': notification === 'editSuccess',
    'alert-danger row mb-0 rounded-0 alert-info alert-dismissible fade show': notification === 'editError',
    alert: true,
  });
  const getNotificationMessage = status => {
    let message;
    switch (status) {
      case 'editSuccess': {
        message = i18n.t('Feedback sent successfully.');
        break;
      }
      default: {
        message = i18n.t('Feedback not sent.');
        break;
      }
    }
    return message;
  };

  const renderAlert = notification => {
    console.log(notification);
    const container = document.querySelector('#game-widget-root');
    const alert = document.createElement('div');
    const button = document.createElement('button');
    const span = document.createElement('span');
    alert.className = notificationStyles(notification);
    button.className = 'close';
    button.setAttribute('data-dismiss', 'alert');
    button.setAttribute('aria-label', 'Close');
    span.setAttribute('aria-hidden', 'true');
    const textNode = document.createTextNode(getNotificationMessage(notification));
    const textNodeSpan = document.createTextNode('×');
    alert.appendChild(textNode);
    span.appendChild(textNodeSpan);
    button.append(span);
    alert.append(button);
    container.insertAdjacentElement('beforebegin', alert);
  };
  return (
    <SlackFeedback
      icon={() => (
        <FontAwesomeIcon
          icon={['fas', 'rss']}
          style={{
            color: '#ee3737', width: '20', height: '20', marginRight: '8px',
          }}
        />
      )}
      theme={themes.dark}
      user={currentUserName}
      onSubmit={(payload, success, error) => sendToServer(payload)
        .then(() => {
          renderAlert('editSuccess');
          success();
        })
        .catch(() => {
          renderAlert('editError');
          return error();
        })}
    />
  );
};
Подсмотрела в файле UserSettings.
Так нормально? Или как то по другому сделать?

**Comment by ReDBrother** [comment]
Fixed
