### ISSUE TITLE
Bug: Не отображаются аватары

### ISSUE THREAD

**Issue by mootar** [hexlet-codebattle/codebattle#1289]
### Summary

Не отображаются аватары повсеместно.

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/
```

### Expected result

В правом верхнем углу отображается аватар пользователя

### Actual result

Вместо аватара отображается только контур с названием.

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by ReDBrother** [comment]
fixed

**Comment by Sh3rlock-git** [comment]
**Summary**
Не прогружается аватар пользователя

**Reproduction steps**

1. Открыть [страницу](https://codebattle.hexlet.io/users/new?locale=en&next=%2F)
2. Нажать на кнопку Sign in with Github

**Expected result**
На главной странице отображается аватар пользователя

**Actual result**
Аватар пользователя не прогружается. В Devtools, на вкладке Console, появляются ошибки

**Environment**
OS Windows 10 Pro x64
Yandex.Browser 24.1.5.736 (64-bit)

**Reproduced in version**
[6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)
![codebattle_avatar_no_load](https://github.com/hexlet-codebattle/codebattle/assets/158310621/df0bc0ed-59f5-4e81-b435-7c339b616d14)
