### ISSUE TITLE
Bug: Окно со смайлами в чате вылезает за экран (мобильная версия)

### ISSUE THREAD

**Issue by mootar** [hexlet-codebattle/codebattle#1290]
### Summary

Окно со смайлами в чате вылезает за экран смартфона (и в режиме гостя и под авторизованным пользователем).

![chat_smile_window_bug](https://user-images.githubusercontent.com/26491495/219304080-9001a9af-8668-4380-ac72-2afb14b62125.jpg)

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/
2. Нажать "Try simple battle"
3. Прокрутить экран до чата.
4. Нажать на иконку смайликов.
```

### Expected result

Окно со смайлами умещается на экране целиком

### Actual result

Окно со смайлами в чате вылезает за экран

### Browsers

Yandex Browser 23.1.4 сборка 84

### OS

VIUI Global 13.0.7 Стабильная

### Device

Xiaomi Mi 11 Lite

**Comment by Anastasia-Kim3** [comment]
Ошибка воспроизводится:
Current version: fd71526
Brouser: Google Chrome 115.0.5790.160
OS: IOS  16.5.1 (20F75)
Device: Apple Iphone 14
![image](https://github.com/hexlet-codebattle/codebattle/assets/133269405/c2bcb43e-7c84-48e7-addc-85e1cc9b0131)

**Comment by AnnaGurina** [comment]
- summary: |
    Окно со смайлами в чатах на главной и в игре не адаптировано в мобильной версии
  environment: |
    Google Chrome   Версия 115.0.5735.124 (Официальная сборка), (64 бит)
    iPhone 14
version 66f5afe
  steps-to-reproduce: |
    1. Зайти на страницу https://codebattle.hexlet.io/
    2. Авторизоваться
    3. Нажать на кнопку смайлов в чате на главной
    4. Нажать 'Create a game' (тип with a bot)
    5. Нажать 'Create battle'
    5. Нажать на кнопку смайлов в чате в игре
  expected-result: |
    Окно со смайлами в чатах на главной и в игре целиком отображается на экране 
  actual-result: |
    Окно со смайлами в чатах на главной и в игре выходит за пределы экрана.
![Фото 10 08 2023, 19 32 51](https://github.com/hexlet-codebattle/codebattle/assets/62752547/ec768940-5760-46c7-90e9-929f17aa7b39)
![Фото 10 08 2023, 19 32 39](https://github.com/hexlet-codebattle/codebattle/assets/62752547/28e7310a-2205-4eb6-8dff-e581283f842a)

**Comment by Darga113** [comment]
Summary:
    Окно со смайлами в чате вылезает за экран смартфона
steps-to-reproduce:
    1. Заходим на главный сайт
    2. Переходим на свой профиль
    3. Заходим в чат
    4. Нажимаем на кнопку смайлов в чате
expected-result:
    Пользователям должно отображаться окно смайлов в экране целиком и не вылезать за границы
actual-result:
   Окно смайлов выходит за границы экрана 
![Screenshot_9](https://github.com/hexlet-codebattle/codebattle/assets/143105877/f9a1895a-6547-4c1d-afe1-9700193d46b3)

  Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
  iPhone 14

**Comment by Darga113** [comment]
Summary:
Окно со смайлами в чате вылезает за экран смартфона
steps-to-reproduce:
1. Заходим на главный сайт
2. Листаем в низ страницы
3. Заходим в чат
5. Нажимаем на кнопку смайлов в чате
expected-result:
Пользователям должно отображаться окно смайлов в экране целиком и не вылезать за границы
actual-result:
Окно смайлов выходит за границы экрана

Google Chrome 107.0.5304.121 (Официальная сборка) (64 бит)
iPhone 14
![Screenshot_9](https://github.com/hexlet-codebattle/codebattle/assets/143105877/2cc415a8-bd9a-4da8-8b4b-aa72705811c0)

**Comment by mrworldwide2000** [comment]
- summary: Окно со смайлами в чате вылезает за экран смартфона
  environment: Iphone 12, Safari

  steps:
    - На главной странице либо в лобби нажать на кнопку смайликов в окне чата
    
  expected-result: Корректно отобразится окно со смайликами
  actual-result: Окно со смайликами отображается некорректно, не помещается на экран полностью, выходит за границы рабочей области
  
  
![photo_2023-12-10_09-02-39](https://github.com/hexlet-codebattle/codebattle/assets/147067757/d90364e2-84d1-4560-b92a-fdaf17f21d48)
![photo_2023-12-10_09-02-38](https://github.com/hexlet-codebattle/codebattle/assets/147067757/62655920-db85-4913-bd54-dc3ec1209447)
