### ISSUE TITLE
Bug: В чате не отображаются смайлики

### ISSUE THREAD

**Issue by mootar** [hexlet-codebattle/codebattle#1291]
### Summary

 В чате не отображаются: кнопка вставить смайлик, сами смайлики на выбор и смайлики непосредственно в сообщениях (и в режиме гостя и под авторизованным пользователем)
![smile_icon_bug](https://user-images.githubusercontent.com/26491495/219309321-85f154f8-2357-41b0-8939-adc30ff74d15.jpg)

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/
2. Нажать "Try simple battle"
3. Нажать на иконку смайликов
4. Нажать на любой смайлик
5. Нажать Send
```

### Expected result

Отображаются: сама кнопка, смайлики на выбор и смайлик в сообщении.

### Actual result

Сама кнопка смайликов, смайлики на выбор и смайлик в сообщении не отображаются.

### Browsers

Chrome

### OS

Windows

**Comment by Goryaminskaya** [comment]
Summary
В чате не отображаются некоторые смайлики (и в режиме гостя и под авторизованным пользователем)
Reproduction steps
1. Зайти на https://codebattle.hexlet.io/
2. Нажать "Try simple battle"
3. Нажать на иконку смайликов в чате 
4. Не все смайлы отображаются

Expected result
Отображаются:  смайлики на выбор и смайлик в сообщении.

Actual result
Смайлики отображаются не все. 

Browsers
Яндекс. Версия 23.1.3.949 (64-bit)

OS
Windows
![Снимок экрана (49)](https://user-images.githubusercontent.com/120749983/221013331-dc873d3a-0617-4ad6-9a72-12fc75c8d8d3.png)

**Comment by alexamuek** [comment]
- summary: |
    В сообщениях другим пользователям нельзя выбрать и отправить символы Emoji
  environment: |
    Google Chrome Версия 114.0.5735.198 (Официальная сборка), (64 бит)
    ОС Linux Mint
  steps-to-reproduce: 
    - Авторизоваться на сайте
    - В поле для ввода сообщений на странице лобби нажать на изображение смайлика
    - Выбрать смайлик
    - Нажать на кнопку "Send"
  expected-result: |
    Соощение с изображением смайлика должно быть отправлено
  actual-result: |
    В сообщениях нельзя выбрать и отправить символы Emoji

**Comment by nonambarneo** [comment]
summary: |
В чат можно отправить заранее подготовленные смайлы
environment: |
Google Chrome Версия 116.0.5845.180 (Официальная сборка), (64 бит)
ОС Windows 10 Pro 22H2
steps-to-reproduce:
1 Авторизоваться на сайте
2 В поле для ввода сообщений на странице лобби нажать на изображение смайла
expected-result: |
Появляется окно выбора смайлов
actual-result: |
Кнопка выбора смайлов не реагирует на нажатия
![image](https://github.com/hexlet-codebattle/codebattle/assets/134539313/dc08d0b4-b9f2-4be5-9cd4-1fc3737201a4)

**Comment by Midire99** [comment]
summary: |
В сообщениях чата нельзя отправить смайл
environment: |
Safari   Версия 16.5.1 (18615.2.9.11.7)
macOS Ventura 13.4.1
steps-to-reproduce:
1 Авторизоваться на сайте
2 В поле для ввода сообщений на странице лобби нажать на изображение смайла
expected-result: |
Появляется окно выбора смайлов
actual-result: |
Кнопка выбора смайлов не реагирует на нажатия

**Comment by St1leXX** [comment]
Баг воспроизводится

  prerequisites: 
    Открыта главная страница Codebattle с авторизованным пользователем
  test-data:
     Codebattle version: ef4c0b9
  steps:
    - В поле ввода сообщений нажать на эмодзи
    - Выбрать эмодзи
    - Нажать на кнопку "Send" для его отправки
  expected-result:
    Эмодзи отправится в чат
  actual result: 
    Иконка эмодзи не нажимается
![смайл](https://github.com/hexlet-codebattle/codebattle/assets/129951745/faaac767-2271-4768-822c-20d3a9252829)

**Comment by denikeev** [comment]
беру в работу

**Comment by denikeev** [comment]
создал PR https://github.com/hexlet-codebattle/codebattle/pull/1629

**Comment by 4Jul** [comment]
При тестировании данного кейса, видно, что баг пофиксили: теперь можно в игре в поле чата выбрать смайл и отправить сообщение 
![issue 6](https://github.com/hexlet-codebattle/codebattle/assets/142840489/acf6f384-ad2b-4086-9f29-947d602347e1)
![issue 7](https://github.com/hexlet-codebattle/codebattle/assets/142840489/18e9efcb-2c0a-4c26-829d-773d604da1cc)
