### ISSUE TITLE
Bug: Некорректные пропорции аватара при просмотре информации о пользователях через вкладки Tournaments (мобильная версия)

### ISSUE THREAD

**Issue by mootar** [hexlet-codebattle/codebattle#1292]
### Summary

Некорректные пропорции аватара при просмотре информации о пользователе при переходе из вкладки Tournaments -> Tournaments info.

![avatar_resolution_bug](https://user-images.githubusercontent.com/26491495/219315206-0bdfc49b-f6d6-4226-aa56-bd4e8be83f43.jpg)

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/
2. Выбрать вкладку Tournaments
3. Нажать Tournaments info
4. Прокрутить вбок до столбца players
5. Нажать на любой аватар (серая полоса на момент написания багрепорта)
```

### Expected result

В открывшемся окне отображается аватар пользователя в корректной пропорции

### Actual result

Аватар деформирован (вытянут вверх)

### Browsers

Chrome

### OS

Android 11

### Device

Pixel 2 XL Build/RP1A.201005.004.A1

**Comment by sonnungr** [comment]
баг актуален  при использовании DevTools параметры Dimensions:Responsive: iPhone XR
Reproduction steps:
   - открыть https://codebattle.hexlet.io/
   - нажать f12,зайти в DevTools
   - нажать toggle Device toolbar
   - в строке Dimensions:Responsive выбрать параметры:iPhone XR
   - в таблице Leaderboard нажать на ссылку TOP list
   - открыть в таблице user любого пользователя
   Expected result
   аватар пользователя выглядит в искаженном виде
![qqqq](https://user-images.githubusercontent.com/120249683/219853691-099c439d-8618-4253-8afe-e11576ec3996.png)

**Comment by likurg42** [comment]
Беру в работу

**Comment by ReDBrother** [comment]
Иконки выровнили
