### ISSUE TITLE
Bug:  Не отображается выпадающий список "Task pack name" при создании турнира с параметром  "Type = stairway"

### ISSUE THREAD

**Issue by Anel1608** [hexlet-codebattle/codebattle#1294]
### Summary

Не отображается выпадающий список "Task pack name" при создании турнира с параметром  "Type = stairway"

### Reproduction steps

```bash
- Открываем меню нажатием на "аватар"
- Нажимаем кнопку "Tournaments"
- В текстовое поле "Name" вводим название турнира
- Выбираем  "Type" = "Stairway"
- Выбираем "Task pack name"
- Выбираем "starts at(utc)"
- Выбираем "Default language
- Прописываем "Match timeout in seconds"
- Нажимаем кнопку "Create"
```

### Expected result

Создается турнир с выбранными параметрами

### Actual result

Параметр "Task pack name" выбрать невозможно
![photo_2023-02-16_12-08-39](https://user-images.githubusercontent.com/119662501/219320286-64e5b75e-3c14-4520-814f-f8a5a6757bbc.jpg)

### Browsers

Яндекс

### OS

Windows

**Comment by ReDBrother** [comment]
fixed
