### ISSUE TITLE
Bug:  Можно ввести недопустимые символы в форме при создании турнира

### ISSUE THREAD

**Issue by borizi** [hexlet-codebattle/codebattle#1296]
### Summary

Можно ввести недопустимые символы в форме при создании турнира

### Reproduction steps

```bash
1. Открыть страницу "Tournaments" (https://codebattle.hexlet.io/tournaments)
2. Ввести в поле "Match timeout in seconds" вместо установленных по умолчанию цифр символы "++".
```

### Expected result

Символы ввести невозможно, поле становится пустым.

### Actual result

В поле появляются символы "++". Форма не сигнализирует об ошибках ввода.
![Возможность ввода символов вместо цифр в таймауте](https://user-images.githubusercontent.com/64551423/219375480-3fbac357-34ef-4858-9540-05160b4973c1.jpg)

### Browsers

Microsoft Edge
Версия 110.0.1587.41 (Официальная сборка) (64-разрядная версия)

### OS

Windows 11 Pro Сборка 22000.1574

**Comment by ReDBrother** [comment]
У нас нет недопустимых символов)
