### ISSUE TITLE
Bug:  Можно ввести символы не по маске в форме при создании турнира

### ISSUE THREAD

**Issue by borizi** [hexlet-codebattle/codebattle#1298]
### Summary

Bug:  Можно ввести символы не по маске в форме при создании турнира

### Reproduction steps

```bash
1. Открыть страницу "Tournaments" (https://codebattle.hexlet.io/tournaments)
2. Ввести в поле "Starts at (UTC)" дату 12.11.245454
```

### Expected result

При вводе года в поле невозможно ввести больше 4 цифр, как показано в маске:
![Форма даёт ввести количество цифр не по маске в графе Starts at_состояние по умолчанию](https://user-images.githubusercontent.com/64551423/219378146-c0f0ed50-6b24-47fc-bce0-8778e0afec44.jpg)

### Actual result

Поле даёт ввести 6 цифр при вводе года:

![Форма даёт ввести количество цифр не по маске в графе Starts at](https://user-images.githubusercontent.com/64551423/219378594-ca153359-51bd-402a-ab98-67f397dd8d45.jpg)

### Browsers

Microsoft Edge
Версия 110.0.1587.41 (Официальная сборка) (64-разрядная версия)

### OS

Windows 11 Pro Сборка 22000.1574

**Comment by 2KO1** [comment]
Воспроизводится:
Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

**Comment by ReDBrother** [comment]
Дата не является важной для механики параметром. Он нужен только для таймера.
