### ISSUE TITLE
Исправление логики игры

### ISSUE THREAD

**Issue by krivtsov** [hexlet-codebattle/codebattle#130]
- [x] 404 ошибка при вызове не сушествующей игры
- [x] если игрок окончил игру и зашёл в неё вновь как спектатор, то кнопка `check` остаётся для него и вызывает ошибки. Нужно её убрать.
- [x] после создания игры игроком, убрать подключения к ней повторно.  (игра с самим собой)
- [x]  запрет спектатору проверять (и заканчивать) игру.

**Comment by PeresvetS** [comment]
Closed #135 #139
