### ISSUE TITLE
Bug: Не умещается часть информации в профиле игрока-мультиязычника с большим количеством боев (мобильная версия)

### ISSUE THREAD

**Issue by mootar** [hexlet-codebattle/codebattle#1303]
### Summary

Некорректно отображается часть описания треугольника lost/won/gave_up и "пиццы" использования языков для пользователей с большим числом языков и/или игр. (мобильная версия)
![profile_portrait_orientation](https://user-images.githubusercontent.com/26491495/219847847-f1b469c8-305a-4aa8-957a-754c3b88b090.jpg)
![profile_landscape_orientation](https://user-images.githubusercontent.com/26491495/219847854-b48998b2-57b1-4ee2-88ab-ae8cdef809a5.jpg)

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/ и авторизоваться
2. Найти пользователя-мультиязычника с большим количеством игр и перейти в его профиль
3. Прокрутить до статистики боев/языков
```

### Expected result

Вся информация в 100% объеме видна на экране смартфона

### Actual result

Часть информации не видна или видна частично

### Browsers

Chrome    /   Yandex Browser 23.1.4 сборка 84

### OS

Android 11   /   VIUI Global 13.0.7 Стабильная

### Device

Pixel 2 XL Build/RP1A.201005.004.A1   /   Xiaomi Mi 11 Lite

**Comment by sonnungr** [comment]
баг актуален при использовании DevTools и выбора параметра в строке Dimensions:Responsive: iPhone XR
![bug1](https://user-images.githubusercontent.com/120249683/219851000-14638555-d9d4-4a10-bd6e-0186bafb936b.png)

**Comment by sonnungr** [comment]
баг актуален при использовании DevTools и выбора параметра в строке Dimensions:Responsive: iPhone XR
![bug11](https://user-images.githubusercontent.com/120249683/219851203-7ff124c0-6d0f-43bd-9574-67b792d5ace9.png)

**Comment by ReDBrother** [comment]
fixed
