### ISSUE TITLE
Bug: не выровнены параметры поиска в мобильной версии

### ISSUE THREAD

**Issue by sonnungr** [hexlet-codebattle/codebattle#1304]
### Summary

параметры поиска не выровнены по сетке в мобильной версии игры

### Reproduction steps

```bash
- открыть https://codebattle.hexlet.io/
- нажать f12,зайти в DevTools
- нажать toggle Device toolbar
- в строке Dimensions:Responsive выбрать параметры:iPhone XR
- в таблице Leaderboard нажать на ссылку TOP list
- в поиске ввести любые значения
```

### Expected result

параметры поиска должны быть выровнены по сетке

### Actual result

параметры Rank, User, Rating, Games played не выровнены в мобильной версии
![wwwwww](https://user-images.githubusercontent.com/120249683/219854120-959cc016-f080-4288-b3a7-a7a2d5e4b8fb.png)

### Browsers

Chrome

### OS

Windows

**Comment by likurg42** [comment]
Беру в работу

**Comment by ReDBrother** [comment]
Выровнили
