### ISSUE TITLE
Bug: Нет возможности предложения игры другому онлайн пользователю

### ISSUE THREAD

**Issue by sonnungr** [hexlet-codebattle/codebattle#1305]
### Summary

отсутствует функция предложения игры пользователю который находится онлайн

### Reproduction steps

```bash
- зайти на сайт https://codebattle.hexlet.io/
   - найти на главной страницу графу Online players
   - выбрать онлайн игрока
```

### Expected result

должна быть осуществлена возможность предложения игры другому онлайн игроку

### Actual result

при выборе пользователя из столбца Online players показана статистика его игр без возможности предложения игры
![players](https://user-images.githubusercontent.com/120249683/219855604-85d4ad50-c6dc-4da0-8652-16a37a45a7fd.png)

**Comment by EEMinch** [comment]
**- summary:** 
Нет возможности предложения игры другому онлайн пользователю без помощи чата  

**- environment:** 
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит)
Mozilla Firefox 110.0 (64-разрядный)
ОС Windows 10

**- steps-to-reproduce:**

1. Заходим на https://codebattle.hexlet.io/ под авторизованным пользователем
2. Прокрутить главную страницу до конца
3. Навести курсор на одного из онлайн игроков

**- expected-result:**
Должен появиться инструмент для возможности предложения игры онлайн пользователю

**- actual-result:**
Нет возможности предложения игры другому онлайн пользователю

![image](https://user-images.githubusercontent.com/120366598/221667448-b2a4f8e5-90cc-4ac4-9aff-c8d96aa82ba3.png)

![image](https://user-images.githubusercontent.com/120366598/221667478-86bc030d-5c7f-42e3-b766-251a8761cd0d.png)

**Comment by 2KO1** [comment]
Функцию "Invite" стоит также распространить и на "LEADERBOARD" во всех вкладках, чтобы можно было бы вызвать на дуэль лидера рейтинга например

**Comment by ReDBrother** [comment]
Инвайты мы будем разрешать только онлайн пользователям. По этой же причине приглашаем только в лобби или в игровой комнате.
