### ISSUE TITLE
Bug: нет плашки при слабом соединении

### ISSUE THREAD

**Issue by sonnungr** [hexlet-codebattle/codebattle#1306]
### Summary

при слабом соединении с игрой нет оповещения

### Reproduction steps

```bash
открыть открыть https://codebattle.hexlet.io/
   нажать f12,зайти в DevTools
   зайти во вкладку Network
   выбрать параметр Slow 3G
   выбрать из таблицы LOBBY игрока
   нажать Fight
```

### Expected result

должна быть плашка о слабом соединении с игрой 

### Actual result

на странице игры должно быть оповещение о слабом соединении

### Browsers

Chrome

### OS

Windows

**Comment by ValeriaStroeva** [comment]
Баг воспроизводится.

- summary: |
    Отсутствует информационное сообщение при отсутствии интернета
  environment: |
    Google Chrome Версия 110.0.5481.177 (Официальная сборка), (arm64)
    OC macOS Ventura 13.1
  steps-to-reproduce: |
    Зайти на страницу сайта при выключенном интернете
  expected-result: |
    На главной странице появляется сообщение об отсутствии интернета
  actual-result: |
    На странице ничего не происходит.
    Ошибка изображена на скриншоте internet.png
<img width="1336" alt="internet" src="https://user-images.githubusercontent.com/74196783/224403683-f4de9bd7-25e2-423b-be36-ee36b9ee76fb.png">

**Comment by Nackles999** [comment]
Баг воспроизводится.

Summary:
Нет плашки при медленном интернете 
environment:
Google Chrome   109.0.5414.75 (Официальная сборка), (64 бит)
OC Windows 10 21H2 64-bit
Steps-to-reproduce:
- Зайти на главную страницу сайта
- Зайти в DevTools 
- Выбрать параметр "Low-end mobile"
Expected-result:
На главной странице появляется сообщение об отсутствии интернета
actual-result:
Сообщение не приходит
![Баг 3](https://user-images.githubusercontent.com/121425048/224671753-99cb1fe7-6835-43ba-88c0-6b57225655b0.png)

**Comment by Makarova94** [comment]
- summary: |
    При слабом интернет соединении нет информационного оповещения 
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
     - Открыть главную страницу сайта
    - Зайти в DevTools
    - Нажать на вкладку "Network"
    - Поменять скорость интерент соединения на "Slow 3G"
   
  expected-result: |
    Веб-сайт корректно прогружается. На странице игры должно быть оповещение о слабом интернет соединении 
  actual-result: |
   Сообщение не приходит. На странице ничего не происходит

**Comment by ReDBrother** [comment]
Оно появляется довольно поздно, потому что дефолт интервала между проверками соединения в сокетном соединении крайне большой.

Нужно будет найти баланс при установлении соединения с сервером, чтобы сильно не увеличить трафик.

**Comment by vtm9** [comment]
мы решили что это слишком сложная для нас фича
