### ISSUE TITLE
Bug: Нет возможности удалить личное сообщение из общего чата

### ISSUE THREAD

**Issue by AllaLoginova** [hexlet-codebattle/codebattle#1308]
### Summary

Нет возможности удалить личное сообщение из общего чата

### Reproduction steps

```bash
1. Перейти в лобби
2. Написать любой текст в строке под чатом
3. Нажать кнопку "Отправить"
```

### Expected result

Написанное сообщение можно удалить 

### Actual result

**Написанное сообщение удалить невозможно**

![2023-02-19_10-29-38](https://user-images.githubusercontent.com/122536827/219926819-b75e781a-b7c8-4786-8e26-69dc61ec3b42.png)

### Browsers

Chrome

### OS

Windows

**Comment by MashaMelon** [comment]
- summary: 
    Нет возможности редактировать и удалить свое сообщение из часа
  environment: 
    Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
    Opera Версия:94.0.4606.38
    Yandex Версия 22.11.3.818 (64-bit)
    Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)
  steps-to-reproduce: 
    Авторизоваться
    Написать сообщение в чат
    Отредактировать сообщение
    Удалить сообщение
  expected-result: 
    Сообщение редактируется и удаляется
  actual-result: 
    Нет возможности редактировать и удалять свои сообщения

**Comment by EEMinch** [comment]
- summary: |
     Нет возможности удалить свое сообщение из общего чата
- environment: |
     Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит)
     Mozilla Firefox 110.0 (64-разрядный)
     ОС Windows 10
- steps-to-reproduce: |

1.  Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем
2.  Прокрутить главную страницу до конца
3.  Написать любой текст в строке под общим чатом
4.  Нажать кнопку «Send»

- expected-result: |
    Отправленное сообщение можно удалить из общего чата
- actual-result: |
   Личное сообщение никак нельзя удалить из общего чата

![image](https://user-images.githubusercontent.com/120366598/221661930-e8845514-3663-473b-a342-1fa2f765a891.png)

**Comment by ValeriaStroeva** [comment]
Баг воспроизводится.

- summary: |
    Нет возможности удалить сообщение из общего чата
  environment: |
    Google Chrome Версия 110.0.5481.177 (Официальная сборка), (arm64)
    OC macOS Ventura 13.1
  steps-to-reproduce: |
    - Зайти на сайт
    - Авторизоваться зарегистрированным пользователем
    - Написать любой текст в строке под общим чатом
    - Нажать кнопку «Send»
  expected-result: |
    Отправленное сообщение можно удалить из общего чата
  actual-result: |
    Нет возможности удалить сообщение из общего чата
    Ошибка изображена на скриншоте message.png
<img width="1324" alt="message" src="https://user-images.githubusercontent.com/74196783/224405343-e91ec18a-f703-4a22-bdbf-822651dd7075.png">

**Comment by ipsdv** [comment]
summary:
Нет возможности редактировать и удалить свое сообщение из часа
environment:
Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Opera Версия:94.0.4606.38
Yandex Версия 22.11.3.818 (64-bit)
Microsoft Edge 108.0.1462.54 (Официальная сборка) (64-разрядная версия)
steps-to-reproduce:
Авторизоваться
Написать сообщение в чат
Отредактировать сообщение
Удалить сообщение
expected-result:
Сообщение редактируется и удаляется
actual-result:
Нет возможности редактировать и удалять свои сообщения

**Comment by Nackles999** [comment]
Summary:
Нет возможности удалить сообщение из чата
environment: 
Google Chrome 109.0.5414.75 (Официальная сборка), (64 бит)
OC Windows 10 21H2 64-bit
steps-to-reproduce:
- Зайти на сайт
- Авторизоваться 
- Написать любое сообщение 
- Нажать кнопку "Send"
expected-result:
Сообщение можно удалять из общего чата 
actual-result:
Сообщение нельзя удалить из общего чата 
![аг 3](https://user-images.githubusercontent.com/121425048/224665232-3b7da398-d253-47fe-8dd3-53484d5958b2.png)

**Comment by vikahati** [comment]
1. Перейти в лобби
2. Написать любой текст в строке под чатом
3. Нажать кнопку "Отправить"

Воспроизводится на Browser: Yandex;    OS: Linux

**Comment by ReDBrother** [comment]
Чат содержит намеренно укороченный функционал, по аналогии с онлайн играм. Это не форум или месенджер, в котором художественность текста играет важную роль. Чат обслуживает базовую коммуникацию, чтобы понимать что в целом происходит.

Для общения уже есть мессенджеры и форумы.
