### ISSUE TITLE
Bug:  Не отображается аватар игрока в браузере Microsoft Edge

### ISSUE THREAD

**Issue by MacKP89** [hexlet-codebattle/codebattle#1312]
### Summary

Не отображается аватар игрока в браузере Microsoft Edge

### Reproduction steps

```bash
1. Открыта страница https://codebattle.hexlet.io/
2. Нажимаем кнопку Sign in
3. Вводим существующие логин и пароль
4. нажимаем Submit
```

### Expected result

В верхнем правом углу отображается аватар игрока

### Actual result

В верхнем правом углу отображается не прогруженная картинка
![Не прогружается аватар Microsoft Edge](https://user-images.githubusercontent.com/119846763/219966996-1e9fe42b-1dff-4512-bcaa-c104a93d620b.png)

### Browsers

Microsoft Edge Версия 110.0.1587.50 (Официальная сборка) (64-разрядная версия)

### OS

Windows 11 Домашняя Версия 21H2 Сборка 22000.1455

**Comment by ReDBrother** [comment]
Edge мы не особо поддерживаем))
