### ISSUE TITLE
Bug: Активная кнопка "Give up" при просмотре завершенной игры

### ISSUE THREAD

**Issue by Its-Kate** [hexlet-codebattle/codebattle#1313]
### Summary

При просмотре собственной завершенной игры пользователь может нажать значок "Give up" 

### Reproduction steps

```bash
1. В своем профиле открываем вкладку "Completed games"
2. Нажимаем "Show" напротив любой вашей завершенной игры
3. Когда на экране появляется запись игры, нажимаем на значок "Give up"
```

### Expected result

При просмотре записи игр, кнопки управлением игрой должны быть не активны или скрыты.

### Actual result

<img width="1434" alt="GiveUp" src="https://user-images.githubusercontent.com/122304486/219981619-19f4f490-33b9-447d-81d9-44a40cb6aa2f.png">

### Browsers

Chrome

### OS

Mac

**Comment by EEMinch** [comment]
Еще буквально вчера тоже видела данный баг, но сегодня он уже не воспроизводится. Видимо починили и не отписались

![image](https://user-images.githubusercontent.com/120366598/221656829-a406c19b-f6a1-4fd1-a7c2-f4a5ce34f2a1.png)

**Comment by 2KO1** [comment]
@EEMinch воспроизводили собственную игру?

**Comment by 2KO1** [comment]
Воспроизводится:
Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

**Comment by ReDBrother** [comment]
fixed
