### ISSUE TITLE
Bug: Искажение отображения кнопки "OUTPUT" в игре

### ISSUE THREAD

**Issue by Anel1608** [hexlet-codebattle/codebattle#1314]
### Summary

Не отображается название кнопки "OUTPUT" в игре

### Reproduction steps

```bash
1. Создать битву "Create a game"
```

### Expected result

Все кнопки отображаются корректно.

### Actual result

![output](https://user-images.githubusercontent.com/119662501/220060214-18b9ef78-bc19-486b-a405-e70a2ceb8b3e.jpg)

### Browsers

Яндекс

### OS

Windows

**Comment by 2KO1** [comment]
@Anel1608 не воспроизводится, есть ли дополнительные условия? версия ОС и Браузера?

**Comment by Anel1608** [comment]
> @Anel1608 не воспроизводится, есть ли дополнительные условия? версия ОС и Браузера?
Яндекс Браузер Версия
23.1.4.779 (64-bit)
Windows 11 версия 21H2

**Comment by 2KO1** [comment]
@Anel1608 в любом виде игры так?

**Comment by Anel1608** [comment]
> @Anel1608 в любом виде игры так?

Проверяла на игре с ботом

**Comment by 2KO1** [comment]
Спасибо

**Comment by ReDBrother** [comment]
Fixed
