### ISSUE TITLE
Bug:Не отображается иконка языка программирования в Профиле и Hover message

### ISSUE THREAD

**Issue by Its-Kate** [hexlet-codebattle/codebattle#1315]
### Summary

Не отображаются иконки языков программирования JavaScript, TypeScript и  Go в профиле пользователя и в "Hover message" 

### Reproduction steps

```bash
1. Заходим в настройки профиля "Settings" 
2. В меню DropDown "Your weapon" выбираем JavaScript
3. Нажимаем на кнопку "Save" 
4. Заходим в "My Profile"
```

### Expected result

На странице профиля и  в "Hover Message" отображается иконка выбранного языка

### Actual result

Иконка языка программирования не отображается 
<img width="1251" alt="iconJscript" src="https://user-images.githubusercontent.com/122304486/220174067-30d376b9-f89d-4b05-98b0-16a544a794cb.png">
<img width="1427" alt="HoverM" src="https://user-images.githubusercontent.com/122304486/220174070-8680fff5-9f95-4ec7-b176-2b9aabb96ccd.png">

### Browsers

Chrome

### OS

Mac

**Comment by AnastasiaKv** [comment]
пр #1346
