### ISSUE TITLE
Feature: Edit profile avatar

### ISSUE THREAD

**Issue by kontok** [hexlet-codebattle/codebattle#1320]
### Summary

Отсутствует возможность изменения аватара пользователя в настройках профиля

### Reproduction steps

```bash
1. Авторизация пользователя с помощью "email" и "password"
2. На главной странице нажимаем на имя пользователя
3. В появившемся меню нажимаем "Settings"
```

### Expected result

На главной странице отображается новый аватар для текущего пользователя

### Actual result

В настройках пользователя нет возможности изменить "Аватар пользователя"

![image](https://user-images.githubusercontent.com/35772879/220361834-a7689ae8-4341-401d-9f3c-3bd6ab1acb6d.png)

Тестовое изображение
![123](https://user-images.githubusercontent.com/35772879/220362184-8de69318-9cab-42fd-9be7-40a6b469179e.jpg)

### Browsers

Chrome

### OS

Windows

**Comment by Germankhz** [comment]
Как вариант можно реализовать изменение аватара в разделе My Profile, где уже отображается некий аватар, кликнув по которому будет появляться окно выбора файла.

  steps:
    - Щелкнуть по имени пользователя в правом верхнем углу страницы
    - В выпадающем меню выбрать пункт My Profile
    - В левой верхней части страницы кликнуть по области фотографии пользователя
    - В появившемся окне выбрать файл для установки в качестве фото пользователя
    - Нажать ОК
  
  
![1](https://user-images.githubusercontent.com/119713022/221458267-fe3a765c-a29e-41f4-a92b-586befb8e036.jpg)

**Comment by kontok** [comment]
Как вариант реализации, можно попробовать в настройках пользователя добавить кнопку "Choise avatar" и реализовать следующих функционал:
1. Нажатие на кнопку "Choise avatar"
2. Выбираем и загружаем файл "123.jpg"
3. Нажимаем "Ok"
4. Нажимаем "Save"
5. Переходим на главную страницу сайта

**Comment by EEMinch** [comment]
**- summary: |**
Невозможно изменить аватар пользователя в настройках личного профиля

**- environment: |**
Mozilla Firefox 110.0 (64-разрядный)
ОС Windows 10

**- steps-to-reproduce: |**
1. Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем
2. Кликнуть по имени пользователя в верхнем правом углу страницы
3. В выпадающем меню выбрать «My Profile»
4. На открывшейся странице пользователя кликнуть по области фотографии

**- expected-result: |**
Появляются инструменты для загрузки и сохранения фотографии 

**- actual-result: |**
Аватар невозможно изменить в профиле пользователя

![image](https://user-images.githubusercontent.com/120366598/221663518-76ed6a40-f64e-49b9-860c-a82304495cb2.png)

**Comment by 2KO1** [comment]
@kontok тут также наверное "enhancement-proposal"?

**Comment by ValeriaStroeva** [comment]
Баг воспроизводится.

- summary: |
    Нет возможности изменить аватар пользователя
  environment: |
    Google Chrome Версия 110.0.5481.177 (Официальная сборка), (arm64)
    OC macOS Ventura 13.1
  steps-to-reproduce: |
    - Зайти на сайт
    - Авторизоваться зарегистрированным пользователем
    - Кликнуть по имени пользователя в верхнем правом углу страницы
    - В выпадающем меню выбрать «My Profile»
  expected-result: |
    Есть возможность изменить аватар пользователя
  actual-result: |
    Нет возможности изменить аватар пользователя
    Ошибка изображена на скриншоте avatar.png
<img width="1326" alt="avatar" src="https://user-images.githubusercontent.com/74196783/224406875-7f593adb-d844-4465-bab0-b12a2a03ecc9.png">

**Comment by den1523** [comment]
**- summary: |**
Невозможно изменить фотографию профиля.

**- environment: |**
Yandex 23.1.2.978 (64-bit)
MacOs Mojave

**- steps-to-reproduce: |**

    1. Авторизоваться на сайте.
    2. На главной странице нажимаем справа на иконку с картинкой.
    2. Выбираем My Profile.

**- expected-result: |**
Пользователь должен увидеть инструменты для изменения фотографии.

**- actual-result: |**
Инструменты для изменения фотографии пользователя отсутствуют.

**Comment by vikahati** [comment]
1. Авторизоваться на сайте.
2. На главной странице нажимаем справа на иконку с картинкой.
2. Выбираем My Profile.

Воспроизводится на Browser: Yandex   OS: Linux

**Comment by Linsept** [comment]
![Снимок экрана 5](https://github.com/hexlet-codebattle/codebattle/assets/130752518/38c31d1b-b79a-400a-b1ba-4d871b747cb1)
- summary: |
    Смена аватарки в профилю
  environment: |
    Google Chrome   49.0.2623 (Официальная сборка) (64 бит)
    ОС Windows 10 20h2
  steps-to-reproduce: |
    1. Зайти на страницу сайта https://codebattle.hexlet.io
    2. Войти в профиль
    3. Нажать на свой никнейм на верхней панели сайта
    4. В открывшемся окне нажать на кнопку "My Profile"
    5. На открывшейся странице нажать на окно аватарки
    6. Добавить любое изображение для аватарки
  expected-result: |
    Аватарка профиля сменилась
  actual-result: |
    На странице "My Profile" нельзя изменить изображение аватарки

**Comment by Katidem62** [comment]
- summary: |
    Невозможно изменить аватар пользователя в настройках профиля
  environment: |
    Яндекс браузер (Официальная сборка) (64 бит)
    Windows 10
  steps-to-reproduce: |
    1. Авторизация пользователя с помощью "email" и "password"
    2. На главной странице нажимаем на имя пользователя
    3. В появившемся меню нажимаем "Settings"
  expected-result: |
    На главной странице отображается новый аватар для текущего пользователя
  actual-result: |
    В настройках пользователя нет возможности изменить "Аватар пользователя"

**Comment by ReDBrother** [comment]
Когда нибудь добавим такой функционал, но не скоро(

**Comment by ReDBrother** [comment]
Придумали как разработать эту фичу
Уберем в пользу #1733

**Comment by Katya11061994** [comment]
Редактирование фото профиля

Шаги для воспроизведения: 
    - Войти в профиль
    - Нажать на кнопку на верхней панели со своим псевдонимом
    - Нажать на кнопку "Мой профиль"
    - 
Ожидаемый результат: 
Пользователь должен иметь возможность изменить фото профиля

Фактический результат: 
Кнопка "Редактировать фото" отсутствует

![Снимок экрана от 2024-12-09 17-18-03](https://github.com/user-attachments/assets/a0abf51c-1574-4a44-ba39-eaf9f153403c)

**Comment by AntonyDn** [comment]
MacOS 15.6.1 (24G90)
Safari 18.6 (20621.3.11.11.3)
Version: 68f356b
