### ISSUE TITLE
Столбцы Присоединился и Гитхаб Рейтинга пользователей выходят за пределы вёрстки в русской локализации

### ISSUE THREAD

**Issue by Mayday4221** [hexlet-codebattle/codebattle#1323]
**summary:** 
    Столбцы Присоединился и Гитхаб Рейтинга пользователей выходят за пределы вёрстки в русской локализации

  **steps:**
    - Перейти на страницу веб-приложения "CodeBattle" по ссылке (https://codebattle.hexlet.io/)
    - Нажимаем правую кнопку мыши
    - Выбираем "Перевести страницу на русский язык"
    - Кликаем по своему профилю в правом верхнем углу 
    - Кликаем Рейтинг пользователей
    
  **expected-result:**
    Столбцы Присоединился и Гитхаб Рейтинга пользователей должны находится в пределах вёрстки в русской локализации 
    
OS  Windows 7
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

![Prnt1](https://user-images.githubusercontent.com/121160308/220372616-154052f5-b2e0-4420-abab-cf1e08e52b52.JPG)

**Comment by ReDBrother** [comment]
Дубль от https://github.com/hexlet-codebattle/codebattle/issues/1487
