### ISSUE TITLE
Bug: Главная страница не адаптирована к мобильной версии

### ISSUE THREAD

**Issue by MashaMelon** [hexlet-codebattle/codebattle#1325]
### Summary

При включении мобильной версии для авторизованного пользователя главная страница не адаптируется

### Reproduction steps

```bash
1. Авторизоваться
2. Открыть DevTools
3. Переключить формат экрана на Samsung Galaxy S 20 Ultra
4. Переключить формат экрана на iPhone 13 Pro
```

### Expected result

Страница адаптирована к мобильной версии 

### Actual result

Страница не адаптирована к мобильной версии. Пользователь вынужден скроллить по горизонтали
![image](https://user-images.githubusercontent.com/119728571/221137562-64b698d3-3522-4f39-aa39-2abccb0a08dd.png)
![image](https://user-images.githubusercontent.com/119728571/221137773-76f1540e-72ac-4446-ac07-e6fb9665638a.png)

### Browsers

Chrome

### OS

Windows

**Comment by StasVorobyev** [comment]
- summary: |
    Проверка адаптивности главной страницы на мобильном устройстве
  requirement: |
    Главная страница должна быть адаптированна под мобильное устройство
  prerequisites: |
    Открыта главная станица в браузере Chrome
  test-data: |
    Нет данных
  steps:
    - Нажать кнопку F12 (Dev Tools)
    - Нажать сочетание клавишь Ctrl+Shift+M
    - Выбрать в выпадающем списке устройство iPhone SE
  expected-result: |
    Страница адаптирована под мобильное устройство

![bagreport1](https://user-images.githubusercontent.com/121265452/221427616-8b54e620-2a8d-4cd6-bc08-665f8816f15b.png)

**Comment by ALBERTO3ABP** [comment]
summary: |
    Нет мобильной версии сайта

environment: |
    ОС: Android 12
    Браузер: Яндекс Браузер

steps-to-reproduce: |
    1. Пройти авторизацию https://codebattle.hexlet.io/session/new?locale=en&next=%2F
    2. На мобильном устройстве через Яндекс Браузер открыть https://codebattle.hexlet.io/#lobby
    3. Нажать кнопку CREATE A GAME
    4. Нажать кнопку With a bot
    5. Нажать кнопку Create Battle
    6. Перейти в редактор кода
    
expected-result: |
    Сайт удобно пользоваться на мобильных устройствах

actual-result: |
    Сайт не адаптирован под мобильные устройства
    
    
![EnTy8WZtnpA](https://user-images.githubusercontent.com/121248340/224095978-95e4c35f-5d1d-4976-a6b2-094ca5876d24.jpg)

**Comment by Freigos** [comment]
Все ещё воспроизводится баг.

ОС: Android 12
Браузер: Google Chrome

**Comment by Ekaterina1913** [comment]
- summary: |
    Сайт должен быть удобным на мобильном устройстве
  requirement: |
     Главная страница должна быть адаптирована к мобильной версии
  prerequisites: |
    Открыта главная страница сайта
  test-data: |
    Мобильное устройство iPhone Xs, OC- iOS 16.3
  steps:
    - Открыть главную страницу сайта, Выбрать раздел Completed games, Выбрать раздел Lobby
  expected-result: |
Разделы расположены неудобно, часть текста не видна на экране.

![IMG_2778р](https://user-images.githubusercontent.com/123669802/232280511-cc7e02cd-30e
![IMG_2779ек](https://user-images.githubusercontent.com/123669802/232280516-5641f8c8-5db4-40c3-abdc-90dfd63c658b.PNG)
a-43f5-8beb-51f0fbe41296.PNG)

![наа](https://user-images.githubusercontent.com/123669802/232280524-a1710d46-79cd-41a0-b8db-2bd3dfd836ae.PNG)

**Comment by katrytikova** [comment]
воспроизводится
Android 13
Chrome 113.0.5672.163
![photo_2023-06-05 13 29 43](https://github.com/hexlet-codebattle/codebattle/assets/122362310/9d4687cd-cf42-4118-948b-12a144fda9f6)

**Comment by ReDBrother** [comment]
Адаптировать список игр точно не получится. Слишком много контента и скролить там придется.
Для остального у нас есть такой тикет: https://github.com/hexlet-codebattle/codebattle/issues/1441
