### ISSUE TITLE
Bug: Невозможно создать баттл в Safari

### ISSUE THREAD

**Issue by polinatswet** [hexlet-codebattle/codebattle#1326]
### Summary

Баттл не создан. Возникает страница с серым фоном, над которым отображается только заголовок с названием проекта и данные авторизованного пользователя.
браузер Safari 14.1.2 (16611.3.10.1.3)

<img width="1088" alt="Снимок экрана 2023-02-24 в 15 20 16" src="https://user-images.githubusercontent.com/120312860/221167776-cdfa5afb-97a3-4c01-a861-90e003572946.png"> 
 <img width="1439" alt="Снимок экрана 2023-02-24 в 15 15 48" src="https://user-images.githubusercontent.com/120312860/221167760-0fc5d605-cf8c-469a-920a-4a5979c0bf9b

### Reproduction steps

```bash
1. Авторизоваться.
2. Перейдите на страницу https://codebattle.hexlet.io/#lobby
3. Нажмите кнопку Создать игру
```

### Expected result

Открывается окно создания игры с параметрами, пользователю доступно создание баттла

### Actual result

Нет возможности создать баттл

### Browsers

Safari

### OS

Mac

**Comment by polinatswet** [comment]
<img width="1439" alt="Снимок экрана 2023-02-24 в 15 15 48" src="https://user-images.githubusercontent.com/120312860/221169158-76f81a59-6448-4fc2-8701-43da03d1188f.png">

**Comment by Olya-S174** [comment]
В мобильной версии сайта, нет возможности создать игру:
- Авторизируемся
- Тапаем кнопку "Create a gamе"

На экране появляется только серое поле.

Браузеров
Сафари
ОС
Макинтош
iphone 2020 se

![photo_2023-02-25_14-11-07](https://user-images.githubusercontent.com/120718068/221348925-6de9863a-2210-4f34-93af-5eb258da3d15.jpg)

**Comment by den1523** [comment]
Браузер Safari. Версия 14.1.2 (14611.3.10.1.7) на MacOs Mojave возникает серая страница при создании игры.
![Screenshot at Mar 11 10-58-16](https://user-images.githubusercontent.com/122207086/224472746-5a0a17b4-b0b4-427f-bf71-81d63f73757e.png)
