### ISSUE TITLE
Bug: Не отображаются аватары игроков при просмотре архивной записи игры

### ISSUE THREAD

**Issue by DavydovDeni** [hexlet-codebattle/codebattle#1327]
### Summary

<img width="1430" alt="Снимок экрана 2023-02-23 в 23 45 17" src="https://user-images.githubusercontent.com/119748342/221227879-9d38cc36-62ba-41b4-ba27-3dc3c0469c51.png">

### Reproduction steps

```bash
1. Открыта главная страница https://codebattle.hexlet.io/ авторизованным пользователем
2. Переходим во вкладку "Completed games"
3. Открываем запись игры нажав на кнопку "Show"
```

### Expected result

В открывшемся окне отображаются аватары участников игры

### Actual result

Аватары участников игры не отображаются

### Browsers

Chrome

### OS

Mac

**Comment by 2KO1** [comment]
Воспроизводится: плавающая ошибка
Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

**Comment by ReDBrother** [comment]
В общем случае, ее будет невозможно решить. Кроме как заглушкой по умолчанию. Сейчас она присутствует
