### ISSUE TITLE
Feature: Нет описания задачи при выборе задания в окне создания игры

### ISSUE THREAD

**Issue by DavydovDeni** [hexlet-codebattle/codebattle#1328]
### Summary

<img width="616" alt="Снимок экрана 2023-02-23 в 23 50 23" src="https://user-images.githubusercontent.com/119748342/221233030-7064149f-9f69-43df-bf0c-7d0055b8386a.png">

### Reproduction steps

```bash
1. Открыта главная страница https://codebattle.hexlet.io/ авторизованным пользователем
2. Нажимаем на вкладку "Create a game"
3. В открывшемся окне переходим к всплывающему списку под пунктом "Choose task by name or tags"
4. Выбираем задание из списка
```

### Expected result

При выборе задания из всплывающего списка отображается краткое описание задачи

### Actual result

Описание задачи в выбранном задании не отображается на этапе создания сценария игры

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
В рамках соревнования, мы не можем показывать подобное описание - это будет лишним преимуществом перед противником
