### ISSUE TITLE
Bug: Нет возможности добавить несколько языков программирования в профиле пользователя

### ISSUE THREAD

**Issue by DavydovDeni** [hexlet-codebattle/codebattle#1330]
### Summary

<img width="1207" alt="Снимок экрана 2023-02-24 в 19 35 03" src="https://user-images.githubusercontent.com/119748342/221243111-76a44d02-a376-4228-81de-ece917861f6d.png">

### Reproduction steps

```bash
1. Открыта главная страница https://codebattle.hexlet.io/ авторизованным пользователем
2. Нажимаем на иконку/аватар профиля
3. В всплывающем окне нажимаем на вкладку "Settings"
4. На странице Settings переходим к всплывающему списку под пунктом "Your weapon"
5. Выбираем язык программирования
6. Нажимаем на кнопку "Add weapon"
7. В всплывающем списке выбираем язык программирования
```

### Expected result

Имеется возможность в настрояках профиля добавить более одного языка программирования

### Actual result

Имеется возможность выбора только одного языка программирования в профиле пользователя

### Browsers

Chrome

### OS

Mac

**Comment by 2KO1** [comment]
@DavydovDeni может лучше классифицировать как "enhancement-proposal"?

**Comment by vikahati** [comment]
1. Открыта главная страница https://codebattle.hexlet.io/ авторизованным пользователем
2. Нажимаем на иконку/аватар профиля
3. В всплывающем окне нажимаем на вкладку "Settings"
4. На странице Settings переходим к всплывающему списку под пунктом "Your weapon"
5. Выбираем язык программирования
6. Нажимаем на кнопку "Add weapon"
7. В всплывающем списке выбираем язык программирования

**Browsers**
Yandex

**OS**
Linux

**Comment by ReDBrother** [comment]
Этот выбор влияет только на язык по умолчанию, который будет использоваться при создании игры.
В текущей итерации игр мы не ограничены в выборе языков, и если бы были, то множественный выбор отображался в форме создания игры, а не в настройках пользователя.
