### ISSUE TITLE
Bug: Кириллица в поле даты создания турнира при английской локализации

### ISSUE THREAD

**Issue by DavydovDeni** [hexlet-codebattle/codebattle#1331]
### Summary

<img width="801" alt="Снимок экрана 2023-02-23 в 23 36 18" src="https://user-images.githubusercontent.com/119748342/221247560-e4a1972b-c2bd-423f-a8da-c7560155bf67.png">

### Reproduction steps

```bash
1. Открыта главная страница https://codebattle.hexlet.io/ авторизованным пользователем
2. Открываем вкладку "Tournaments"
3. Нажимаем на гиперссылку "Tournamets Info"
4. Скроллим вниз страницы к полям создания сценария турнира "Create a new tournament"
5. Переходим к полю "Starts at (UTC)" для выбора даты турнира
6. Поле выбора даты турнира заполнено в формате: "dd.mm.yyyy"
```

### Expected result

Поле выбора даты отображается латиницей: "dd.mm.yyyy"

### Actual result

Поле выбора даты отображается кириллицей: "дд.мм.гггг"

### Browsers

Chrome

### OS

Mac

**Comment by AnastasiaKv** [comment]
@DavydovDeni , актуально ещё? не могу воспроизвести
![2023-02-28_10-28-53](https://user-images.githubusercontent.com/10958822/221783927-567f59ea-b3d2-424b-8248-83599beb21cd.png)

**Comment by DavydovDeni** [comment]
Баг воспроизводится. Chrome Версия 110.0.5481.178 (Официальная сборка), (64 бит). Windows 10 PRO.
![Снимок](https://user-images.githubusercontent.com/119748342/221960902-2e11542f-98cc-4453-8927-6e465e97c3d5.PNG)

**Comment by Salivya** [comment]
Баг воспроизводится 

environment:
Safari Версия 16.1 (18614.2.9.1.12)
macOS Ventura Версия 13.0 (22A380)

<img width="1280" alt="Снимок экрана 2023-04-03 в 17 52 22" src="https://user-images.githubusercontent.com/119805947/229547176-8a3bed9d-b791-42eb-89f8-b699457a0750.png">

**Comment by ReDBrother** [comment]
Это встроенный datapicker браузера. Мы не можем это контролировать.
