### ISSUE TITLE
Bug: Грамматическая ошибка в гиперссылке Tournamets Info

### ISSUE THREAD

**Issue by DavydovDeni** [hexlet-codebattle/codebattle#1332]
### Summary

<img width="625" alt="Снимок экрана 2023-02-24 в 20 40 31" src="https://user-images.githubusercontent.com/119748342/221250513-fb4f00ea-0563-4278-a808-4cd212610716.png">

### Reproduction steps

```bash
1. Открыта главная страница https://codebattle.hexlet.io/ авторизованным пользователем
2. Открываем вкладку "Tournaments"
3. Переходим к гиперссылке https://codebattle.hexlet.io/tournaments
```

### Expected result

Ссылка отображается без грамматических ошибок: Tournaments Info

### Actual result

Ссылка отображается с грамматической ошибкой: Tournamets Info

### Browsers

Chrome

### OS

Mac

**Comment by DavydovDeni** [comment]
Баг не закрыт
<img width="541" alt="Снимок экрана 2023-02-26 в 17 56 52" src="https://user-images.githubusercontent.com/119748342/221418373-55f53b79-aed1-45bf-805f-286a10d77e29.png">

**Comment by StasVorobyev** [comment]
Reproduction steps
   - Открываем главную страницу авторизованным пользователем
   - Нажимаем на вкладку Tournaments
   - Проверяем гиперссылку Tournamets Info на наличие грамматических ошибок

Expected result
Ссылка отображается без грамматических ошибок

Actual result
Ссылка отображается с грамматической ошибкой: Tournamets Info

Browsers
Версия 110.0.5481.177 (Официальная сборка), (64 бит)

OS
Windows 11
![bagreport2](https://user-images.githubusercontent.com/121265452/221429200-3cbbd259-dab2-4a8a-842f-eeb8d595240e.png)

**Comment by borizi** [comment]
Баг до сих пор воспроизводится.

**Steps to reproduce**

Авторизоваться на сайте
Открыть вкладку "Tournaments" на главной странице

**Expected result**
Отображается ссылка "Tournaments info" без орфографических ошибок

**Actual result**
Отображается ссылка "Tournamets info" с орфографической ошибкой
![Орфографическая ошибка в ссылке Tournaments info](https://user-images.githubusercontent.com/64551423/221658175-728d8fa5-d6d0-4523-aa64-86d11dda59d5.jpg)

**Browsers**
Chrome
Версия 110.0.5481.104 (Официальная сборка), (64 бит)

**OS**
Windows 11 Pro 22H2
Сборка 22621.1265
