### ISSUE TITLE
Bug:  Наслоение поясняющей информации к диаграмме в мобильной версии

### ISSUE THREAD

**Issue by Olya-S174** [hexlet-codebattle/codebattle#1334]
### Summary

При нахождении на странице участника, в мобильной версии сайта, поясняющая информация к диаграмме о ЯП, наслаивается одна на другую

### Reproduction steps

```bash
Авторизируемся 
Переходим по ссылке: https://codebattle.hexlet.io/users/-16
```

### Expected result

поясняющие элементы отображаются ровно и аккуратно,  без наслоений

![photo_2023-02-25_13-02-53](https://user-images.githubusercontent.com/120718068/221347305-dabe5f15-e182-47be-99d8-9402e2299cff.jpg)

### Actual result

поясняющая  информация к диаграмме наслаивается одна на другую 

### OS

Mac

**Comment by ushachev** [comment]
включает более простой кейс из #1303 
взял в работу
