### ISSUE TITLE
Bug: Нельзя отсортировать по Perfomance в таблице рейтинга 

### ISSUE THREAD

**Issue by BeerLock** [hexlet-codebattle/codebattle#1336]
### Summary

Нельзя отсортировать пользователей по Perfomance в таблице рейтинга 

### Reproduction steps

```bash
1. Авторизоваться на Codebattle
2. Открыть TOP list в блоке LEADERBOARD
3. Нажать на Perfomance
```

### Expected result

Пользователи сортируются по Perfomance

### Actual result

Perfomance не кликабельный, пользователи не сортируются

### Browsers

Chrome 
Версия 110.0.5481.105 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro
Версия 21H2

![image](https://user-images.githubusercontent.com/120048767/221380433-3a957b9d-5785-4b51-95bd-0b9febd0a3b2.png)

**Comment by 2KO1** [comment]
@BeerLock может лучше классифицировать как "enhancement-proposal"?

**Comment by Mayday4221** [comment]
Также не получается отсортировать по **Performance**.
OS Windows 7
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

Reproduction steps

1. Авторизоваться на Codebattle
2. Открыть TOP list в  LEADERBOARD
3. Нажать на Performance

**Comment by Makarova94** [comment]
- summary: |
   Не осуществляется сортировка пользователей по "Результаты игр" в таблице рейтинг пользователей
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
   - Открыть TOP list в блоке LEADERBOARD
    - Нажать кнопку "Performance"
  
  expected-result: |
    Осуществляется сортировка пользователей после нажатия на кнопку "Performance"
  actual-result: |
   Perfomance не кликабельный, пользователи не сортируются

**Comment by ReDBrother** [comment]
Поле перфоманс убрали
