### ISSUE TITLE
Feature request: Нет уведомления о начале баттла

### ISSUE THREAD

**Issue by BeerLock** [hexlet-codebattle/codebattle#1337]
### Summary

На странице баттла не появляется уведомление для одновременного начала баттла

### Reproduction steps

```bash
1. Авторизоваться на codebattle
2. Создать игру с ботом
3. Подтвердить готовность
```

### Expected result

После временного отсчёта появляется уведомление о начале баттла

### Actual result

Временного отсчета нет, игра начинается сразу

### Browsers

Chrome
Версия 110.0.5481.105 (Официальная сборка), (64 бит)
### OS

Windows
Версия 21H2
![image](https://user-images.githubusercontent.com/120048767/221380887-d1e5d7f2-e1c4-4dc6-94e8-d5c943b4d9f3.png)

**Comment by 2KO1** [comment]
@BeerLock может лучше классифицировать как "enhancement-proposal"?

**Comment by ReDBrother** [comment]
Cейчас нет полноценных нотификаций
Вот proposal issue: https://github.com/hexlet-codebattle/codebattle/issues/1498
