### ISSUE TITLE
Bug: Нет адаптации страницы рейтинга

### ISSUE THREAD

**Issue by BeerLock** [hexlet-codebattle/codebattle#1339]
### Summary

Не адаптирована страница рейтинга для мобильных устройств

### Reproduction steps

```bash
1. Авторизоваться на codebattle на мобильном устройстве 
2. Открыть "TOP list" в блоке LEADERBOARD
3. Отзумить экран телефона
```

### Expected result

Экран не может отзумиться, страница адаптирована к мобильному устройству

### Actual result

Экран может отзумиться, страница не адаптирована к мобильному устройству

### Browsers
Yandex 
Версия 23.1.5.90

### OS
Samsung Galaxy s21 5G
Android 13

![image](https://user-images.githubusercontent.com/120048767/221381689-52cd0543-0a67-41e1-8870-aa425af4f77b.png)

**Comment by kininaruneko** [comment]
Воспроизводится

steps-to-reproduce:
1. Авторизоваться на сайте https://codebattle.hexlet.io/
2. Нажать "TOP list" в блоке LEADERBOARD
3. Открыть DevTools

environment:
ОС Windows 11
Google Chrome Версия 111.0.5563.64 (Официальная сборка), (64 бит)

![mobile_bug](https://user-images.githubusercontent.com/119680935/224509036-589796a0-0b17-43be-87ad-08708ea90dc9.png)
![mobie_bug2](https://user-images.githubusercontent.com/119680935/224509040-9de47f5f-4c90-4245-a887-bf0b3c431101.png)

**Comment by Nackles999** [comment]
Воспроизводится

summary: |
   Проверка мобильной адаптивности
environment: |
    Google Chrome   109.0.5414.75 (Официальная сборка), (64 бит)
    OC Windows 10 21H2 64-bit
steps-to-reproduce: |
    Открываем главную страницу с помощью мобильного симулятора DevTools
expected-result: |
    Мобильная версия сайта адаптирована
actual-result: |
![Bug](https://user-images.githubusercontent.com/121425048/224656310-496d0ddf-4211-46eb-b583-3675c6ff7b44.png)

Сайт не адаптирован под мобильные устройства

**Comment by Svetlana111777** [comment]
Баг воспроизводится

iOS 16.3.1

![photo_2023-03-14_13-59-14](https://user-images.githubusercontent.com/122152016/224949448-cb9776ee-f273-41b1-9812-21dea7fdd881.jpg)
![photo_2023-03-14_13-59-16](https://user-images.githubusercontent.com/122152016/224949475-95c05bee-6c33-4552-8889-1d5645e5fd1d.jpg)
![photo_2023-03-14_13-51-51](https://user-images.githubusercontent.com/122152016/224949384-7f3dd490-ea17-4d5e-8de4-53a5f807be84.jpg)

**Comment by Irina28Ivashko** [comment]
Воспроизводится

summary: |
Проверка мобильной адаптивности
environment: |
Vivaldi	5.7.2921.60 (Stable channel) (64 бита) 
Версия	b442729c9d1d213fb300493d3f89eba4987bd132
ОС Windows 10 Version 22H2 (Build 19045.2486)
steps-to-reproduce: |
- Авторизоваться на сайте https://codebattle.hexlet.io/
- Нажать "TOP list"
- Открыть мобильный симулятор в DevTools

expected-result: |
Мобильная версия сайта адаптирована
actual-result: |
Сайт не адаптирован под мобильные устройства

<img width="166" alt="Рисунок1" src="https://user-images.githubusercontent.com/125243915/233126084-8b86cd52-d3fa-495f-bab5-b5a585197107.png">

<img width="160" alt="Рисунок2" src="https://user-images.githubusercontent.com/125243915/233126117-540a297f-0193-41a1-ab52-d6f869801769.png">

**Comment by kos342** [comment]
**Summary:**
Страница рейтинга не адаптирована в мобильной версии сайта
**Environment:**
iOS 16.4.1
Safari Browser
**Prerequisites:**
Открыта стартовая страница сайта [Codebattle](https://codebattle.hexlet.io)
Test-data:
Nickname = Test_User Password = 123456
**Steps:**

1. Нажать кнопку 'Sign In'
2. Ввести Nickname и Password
3. Нажать кнопку 'Submit'
4. Нажать кнопку 'TOP list'

**Expected-result:**
Верстка сайта соответствует десктопной версии сайта
**Actual-result:**
Страница не адаптирована для мобильных устройств. Верстка съехала, текст не влезает полностью в границы экрана.

**Comment by katrytikova** [comment]
Воспроизводится 
Android 13
Chrome 113.0.5672.163
![photo_2023-06-05 13 29 43](https://github.com/hexlet-codebattle/codebattle/assets/122362310/09aab110-4291-4305-8f78-ff12cea1d43d)

**Comment by katrytikova** [comment]
воспроизводится
Android 13
Chrome 113.0.5672.163
![photo_2023-06-05 13 29 37](https://github.com/hexlet-codebattle/codebattle/assets/122362310/b9c60689-b750-439d-a385-5bb6ded75a16)

**Comment by ReDBrother** [comment]
Дубль от https://github.com/hexlet-codebattle/codebattle/issues/1487
