### ISSUE TITLE
Bug: Грамматическая ошибка в гиперссылке Tournamets Info

### ISSUE THREAD

**Issue by BeerLock** [hexlet-codebattle/codebattle#1341]
### Summary

![image](https://user-images.githubusercontent.com/120048767/221412468-f666262e-8e16-4663-bfa2-45602dc63dae.png)

### Reproduction steps

```bash
1. Авторизоваться на codebattle
2. Открыть вкладку Tournaments
```

### Expected result

Ссылка отображается без грамматических ошибок: Tournaments Info

### Actual result

Ссылка отображается с грамматической ошибкой: Tournamets Info

### Browsers

Chrome
Версия 110.0.5481.105 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro
Версия 21H2

**Comment by DavydovDeni** [comment]
Повтор [https://github.com/hexlet-codebattle/codebattle/issues/1332](url)

**Comment by 2KO1** [comment]
#1332

**Comment by EEMinch** [comment]
Ошибка воспроизводится 

Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит)
Mozilla Firefox 110.0 (64-разрядный)
ОС Windows 10

**Comment by borizi** [comment]
#1332 
Баг до сих пор воспроизводится.

**Browsers**
Chrome
Версия 110.0.5481.104 (Официальная сборка), (64 бит)

**OS**
Windows 11 Pro 22H2
Сборка 22621.1265

**Comment by polinatswet** [comment]
Баг воспроизводится. Chrome. MacOS.
<img width="1172" alt="Снимок экрана 2023-03-03 в 18 15 59" src="https://user-images.githubusercontent.com/120312860/222745868-a55da988-6b44-4a13-8503-1708ef1d152a.png">

**Comment by Marria22** [comment]
Баг воспроизводится [#1332](https://github.com/hexlet-codebattle/codebattle/issues/1332)

Браузер
Chrome Версия 110.0.5481.178 (Официальная сборка), (64 бит)

ОС
Windows 10 версия 22H2

**Comment by AlenaSup** [comment]
Баг подтверждается:
![image](https://user-images.githubusercontent.com/122166113/223338295-cbb72c47-a2fb-4e74-9313-1c0949227ccb.png)

Окружение:
Windows 10 Pro Версия 21H2, Opera Browser Версия   95.0.4635.46

**Comment by Guryanov-Maksim** [comment]
Здравствуйте! Сейчас баг не воспроизводится. Можете подтвердить отсутствие бага, пожалуйста?

**Comment by Guryanov-Maksim** [comment]
Здравствуйте! Сейчас баг не воспроизводится. Можете подтвердить отсутствие бага, пожалуйста?

**Comment by 2KO1** [comment]
Не воспроизводится

**Comment by Guryanov-Maksim** [comment]
Спасибо, закрываем
