### ISSUE TITLE
Bug: Не отображается заголовок My Profile

### ISSUE THREAD

**Issue by Germankhz** [hexlet-codebattle/codebattle#1343]
### Summary

Не отображается заголовок My Profile при переходе на страницу с информацией о профиле пользователя

### Reproduction steps

```bash
1. Щелкнуть по имени пользователя в правом верхнем углу страницы
2. В выпадающем меню выбрать пункт My Profile
```

### Expected result

Страница с информацией профиля пользователя имеет заголовок My Profile

### Actual result

Страница с информацией профиля пользователя НЕ имеет заголовок My Profile

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Добавили
