### ISSUE TITLE
Bug: Задублирована кнопка «Join» в незавершенных турнирах, где есть хоть один участник 

### ISSUE THREAD

**Issue by EEMinch** [hexlet-codebattle/codebattle#1347]
### Summary

Задублирована кнопка «Join» в незавершенных турнирах, где есть хоть один участник 

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем
2. Выбрать вкладку «TOURNAMENTS»
3. Нажать кнопку «Show» в любом турнире из списка ‘Live Tournaments’, где есть хоть один участник
```

### Expected result

На открытой странице незавершенного турнира присутствует одна кнопка «Join»

### Actual result

На открытой странице незавершенного турнира задублирована кнопка «Join»

![image](https://user-images.githubusercontent.com/120366598/221888697-596ee7f0-7d80-4486-b8b9-8a5db1848c46.png)

![image](https://user-images.githubusercontent.com/120366598/221888784-14d9cd09-bf2f-47d4-b276-8b1bd389bcab.png)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by BeerLock** [comment]
Баг воспроизводится
`Browsers`
Chrome
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

`OS`
Windows
Версия 21H2
![image](https://user-images.githubusercontent.com/120048767/222551876-a7843cc9-e8ac-4bde-8b59-a12d706b3d77.png)

**Comment by ReDBrother** [comment]
Он дублировался из-за механики Intended players -> players.
Этой механики больше нет
