### ISSUE TITLE
Bug: Невозможно принять приглашение на игру

### ISSUE THREAD

**Issue by EEMinch** [hexlet-codebattle/codebattle#1348]
### Summary

Невозможно принять приглашение на игру, отправленное другом, т.к. кнопка «Accept» в разделе "Invites" не производит никаких действий

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем
2. Нажать «Create a game»
3. В модальном окне выбрать Level, Came Type, Time control, Opponent, Task, Tag
4. Нажать "Create Invite"
5. Приглашенному пользователю нажать на кнопку «Invites»
6. Нажать на кнопку «Accept»
```

### Expected result

Пользователь попадет на страницу игры против пригласившего игрока

### Actual result

Ничего не происходит даже после нескольких нажатий и перезагрузки страницы

![image](https://user-images.githubusercontent.com/120366598/221931947-793909fe-71ff-4748-abae-b477a1838600.png)

![image](https://user-images.githubusercontent.com/120366598/221931986-55e538fc-4a8d-4c90-ab36-1a174fb1036a.png)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by BeerLock** [comment]
Баг воспроизводится!

`Browsers`
Chrome
Версия 110.0.5481.105 (Официальная сборка), (64 бит)

`OS`
Windows
Версия 21H2

**Comment by 2KO1** [comment]
Не воспроизводится:
Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

@EEMinch Здравствуйте, подскажите, перед этим баг-репортом случайно не создавали турнир для проверки и отменяли его?

**Comment by ReDBrother** [comment]
Была поломана логика приглашений. Fixed
