### ISSUE TITLE
Bug: Грамматические ошибки в пояснении к полю формы

### ISSUE THREAD

**Issue by Germankhz** [hexlet-codebattle/codebattle#1349]
### Summary

В форме создания TaskPack пояснение к полю Name написано с ошибками.
![1](https://user-images.githubusercontent.com/119713022/222010572-9d744504-9866-4b98-b1f4-aeae8c68c109.jpg)

### Reproduction steps

```bash
1. Авторизоваться
2. Кликнуть по имени пользователя
3. В выпадающем меню выбрать раздел Tasks
4. Кликнуть по кнопке Task packs
5. Кликнуть по кнопке Create new task pack
```

### Expected result

Пояснение написано следующим образом: 

**Name of the task pack should be unique**

### Actual result

Пояснение написано с ошибками: **Name for task pack, sould be uniq**

### Browsers

Chrome

### OS

Windows

**Comment by borizi** [comment]
#1340

Ошибки до сих пор присутствуют

### Steps to reproduce

```bash
1. Авторизоваться на сайте
2. Перейти на страницу с задачами https://codebattle.hexlet.io/tasks
3. Нажать кнопку "Create new task"
```

### Expected result

Отображается страница создания задачи, в подсказке к полю Name написано "Name for task, should be unique"

### Actual result

Отображается страница создания задачи, в подсказке к полю Name написано "Name for task, sould be uniq" 

![Ретест-Орфографические ошибки в подсказке при создании задачи](https://user-images.githubusercontent.com/64551423/221966151-ecfe571f-5f19-4488-bc60-20cc2137620d.jpg)


### Browsers

Chrome
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

### OS

Windows 11 Pro 22H2
Сборка 22621.1265

**Comment by borizi** [comment]
#1340 

Аналогично ошибка всё так же присутствует и на странице создания группы задач.

**Steps to reproduce**
1. Авторизоваться на сайте
2. Перейти на страницу с задачами https://codebattle.hexlet.io/tasks
3. Нажать кнопку "Task packs"
4. Нажать кнопку "Create new task pack"

**Expected result**
Отображается страница создания группы задач, в подсказке к полю Name написано "Name for task pack, should be unique"

**Actual result**
Отображается страница создания группы задач, в подсказке к полю Name написано "Name for task pack, sould be uniq"
![Ретест-Орфографические ошибки в подсказке при создании группы задач](https://user-images.githubusercontent.com/64551423/221966575-1c86cdc3-408a-4a65-a674-3642834ac143.jpg)

**Browsers**
Chrome
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

**OS**
Windows 11 Pro 22H2
Сборка 22621.1265

**Comment by EEMinch** [comment]
Так же воспроизводится баг - https://github.com/hexlet-codebattle/codebattle/issues/1340

**environment:** 
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит)
Mozilla Firefox 110.0 (64-разрядный)
ОС Windows 10

**Comment by BeerLock** [comment]
Баг воспроизводится
`Browsers`
Chrome
Версия 110.0.5481.178 (Официальная сборка), (64 бит)
`OS`
Windows
Версия 21H2

![image](https://user-images.githubusercontent.com/120048767/222554979-cf2e2287-ea72-4aba-b46b-ecdf7347065a.png)

**Comment by Marria22** [comment]
На данный момент, баг воспроизводится.

Браузер
Chrome Версия 110.0.5481.178 (Официальная сборка), (64 бит)

ОС
Windows 10 версия 22H2

**Comment by AlenaSup** [comment]
Баг подтвержден:

![Снимок экрана (174)](https://user-images.githubusercontent.com/122166113/223336813-40ad6685-1fd2-4c1a-854b-2997c729519b.png)
Окружение: Windows 10 Pro Версия 21H2, Opera Browser Версия   95.0.4635.46

**Comment by AllIzm** [comment]
Орфографические ошибки в подсказке при создании задачи. 
Воспроизведение бага #1340 

**Browsers**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) – пользователь AllIzm
Mozilla Firefox 110.0.1 (64-разрядный) - пользователь Varya
Safari


**OS**
Windows 11 22H2
Windows 11 22H2
iOS16.2

![Re-issue1340](https://user-images.githubusercontent.com/121917310/223530469-405e874f-18cc-4f5a-923c-57edfcf86f85.png)

**Comment by ALBERTO3ABP** [comment]
![image](https://user-images.githubusercontent.com/121248340/224100591-49f058f9-8698-4513-be16-3f5635be9172.png)

Browsers
Microsoft Edge 110.0.1587.63 (Официальная сборка) (64-разрядная версия)

OS
Выпуск: Windows 10 Домашняя
Версия: 22H2

**Comment by mx3drive** [comment]
Исправлено: 

ОС:
Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎10.‎02.‎2023
Сборка ОС 22621.1265
Взаимодействие Windows Feature Experience Pack 1000.22638.1000.0

Браузер:
Яндекс Браузер Версия 23.1.4.778 (64-bit)

![image](https://user-images.githubusercontent.com/119818671/225042944-486dc593-9e5b-44b3-a9c4-df942a96eefe.png)
![image](https://user-images.githubusercontent.com/119818671/225043406-b1ba1033-79f0-45a0-9887-7479a85d360d.png)
