### ISSUE TITLE
Bug: Не отображается страница баттла при открытии скопированной на него ссылки

### ISSUE THREAD

**Issue by borizi** [hexlet-codebattle/codebattle#1352]
### Summary

#1335 
Не отображается страница баттла при открытии скопированной на него ссылки. 
Воспроизводится до сих пор.

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать кнопку "Create a game"
3. Нажать на кнопку "Create Battle"
4. Нажать на иконку "Copy link" напротив созданного баттла
5. Открыть скопированную ссылку в новой вкладке браузера
```

### Expected result

Отображается страница созданного баттла

### Actual result

Отображается главная страница без списка баттлов в лобби

![Ретест-Неправильная ссылка при копировании адреса баттла 2](https://user-images.githubusercontent.com/64551423/221967685-551945ec-c646-4238-8a64-3fc77a6408d4.jpg)

![Ретест-Неправильная ссылка при копировании адреса баттла](https://user-images.githubusercontent.com/64551423/221967703-66863a49-cefa-42d3-9d48-40b8ab6cc7d4.jpg)

### Browsers

Chrome

### OS

Windows

**Comment by EEMinch** [comment]
Все еще воспроизводится закрытый баг - https://github.com/hexlet-codebattle/codebattle/issues/1335

**environment:** 
Mozilla Firefox 110.0 (64-разрядный)
ОС Windows 10

**Comment by 2KO1** [comment]
@borizi данную функцию убрали?

**Comment by borizi** [comment]
@2KO1 Нет, всё воспроизводится по-прежнему

**Comment by 2KO1** [comment]
@borizi зря побеспокоил, сам ошибся. Воспроизводится:
Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Версия 110.0.5481.178 (Официальная сборка), (64 бит)

**Comment by Guryanov-Maksim** [comment]
Здравствуйте! Баг в данный момент не вопроизводится. Проверьте его наличие, пожалуйста.

**Comment by 2KO1** [comment]
Не воспроизводится

**Comment by Guryanov-Maksim** [comment]
Спасибо, закрываем
