### ISSUE TITLE
Bug: Не создается игра, если язык программирования в профиле - TypeScript 

### ISSUE THREAD

**Issue by Marria22** [hexlet-codebattle/codebattle#1361]
### Summary

Не создается игра, если язык программирования в профиле - TypeScript. Баг до сих пор воспроизводится [#1317](https://github.com/hexlet-codebattle/codebattle/issues/1317)

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на аватар игрока в верхнем правом углу
3. В меню выбрать "Settings"
4. В DropDown меню "Your weapon" выбрать "TypeScript"
5. Нажать "Save"
4. Нажать на логотип Codebattle в верхнем левом углу
5. Нажать "Create a game"
6. Выбрать "Level" - 1, "Game Type" - "With a bot"
7. Нажать кнопку "Create Battle"
```

### Expected result

На экране отображается страница битвы

### Actual result

Игра не создана, на экране отображается главная страница

### Browsers

Chrome

### OS

Windows

**Comment by Marria22** [comment]
Bug также воспроизводится, если выбрать язык программирования Go.

Окружение:
Браузер
Chrome Версия 110.0.5481.178 (Официальная сборка), (64 бит)

ОС
Windows 10 версия 22H2

**Comment by mx3drive** [comment]
Подтверждаю, что баг воспроизводится:

ОС:
Выпуск	Windows 11 Домашняя для одного языка
Версия	22H2
Дата установки	‎10.‎02.‎2023
Сборка ОС	22621.1265
Взаимодействие	Windows Feature Experience Pack 1000.22638.1000.0

Браузер:
Яндекс Браузер Версия 23.1.4.778 (64-bit)

![image](https://user-images.githubusercontent.com/119818671/225040344-7fd24c32-3c5d-4595-890e-fb5328f48140.png)

**Comment by Guryanov-Maksim** [comment]
Здравствуйте, на данный момент баг не воспроизводится, возможно недавно был произведен деплой. Можете перепроверить и подтвердить, пожалуйста?

**Comment by Marria22** [comment]
Да, в настоящий момент, баг не воспроизводится.

**Comment by Guryanov-Maksim** [comment]
Спасибо, тогда закрываем
