### ISSUE TITLE
Bug: В настройках профиля, при изменении уровня громкости, не воспроизводится новый выбранный звук. 

### ISSUE THREAD

**Issue by Marria22** [hexlet-codebattle/codebattle#1363]
### Summary

В настройках профиля, новый звук звучит только один раз, когда напротив него ставится флажок. Затем при изменении громкости снова звучит звук, который был выбран на момент открытия 'Settings'. Bug [#1279](https://github.com/hexlet-codebattle/codebattle/issues/1279) все еще воспроизводится.

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на аватар пользователя в левом верхнем углу
3. В меню выбрать "Settings"
4. Сменить тип звука на другой (кроме Silent)
5. Подвинуть слайдер громкости
```

### Expected result

Прозвучит выбранный звук

### Actual result

Прозвучит звук, выбранный на момент открытия "Settings"
![sound bug](https://user-images.githubusercontent.com/119875618/223164561-6b7862f6-0053-4e28-b80e-0897d615bfbe.png)

### Browsers

Chrome

### OS

Windows

**Comment by Mayday4221** [comment]
Баг воспроизводится:
OS Windows 7
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

**Comment by Guryanov-Maksim** [comment]
Здравствуйте, на данный момент баг не воспроизводится. Можете перепроверить и подтвердить, пожалуйста?

**Comment by Marria22** [comment]
В настоящий момент баг не воспроизводится.

**Comment by Guryanov-Maksim** [comment]
Спасибо, тогда закрываем
