### ISSUE TITLE
Bug: Отображение редактора на игровой странице баттла неадаптировано под мобильные устройства

### ISSUE THREAD

**Issue by AllIzm** [hexlet-codebattle/codebattle#1364]
### Summary

Неадаптированное отображение окна редактора кода на игровой странице баттла в мобильной версии.
Пользователю необходимо скролить экран по горизонтали

### Reproduction steps

```bash
1.Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем
2.На главной странице нажать кнопку “CREATE A GAME”
3.В появившемся окне выбрать параметры баттла и нажать "Create Battle"
```

### Expected result

Открывшаяся игровая страница баттла адаптирована под экран мобильного устройства.

### Actual result

Поля игровой страницы баттла выходят за пределы экрана мобильного устройства.
![Отображение редактора в мобильной версии](https://user-images.githubusercontent.com/121917310/223213971-5f126cfa-8317-425a-987f-1131677e30ee.PNG)

**Browsers**
Safari iOS16.2

**Comment by ReDBrother** [comment]
Мы ограничены чужой реализации редактора, который авторы изначально не планируют поддерживать на мобильных устройствах
