### ISSUE TITLE
Bug: Отображение баттла незарегистрированного пользователя с ботом на главной странице

### ISSUE THREAD

**Issue by AllIzm** [hexlet-codebattle/codebattle#1365]
### Summary

Проходящий баттл незарегистрированного пользователя не отображается на главной странице.

### Reproduction steps

```bash
1.Зайти на https://codebattle.hexlet.io/  как незарегистрированный пользователь
2.Выбрать опцию "TRY SIMPLE GAME"
3.Зайти с другого устройства на https://codebattle.hexlet.io/ под авторизованным пользователем
4.Выбрать вкладку "Lobby"
```

### Expected result

Баттл должен быть в списке баттлов, проходящих в данный момент

### Actual result

Баттл не отображается в списке баттлов, проходящих в данный момент. 

![Игра незарегистрированного пользователя1](https://user-images.githubusercontent.com/121917310/223218258-d50a2cd6-eb4a-4ecc-bc13-86a8baa3aae9.png)

![Игра незарегистрированного пользователя2](https://user-images.githubusercontent.com/121917310/223218301-1f5d3441-ad30-4a79-9a64-c7c28eaa5e8f.png)

**Browsers**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) – пользователь AllIzm
Mozilla Firefox 110.0.1 (64-разрядный) – незарегистрированный пользователь

**OS**
ОС Windows 11 22H2

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by kininaruneko** [comment]
Воспроизводится

environment:
ОС Windows 11
Яндекс Браузер Версия 23.1.0.2949 (64-bit) 
Google Chrome Версия 111.0.5563.64 (Официальная сборка), (64 бит)

**Comment by ReDBrother** [comment]
Эти игры мы намеренно не показываем. Они носят ознакомительный характер и там меньше ограничений и отвественности. Мы не можем наружу выставлять их содержимое
