### ISSUE TITLE
Bug: Отправка сообщений зрителем в уникальный игровой чат участников баттла

### ISSUE THREAD

**Issue by AllIzm** [hexlet-codebattle/codebattle#1366]
### Summary

Присоединившийся к просмотру баттла зритель может писать и отправлять сообщения в уникальный игровой чат участников баттла

### Reproduction steps

```bash
1. Зайти на сайт под авторизованным пользователем
2. Выбрать вкладку "Lobby"
3. Нажать на кнопку "Show" напротив лобби, где есть оба соперника
4. Навести курсор на строку набора сообщений в игровой чат участников и нажать ЛКМ
5. Начать вводить "Hello"
```

### Expected result

Ничего не должно произойти. Вводимые символы не должны вписываться в строку

### Actual result

Сообщение вводится в строку набора с возможность его отправить в чат

![Отправка сообщения зрителем1](https://user-images.githubusercontent.com/121917310/223221984-067279b3-b93e-4705-965d-452e306dd413.png)

![Отправка сообщения зрителем2](https://user-images.githubusercontent.com/121917310/223222012-fc8343bf-26c3-4f88-b45d-de8c21aafa93.png)

**Browsers**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит)
Mozilla Firefox 110.0.1 (64-разрядный) 

**OS**
ОС Windows 11 22H2

**Comment by 2KO1** [comment]
@AllIzm Здравствуйте, может стоит в "enhancement-proposal" отнести данную проблему?

**Comment by Shvidunov** [comment]
также разумно ограничить длину сообщения в чате. На данный момент туда можно вставить длинный текст и похоронить предыдущие комментарии.
![image](https://user-images.githubusercontent.com/121935818/235737251-ab2e7348-db17-4d5b-9312-72f4c9fb2ddd.png)

**Comment by ReDBrother** [comment]
Игровой чат точно будет общим для всех.
С появлением комнат, мы можем отправлять приватные сообщения оппоненту и любому другому пользователю в чате.

**Comment by ReDBrother** [comment]
Завели реквест фичи https://github.com/hexlet-codebattle/codebattle/issues/1499
