### ISSUE TITLE
Bug: Пропадают уведомления пользователей о приглашении на баттл друг другу после принятия одного из них

### ISSUE THREAD

**Issue by AllIzm** [hexlet-codebattle/codebattle#1367]
### Summary

Пропадают уведомления пользователей о приглашении на баттл друг другу после принятия одного из них.

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/ под авторизованным пользователем1
2. На главной странице нажать кнопку “CREATE A GAME”
3. В модальном окне выбрать рандомно Level, Time-Control, Task и Game Type “With a friend”
4. В выпадающем списке выбрать пользователя2
5. Нажать "Create Battle"
6. На главной странице ожидать ответа соперника на приглашение
7. Повторить действия шагов 2 и 3 с другого авторизованного аккаунта пользователя2
8. В выпадающем списке выбрать пользователя2
9. Нажать "Create Battle"
10. На главной странице в выпадающем списке (при нажатии на иконку приглашений на баттл) принять приглашение на баттл от пользователя1
```

### Expected result

Открывается игровая страница по принятому приглашению. Отправленное приглашение отображается на иконке вызовов на баттл (перекрещенные мечи).

### Actual result

Открывается игровая страница, но отправленное приглашение на баттл пропадает.

![Взаимные приглашения1](https://user-images.githubusercontent.com/121917310/223226144-9a0f018f-b1da-4ebb-b19b-f5742139e6e6.png)

![Взаимные приглашения2](https://user-images.githubusercontent.com/121917310/223226191-460eabdf-52c0-45cc-84fa-19a5636ff277.png)

**Browsers**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) – пользователь AllIzm
Mozilla Firefox 110.0.1 (64-разрядный) - пользователь Varya
ОС Windows 11 22H2

**OS**
ОС Windows 11 22H2

**Comment by ReDBrother** [comment]
Cписок инвайтов не будет являться полноценной нотификационной панелью.
Завели отдельный тикет под эту фичу https://github.com/hexlet-codebattle/codebattle/issues/1498
