### ISSUE TITLE
Bug: Активная кнопка "Create Invite" при создании приглашения на баттл "with a friend" без выбора соперника

### ISSUE THREAD

**Issue by AllIzm** [hexlet-codebattle/codebattle#1368]
### Summary

Кнопка "Create Invite" активна при создании приглашения на баттл "with a friend" без указания соперника в модальном окне

### Reproduction steps

```bash
1.Зайти на сайт под авторизованным пользователем
2.На главной странице нажать кнопку “CREATE A GAME”
3.В модальном окне выбрать рандомно Level, Time-Control, Task и Game Type “With a friend”
4.Нажать "Create Invite"
```

### Expected result

Кнопка "Create Invite" неактивна. Пользователь должен увидеть уведомление о необходимости выбора соперника. 

### Actual result

Кнопка "Create Invite" активна, но происходит сброс данных и закрытие окна кастомизации.

**Browsers**
Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) – пользователь AllIzm

**OS**
ОС Windows 11 22H2

**Comment by 2KO1** [comment]
Воспроизводится: 
Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

**Comment by kininaruneko** [comment]
Воспроизводится:

environment:
ОС Windows 11
Google Chrome Версия 111.0.5563.64 (Официальная сборка), (64 бит)
