### ISSUE TITLE
Bug: Возможность зарегистрировать email c невидимыми символами

### ISSUE THREAD

**Issue by AllIzm** [hexlet-codebattle/codebattle#1369]
### Summary

Возможность зарегистрировать email c невидимыми символами. Воспроизводится баг #1318 

Browsers
Safari

OS
iOS16.2

### Reproduction steps

```bash
1. Открыть страницу "Sign up".
2. В поле Nickname ввести "Visual"
3. В поле Email ввести электронную почту "⠀⠀⠀⠀@⠀⠀⠀.⠀⠀" (4 невидимых символа "⠀" подряд до "@", 2 до точки и 2 после точки)
4. Заполнить оставшиеся поля с паролем валидными данными (123456).
5. Нажать кнопку "Submit"
```

### Expected result

Появляется уведомление о недопустимых символах в поле Email, регистрация не происходит.

### Actual result

Успешная регистрация пользователя с невидимым логином, происходит перенаправление на главную страницу.

![Невидимый email1 Re-issue#1318](https://user-images.githubusercontent.com/121917310/223278198-aaa06fc7-bc18-46c8-b2e8-66c592c82131.jpg)

![Невидимый email2 Re-issue#1318](https://user-images.githubusercontent.com/121917310/223278217-605b7ac3-76db-4a11-9b06-fc20236d30b3.jpg)

### Browsers

Safari

**Comment by Freigos** [comment]
Воспроизводится закрытый баг - https://github.com/hexlet-codebattle/codebattle/issues/1318

environment:
Google Chrome 111.0.5563.65 (64-разрядный)
ОС Windows 11

**Comment by SimakovMaxim** [comment]
Воспроизводится закрытый баг - https://github.com/hexlet-codebattle/codebattle/issues/1318

environment:
 Yandex 23.1.4.776 (64-bit)
ОС Windows 10

**Comment by kininaruneko** [comment]
Воспроизводится

summary: |
    Регистрация с указанием email с невидимыми символами
  
environment: |
    Google Chrome Версия 111.0.5563.64 (Официальная сборка), (64 бит)
    Windows 11
  
steps-to-reproduce: |
    1. Зайти на страницу https://codebattle.hexlet.io/
    2. Нажать кнопку Sigh up
    3. В поле Nickname ввести user45
    4. В поле Email ввести "⠀⠀⠀⠀⠀⠀@⠀⠀⠀⠀.⠀⠀" (6 невидимых символа "⠀" подряд до "@", 4 до точки и 2 после точки)
    5. В поле Password ввести пароль
    6. Нажать кнопку Submit
  
expected-result: |
    Появляется уведомление о недопустимых символах в поле Email
  
actual-result: |
    Успешная регистрация пользователя с невидимым email

![sighup_bug](https://user-images.githubusercontent.com/119680935/224511255-836ab938-ac0f-4481-b94c-f70296072a87.png)
![sighup_bug2](https://user-images.githubusercontent.com/119680935/224511261-836b4e5d-ca60-4bb6-aa53-33399d04956c.png)

**Comment by den1523** [comment]
Воспроизводится закрытый баг - https://github.com/hexlet-codebattle/codebattle/issues/1318

**environment:**
Yandex 23.1.2.978 (64-bit)
![Screenshot at Mar 12 10-00-57](https://user-images.githubusercontent.com/122207086/224529950-4e572cd6-1512-4d09-aef6-5ab05da25e61.png)

MacOs Mojave 10.14.6

**Comment by gleb5656** [comment]
### summary
Пользователь может зарегистрировать email с невидимыми символами
### environment 
macOS Ventura 13.2 Версия 111.0.5563.64 (Официальная сборка), (arm64)
### Reproduction steps
1. Переходим к регистрации
2. Вводим в поле никнейм voidx
3. Вводим в поле email test@brd⠀.com
4. Вводим пароль
5. Подтверждаем пароль
6. Нажимаем Submit
### Expected result
Система отклоняет регистрацию, пользователь видит warn, сообщающий о том, что email не подходит

### Actual result
Регистрация проходит успешно

Uploading Запись экрана 2023-04-19 в 15.36.43.mov…

**Comment by Romul76** [comment]
Воспроизвелось.

environment:
Google Chrome Version 112.0.5615.138 (Official Build) (64-bit)
ОС Windows 10
