### ISSUE TITLE
Bug: Отображение форм списков на главной странице не адаптировано под мобильную версию

### ISSUE THREAD

**Issue by Freigos** [hexlet-codebattle/codebattle#1373]
### Summary

Неадаптированное отображение форм на главной странице баттла в мобильной версии.
Пользователю необходимо скролить экран по горизонтали.

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/
2. Авторизоваться на сайте
3. Смотреть разделы Lobby, Tournaments, Completed Games
```

### Expected result

Открывшаяся главная страница баттла адаптирована под экран мобильного устройства

### Actual result

Поля форм главной страницы не адаптируются под экран мобильного устройства.
![Баг-репорт 1](https://user-images.githubusercontent.com/117305213/224012243-417db0fe-6ce2-47c8-ba8c-10a961202ae3.jpg)
![Баг-репорт 2](https://user-images.githubusercontent.com/117305213/224012339-dc964413-d772-4724-b8b2-c50861ee0d96.jpg)
![Баг-репорт 3](https://user-images.githubusercontent.com/117305213/224012368-25bfb4fe-ecf6-4fea-ad9f-d86f4d84eb1f.jpg)

### Browsers

Chrome

**Comment by 2KO1** [comment]
Дубль
#1325

**Comment by 2KO1** [comment]
Здравствуйте, если возможно дополните пожалуйста свое окружение в комментарии к уже открытому issues
