### ISSUE TITLE
Bug: Не открывается главная страница приложения codebattle

### ISSUE THREAD

**Issue by PavelBobby** [hexlet-codebattle/codebattle#1377]
### Summary

После успешного введения e-mail  и пароль на странице входа не открывается главная страница приложения
![codebattle](https://user-images.githubusercontent.com/121235023/224551642-6954c7b6-c5bb-4a14-9837-27490a9be7c8.png)

### Reproduction steps

```bash
1. Зайти в страницу входа
2. Ввести e-mail и пароль
3. Нажать на sign-in
```

### Expected result

Должна основная главная страница приложения.

### Actual result

Основная страница приложения не открывается. Бесконечно крутится колесо загрузки

### Browsers

Chrome

### OS

Windows

**Comment by 2KO1** [comment]
@PavelBobby работает?

**Comment by PavelBobby** [comment]
> @PavelBobby работает?

да.
