### ISSUE TITLE
Bug: Нет проверки пароля на надёжность при регистрации.

### ISSUE THREAD

**Issue by den1523** [hexlet-codebattle/codebattle#1379]
### Summary

При регистрации нового пользователя можно вводить самые простые пароли, так как система не проверяет их на надёжность и безопасность. Нет защиты от взлома по паролю.
Надёжный пароль должен содержать спецсимволы и знаки, строчные и прописные буквы.

### Reproduction steps

```bash
1. Нажимаем на кнопку "Sign up"
2. В поле Nickname вводим 33265
3. В поле Email вводим testagain@mailer.com
4. В поле Password вводим 123456
5. В второе поле Password повторяем 123456
```

### Expected result

Снизу подсвечивается сообщение о ненадёжности введённого пароля.

### Actual result

Система никак не реагирует на простой пароль. Присутствует ограничение только на количество символов.

### Browsers

Safari

### OS

Mac

**Comment by Trouble666** [comment]
Summary:
Нет проверки надёжности пароля

Environment:
Opera GX LVL4 (core: 94.0.4606.69) Версия Chromium:108.0.5359.125
Windows 10 64-bit

Steps-to-reproduce:
1. Находясь на главной странице нажать кнопку "Sign Up"
2. Вводим данные для регистрации: - Nickname
                                                             - gmail@gmail.com
                                                             - qwerty
                                                             - qwerty


Expected-result:
Под полем пароля должно высветится сообщение о ненадежности пароля и советы добавить цифр и букв других регистров

Actual-result:
Имеется только предупреждение о необходимом количестве символов

**Comment by vikahati** [comment]
1. Находясь на главной странице нажать кнопку "Sign Up"
2. Вводим данные для регистрации: 
Nickname: Name Surname
Email: namesurname@mail.ru
Password: 1234
Password: 1234

**Browsers**
Yandex
**OS**
Linux

**Comment by kos342** [comment]
**Summary:**
Отсутствие 
проверки пароля на надежность
**Environment:**
Windows 11 Pro Version 22H2 OS build 22621.1555
Google Chrome Version 112.0.5615.121 (Official Build) (64-bit)
**Prerequisites:**
Открыта стартовая страница сайта [Codebattle](https://codebattle.hexlet.io/)
**Test-data:**
Nickname = Test_User Email = [imaginary_email_adress@hexlet.io](mailto:imaginary_email_adress@hexlet.io) Password = пароль
**Steps:**


1. Нажать кнопку 'Sign Up
2. Заполнить поля ввода
3. Нажать кнопку 'Submit'


**Expected-result:**
Система просит ввести новый пароль. Выводится сообщение "Пароль ненадежный. В пароле должны присутствовать буквы в верхнем регистре, цифры и спецсимволы"
**Actual-result:**
Регистрация успешна. Открывается стартовая страница сайта.

**Comment by Romul76** [comment]
Воспроизвелось.

environment:
Google Chrome Version 112.0.5615.138 (Official Build) (64-bit)
ОС Windows 10

**Comment by ReDBrother** [comment]
Дубликат от https://github.com/hexlet-codebattle/codebattle/issues/1391
Прикрутим свою валидацию
