### ISSUE TITLE
Добавление возможности удаления Task/Task pack

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1380]
### Summary

На данный момент отсутствует возможность удаления созданных Task/Task pack

### Reproduction steps

```bash
- Авторизоваться в приложении
- Нажать на аватар
- Нажать на кнопку "Tasks"
- Нажать на кнопку "Create new task"/"Task packs"
```

### Expected result

Доступна возможность удаления Task/Task pack

### Actual result

Отсутствует возможность удаления созданных Task/Task pack

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
@vtm9 Хорошо бы их удалять)
