### ISSUE TITLE
Bug: Возможность отправки Invite боту

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1381]
### Summary

Во время игры с ботом, ему можно отправить invite, как другу.
![image](https://user-images.githubusercontent.com/102296858/224810976-1f220b07-3ee2-47a8-8d35-7691d34446ca.png)
![image](https://user-images.githubusercontent.com/102296858/224811126-8e4ff3f8-515f-4d19-8015-f41c3ce0a4f6.png)
![image](https://user-images.githubusercontent.com/102296858/224811335-a183bec3-7630-4b20-9381-e95582cbcb7c.png)

### Reproduction steps

```bash
- Авторизоваться в приложении
- Создать игру с ботом/нажать кнопку "Fight" в разделе lobby
- Во время игры нажать на значек "Invite" рядом с сообщение бота
- Подтвердить отправку приглашения
- Нажать кнопку "Create invite"
```

### Expected result

Значек "Invite" рядом с сообщением бота неактивен

### Actual result

Значек "Invite" рядом с сообщением бота активен и функционирует 

### Browsers

1. Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
2. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)

**Comment by smokeinureyes** [comment]
Кнопка всё еще активна

Browsers
Google Chrome

OS
Windows
![Screenshot_2](https://github.com/hexlet-codebattle/codebattle/assets/134138572/2ef2c0d6-53ab-4142-b54c-e1c3077e9378)
