### ISSUE TITLE
Bug: CodeBattle webExtension отображает как список игр, так и завершенные игры

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1384]
### Summary

CodeBattle webExtension отображает как список игр, так и завершенные игры. Кроме того игры отображенные из вкладки lobby, отображены не по порядку.
![image](https://user-images.githubusercontent.com/102296858/224975220-8c6fc676-2e8e-43eb-9b49-38a1b0e087d9.png)
![image](https://user-images.githubusercontent.com/102296858/224975242-cdfe8c83-b8b8-49b0-a59c-1bc209d32441.png)

### Reproduction steps

```bash
- Нажать на значек CodeBattle webExtension
```

### Expected result

Отображен список игр вкладки lobby в режиме онлайн

### Actual result

Отображен список игр вкладки lobby не по порядку, а также некоторые завершенные игры

### Browsers

Chrome

### OS

Windows

**Comment by Darga113** [comment]
Summary: 
    CodeBattle webExtension отображает пользователям как список игр, так и завершенные игры

Reproduction steps:
    1. Зайти на главный сайт
    2. Перейти в свой профиль
    3. Нажать на значек CodeBattle webExtension
    
Expected result:
   Отображен список игр вкладки lobby в режиме онлайн

Actual result:
    Пользователи видят список игр в совокупности с завершенными играми

OS Windows 10
Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)

**Comment by vtm9** [comment]
Chrome extension deprecated
