### ISSUE TITLE
Bug: В CodeBattle webExtension не работают уведомления (Show notifications)

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1385]
### Summary

Не работают уведомления в расширении для Chrome. 
1. При добавлении новых игр другими игроками в список lobby, не происходит уведомление.
2. При создании нового турнира, также нет уведомления
3. При присоединении к игре через invite другого игрока, не происходит уведомление

### Reproduction steps

```bash
- Создать игру "With other users"/создать турнир/присоединиться другим пользователем к ранее отправленному "invite"
```

### Expected result

Появляется всплывающее уведомление

### Actual result

Уведомления не происходит

### Browsers

Chrome

### OS

Windows

**Comment by vtm9** [comment]
Chrome extension deprecated
