### ISSUE TITLE
Bug: Кнопка "Sign In" в CodeBattle webExtension не перенаправляет на страницу авторизации пользователя.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1386]
### Summary

При нажатии на  кнопку "Sign In" в CodeBattle webExtension происходит переход на главную страницу CodeBattle (https://codebattle.hexlet.io/)

### Reproduction steps

```bash
- Установить расширение CodeBattle webExtension
- Нажать на значек расширения
- Нажать на кнопку "Sign In"
```

### Expected result

Осуществлен переход на страницу авторизации (https://codebattle.hexlet.io/session/new?locale=en&next=%2F)

### Actual result

Осуществлен переход на главную страницу CodeBattle (https://codebattle.hexlet.io/)

### Browsers

Chrome

### OS

Windows

**Comment by vtm9** [comment]
Chrome extension deprecated
