### ISSUE TITLE
Добавить уведомление "Invite" в CodeBattle webExtension

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1387]
### Summary

Было бы удобно получать уведомление на дуэль от расширения для последующего перехода в CodeBattle и начала игры.

### Reproduction steps

```bash
- Установить CodeBattle webExtension
```

### Expected result

Уведомление о "Invites"

### Actual result

Уведомление отсутствует

### Browsers

Chrome

### OS

Windows

**Comment by vtm9** [comment]
Chrome extension deprecated
