### ISSUE TITLE
Предложение: Сделать главную страницу, вкладки "lobby","tournaments","completed games" без скролинга

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1388]
### Summary

На данный момент на вкладках "lobby","tournaments","completed games" строка ввода текста чата не видна без прокрутки вниз, а без наличия сообщения в чате можно даже не заметить такую возможность на главное странице, возможно стоит сделать данные вкладки без скролинга.
Пример: 
![image](https://user-images.githubusercontent.com/102296858/225013794-b55be09f-6854-48a6-b6f7-fc2f747642b5.png)
![image](https://user-images.githubusercontent.com/102296858/225013879-976c759d-cb28-4606-97ab-aa8755ad344f.png)

### Reproduction steps

```bash
- Авторизоваться в приложении
```

### Expected result

Главная страница отображена без скролинга

### Actual result

Для доступа к чату нужно опуститься в нижнюю часть страницы

### Browsers

1. Google Chrome Версия 111.0.5563.65 (Официальная сборка), (64 бит)
2. Opera Версия 94.0.4606.76

### OS

1. Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)
Разрешение дисплея 2560х1600
3. Windows 10 Pro Версия 22H2 (сборка ОС 19045.2486)
Разрешение дисплея 1920х1080

**Comment by ReDBrother** [comment]
С учетом пожеланий по адаптации на мобильные устройства, мы не можем для нормальных мониторов сделать фиксированный размер виджетов под вьюпорт.
Чуть поменьше сделали размеры таблиц, чтобы видеть сам чат на обычных мониторах
