### ISSUE TITLE
Bug: артефакт отображения State в разделе Lobby.

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1390]
### Summary

В правой верхней части значка ожидания другого игрока во вкладке "Lobby" артефакт в виде черты.
![image](https://user-images.githubusercontent.com/102296858/225023616-15878de1-1770-4bbf-ac80-055adbb318ba.png)
![image](https://user-images.githubusercontent.com/102296858/225023814-e9151d64-5459-48e7-b5f8-01b197f33c2d.png)

### Reproduction steps

```bash
- Авторизоваться в приложении
```

### Expected result

Значек отображен без артефакта

### Actual result

В правой верхней части значка ожидания другого игрока во вкладке "Lobby" артефакт в виде черты

### Browsers

Chrome

### OS

Windows

**Comment by Trouble666** [comment]
Summary:
Визуальный баг отображения иконки в таблице "Lobby" в разделе "State"

Environment:
Opera GX LVL4 (core: 94.0.4606.69) Версия Chromium:108.0.5359.125
Windows 10 64-bit

Steps-to-reproduce:
1. Быть авторизованным на главной странице сайта

Expected-result:
Иконки должны быть без артефактов, размытых краев

Actual-result:
В верхнем правом углу виден артефакт в виде тонкой черты

![изображение_2023-03-14_203801034](https://user-images.githubusercontent.com/40794849/225118109-bb6b6150-9759-4f6e-8497-f3b0eb098bab.png)
![изображение_2023-03-14_203819601](https://user-images.githubusercontent.com/40794849/225118169-1cd66be9-1712-403e-849f-01ec67110270.png)

**Comment by sidorovamariya1406** [comment]
summary:
    Визуальный баг на вкладке Lobby
environment:

-  Microsoft Edge
-  Chrome
-  Firefox iPone

steps-to-reproduce:
   Открыть главную страницу Codebattle
expected-result:
    Интерфейс страницы будет отражаться без визуальных багов
actual-result:
    Над иконками в столбце State визуальный баг в виде черточки
 
![Баг 7](https://user-images.githubusercontent.com/122470975/225761935-2cb6b404-3200-480a-8b9d-c33da4d45b77.png)
