### ISSUE TITLE
Bug: В форме создания турнира календарь на русском языке

### ISSUE THREAD

**Issue by Trouble666** [hexlet-codebattle/codebattle#1392]
### Summary

В форме создания турнира календарь на русском языке, в то время как вся форма на английском, как и весь сайт (исключая описание задачи внутри игры, и то, с возможностью смены языка)

![изображение_2023-03-14_213236819](https://user-images.githubusercontent.com/40794849/225129884-2f2abeb7-b76e-4d74-8ba1-5c75b57c921b.png)

### Reproduction steps

```bash
1. Быть авторизованным на сайте
2. Находится на главной странице
3. Перейти в раздел турниров по кнопке "Tournaments"
4. Нажать на кнопку "You may want to create one"
5. Нажать на иконку календаря в поле даты
```

### Expected result

Календарь, как и вся форма создания турнира, должен быть на английском языке

### Actual result

Календарь на русском языке

### Browsers

Opera

### OS

Windows

**Comment by teanacheys** [comment]
![3](https://user-images.githubusercontent.com/121870362/226953735-7738f07a-2bf0-4c35-81e0-c031e4b3ee2e.png)
Windows 7
Версия 109.0.5414.120 (Официальная сборка), (64 бит)

1. Авторизоваться 
2. Быть на главной странице 
3. Выбрать раздел "Tournaments"
4. Создать новый турнир "You may want to create one"
5. Нажать на календарь

**Comment by mihailsadov** [comment]
Браузер Mozilla Firefox 111.0.1 (64-разрядный) баг воспроизводится

**Comment by gleb5656** [comment]
- summary: |
    При создании турнира окно календаря на русском языке.  
  environment: |
    macOS Ventura 13.2
Safari 16.3 (18614.4.6.1.5)
  steps-to-reproduce: |
1. Пройти авторизацию    
2. Перейти во вкладку Tournaments в правом верхнем углу главной страницы
3. .  Кликнуть на поле ''Starts at (UTC)''  
<img width="981" alt="Снимок экрана 2023-04-17 в 14 19 19" src="https://user-images.githubusercontent.com/127134216/232471783-933d9389-7d9c-4882-930a-894cccb37e7a.png">
  expected-result: |
    Появляющееся при нажатии на поле ''Starts at (UTC)''  окно календаря имеет тот же язык, что и весь остальной сайт
  actual-result: |
    Окно календаря имеет русский язык, в то время как весь остальной сайт на английском языке.

**Comment by smokeinureyes** [comment]
Reproduction steps
1. Быть авторизованным на сайте
2. Находится на главной странице
3. Перейти в раздел турниров по кнопке "Tournaments"
4. Нажать на кнопку "You may want to create one"
5. Нажать на иконку календаря в поле даты
Expected result
Календарь, как и вся форма создания турнира, должен быть на английском языке

Actual result
Календарь на русском языке

Browsers
Chrome (114.0.5735.133 (Официальная сборка), (64 бит))

OS
Windows 10 Pro (21H2)
![Screenshot_4](https://github.com/hexlet-codebattle/codebattle/assets/134138572/1f8903b6-0af2-41c6-bf8b-6602d7f3e056)

**Comment by ReDBrother** [comment]
Это встроенный календарь браузера. Мы не можем его локализацию контролировать. Она жестко привязана к вашему браузеру
