### ISSUE TITLE
Bug: Визуальный баг отображения иконки в таблице "Lobby" в разделе "State"

### ISSUE THREAD

**Issue by Trouble666** [hexlet-codebattle/codebattle#1396]
### Summary

Визуальный баг отображения иконки в таблице "Lobby" в разделе "State"
(Не исправленный баг https://github.com/hexlet-codebattle/codebattle/issues/1390#issue-1623537542)

### Reproduction steps

```bash
1. Быть авторизованным на главной странице сайта
```

### Expected result

Иконки должны быть без артефактов, размытых краев

### Actual result

В верхнем правом углу виден артефакт в виде тонкой черты
![изображение_2023-03-15_170907429](https://user-images.githubusercontent.com/40794849/225371353-dbea3c2b-c2c5-4f80-aac9-0fae71bdf297.png)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by 2KO1** [comment]
#1390
