### ISSUE TITLE
Bug: неправильное отображение иконки и названия ссылки на телеграм-канал 

### ISSUE THREAD

**Issue by Trouble666** [hexlet-codebattle/codebattle#1399]
### Summary

Неправильное отображение иконки и названия ссылки на телеграм-канал. Вместо них отображается иконка и название слака
(не исправленный, но закрытый баг https://github.com/hexlet-codebattle/codebattle/issues/1376#issue-1619995878)

### Reproduction steps

```bash
1. Быть авторизованным на сайте
2. Нажать на иконку профиля в правом верхнем углу
3. Нажать на ссылку Slack#Codebattle
```

### Expected result

Переход по ссылке в слак

### Actual result

Переход на страницу телеграма с подтверждением открыть приложение

![изображение_2023-03-16_173820821](https://user-images.githubusercontent.com/40794849/225690578-dddfd0a8-feaa-4c56-9a11-31b64aed40e5.png)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by teanacheys** [comment]
![2](https://user-images.githubusercontent.com/121870362/226952265-d109bc2d-c454-4b2d-bf6d-a9e348dc8d10.png)
Windows 7. 
Версия 109.0.5414.120 (Официальная сборка), (64 бит)
Авторизоваться на сайте
Нажать на имя своего профиля вверхнем правом углу

**Comment by fey** [comment]
Correct link: https://t.me/hexletcommunity/5

**Comment by vtm9** [comment]
fixed
