### ISSUE TITLE
Bug: Нечитаемые символы в ссылке-приглашении

### ISSUE THREAD

**Issue by Trouble666** [hexlet-codebattle/codebattle#1400]
### Summary

В картинке, которая отправляется вместе с ссылкой-приглашением, под аватаркой есть странные нечитаемые символы. Воспроизводится в телеграме, вк, 

### Reproduction steps

```bash
1. Быть авторизованным на сайте
2. Создать игру с указанием "With other users"
3. Скопировать ссылку на игру
4. Отправить через личные сообщения тереграм или вк
```

### Expected result

Текст на изображении, автоматически приклепляемое к сообщению, будет понятным и читаемым 

### Actual result

Текст на изображении, автоматически приклепляемое к сообщению, имеет строчку с нечитаемыми символами
![изображение_2023-03-16_180240726](https://user-images.githubusercontent.com/40794849/225696969-d6fe4e61-152c-41b9-bc8b-704b5952a0ae.png)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by vikahati** [comment]
**Summary**
В картинке, которая отправляется вместе с ссылкой-приглашением есть нечитаемые символы. Воспроизводится в телеграме, вк.
**Reproduction steps**

1. Быть авторизованным на сайте.
2. Создать игру с указанием "With other users".
3. Скопировать ссылку на игру.
4. Отправить через личные сообщения тереграм или вк.

**Expected result**
Текст на изображении, автоматически приклепленый к сообщению понятный и читаемый.

**Actual result**
Текст на изображении, автоматически приклепленый к сообщению, имеет строчку с нечитаемыми символами

**Browsers**
Yandex

**OS**
Linux
