### ISSUE TITLE
Bug: Пользователь может несколько раз выигрывать одну и ту же игру

### ISSUE THREAD

**Issue by sidorovamariya1406** [hexlet-codebattle/codebattle#1402]
### Summary

Проверка работы антифрода на повторное создание ранее выигранной игры

### Reproduction steps

```bash
1. Выбрать Lavel
2. Выбрать Game Type = With other users
3. Установить Time control
4. Выбрать игру (раскрывающийся список Choose task by name or tags)
5. Нажать Create Battle
6. Выиграть игру
7. Нажать на Create a game
8. Выбрать Lavel
9. Выбрать Game Type = With other users
10. Установить Time control
11. Выбрать ту же игру, что и на шаге 4 (раскрывающийся список Choose task by name or tags)
12. Нажать Create Battle
```

### Expected result

Пользователь получит предупреждение, о том, что уже выигрывал эту игру

- и не может повторно ее проходить
или
- может пройти ее повторно без изменения результатов в показателях своего рейтинга

### Actual result

Пользователь может повторно создать ранее выигранную игру несколько раз. При этом каунтер его побед засчитывает каждый повторный выигрыш

![Баг 4 1](https://user-images.githubusercontent.com/122470975/225751232-c54e731c-052b-44e6-8e2e-644c5175e4b3.png)
![Баг 4 2](https://user-images.githubusercontent.com/122470975/225751235-5173731d-d583-4b50-9138-c7e7ff69f53f.png)
![Баг 4 3](https://user-images.githubusercontent.com/122470975/225751239-fa1bbd1a-ed88-46e8-833a-e9e08f780db5.png)
![Баг 4 4](https://user-images.githubusercontent.com/122470975/225751242-0735142f-9e55-445b-85ef-9f87b00d1b2a.png)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это фича. Сейчас мы не будем этот процесс контролировать, так же как мы не можем запретить создавать игры пользователям, которые прошли все задачи полностью)
