### ISSUE TITLE
Bug: С пользователя списывается время просмотра руководства

### ISSUE THREAD

**Issue by sidorovamariya1406** [hexlet-codebattle/codebattle#1403]
### Summary

Проверка учета времени на игру во время просмотра руководства

### Reproduction steps

```bash
prerequisites: Игра в процессе
steps:
1. Отметить оставшееся время на игру
2. Нажать на Show guide
3. Нажать Next
4. Нажать Skip guide
5. Отметить оставшееся время на игру
```

### Expected result

Просмотр руководства пользователя не должно учитываться во времени на игру

### Actual result

После возвращения пользователя в игру время, проведенное в руководстве, списалось (засчиталось как игровое)

https://user-images.githubusercontent.com/122470975/225756922-9df540f3-2ace-42e8-9279-0c75c9c52148.mov

### Browsers

Chrome

### OS

Windows

**Comment by mihailsadov** [comment]
Браузер Mozilla Firefox 111.0.1 (64-разрядный) баг воспроизводится

**Comment by ReDBrother** [comment]
Гайд и игровой процесс не будут связаны между собой. Это немного жестоко, но это часть такого соревнования)
