### ISSUE TITLE
Feature Request: show TOP users without bots by default

### ISSUE THREAD

**Issue by sidorovamariya1406** [hexlet-codebattle/codebattle#1404]
### Summary

Переключатель With bot отмечен активным по умолчанию

### Reproduction steps

```bash
1. Открыть страницу Users rating (нажать ссылку TOP list)
```

### Expected result

При открытии страницы все фильтры будут сброшены

- переключатель назван  Without bot (изначально рейтинг сформирован с пользователями и ботами, при включении Without bot список отчищается от ботов)
или
- переключатель назван With bot (изначально рейтинг сформирован без учета ботов, при включении With bot список дополняется ботами)

### Actual result

При открытии страницы переключатель With bot активен

![Баг 6 1](https://user-images.githubusercontent.com/122470975/225758480-25de3d92-621a-414a-8f20-36c8e56a7b4e.png)
![Баг 6 2](https://user-images.githubusercontent.com/122470975/225758487-31549cb2-55a3-432b-8cad-467dfecee89a.png)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Добрый день.

Обратите внимание, что у ботов нет рейтинга. А у пользователей есть. На втором скрине у пользователей есть рейтинг.

**Comment by sidorovamariya1406** [comment]
Добрый день!
Я понимаю, что работает все правильно.
Я заводила баг как UI, предлагая изначально оставить этот чекбокс неактивным 



Отправлено из мобильной Почты Mail.ru


четверг, 23 марта 2023 г., 10:27 +0300 от ***@***.***  ***@***.***>:

**Comment by solar05** [comment]
Fixed
