### ISSUE TITLE
Bug: empty page on TOP list page

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#1408]
### Summary

При открытии последней страницы с топом пользователей и выключенным тогглом "With bots" выводится пустая страница.

### Reproduction steps

```bash
1. заходим на https://codebattle.hexlet.io/users
2. убираем галочку "With bots"
3. водим в поиск `bot`, жмем enter
4. Скроллим вниз и выбираем последнюю страницу (5)
```

### Expected result

Пользователь может открыть только те страницы в списке, на которых есть юзеры.

### Actual result

Пользователь попадает на пустую страницу

При этом есл инажать на номер страницы (1)

![image](https://user-images.githubusercontent.com/697178/227133285-a1c77c5e-62a5-4223-a2d0-692e1153f06e.png)

То загрузится список пользователей.

![image](https://user-images.githubusercontent.com/697178/227133603-e25b236a-9615-4289-a2f3-32da7781963c.png)

### Browsers

Chrome

### OS

Linux

**Comment by ReDBrother** [comment]
Мы убрали (bot) из имени и поставили на ее место иконку - бага неактуальна)
