### ISSUE TITLE
Bug: Нет полного перевода меню на русский язык

### ISSUE THREAD

**Issue by Ser1983gey** [hexlet-codebattle/codebattle#1412]
### Summary

Проверка версии Codebattle на русском языке

### Reproduction steps

```bash
1.Заходим на страницу сайта Codebattle.
 2.Переходим в настройки сайта.
 3.Заходим в любую игру.
 4.Меняем язык с английского на русский в условии игры(Task).
```

### Expected result

Все меню Codebattle на русском языке

### Actual result

На русский язык переводится только условие во время игры

### Browsers

Chrome

### OS

Windows

**Comment by gleb5656** [comment]
###  summary: 
    Страница сражений, поддерживающая русский язык, не переводит все что должна переводить.  
  ### environment: 
    macOS Ventura 13.2 Safari 16.3 (18614.4.6.1.5)
  ### steps-to-reproduce:
1. Авторизуемся    
2. Вступаем в бой с любым ботом
3. Выбираем русский язык
  ### expected-result:
    Все, что подлежит переводу переводится на русский. 
  ### actual-result: 
    Некоторые блоки не переводятся на русский, хотя должны (например, надпись ''this users have contributed to this task" и всплывающие окна гайда. 
<img width="1440" alt="Снимок экрана 2023-04-18 в 23 39 55" src="https://user-images.githubusercontent.com/127134216/232900788-f89a0604-30f8-448a-9913-37f5e44f8482.png">
![Uploading Снимок экрана 2023-04-18 в 23.45.43.png…]()

**Comment by Steelrat3** [comment]
Воспроизводится.

Summary: 
Успешное переключение языка с русского на английский во время игры
Environment:
Windows 10 pro.
Google Chrome.
Версия 113.0.5672.127 (Официальная сборка), (64 бит)
Prerequisites:
В браузере открыты две одинаковые вкладки URL = https://codebattle.hexlet.io/games/135387
В первой вкладке установлен язык "English"
Во второй вкладке установлен язык "Русский"
Test-data: 
-
Steps: 
Убедиться в корректности перевода текста на русский язык
Expected-result: 
Перевод на русский язык выполняется корректно
Actual result:
Перевод выполняется некорректно: на русский язык переводится только условие во время игры

**Comment by katrytikova** [comment]
Воспроизводится.
Google Chrome 113.0.5672.126 (Официальная сборка), (arm64)
macOS Ventura 13.1

**Comment by ReDBrother** [comment]
Русской локализации не будет. Только контент задач
