### ISSUE TITLE
Bug: Неправильное название ссылки slack вместо telegram

### ISSUE THREAD

**Issue by Ser1983gey** [hexlet-codebattle/codebattle#1413]
### Summary

В правом верхнем углу в выпадающем меню выходит название ссылки slack вместо telegram #1399

### Reproduction steps

```bash
1.Зарегистрироваться в Codebattle.
2.Вызвать мышкой выпадающее меню в правом верхнем углу.
```

### Expected result

Должна быть ссылка с названием Telegram

### Actual result

Есть ссылка с названием Slack

### Browsers

Chrome

### OS

Windows

**Comment by vikahati** [comment]
**Summary**
В правом верхнем углу в выпадающем меню выходит название ссылки slack вместо telegram 
**Reproduction steps**

1. Зарегистрироваться в Codebattle.
2. На главной странице профиля возле иконки профиля вызвать выпадающее меню.
**Expected result**
Должна быть ссылка с названием Telegram
**Actual result**
Ссылка с названием Slack
**Browsers**
Yandex
**OS**
Linux

**Comment by 2KO1** [comment]
Исправлено
