### ISSUE TITLE
Bug: В окне турнира надпись об отсутствии участников выходит за рамки поля

### ISSUE THREAD

**Issue by Salivya** [hexlet-codebattle/codebattle#1414]
### Summary

Надпись No participants yet вылезает за рамки окна на странице созданного турнира
<img width="1280" alt="Снимок экрана 2023-04-03 в 17 20 29" src="https://user-images.githubusercontent.com/119805947/229543637-d7fa1caf-c462-43c2-93fe-b9bc77342979.png">

### Reproduction steps

```bash
prerequisites:
    Пользователь авторизован
    Открыта страница: https://codebattle.hexlet.io/tournaments
  steps:
    - Оставляем базовые настройки
    - Нажимаем кнопку Create
```

### Expected result

Турнир создан, надписи отображаются корректно

### Actual result

Турнир создан, но надпись  No participants yet отображается некорректно 

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Сможем сделать адаптивную страницу только когда перепишем турниры
https://github.com/hexlet-codebattle/codebattle/issues/963
