### ISSUE TITLE
Bug: Не исчезает визуальное отображение Guide после его закрытия 

### ISSUE THREAD

**Issue by Salivya** [hexlet-codebattle/codebattle#1415]
### Summary

Нажатие на значок Х закрывает окно Guide, но не закрывает визуальное отображение гида (синий кружок)

https://user-images.githubusercontent.com/119805947/229748320-911f80be-313e-4480-9d85-0adf5dbfdc5d.mp4

**Похожий закрытый баг: https://github.com/hexlet-codebattle/codebattle/issues/1235**

Safari Версия 16.1 (18614.2.9.1.12)
macOS Ventura Версия 13.0 (22A380)

### Reproduction steps

```bash
Пользователь должен быть авторизован в программе

- Открываем страницу https://codebattle.hexlet.io/#lobby
- Нажимаем кнопку "Create a game"
- Нажимаем кнопку "Show guide"
- Нажимаем кнопку "x"
```

### Expected result

Guide пропал

### Actual result

Guide пропал частично, остается визуальное отображение

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Сложный момент, попробуем подумать над тем как усовершенствовать гайд. Сейчас это фича
