### ISSUE TITLE
Реализовать выбор Task_pack в настройках создания турнира

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1417]
### Summary

Необходимо реализовать выбор Task_pack в настройках создания турнира.
![image](https://user-images.githubusercontent.com/102296858/230410427-08873435-0f05-4f92-a397-763c529ea8a3.png)
Возможно стоит сделать выбор сборников заданий, также как и выбор уровня сложности игры, т.е. выпадающим списком.

### Reproduction steps

```bash
- Авторизоваться в Codebattle
- Нажать на аватар в правом верхнем углу
- Перейти в раздел "Tournaments"
- В настройках создания турнира выбрать "task_pack" в "Task provider"
- В появившемся поле "Task pack" выбрать интересующий сборник
```

### Expected result

 В появившемся поле "Task pack" имеется возможность выбора сборников

### Actual result

В появившемся поле "Task pack"  невозможно произвести выбор сборников заданий

**Comment by Shvidunov** [comment]
видимо поиск должен осуществляться по уникальному номеру task pack, поскольку поле позволяет вводить только числовые значения. Безусловно намного удобнее выбирать по названию из выпадающего списка.

**Comment by ReDBrother** [comment]
Починили
