### ISSUE TITLE
Визуальный дефект кнопки "Challenge to a game" в чате игры

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1419]
### Summary

![image](https://user-images.githubusercontent.com/102296858/230429899-60502402-e1dd-4968-9ea5-67d7b09cd2b2.png)
а самое верхнее сообщение имеет еще дефект рамки сверху:
![image](https://user-images.githubusercontent.com/102296858/230430198-60003a0b-b724-4cdf-9948-c0464e28a562.png)
в чате игры:
![image](https://user-images.githubusercontent.com/102296858/230430642-f7cf7b86-6b35-4197-8314-e22dbe346107.png)

### Reproduction steps

```bash
- Авторизоваться в Codebattle
- Нажать на кнопку "Challenge to a game"
```

### Expected result

Кнопка не имеет визуальных дефектов

### Actual result

Кнопка имеет визуальный дефект

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Убрали кнопку в контекстное меню
