### ISSUE TITLE
Ошибка 429 при нажатии на "Return to game" при просмотре истории во время игры

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1421]
### Summary

![image](https://user-images.githubusercontent.com/102296858/230485574-6b2213e2-600d-4790-8ef8-3fdb49d2e23e.png)
![image](https://user-images.githubusercontent.com/102296858/230485924-bcb61dd2-fe6b-41ca-ab52-b9b400c3dfe0.png)

### Reproduction steps

```bash
- Авторизоваться в Codebattle
- Создать игру с ботом
- Нажать кнопку "Open History"
- Нажать кнопку "Return to game"
```

### Expected result

Отсутствие ошибок в DevTools

### Actual result

Отображена ошибка 429

### Browsers

Chrome

### OS

Windows

**Comment by smokeinureyes** [comment]
Баг всё еще воспроизводится

Reproduction steps
1. Авторизоваться в Codebattle
2. Создать игру с ботом
3. Нажать кнопку "Open History"
4. Нажать кнопку "Return to game"

Browsers
Chrome

OS
Windows
![Screenshot_3](https://github.com/hexlet-codebattle/codebattle/assets/134138572/42ed781e-c81f-48a9-93d2-9164fe369e0a)

**Comment by ReDBrother** [comment]
fixed
