### ISSUE TITLE
Bug: При создании игры с ботом, нет возможности перевода его фраз.

### ISSUE THREAD

**Issue by sddanilin** [hexlet-codebattle/codebattle#1422]
### Summary

При создании игры с ботом, есть возможность перевода на русский язык только задачи. К сожалению, слова бота таким же образом перевести нельзя. 

### Reproduction steps

```bash
1. Зайти на главную страницу
2. Нажать кнопку «Create a game»
3. Выбрать «Game Type» – «With a bot»
```

### Expected result

В созданной игре будет возможность перевода текста задачи, но нет такой же возможности перевода и слов бота. 

### Actual result

![Снимок проект](https://user-images.githubusercontent.com/121114052/230579042-a509b41f-3f2f-4991-861e-5e281d3fda87.PNG)

### Browsers

Chrome

### OS

Windows

**Comment by Soomario** [comment]
Browsers
Opera

OS
Windows

**Comment by ReDBrother** [comment]
Русской локализации ничего кроме контента задач не будет. Ни интерфейса, ни бота
