### ISSUE TITLE
Некорректное отображение главной страницы

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1423]
### Summary

![image](https://user-images.githubusercontent.com/102296858/230771054-79f181f8-a37d-4c40-8097-2541504d233c.png)
Ошибка плавающая

### Reproduction steps

```bash
- Авторизоваться в Codebattle
- Нажать на аватар в правом верхнем углу
- Перейти в раздел "Tournaments"
- Нажать на кнопку "Codebattle" в верхнем левом углу
```

### Expected result

Корректное отображение главной страницы

### Actual result

Некорректное отображение главной страницы

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
@2KO1 а что здесь не так? :thinking:

**Comment by 2KO1** [comment]
@fey 
![image](https://user-images.githubusercontent.com/102296858/230935441-7dbc7216-37ff-4ff0-9b44-cb9698319efb.png)
главная страница должна отображать лишь один открытый раздел на выбор "lobby"/"tournaments"/"completed games" и соответственно чат главной страницы, при возникновении данной ошибки отображены все вкладки одновременно друг под другом, получается смысл вкладок отпадает в целом

**Comment by fey** [comment]
а, понял. Может быть здесь какой-то js код не отрабатывает? Можно поиграть с девтулс .чтобы повторить ошибку.

**Comment by 2KO1** [comment]
к сожалению мне пока знаний не хватает, но попробую что-то сообразить

**Comment by ReDBrother** [comment]
Fixed
