### ISSUE TITLE
Отображение времени в едином формате

### ISSUE THREAD

**Issue by 2KO1** [hexlet-codebattle/codebattle#1424]
### Summary

На данный момент время во вкладках "tournaments"/"completed_games" отображено в соответствии с системным временем пользователя, на странице "https://codebattle.hexlet.io/tournaments" время в списке турниров отображается в формате UTC +3.
![image](https://user-images.githubusercontent.com/102296858/231231441-bbb6fd4c-89c9-4cea-9a27-ebb5f736f1cb.png)
![image](https://user-images.githubusercontent.com/102296858/231231496-fdf7260e-c719-421b-8a8d-39a032d7ce8a.png)

### Reproduction steps

```bash
- Авторизоваться в Codebattle
- Перейти во вкладку "Tournaments"
- Нажать на аватар в правом верхнем углу
- Перейти в раздел "Tournaments"
```

### Expected result

Время во вкладках "tournaments"/"completed_games" и на странице "https://codebattle.hexlet.io/tournaments" отображено в соответствии с временем пользователя.

### Actual result

Время во вкладках "tournaments"/"completed_games" и на странице "https://codebattle.hexlet.io/tournaments" не отображено в соответствии с временем пользователя.

### Browsers

Chrome

### OS

Windows

**Comment by IoannP** [comment]
возьму
