### ISSUE TITLE
Bug: После завершения игры, остается возможность редактировать код

### ISSUE THREAD

**Issue by vaysl7599** [hexlet-codebattle/codebattle#1425]
### Summary

Проверка отсутствия возможности редактировать код в завершенной игре

### Reproduction steps

```bash
1. Зайти на главную страницу Codebattle 
2. Во вкладке "LOBBY" выбрать подходящую игру
3. Нажать кнопку "Fight    
4. Нажать на значок с красным флажком над редактором кода "Give up"
5. Во всплывающем окне нажать кнопку "Give up"
6. Редактировать код в своем редакторе
```

### Expected result

Код остается неизменным

### Actual result

Код редактируется

https://user-images.githubusercontent.com/122399471/231291107-b72be48b-8bdb-4a89-9060-7c1bd4dcbfab.mp4

### Browsers

Chrome, Safari, Opera

### OS

Windows, Mac

**Comment by gleb5656** [comment]
###  summary: 
    Игрок может продолжить редактирование кода после конца игры.  
  ### environment: 
    macOS Ventura 13.2 Safari 16.3 (18614.4.6.1.5)
  ### steps-to-reproduce:
1. Пройти авторизацию    
2. Вступить в любой бой с ботом 
3. Нажать на красный флаг
4. Нажать на give up
5. Закрыть всплывающее окно
6. Попробовать ввести код
  ### expected-result:
    Пользователь не сможет вводить и изменять код после завершения игры. 
  ### actual-result: 
    Пользователь может вводить и изменять код после завершения игры.

**Comment by ReDBrother** [comment]
Это фича. После завершения игры мы даем ограниченное время поиграть с задачей
