### ISSUE TITLE
Bug: Визуальный баг на странице статистики игрока в мобильной версии

### ISSUE THREAD

**Issue by gleb5656** [hexlet-codebattle/codebattle#1427]
### Summary

Пирамида статистики переносится в мобильный браузер некорректно, надписи Lost и Gave Up "съедаются"
iOS 16.0. Safari

### Reproduction steps

```bash
1.Авторизоваться на сайте с телефона
2.Перейти к лидерборду, расположенному на главной странице. 
3 Нажать на ник любого пользователя
```

### Expected result

Все элементы описания выводятся в мобильной версии корректно и без визуальных ошибок 

### Actual result

Пирамида статистики выводится на мобильной версии с визуальным багом 
![photo_2023-04-17 15 53 30](https://user-images.githubusercontent.com/127134216/232507836-d47c17f2-5f8a-4a14-9899-fe876fa913b3.jpeg)

### Browsers

Safari

**Comment by ReDBrother** [comment]
Дубликат от https://github.com/hexlet-codebattle/codebattle/issues/1488
