### ISSUE TITLE
Bug: при регистрации нет никакого ограничения на кол-во символов больше 6

### ISSUE THREAD

**Issue by kolian181002** [hexlet-codebattle/codebattle#1429]
### Summary

При регистрации пользователь может ввести любое количество символов больше 6

### Reproduction steps

```bash
1. В поле "Nickname" вводим qwertyuiopasdfg
2. В поле "Email" вводим closedoor2@mail.ru
3. В поле "Password" 1234567890123456
4. Нажимаем на кнопку "Submit"
```

### Expected result

Пользователь не может ввести более 15-ти символов, под полем "Password" появляется сообщение "Пароль должен состоять из 6-15 символов"

### Actual result

Пользователя переносит на главную страницу сайта, регистрация проходит "успешно"

### Browsers

Chrome

### OS

Windows

**Comment by ArturNut** [comment]
Пароль может быть от 6 до 16 символов, в данном тест кейсе как раз их 16. Если больше регистрация не возможна. 
Bug CLOSED.
