### ISSUE TITLE
Bug: Некорректное отображение "rank" у впервые созданного пользователя.

### ISSUE THREAD

**Issue by AavadaKedavra** [hexlet-codebattle/codebattle#1430]
### Summary

При регистрации пользователя,  "rank" отображены некорректно в окне статистики, так и на иконке под никнеймом профиля в главном меню.
Upd. По прошествии некоторого времени ( ~5 минут) значения меняются на корректные. Никаких действий при этом не совершалось.
(Не исправленный баг https://github.com/hexlet-codebattle/codebattle/issues/1220#issue-1560381665)

### Reproduction steps

```bash
- Перейти на страницу регистрации(https://codebattle.hexlet.io/users/new?locale=en&next=%2F)
- Вводим "Nickname"
- Вводим "Email"
- Вводим "Password"
- Нажимаем "Submit"
- Открыть "My profile"
```

### Expected result

Отображены корректные данные пользователя.
У впервые зарегистрированного пользователя отображено "rank" = 190 и "elo_rating" = 1200.

### Actual result

Некорректное отображение очков "rank"
![bub20_04_2023](https://user-images.githubusercontent.com/126116401/233218619-b8b35a38-7539-478d-9cd9-0734847899f4.png)

### Browsers

 Opera GX LVL 4 (core: 95.0.4635.74) 
 Brave V. 1.50.119 Chromium: 112.0.5615.121 (Official Build) (64-bit)

### OS

Windows  10 Pro V. 21H2

**Comment by ReDBrother** [comment]
Лучше для только созданных профилей его вообще перекрыть (Оставим для списка пользователей)

**Comment by potemkina-e** [comment]
Баг воспроизводится

**summary**: |
Неправильный рейтинг у пользователя сразу после регистрации

**environment**: |
Safari версия 17.4.1 (19618.1.15.11.14)
Google Chrome версия 123.0.6312.124 (Официальная сборка), (arm64)
macOS Sonoma 14.4.1 (23E224)
Current version: e9cfc50 deployedAt UTC: 2024-04-22 12:48:14

**steps-to-reproduce**: |
Регистрируем пользователя
Переходим в личный кабинет My Profile
Анализируем Users Rating: сортировка по Rank от большего к меньшему
Через 10 минут обновляем страницу

**expected-result**: |
Рейтинг пользователя соответствующий количеству очков, сыгранным играм

**actual-result**: |
Сразу после регистрации пользователю присваивается Rank 5432. При переходе в Users Rating видно, что предшествующий Rank - 357, то есть у нового пользователя должен быть 358. Через несколько минут при отсутствии действий Rank самоcтоятельно меняется на 199
<img width="1213" alt="rank1" src="https://github.com/hexlet-codebattle/codebattle/assets/156904691/032b403b-8b48-4094-9979-73d6334557c6">
<img width="1201" alt="rank2" src="https://github.com/hexlet-codebattle/codebattle/assets/156904691/fc4b1ea4-2f9a-4316-a243-3827e393c46a">
<img width="1200" alt="rank3" src="https://github.com/hexlet-codebattle/codebattle/assets/156904691/c84ca2c1-9932-4f05-bc9a-8c99744ba162">

**Comment by ReDBrother** [comment]
Не баг, а фича
В свое время СТО выбрал такой номер для ребят, которые еще не сыграли ни одной игры)
