### ISSUE TITLE
Bug: Отображение Codebattle происходит не на всю страницу браузера

### ISSUE THREAD

**Issue by Kolesnikov92** [hexlet-codebattle/codebattle#1431]
### Summary

Запуская в браузере Safari Codebattle мы видим что он не растягивается на все окно браузера 
<img width="1281" alt="Снимок экрана 2023-04-20 в 10 02 47" src="https://user-images.githubusercontent.com/124597763/233272808-1428cd26-1582-47b9-b106-fadc5bb1548a.png">

### Reproduction steps

```bash
1. Запускаем браузер Safari 
2. Заходим на сайт Codebattle
```

### Expected result

Зайти на сайт и увидеть корректное отображение Codebattle

### Actual result

Сайт растянут не по всей области окна браузера

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Для достаточно больших экранов это сделано намеренно для всех браузеров
