### ISSUE TITLE
Bug: Смещение шрифта в мобильной версии Codebattle

### ISSUE THREAD

**Issue by Kolesnikov92** [hexlet-codebattle/codebattle#1432]
### Summary

Зайдя в мобильную версию сайта Codebattle мы видим смещение шрифта 
![IMG_34954C1AF078-1](https://user-images.githubusercontent.com/124597763/233275147-c4df575e-e746-44f9-8ae3-f65858eb0b74.jpeg)

### Reproduction steps

```bash
1. Заходим в браузер Safari на iPhone 
2. Вводим Codebattle в браузере
3. Нажимаем на свой ник
4. Нажимаем кнопку мой профиль
```

### Expected result

Корректное отображение текста 

### Actual result

Текст поехал в правом верхнем углу

### Browsers

Safari

### OS

Mac

**Comment by bodyamog** [comment]
Summary
Текст и элементы страницы профиля пользователя отображаются некорректно
![Screenshot_7](https://github.com/hexlet-codebattle/codebattle/assets/131721540/d11f297f-af60-4a4e-8dc0-32a1d27b5d31)

Reproduction steps
1. Используя мобильное устройство авторизоваться на сайте
2. Открыть страницу профиля своего пользователя

Expected result
Все элементы страницы корректно отображаются на мобильных устройствах

Actual result
Аватар пользователя слишком большой. Ник пользователя отображается с переносом на новую строку

**Comment by ReDBrother** [comment]
В рамках адаптации всей страницы профиля
https://github.com/hexlet-codebattle/codebattle/issues/1488
