### ISSUE TITLE
Bug: Некорректное отображение названия столбцов

### ISSUE THREAD

**Issue by Kolesnikov92** [hexlet-codebattle/codebattle#1433]
### Summary

Некорректное отображение названия столбцов
<img width="1281" alt="Снимок экрана 2023-04-20 в 10 22 57" src="https://user-images.githubusercontent.com/124597763/233276474-b9c217e4-4f91-49af-8069-23e99c929b07.png">

### Reproduction steps

```bash
1. Заходим в браузер Safari
2. Заходим в Codebattle
3. Нажимаем на свой ник 
4. Нажимаем кнопку Users raiting
```

### Expected result

Увидеть корректное отображение названия столбцов

### Actual result

Шрифт и качелька регулировки скачет как попало 

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Перенесли ранг в другое место и на ее перенесли реальную нумерацию.
