### ISSUE TITLE
Bug: При создании игры, в ситуации, когда игрок не завершил предыдущую игру ничего не происходит

### ISSUE THREAD

**Issue by gleb5656** [hexlet-codebattle/codebattle#1434]
### Summary

При создании игры, в ситуации, когда игрок не завершил предыдущую игру ничего не происходит

### Reproduction steps

```bash
1. Авторизуемся 
2. Начинаем бой с ботом
3. Нажимаем в левый верхний угол чтобы вернуться к главному меню 
4. Нажимаем кнопку create a game 
5. Вводим любые параметры
6. Нажимаем Create battle.
```

### Expected result

Пользователь видит предупреждение, что он не закончил прошлую игру/Игра начинается 

### Actual result

После нажатия на кнопку Create Battle окно создания баттла закрывается и больше ничего не происходит. 

### Browsers

Safari

### OS

Mac

**Comment by Daria-new** [comment]
Баг воспроизводится
Chrome
Windows

**Comment by ReDBrother** [comment]
Это не баг. Это важное ограничение платформы. Нельзя создавать больше одной игры
