### ISSUE TITLE
Bug: Кнопки отображаются разного цвета

### ISSUE THREAD

**Issue by Romul76** [hexlet-codebattle/codebattle#1435]
### Summary

При переходе на "Try Simple Battle" кнопки Sign in и Sign up отображаются разного цвета

### Reproduction steps

```bash
1. Перейти на сайт как незарегистрированный пользователь
2. Нажать "Try Simple Battle"
```

### Expected result

У кнопок Sign in и Sign up не меняется цвет

### Actual result

У кнопок Sign in и Sign up меняется цвет

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Рассинхрон между стилями главной и всего остального приложения.
В общую кучу с https://github.com/hexlet-codebattle/codebattle/issues/1261

**Comment by ReDBrother** [comment]
fixed
