### ISSUE TITLE
Bug: Неадаптированное отображение

### ISSUE THREAD

**Issue by kolian181002** [hexlet-codebattle/codebattle#1441]
### Summary

Неадаптированное отображение форм на главной странице баттла в мобильной версии.
Пользователю необходимо скролить экран по горизонтали.

### Reproduction steps

```bash
1. Зайти на https://codebattle.hexlet.io/
2. Авторизоваться на сайте
3. Смотреть разделы Lobby, Tournaments, Completed Games
```

### Expected result

Открывшаяся главная страница баттла адаптирована под экран мобильного устройства

### Actual result

Поля форм главной страницы не адаптируются под экран мобильного устройства.
![Снимок экрана 2023-04-26 200956](https://user-images.githubusercontent.com/128052786/234652166-23f39dbd-1dba-4b2c-887d-bcfac5001c3a.png)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нужно переработать все колонки, чтобы последовательность для мобильной версии была такой (сверху-вниз):
1) Create Game
2) Вся таба Lobby/Tournaments/Completed Game
3) Чат
4) Рейтинг
5) Анонсы

На обычных экранах все должно остаться на месте

**Comment by rizhik356** [comment]
имеешь ввиду вот так вот? В целом могу попробовать.
<img width="295" alt="Снимок экрана 2023-06-29 в 21 59 32" src="https://github.com/hexlet-codebattle/codebattle/assets/116464559/9ed8167f-2746-45ef-b9cb-ec1537553de8">

**Comment by ReDBrother** [comment]
Да, только там будет один SMTH - это кнопка сreate game)

**Comment by rizhik356** [comment]
ага понял, ну давай попробую сделать

**Comment by AnnaGurina** [comment]
- summary: |
    Раздел Lobby/Tournaments/Completed Game не адаптирован в мобильной версии
  environment: |
    Google Chrome   Версия 115.0.5735.124 (Официальная сборка), (64 бит)
    iPhone 14
Cb version: 6de75b
  steps-to-reproduce: |
    1. Зайти на страницу https://codebattle.hexlet.io/
    2. Авторизоваться
  expected-result: |
    Раздел Lobby/Tournaments/Completed Game адаптирован в мобильной версии
  actual-result: |
    Раздел Lobby/Tournaments/Completed Game не адаптирован в мобильной версии: для просмотра необходимо скроллить его по горизонтали.
![Фото 12 08 2023, 13 48 31](https://github.com/hexlet-codebattle/codebattle/assets/62752547/28f12916-cea2-4d3d-a665-de2f83202ca9)
![Фото 12 08 2023, 14 13 01](https://github.com/hexlet-codebattle/codebattle/assets/62752547/4a42610f-24cb-4602-9c4c-4db5e6fd3781)

**Comment by ElenaSimanina** [comment]
- summary: |
     Сайт некорректно отображается на разных мобильных устройствах
  environment: |
     Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
     ОС Windows 10
  steps-to-reproduce: |
     1. Открыть страницу сайта https://codebattle.hexlet.io/#lobby
     1. Открыть инструмент DevTools
     2. Выбрать в меню «Дополнительные инструменты → Инструменты разработчика» 
     3. Нажать на кнопку «Toggle device toolbar» 
     4. Выбрать поочередно разные мобильные устройства  
  expected-result: |
     При выборе разных мобильных устройств страница сайта, кнопки и чаты  отображаются корректно  
  actual-result: |
     При выборе разных мобильных устройст страница сайта, кнопки и чаты отображаются некорректно или не отображаются совсем. 
     
![Скриншот Некорректное отображение страницы сайта на разных мобильных устройствах](https://github.com/hexlet-codebattle/codebattle/assets/135851722/0ddc590a-f311-4221-b509-07d6b7517bc2)

**Comment by ReDBrother** [comment]
> * summary: |
>   Сайт некорректно отображается на разных мобильных устройствах
>   environment: |
>   Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
>   ОС Windows 10
>   steps-to-reproduce: |
>   
>   1. Открыть страницу сайта https://codebattle.hexlet.io/#lobby
>   2. Открыть инструмент DevTools
>   3. Выбрать в меню «Дополнительные инструменты → Инструменты разработчика»
>   4. Нажать на кнопку «Toggle device toolbar»
>   5. Выбрать поочередно разные мобильные устройства
>      expected-result: |
>      При выборе разных мобильных устройств страница сайта, кнопки и чаты  отображаются корректно
>      actual-result: |
>      При выборе разных мобильных устройст страница сайта, кнопки и чаты отображаются некорректно или не отображаются совсем.
> 
> ![Скриншот Некорректное отображение страницы сайта на разных мобильных устройствах](https://user-images.githubusercontent.com/135851722/260526872-0ddc590a-f311-4221-b509-07d6b7517bc2.png)

Мы точно не сможем адаптировать именно содержимое таблицы, и вместить все в экран, поэтому скроллить можно и по горизонтали до остального контента.

**Comment by ElenaSimanina** [comment]
Доброго времени суток!
Я поняла!
Спасибо большое за ответ!)

пн, 14 авг. 2023 г. в 23:39, Dmitriy Bataev ***@***.***>:

**Comment by ReDBrother** [comment]
Поправили
