### ISSUE TITLE
Bug: Некорректное расположение кнопок Save и Back на странице Create new task

### ISSUE THREAD

**Issue by Shvidunov** [hexlet-codebattle/codebattle#1443]
### Summary

Проверка оформления страницы создания новой задачи Create new task

### Reproduction steps

```bash
1. зайти на сайт https://codebattle.hexlet.io/#lobby и авторизоваться
2. перейти по адресу https://codebattle.hexlet.io/tasks/new в раздел Create new task 
3. изучить элементы оформления
```

### Expected result

все элементы выполнены в одном стиле, выровнены, соответствуют оформлению страницы

### Actual result

надписи в кнопках Save и Back расположены на разном уровне, кнопка Back не имеет цветовой индикации границ, активное поле кнопки значительно больше надписи и не идентифицируется визуально

![image](https://user-images.githubusercontent.com/121935818/235743859-b0dd2dc2-fcee-45cc-bbcf-70168d20faa5.png)

### Browsers

Firefox, Chrome, Microsoft Edge

### OS

Windows

**Comment by Shvidunov** [comment]
аналогично для страницы Create new task pack

**Comment by GordienkoEvgeny** [comment]
беру в работу
