### ISSUE TITLE
Bug: Неочевидная последовательность перехода новой задачи из статуса draft в статус active

### ISSUE THREAD

**Issue by Shvidunov** [hexlet-codebattle/codebattle#1444]
### Summary

Проверка присвоения статуса новой задаче после создания

### Reproduction steps

```bash
1. перейти на страницу сайта https://codebattle.hexlet.io/ и авторизоваться
2. перейти на страницу создания новой задачи Create new task https://codebattle.hexlet.io/tasks/new
3. создать новую задачу с корректным заполнением всех полей
4. сохранить новую задачу
```

### Expected result

новая задача сохранена, дополнительно выводится информация о статусе "черновик" и необходимости проверки (или иных действиях) до перевода в статус "активна"

### Actual result

Новой задаче присвоен статус черновик, информация о сроках и требованиях для активации отсутствует

![image](https://user-images.githubusercontent.com/121935818/235747141-f2b71d5b-3e77-4246-bb10-5cd6e158b6b2.png)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
@vtm9 Что скажешь?

**Comment by vtm9** [comment]
возможно надо написать пояснение что такое драфт и чтобы задача стала active надо пингануть кого-то из админов чтобы они ее активировали

**Comment by vtm9** [comment]
в draft задачи по прежнему можно играть, но они будут попадаться только если создатель сам создает игру для других игроков они не видимы

**Comment by ReDBrother** [comment]
Ок, в доке будет
https://github.com/hexlet-codebattle/codebattle/issues/1500
