### ISSUE TITLE
Bug: Слабая визуализация требований к заполнению обязательных полей в Create new task

### ISSUE THREAD

**Issue by Shvidunov** [hexlet-codebattle/codebattle#1445]
### Summary

Проверка интерфейса создания новой задачи Create new task с пустыми полями 

### Reproduction steps

```bash
1. перейти на сайт и авторизоваться
2. перейти на страницу Create new task
3. нажать Save не заполняя форму
```

### Expected result

Появляется сообщение о необходимости заполнить обязательные поля. Поля подсвечиваются, выделяются размером шрифта или иным образом для быстрой идентификации

### Actual result

После попытки сохранения пустой формы сообщения о необходимости заполнения полей и их локализация практически нечитаемы, использован шрифт и цвет основной массы текста на странице. Быстрый поиск незаполненного поля затруднен.
**ФОРМА ДО СОХРАНЕНИЯ**

![Create new task до сохранения](https://user-images.githubusercontent.com/121935818/235752965-964c9d5c-7ff9-4a22-87e3-15fa957e313b.jpg)

**ФОРМА ПОСЛЕ СОХРАНЕНИЯ**

![Create new task после сохранения](https://user-images.githubusercontent.com/121935818/235752973-b57b6b0d-4809-4926-bd4a-673c781ab885.jpg)
 

### Browsers

Firefox, Chrome, Microsoft Edge

### OS

Windows

**Comment by GordienkoEvgeny** [comment]
Беру в работу
