### ISSUE TITLE
Bug: Элементы сайта не выровнены по высоте 

### ISSUE THREAD

**Issue by Steelrat3** [hexlet-codebattle/codebattle#1457]
### Summary

Проверка соответствия элементов сайта требованиям дизайна

### Reproduction steps

```bash
1. Выполнить авторизацию пользователя с тестовыми значениями
   Nickname = hodor1
   Email = hodor10@hodor.ru
2. Вставить в адресную строку браузера url https://codebattle.hexlet.io
3. Убедиться, что расположение элементов сайта соответствует требованиям дизайна
```

### Expected result

Элементы сайта соответствуют требованиям дизайна

### Actual result

Верхнее меню сайта и кнопка "Create a game" находятся в одном ряду, но не совпадают по высоте

![Размер поля тулбар и кнопки Начать игру отличаются](https://github.com/hexlet-codebattle/codebattle/assets/123881761/7c486fa7-f099-4346-91d0-79b0cd3d9e90)

### Browsers

Chrome

### OS

Windows

**Comment by katrytikova** [comment]
Воспроизводится. "Lobby" высота плашки 58px, "create a game" 60px

Google Chrome 113.0.5672.126 (Официальная сборка), (arm64)
macOS Ventura 13.1

<img width="1440" alt="Снимок экрана 2023-05-24 в 14 05 05" src="https://github.com/hexlet-codebattle/codebattle/assets/122362310/77a61758-2568-456f-a4bb-60b555f4a24e">
<img width="1440" alt="Снимок экрана 2023-05-24 в 14 04 41" src="https://github.com/hexlet-codebattle/codebattle/assets/122362310/9f0a5661-b9b7-4f53-8301-7420924a1a13">
