### ISSUE TITLE
Bug: Не валидируется почтовый адрес, состоящий из спецсимволов

### ISSUE THREAD

**Issue by Steelrat3** [hexlet-codebattle/codebattle#1459]
### Summary

Проверка валидации данных поля Email при указании корректного почтового домена

### Reproduction steps

```bash
1 Открыть форму регистрации пользователя
2 Ввести в поле "Email" значение: !_/@mail.ru
2 Заполнить оставшиеся поля: 
 Nickname = hodor12
 Password = 123456
3 Нажать "Submit"
```

### Expected result

Появляется уведомление о недопустимых символах в поле "Email", регистрация не происходит 

### Actual result

Регистрация проходит успешно
![Форма регистрации нового пользователя11 1](https://github.com/hexlet-codebattle/codebattle/assets/123881761/f98375d8-024b-477d-9bad-572d53307d2c)
![Форма регистрации нового пользователя11 2](https://github.com/hexlet-codebattle/codebattle/assets/123881761/afedbec1-e501-46da-a590-e2c23e12e046)

### Browsers

Chrome

### OS

Windows

**Comment by imr333** [comment]
Summary
Проверка валидации данных поля Email 

Reproduction steps
1 Открыть форму регистрации пользователя
2 Ввести в поле "Email" значение: __/@gmail.com
3 Заполнить поле "Nickname" = sansa13
4 Заполнить поле "Password" = qwertyq
5 Нажать кнопку "Submit"

Expected result
Появляется уведомление о недопустимых символах в поле "Email", регистрация не происходит

Actual result
Происходит регистрация пользователя

**Comment by Aallyycoop** [comment]
Взяла в работу
