### ISSUE TITLE
Bug: Не валидируется данные поля Nickname

### ISSUE THREAD

**Issue by Steelrat3** [hexlet-codebattle/codebattle#1460]
### Summary

Проверка валидации данных поля Nickname при регистрации нового пользователя

### Reproduction steps

```bash
1 Открыть форму регистрации пользователя
2 Ввести в поле "Nickname" значение = "-111"
3 Заполнить оставшиеся поля: 
 Email = "Bella@anna.ru"
 Password = "123456"
4 Нажать "Submit"
5 Выйти из учетной записи пользователя
6 Ввести в поле "Nickname" значение = "!_<>?"
7 Заполнить оставшиеся поля: 
 Email = "Anna@bella.ru"
 Password = "123456"
8 Нажать "Submit"
```

### Expected result

Появляется уведомление о недопустимых символах в поле "Nickname", регистрация не происходит.

### Actual result

Регистрация проходит успешно
![Форма регистрации нового пользователя12 1](https://github.com/hexlet-codebattle/codebattle/assets/123881761/e014205f-a580-432a-9e9c-8d45417bc1b7)
![Форма регистрации нового пользователя12 2](https://github.com/hexlet-codebattle/codebattle/assets/123881761/6bc73b7b-971f-4502-885c-482c49a1783b)
![Форма регистрации нового пользователя13 1](https://github.com/hexlet-codebattle/codebattle/assets/123881761/69bf3247-7e98-43c7-9e22-287b6dfcced3)
![Форма регистрации нового пользователя13 2](https://github.com/hexlet-codebattle/codebattle/assets/123881761/0fe6223b-a3df-499b-9e5e-741cbb938c2f)

### Browsers

Chrome

### OS

Windows

**Comment by imr333** [comment]
Summary
Проверка валидации данных поля Nickname при регистрации нового пользователя

Reproduction steps
1 Открыть форму регистрации пользователя
2 Ввести в поле "Nickname" значение = "1-2<>@$"
3 Заполнить поле "Email" = sansa/@gmail.com
4 Заполнить поле "Password" = "qwertyq"
5 Нажать кнопку "Submit"

Expected result
Появляется уведомление о недопустимых символах в поле "Nickname", регистрация не происходит.

Actual result
Регистрация происходит успешно

<img width="482" alt="Снимок экрана 2023-05-23 132116" src="https://github.com/hexlet-codebattle/codebattle/assets/118901326/39c5420b-8260-47ad-b854-63fde786e1c5">

<img width="198" alt="Снимок экрана 2023-05-23 132131" src="https://github.com/hexlet-codebattle/codebattle/assets/118901326/1ff9eb63-5189-4791-8df7-ca94b0c22a3b">

Browsers
Yandex

OS
Windows

**Comment by Aallyycoop** [comment]
Возьму в работу

**Comment by ReDBrother** [comment]
@solar05, @Aallyycoop  Можете посмотреть работает фича или нет на проде? Если да, то закроем тикет

**Comment by solar05** [comment]
Ага, на проде все работает 
<img width="466" alt="image" src="https://github.com/hexlet-codebattle/codebattle/assets/38437931/730ac90c-e459-43e8-8872-841e04624ed1">
