### ISSUE TITLE
Bug: Оформление кнопки "Sign in" содержит лишний элемент

### ISSUE THREAD

**Issue by Steelrat3** [hexlet-codebattle/codebattle#1461]
### Summary

Проверка соответствия элементов сайта требованиям дизайна

### Reproduction steps

```bash
1 Вставить в адресную строку браузера url = https://codebattle.hexlet.io/
2 Установить курсор мыши на кнопку "Sign in"
```

### Expected result

Элементы сайта соответствуют требованиям дизайна

### Actual result

Кнопка "Sign in" содержит лишний элемент
![Дизайн кнопки Sign in](https://github.com/hexlet-codebattle/codebattle/assets/123881761/4cc096d1-3caf-4a28-9b46-65e0a3cf8118)

### Browsers

Chrome

### OS

Windows

**Comment by nevograd1613** [comment]
Беру в работу

**Comment by Abikimoz** [comment]
уже не воспроизводится, необходимо закрыть

**Comment by ReDBrother** [comment]
fixed
