### ISSUE TITLE
Bug: Наслоение элементов страницы при уменьшении окна браузера

### ISSUE THREAD

**Issue by face2face321** [hexlet-codebattle/codebattle#1462]
### Summary

Проверка адаптации страницы под разное разрешение экрана 

### Reproduction steps

```bash
1. Перейти и авторизоваться на сайте 
2. Перейти в раздел "My Profile"
3. Открыть DevTools
4. Уменьшить окно браузера до 1199.20px x 728px
```

### Expected result

Все элементы видны, читаемы и корректно отображаются на странице.

### Actual result

При уменьшении разрешения экрана элементы страницы наслаиваются на текст "gaveUp" в пирамиде статистики.
![pixel](https://github.com/hexlet-codebattle/codebattle/assets/127731960/2797c2ac-2ac6-477c-a81f-7096ba55b275)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубликат от https://github.com/hexlet-codebattle/codebattle/issues/1488
