### ISSUE TITLE
Bug: Не скроллится страница с наведенным курсором на поле ввода  

### ISSUE THREAD

**Issue by Jumpykot** [hexlet-codebattle/codebattle#1468]
### Summary

Не скроллится страница игры, если курсор находится в поле ввода кода
![image](https://github.com/hexlet-codebattle/codebattle/assets/109305528/da102476-587b-4498-b9ff-876997f8b501)

### Reproduction steps

```bash
1) Зайти в лобби https://codebattle.hexlet.io/#lobby
2) Кликнуть на [Create a game]
3) Нажать [Create Battle]
4) Стянуть страницу браузера как на скрине
5) Поскроллить страницу на трекпаде или колесиком мыши, наведя курсор на поле для ввода кода
```

### Expected result

Страница скроллится при наведении курсора на любом месте

### Actual result

Страница не скроллится 

### Browsers

Chrome

### OS

Mac

**Comment by smokeinureyes** [comment]
Actual Result
Страница не скроллится при наведении курсора на поле ввода кода

Browser
Chrome

OS
Windows

**Comment by ReDBrother** [comment]
Это невозможно контролировать. Мы не можем знать что хочет пользователь, когда скролит с позиции редактора кода, когда и его контент может не вмещаться в его окне. Используемый в проекте Monaco editor не умеет учитывать это при скроле
