### ISSUE TITLE
Bug: Невозможно вызвать игрока или бота на баттл из чата

### ISSUE THREAD

**Issue by Timkalena** [hexlet-codebattle/codebattle#1469]
### Summary

При открытии чата игры невозможно вызвать написавшего в чат игрока или бота на баттл 
![image](https://github.com/hexlet-codebattle/codebattle/assets/127779508/0c941782-f965-4bd4-887d-53c7222ffa4b)
![image](https://github.com/hexlet-codebattle/codebattle/assets/127779508/55649ead-49af-4297-aaa7-f1051efbab8a)
![image](https://github.com/hexlet-codebattle/codebattle/assets/127779508/8fcf0706-43d2-42a2-9f55-0ff2f49b986d)

### Reproduction steps

```bash
1. Открываем вкладку COMPLETED GAMES https://codebattle.hexlet.io/#completedGames
2. Выбираем игру и открываем ее
3. В чате находим написавшего бота или игрока, справа от сообщения которого будет черным гореть символ со скрещенными мечами
4. Нажимаем на символ с мечами
5. Нажимаем на зеленую кнопку с галочкой
```

### Expected result

Открывается окно создания баттла

### Actual result

Происходит переход в лобби или при клике нет ничего

### Browsers

Chrome

### OS

Windows

**Comment by solar05** [comment]
Бота нельзя звать, это нормальное поведение (по хорошему нужно будет скрыть кнопку)

**Comment by ReDBrother** [comment]
Поступим иначе, мы создадим кнопку создать битву с ботом.

**Comment by ReDBrother** [comment]
Мы переехали на контексное меню (по клику левой или правой кнопки мыши по имени в чате). Пригласить можно только пользователя, которые доступен в чате и не участвует в других битвах.
