### ISSUE TITLE
Bug: Длинные юзернеймы ломают отображение рейтинговой таблицы

### ISSUE THREAD

**Issue by Daria-new** [hexlet-codebattle/codebattle#1474]
### Summary

Длинные юзернеймы  ломают отображение рейтинговой таблицы. Столбцы со статистикой не отображаются

### Reproduction steps

```bash
1. Перейти на https://codebattle.hexlet.io/users
2. Набрать в поиске по юзернейму "qwert"
```

### Expected result

Рейтинговая таблица отображается со всеми столбцами
![image](https://github.com/hexlet-codebattle/codebattle/assets/127126343/a4a5c98e-8d53-4221-a6ff-2fa32ea9c117)

### Actual result

Таблица отображается некорректно. Юзернейм выезжает за поле. Столбцы со статистикой пропали

![image](https://github.com/hexlet-codebattle/codebattle/assets/127126343/e81f105f-b5df-4fbd-a6a2-690cd680c88f)

### Browsers

Chrome

### OS

Windows

**Comment by Shalygin-Sergey** [comment]
взял в работу

**Comment by Carpetdude** [comment]
**Summary**
Длинный юзернейм ломает верстку таблицы
Версия: [d12525d](https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806)

**Reproduction steps**
1. Открыть страницу User Rating
2. Ввести в поиск "qwert"

**Expected result**
Рейтинговая таблица отображается со всеми столбцами

**Actual result** 
Длинный юзернейм сдвигает столбцы за пределы страницы
![image](https://github.com/hexlet-codebattle/codebattle/assets/134539146/3b414c78-83a7-4bf2-8887-1cb8b3fffc02)

**Browsers**
Opera

**OS**
Windows
