### ISSUE TITLE
Bug: Страница "Users Rating" не адаптивна для масштабируемости

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1484]
### Summary

При переходе на страницу общей статистики рейтинга пользователей "User Rating" значения выходят за форму

### Reproduction steps

```bash
1. Перейти на https://codebattle.hexlet.io/users
2. Уменьшить окно браузера
```

### Expected result

Страница сайта адаптируется под размер окна браузера

### Actual result

Страница сайта не адаптивна для масштабируемости
![Screenshot_2](https://github.com/hexlet-codebattle/codebattle/assets/134138572/864966e5-9845-4c8c-8408-1e5393c503cb)
![Screenshot_4](https://github.com/hexlet-codebattle/codebattle/assets/134138572/3136c0e4-d0ef-4620-adb0-e38f2077b07e)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубликат от https://github.com/hexlet-codebattle/codebattle/issues/1484

**Comment by FilimonPK** [comment]
[Масштабирование страницы - некорректное отображение  (десктопная версия сайта) #1517](https://github.com/hexlet-codebattle/codebattle/issues/1517)
