### ISSUE TITLE
Bug: Нет возможности отвязать учетку Discord и GitHub

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1485]
### Summary

При переходе в настройки профиля, имеется возможность привязать аккаунт Discord и GitHub, но нет возможности отвязать, кнопки не активны

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/settings
2. Нажать кнопку "Link" Discord / GitHub
3. Нажать кнопку "Unlink Discord" / "Unlink GitHub"
```

### Expected result

Аккаунт Discord / GitHub отвяжется

### Actual result

Нет возможности отвязать аккаунт, кнопки не активны
![Screenshot_5](https://github.com/hexlet-codebattle/codebattle/assets/134138572/1900ed2f-05e7-48fd-94b3-4dacf56fbe79)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Важная бага. Мы блокируем (disabled) отвязку соц сетей только в том случае, если пользователь не зарегистрировался по email и привязана только одна социальная сеть.

**Comment by Makarova94** [comment]
- summary: |
    Нет возможности отвязать аккаунт GitHub, кнопка не активна
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
    - Авторизоваться с помощью Github
    - Перейти в раздел Settings
    - Нажать кнопку Unlink Github

  expected-result: |
    Аккаунт Github отвязан, на странице пользователя перестает отображаться ссылка на него
  actual-result: |
   Нет возможности отвязать аккаунт

**Comment by ElenaSimanina** [comment]
- summary: |
     Неактивные кнопки отключения аккаунтов GitHub и Discord от профиля пользователя
  environment: |
     Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
     ОС Windows 10
  steps-to-reproduce: |
     1. Авторизоваться на сайте https://codebattle.hexlet.io/
     2. Нажать на кнопку "Настройки
     3. Нажать на кнопки "Отключить Github"/"Отключить Discord"
  expected-result: |
     Пользователь может отключить аккаунты GitHub и Discord от своего профиля
  actual-result: |
     Кнопки "Отключить Github"/"Отключить Discord" неактивные. 
![Скриншот Неактивные кнопки удаления ](https://github.com/hexlet-codebattle/codebattle/assets/135851722/15799416-14a8-48ca-992e-f7666afc466f)

**Comment by ElenaRedkina89** [comment]
summary: 
Нет возможности отвязать аккаунт GitHub, кнопка не активна

environment: 
Chrome 117.0.5938.134 (Официальная сборка), (64 бит)
Windows 10 Pro
Codebattle Current version: ef4c0b9

steps-to-reproduce: 

-Авторизоваться с помощью Github
-Перейти в раздел Settings
-Нажать кнопку Unlink Github

expected-result: 
Аккаунт Github отвязан, на странице пользователя перестает отображаться ссылка на него

actual-result: 
Нет возможности отвязать аккаунт Github
![Нет возможности отвязать учетку GitHub#1485](https://github.com/hexlet-codebattle/codebattle/assets/139364594/984c9a53-6815-4a91-96dd-740c5b793768)

**Comment by ReDBrother** [comment]
fixes

**Comment by vtm9** [comment]
Fixed in commit 8440b39d1: https://github.com/hexlet-codebattle/codebattle/commit/8440b39d1

What changed:
- kept social unlink blocked only when it would remove the user’s last available sign-in method
- added backend protection in `DELETE /auth/:provider` so the rule is enforced even on direct requests
- exposed the capability flag to the settings UI so the button state matches the real auth state
- added frontend and controller tests for both allowed and blocked unlink cases
