### ISSUE TITLE
Bug: Страничка информации выбранного турнира не адаптивна к масштабируемости

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1486]
### Summary

Переходя на страничку с информацией о выбранном турнире, изменив размер окна браузера, значения в поле "Total Players" выходят за форму

### Reproduction steps

```bash
1. Перейти на https://codebattle.hexlet.io/tournaments/739/
2. Уменьшить окно браузера
```

### Expected result

Страничка полностью адаптируется под размер окна браузера

### Actual result

Значения в поле "Total Players" выходят за форму
![Screenshot_7](https://github.com/hexlet-codebattle/codebattle/assets/134138572/0c94422e-616b-4a0a-a738-cedcec8a89ae)
![Screenshot_8](https://github.com/hexlet-codebattle/codebattle/assets/134138572/01d58c32-7dc6-4c7e-9def-6d1668958d84)

### Browsers

Chrome

### OS

Windows

**Comment by gagariq** [comment]
**Summary**
Описание поля для ввода сообщения не отображено полностью
**Steps:**
 Создать любой турнир
**Expected result**
В поле ввода сообщения есть надпись "Write your message"
**Actual result**
В поле ввода сообщения отображается надпись "Write your m"

**OS**
MacOS Ventura 13.4 
Display Retina 13,3-дюймовый (2560 × 1600)

**Browser**
Firefox 113.0.1 (64-разрядный)
<img width="1398" alt="message " src="https://github.com/hexlet-codebattle/codebattle/assets/130165746/4269f552-f2f7-4e57-96b6-d2f13ecb8f81">

**Comment by YukKaji** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/128067636/2ef2e78c-0cc5-4d79-aa24-6be7638248c7)
Внешний вид турнирной сетки на мобильной версии
Текущая версия: 764df7e

**Comment by fidilly** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/13aee394-9d19-46fe-80d1-e28caa5d1f00)

Browsers: Firefox
OS: Linux

**Comment by kairina2020** [comment]
Масштабируемость страницы некорректная. При увеличении масштаба на 150 и 200 % элементы начинают выходить за пределы или "заезжать" на другие элементы.
![масшт150](https://github.com/hexlet-codebattle/codebattle/assets/110185387/6759ae1a-56b8-4927-8ea8-3a3bce90bf6c)
![масштабирование](https://github.com/hexlet-codebattle/codebattle/assets/110185387/eddea2aa-4be0-4880-b085-0d15806e6f05)

**Comment by SabishiSenshi** [comment]
Summary
Переходя на страничку с информацией о выбранном турнире, ломается разметка страницы при просмотре с мобильных устройств

Reproduction steps
1. Перейти на https://codebattle.hexlet.io/tournaments/919/

Expected result
Страничка полностью адаптируется под размер экрана пользователя

Actual result
Элементы выходят за границы блоков

Browsers: Google Chrome 117.0.5938.60
OS: Android
[Текущая версия: [f1a3f08](https://github.com/hexlet-codebattle/codebattle/commit/f1a3f08bc38d51330daa21d6c5b5cb5e20c456c7)

![photo_2023-09-25_01-55-28](https://github.com/hexlet-codebattle/codebattle/assets/36118971/03a7f95c-9e09-4688-b3dd-17b13e56d178)
![photo_2023-09-25_01-55-29](https://github.com/hexlet-codebattle/codebattle/assets/36118971/91273554-5194-4e40-8154-dbc46c7aba10)

**Comment by ElenaRedkina89** [comment]
summary:
При уменьшении окна браузера параметры игроков "Total players" выходят за пределы блока и в поле ввода сообщения надпись "Write your message" отображается частично

environment:
Chrome 117.0.5938.134 (Официальная сборка), (64 бит)
Windows 10 Pro
Codebattle Current version: ef4c0b9

steps-to-reproduce:

-Авторизоваться
-Нажать на изображение учетной записи
-Перейти в раздел "Tournament"
-В таблице выбрать турнирную сетку
-Нажать на "Show"
-Уменьшить окно браузера

expected-result:
Параметры игроков "Total players" не выходят за пределы блока,  в поле ввода сообщения надпись "Write your message" отображается полностью

actual-result:
Параметры игроков "Total players" выходят за пределы блока, в поле ввода сообщения надпись "Write your message" отображается частично
![Страничка информации выбранного турнира не адаптивна к масштабируемости#1486](https://github.com/hexlet-codebattle/codebattle/assets/139364594/21173586-8623-45d1-b80b-1d94df9ddf20)

**Comment by alexidude** [comment]
**summary:**
Неадоптирована страница редактирования сайта в мобильной версии

**environment:**
Google Chrome 118.0.5993.89 (Официальная сборка) (64 бит)
ОС Windows 10 Enterprise
Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/8a2935d7b74ffeda3b53235a99020ea69f7ac8d7

**steps-to-reproduce:**
- Авторизвоваться на сайте
- Открыть DevTools
- Нажать на кнопку «Toggle device toolbar»
- Выбрать из списка мобильных устройств iPhone 12 pro
- Перейти в раздел "Tournament"
- Выбрать турнир из списка
- Нажать на кнопку "Show"

**expected-result:**
Элементы на странице адаптированы на мобильном устройстве

**actual-result:**
Элементы на странице выходят за границу экрана

**Comment by ReDBrother** [comment]
Переверстали все турниры. Проблема решена
