### ISSUE TITLE
Bug: Нет адаптации на мобильных устройствах на страничке "Users Rating"

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1487]
### Summary

При переходе на страничку с общей статистикой рейтинга пользователей, сайт не адаптируется под мобильное устройство

### Reproduction steps

```bash
1. Открыть браузер на мобильном устройстве
2. Перейти на https://codebattle.hexlet.io/users
```

### Expected result

Страничка сайта адаптируется под мобильное устройство

### Actual result

Страничка сайта с общей статистикой рейтинга пользователей не адаптивна для мобильных устройств
![photo_5210857188153740072_y](https://github.com/hexlet-codebattle/codebattle/assets/134138572/360487ed-36cb-4a88-965e-3188a150db32)

### Browsers

Chrome

### OS

Android

**Comment by smokeinureyes** [comment]
#1484

**Comment by Witchbanee** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/55561686/16219d4d-76b4-4f37-9fd7-8f101ad9423f)

**summary:** 
    Нет адаптации на мобильных устройствах на страничке рейтинга пользователей
  **environment:**
    Google Chrome
    Android
    Версия сайта - d12525d
  **steps-to-reproduce:** 
    1. Открыть сайт на мобильном устройстве
    2. Перейти на страницу рейтинга пользователей
  **expected-result:** 
    Страница  адаптирована под мобильные устройства
  **actual-result:** 
   Страница не  адаптирована под мобильные устройства

**Comment by Carpetdude** [comment]
Summary:
При отображении с мобильных устройств таблица на странице [Users Rating](https://codebattle.hexlet.io/users) ломает верстку

Reproduction steps
'''

Перейти на страницу Users Rating
В девтулз выбрать отображение с мобильного устройства
Потянуть таблицу вправо
'''
Expected result
Скроллу подвержена только сама таблица
Actual result
Вся страница начинает скроллиться
![image](https://github.com/hexlet-codebattle/codebattle/assets/134539146/ba8829ae-6e5f-42cd-b0bf-296ea5e88164)
Current version: [45e13e3](https://github.com/hexlet-codebattle/codebattle/commit/45e13e3a4b71833b89428ebde1980399bedcc874)

Browsers
Не имеет значения

OS
Не имеет значения

**Comment by AntonKondrat7** [comment]
Тот же баг IPhone 12 Pro

Google Chrome Версия 114.0.5735.199 (Официальная сборка), (64 бит)
Windows 10 Домашняя
Версия 22H2 Сборка 19045.3086
Current version: 764df7e

**Comment by anastasiya-breusova** [comment]
**summary:**
На странице "Users rating" страница не адаптирована на мобильные устройства

**environment:**
Google Chrome
iOS
Версия сайта - 764df7e

**steps-to-reproduce:**
1. Авторизоваться
2. Нажать на изображение учетной записи
3. Перейти в раздел "Users rating"

**expected-result:**
Страница сайта адаптирована под мобильные устройства

**actual-result:**
Адаптация сайта под мобильные устройства отсутствует
<img width="293" alt="Снимок экрана 2023-07-11 в 18 52 44" src="https://github.com/hexlet-codebattle/codebattle/assets/129413395/7775cf80-e048-47e3-b5d5-3a17e397a69f">

**Comment by anastasiya-breusova** [comment]
**summary:**
На странице "Users rating" между параметрами настройки таблицы отсутствуют отступы

**environment:**
Google Chrome
iOS
Версия сайта - 764df7e

**steps-to-reproduce:**
1. Авторизоваться
2. Нажать на изображение учетной записи
3. Перейти в раздел "Users rating"

**expected-result:**
Между параметрами настройки таблицы присутствуют отступы

**actual-result:**
Отсутствуют отступы между параметрами настройки таблицы 
<img width="278" alt="Снимок экрана 2023-07-11 в 19 15 29" src="https://github.com/hexlet-codebattle/codebattle/assets/129413395/bb0ab029-6dc2-45e5-a9d3-477d86eb4c37">

**Comment by etibarovna** [comment]
summary:
Некорректная адаптация на мобильных устройствах раздела Users rating 
environment:
Google Chrome
Android
Версия сайта – [764df7e](https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806)
steps-to-reproduce:
1. Авторизоваться на странице https://codebattle.hexlet.io/
2. Перейти в раздел Users rating
3. Открыть DevTools
expected-result:
Все изображения, текст и таблицы раздела Users rating корректно адаптированы под мобильные устройства
actual-result:
Данные профиля в разделе Users rating не имеют адаптации на мобильные устройства

![image](https://github.com/hexlet-codebattle/codebattle/assets/129650700/c923a522-bc3b-49b1-8dca-17e6df572584)

**Comment by Makarova94** [comment]
- summary: |
    При переходи на мобильную версию, раздел Users rating перестает корректно отображать верстку 
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
   - Открыть главную страницу сайта 
   - Зайти в DevTools
   - Переключиться на мобильную версию 
   - Выбрать из списка Iphone 12 PRO
   - Нажать на изображение учетной записи
   - Выбрать раздел "Users rating" в выпадающем списке
  
  expected-result: |
    На мобильных устройствах раздел Users rating сохраняет функционал и верстку 
  actual-result: |
    При переходи на мобильную версию раздел Users перестает корректно отображать верстку.Текст выходит за края блоков


![баг рейтинг](https://github.com/hexlet-codebattle/codebattle/assets/129146395/f6051efe-ca56-4a49-8dd6-db821fb6685a)

**Comment by ReDBrother** [comment]
Теперь есть)
