### ISSUE TITLE
Bug: Нет адаптации на мобильных устройствах на страничке профиля пользователя

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1488]
### Summary

При переходе на страничку профиля пользователя с мобильного устройства, аватар сужается и одновременно растягивается

### Reproduction steps

```bash
1. Открыть браузер на мобильном устройстве
2. Перейти по ссылке https://codebattle.hexlet.io/users/10786
```

### Expected result

Страничка адаптируется под мобильное устройство

### Actual result

Страничка частично адаптируется, но аватарка пользователя сужается и одновременно растягивается
![photo_5210944706702330668_y](https://github.com/hexlet-codebattle/codebattle/assets/134138572/ec059d74-8a04-4fc7-af24-e17ccaac7923)

### Browsers

Chrome

### OS

Android

### UDP:
В этом тикете будут все недоработке по адаптивности страницы

- [x] Описание пользователя #1432
- [ ] Статистика пользователя  #1427 #1462

**Comment by rizhik356** [comment]
беру

**Comment by ReDBrother** [comment]
Все в одну копилку с https://github.com/hexlet-codebattle/codebattle/issues/1495

**Comment by Carpetdude** [comment]
**Summary**
При просмотре с мобильного устройства на странице профиля растягивается аватарка пользователя

**Reproduction steps**
1. Открыть страницу профиля любого пользователя
2. В девтулз выбрать отображение с мобильного устройства

**Expected result** 
Аватарка пользователя уменьшается с сохранением пропорций

**Actual result**
Аватарка пытается изменить размер без учета пропорций изображения
![image](https://github.com/hexlet-codebattle/codebattle/assets/134539146/0d4856a7-e060-4f9c-9c5b-8a5e1cd6e837)

**Comment by Witchbanee** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/55561686/92ae4655-8479-431d-b3bb-34e3d94a2e40)
**summary:** 
    При просмотре с мобильного устройства на странице профиля растягивается аватарка пользователя
  **environment:**
    Google Chrome
    Android
  **steps-to-reproduce:** 
    1. Авторизоваться 
    2. Перейти в профиль
  **expected-result:** 
   Аватарка адаптирована под мобильные устройства
  **actual-result:** 
   Аватарка не адаптирована под мобильные устройства

**Comment by gagariq** [comment]
**summary:**
Аватар пользователя не адаптирован по размеру в мобильной версии 
**environment:**
Google Chrome 114.0.5735.124
Apple IPhone 11  iOS 16.1.1
Версия сайта - d12525d
**steps:**
- Авторизоваться на сайте
- Нажать "My profile"
**expected-result:**
Аватар пользователя адаптирован по размеру
**actual-result:**
Аватар пользователя не адаптирован по размеру

**Comment by Xtoseone** [comment]
the identity is too big, also the graphics are skewed and not adapted
galaxy S10 360*760px

https://github.com/hexlet-codebattle/codebattle/assets/114728833/895f69b0-05ab-443a-be33-a7b66709c771

**Comment by ReDBrother** [comment]
В этот тикет будет сбрасываться все недоработки по адаптивности всего содержимого страницы профиля

**Comment by ReDBrother** [comment]
Решили вопрос, дальше уже может по отдельных случая разъехаться.
