### ISSUE TITLE
Bug: Отличие шрифтов в настройке профиля, поля находятся на разных уровнях по высоте

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1491]
### Summary

В настройках профиля название поля "Your weapon" имеет другой шрифт в отличии от названия поля "Your name" и поля находятся на разных уровнях по высоте

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на свой никнейм
3. Нажать на "Settings"
```

### Expected result

Все названия полей будут иметь одинаковый шрифт и находится на одном уровне по высоте

### Actual result

Название поля "Your weapon" имеет другой шрифт в отличии от названия поля "Your name" и поля находятся на разных уровнях по высоте
![Screenshot_5](https://github.com/hexlet-codebattle/codebattle/assets/134138572/0ed1a190-389d-498e-a4a2-09b64660bad9)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нужно убрать из селектора его собственные кастомные стили, чтобы они не перекрывали системные. И подогнать все размеры/отступы

**Comment by Abikimoz** [comment]
Я возьмусь за эту задачу

**Comment by ReDBrother** [comment]
Пофикшены отступы

**Comment by ReDBrother** [comment]
fixed
