### ISSUE TITLE
Bug: Форма с окном чата и форма со списком игроков онлайн находятся не на одном уровне

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1492]
### Summary

Форма с окном чата и форма со списком игроков онлайн находятся не на одном уровне по высоте

### Reproduction steps

```bash
1. Авторизоваться
2. Перейти к форме с окном чата
```

### Expected result

Форма с окном чата и форма со списком игроков онлайн находятся на одном уровне по высоте

### Actual result

Форма со списком игроков онлайн находится ниже по высоте, чем форма с окном чата
![Screenshot_7](https://github.com/hexlet-codebattle/codebattle/assets/134138572/51803810-db80-459b-aebd-3e8cee9405a0)

### Browsers

Chrome

### OS

Windows

**Comment by Abikimoz** [comment]
@smokeinureyes Я займусь данной проблемой

**Comment by ReDBrother** [comment]
Уже поправили в мастере) Скоро зарелизим)
