### ISSUE TITLE
Bug: После просмотра завершенной игровой сессии (Completed Games) в профиле нет возможности вернуться к списку Completed Games

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1493]
### Summary

После просмотра завершенной игровой сессии (Completed Games) в профиле нет возможности вернуться к списку Completed Games, можно только вернуться на главную https://codebattle.hexlet.io/, нажав кнопку Back to Home

### Reproduction steps

```bash
1. Авторизоваться
2. Зайти в свой профиль
3. Перейти к списку Completed Games
4. Нажать Show у рандомной сессии
5. Нажать Back to Home
```

### Expected result

Вернет к списку Completed Games в профиле

### Actual result

Перекидывает на главную страницу https://codebattle.hexlet.io/ , от чего приходится снова проделывать шаги для попадания на страничку профиля
![Screenshot_8](https://github.com/hexlet-codebattle/codebattle/assets/134138572/2c7541d8-2f75-4262-8cc9-a4cbc96207fd)
![Screenshot_9](https://github.com/hexlet-codebattle/codebattle/assets/134138572/324adcd2-9c89-4c33-8657-8037fe22b1b4)
![Screenshot_10](https://github.com/hexlet-codebattle/codebattle/assets/134138572/db91af67-7fcd-45f8-ad64-9230c7de9379)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это невозможно. Мы не планируем делать из приложения single page aplication.
Для подобных целей у нас есть браузерное расширение, которое постоянно держит список игр.
