### ISSUE TITLE
Bug: Нет адаптации кнопки, вызывающей данные о профиле в мобильной версии сайта

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1494]
### Summary

Рамка кнопки, вызывающая данные профиля выходит за границы экрана на мобильной версии сайта

### Reproduction steps

```bash
1. Авторизоваться
2. Зайти на главную https://codebattle.hexlet.io/
```

### Expected result

Рамка кнопки вызывающая данные профиля не выходит за границы экрана и адаптирована к мобильным устройствам

### Actual result

Рамка кнопки выходит за границы экрана

### Browsers

Chrome

### OS

Android

**Comment by ReDBrother** [comment]
Нужно усовершенствовать поповер (на картинке), которые открывается по этому действию.

<img width="226" alt="Screenshot 2023-06-17 at 15 44 23" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/2a4efe7e-b096-469f-827f-7d9cd953d293">


Если он заходит за вьюпорт, то нам нужно его позицию скорректировать. В случае, если это невозможно из-за разных ограничений (например, сторонняя либа), то убрать этот функционал и заменить на контекстное меню (useContextMenu), как сделано с чатом.

**Comment by ushachev** [comment]
Взял в работу
