### ISSUE TITLE
Bug: Нет адаптации на мобильных устройствах на страничке профиля, в разделе статистики

### ISSUE THREAD

**Issue by smokeinureyes** [hexlet-codebattle/codebattle#1495]
![125ff12d-cabb-4e89-bb2b-f1833790734f](https://github.com/hexlet-codebattle/codebattle/assets/134138572/af34ce53-122d-45dc-95da-f2b72c6687fd)
![Screenshot_1](https://github.com/hexlet-codebattle/codebattle/assets/134138572/78d218ce-d552-471b-b884-58539e459995)
### Summary

На страничке профиле, в разделе статистики нет адаптации диаграмм под мобильные устройства, не видны названия показателей и некоторые значения

### Reproduction steps

```bash
1. Авторизоваться
2. Перейти в профиль
3. Перейти в раздел Statistics
```

### Expected result

Страничка профиля будет адаптирована под мобильные устройства

### Actual result

Данные профиля в разделе статистики не имею адаптации на мобильные устройства

### Browsers

Chrome

### OS

Android

**Comment by ReDBrother** [comment]
Сейчас адаптировано лишь под большие экраны (отчасти).
У bootstrap есть все необходимые стили (Grid System) и ими нужно для остальных размеров подогнать

**Comment by Witchbanee** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/55561686/ac974992-6bb7-42ea-8d2d-74d2b2d45235)
- summary: |
    Нет адаптации на мобильных устройствах на страничке профиля, в разделе статистики
  environment: |
    Google Chrome
    Android
  steps-to-reproduce: |
    1. Авторизоваться 
    2. Перейти в профиль
    3. Перейти в раздел Statistics
  expected-result: |
    Страничка профиля будет адаптирована под мобильные устройства
  actual-result: |
   Данные профиля в разделе статистики не имеют адаптации на мобильные устройства

**Comment by YukKaji** [comment]
![mob_profile_diag](https://github.com/hexlet-codebattle/codebattle/assets/128067636/ae7c5982-70ae-40da-a31f-9734d6f1d4dc)
Внешний вид статистики в мобильной версии
Текущая версия: 764df7e

**Comment by etibarovna** [comment]
summary:
Некорректная адаптация на мобильных устройствах раздела Statistics на странице профиля environment:
Google Chrome
Android
Версия сайта – https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806
steps-to-reproduce:
1. Авторизоваться на странице https://codebattle.hexlet.io/
2. Перейти в профиль иконка в правом верхнем углу экрана
3. Перейти в раздел Statistics
expected-result:
Все изображения и текст раздела Statistics в профиле корректно адаптированы под мобильные устройства
actual-result:
Данные профиля в разделе статистики не имеют адаптации на мобильные устройства

![image](https://github.com/hexlet-codebattle/codebattle/assets/129650700/06ec14ec-a064-431f-8fd4-6e2d88030104)

**Comment by fidilly** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/922842cb-7c07-4d6a-b8a0-e2c805860f68)

Browser: Firefox
OS: Linux

[Текущая версия: fd71526](https://github.com/hexlet-codebattle/codebattle/commit/fd71526086b97b7a700fb8ae09eab33f7a521dae)

**Comment by AnnaGurina** [comment]
- summary: |
    Диаграмма в разделе статистика профиля не адаптирована в мобильной версии
  environment: |
    Google Chrome   Версия 115.0.5735.124 (Официальная сборка), (64 бит)
    iPhone 14
Cb version: bde7cb
  steps-to-reproduce: |
    1. Зайти на страницу https://codebattle.hexlet.io/
    2. Авторизоваться
    3. Нажать на кнопку профиля и выбрать 'My profile'
    4. Открыть раздел 'Statistics' 
  expected-result: |
    Диаграмма в разделе статистика профиля адаптирована в мобильной версии 
  actual-result: |
    Диаграмма в разделе статистика профиля не адаптирована в мобильной версии: текст и значения искажены или отображены не полностью
![Фото 12 08 2023, 11 15 13](https://github.com/hexlet-codebattle/codebattle/assets/62752547/0991e73b-a9d0-438f-99df-82d249c31513)

**Comment by kairina2020** [comment]
summary: |
Описание используемых языков для решения задач не адаптирована в мобильной версии
environment: |
Яндекс Версия 23.1.2.931 corp (64-bit)
Десктоп
version ОС:  Windows 10 Pro
steps-to-reproduce: |
Зайти на страницу https://codebattle.hexlet.io/
Открыть DivTools, вкладка Элементы
Выбрать Galaxy Fold
Проскролить страницу

expected-result: |
Все элементы/логотипы входят на ширину экрана
actual-result: |
Элементы выходят за границы выделенной области 

![image](https://github.com/hexlet-codebattle/codebattle/assets/110185387/3d761bee-aaf4-4ece-89f6-270b9dc36c9f)
![image](https://github.com/hexlet-codebattle/codebattle/assets/110185387/3abdd7ba-bdac-44b6-9724-3555c0036aa2)

**Comment by ushachev** [comment]
взял в работу
