### ISSUE TITLE
Bug: Не загружаются аватарки игроков при начале просмотра игры

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#1497]
### Summary

![image](https://github.com/hexlet-codebattle/codebattle/assets/697178/993aeb26-4c77-4ea6-a019-5fd6c44f25e3)

В девтулс ошибок загрузки не увидел.

### Reproduction steps

```bash
1. Открываем игру, например https://codebattle.hexlet.io/games/139616/
2. Видим инфу о двух игроках, аватарок нет
```

### Expected result

Показываются аватрки юзеров или плейсхолдеры

### Actual result

Появляется блок, на котором возможно неверная ссылка или что-то еще.

### Browsers

Chrome

### OS

Linux

**Comment by ReDBrother** [comment]
В целом такая проблема возникает всегда, когда загружаем статику в приложение, и невозможно решить.
На кейс когда информация по avatar_url отсутствует, мы завели заглушку.
