### ISSUE TITLE
Bug: Таблица с рейтингом игроков выходит за границы экрана при отображении с мобильного

### ISSUE THREAD

**Issue by Carpetdude** [hexlet-codebattle/codebattle#1506]
**Summary:** 
При отображении с мобильных устройств таблица на странице [Users Rating](https://codebattle.hexlet.io/users) ломает верстку

**Reproduction steps** 
'''
1.  Перейти на страницу Users Rating 
2. В девтулз выбрать отображение с мобильного устройства
3. Потянуть таблицу вправо 
'''
**Expected result**
Скроллу подвержена только сама таблица

**Actual result**
Вся страница начинает скроллиться 
![image](https://github.com/hexlet-codebattle/codebattle/assets/134539146/d0f31bb2-d9c6-4379-89ae-96fc18b49bf8)

Current version: [f30dbf4](https://github.com/hexlet-codebattle/codebattle/commit/f30dbf480db7b93d0e083d9c46a37d70d150bfd8)

**Browsers**
Не имеет значения

**OS**
Не имеет значения

**Comment by ReDBrother** [comment]
Дубль от https://github.com/hexlet-codebattle/codebattle/issues/1487
