### ISSUE TITLE
Bug: После поражения в баттле, картинка в модальном окне смещена вправо на мобильных устройствах

### ISSUE THREAD

**Issue by Witchbanee** [hexlet-codebattle/codebattle#1507]
### Summary

![image](https://github.com/hexlet-codebattle/codebattle/assets/55561686/4a72d27d-6811-4be6-ac99-4d4247ba350d)

После поражения в баттле, картинка в модальном окне смещена вправо на мобильных устройствах

### Reproduction steps

```bash
1. Заходим на сайт с мобильного устройства
2. Принимае участие в баттле
3. Проигрываем
```

### Expected result

Картинка корректно отображается посередине

### Actual result

Картинка смещена вправо

### Browsers

Chrome

### OS

Windows

Версия сайта - https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806

**Comment by gagariq** [comment]
**Environment** 
Google Chrome 114.0.5735.124
Apple IPhone 11 iOS 16.1.1
Версия сайта - https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806

**Comment by Xtoseone** [comment]
Galaxy S10 Android 11
![Скриншот 22-06-2023 012001](https://github.com/hexlet-codebattle/codebattle/assets/114728833/cb160a7c-cfd4-43c3-8864-c986472a53d7)

**Comment by Makarova94** [comment]
- summary: |
    При переходи на мобильную версию, веб-сайт перестает корректно прогружать изображения
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. [Current version: 764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
  steps-to-reproduce: |
   - Открыть главную страницу сайта 
   - Зайти в DevTools
   - Переключиться на мобильную версию 
   - Выбрать из списка Iphone 12 PRO
   -  Нажать на кнопку "Create a game"
    - Выбрать первый уровень сложности
    - Выбрать игра с ботом 
    - Выбрать время 8 минут
    - Выбрать задачу по поиску площади прямоугольника
    - Нажать кнопку "Create battle"
    - Нажать на иконку с флажком "Give up"
    - В сплывающем окне нажать на кнопку "Give up" 
 expected-result: |
    На мобильных устройствах изображенние о проигрыше корректно отображается посередине
 actual-result: |
    При переходи на мобильную версию изображение всплывающее после проигрыша смещается вправо

![обрезан картинка](https://github.com/hexlet-codebattle/codebattle/assets/129146395/f75c039b-2ab9-4fdc-b05e-b230f7a69a4e)

**Comment by ReDBrother** [comment]
Пофиксили)
