### ISSUE TITLE
Bug: Описание поля для ввода сообщения не отображено полностью

### ISSUE THREAD

**Issue by gagariq** [hexlet-codebattle/codebattle#1508]
<img width="1398" alt="Code1" src="https://github.com/hexlet-codebattle/codebattle/assets/130165746/3785c55d-4b1b-4982-8cc3-686dc583f783">
### Summary

В ТУРНИРЕ поле ввода сообщения в чате не польностью отображает надпись 

### Reproduction steps

```bash
1. Создать любой турнир
```

### Expected result

В поле ввода сообщения есть надпись "Write your message"

### Actual result

В поле ввода сообщения отображается надпись "Write your m"

### Browsers

Firefox

### OS

Mac

**Comment by ReDBrother** [comment]
Дубль от https://github.com/hexlet-codebattle/codebattle/issues/1486

**Comment by Tatyana8TA** [comment]
Окошко не свернуто. Кнопку почти не видно.   environment: Google Chrome   v1  120.2212.4190.0   64-разрядная операционная система, процессор x64  ОС Windows 10 Pro 12.2020
![image](https://github.com/hexlet-codebattle/codebattle/assets/123509744/01144ca8-5b0f-45a8-b593-85f11500d33c)
