### ISSUE TITLE
Bug: страница турнира не адаптирована под мобильное устройство

### ISSUE THREAD

**Issue by gagariq** [hexlet-codebattle/codebattle#1510]
### Summary

При создании нового турнира, элементы страницы расположены некорректно
![createtour1](https://github.com/hexlet-codebattle/codebattle/assets/130165746/371c6499-acd3-4e1f-bea6-a5b00867081d)
![createtour2](https://github.com/hexlet-codebattle/codebattle/assets/130165746/e85e43f1-dcbe-4a5c-a1b8-3cd25e343470)

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать "Тournaments"
3. Изменить дату на 20.06.2024
4. Нажать "Create"
```

### Expected result

Страница нового турнира адаптирована для мобильного устройства

### Actual result

Страница созданного турнира не адаптирована для мобильного устройства

**ENVIRONMENT! 
GOOGLE CHROME 
APPLE IPHONE 11 iOS 16.1.1**

### Browsers

Chrome

**Comment by Xtoseone** [comment]
![Скриншот 22-06-2023 011811](https://github.com/hexlet-codebattle/codebattle/assets/114728833/9507dd2e-c10b-42fb-93d9-a15c55166f4d)

**Comment by ReDBrother** [comment]
Дубль от https://github.com/hexlet-codebattle/codebattle/issues/1486
Все будет только после переписывания турниров на реакт

**Comment by MziyaUsubova** [comment]
В мобильной версии поле Round config type не выровнено

1. Авторизоваться на сайте
2. Нажать "Тournaments"
3. Открыть Devtools 
4. Мобильная версия
5. Type - установить swiss
6. Скрол вниз , появилось поле  Round config type 


[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by MziyaUsubova** [comment]
<img width="746" alt="Screenshot 2024-03-13 at 23 20 47" src="https://github.com/hexlet-codebattle/codebattle/assets/152481283/2ae12368-25a8-472e-b585-f2d63035610f">
