### ISSUE TITLE
Bug: Текст не помещается в полях формы в Settings

### ISSUE THREAD

**Issue by gagariq** [hexlet-codebattle/codebattle#1511]
### Summary

Текст не полностью выводится в полях форм в Настройках профиля

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать "Settings"
```

### Expected result

Текст полностью выводится в поле 

### Actual result

Текст не выводится полностью в форме
![Settings](https://github.com/hexlet-codebattle/codebattle/assets/130165746/dbe25dc9-5796-4edd-8d44-c183c2cb6061)

**Environment**
Google Chrome 114.0.5735.124
Apple IPhone 11 iOS 16.1.1
Версия сайта - https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806

### Browsers

Chrome

**Comment by cmeshnoy** [comment]
Google Pixel 5А тоже самое
![photo_2023-07-05_20-57-48](https://github.com/hexlet-codebattle/codebattle/assets/114485692/0c33d31d-0b2a-41a0-9d63-40a92ad31b79)

**Comment by YukKaji** [comment]
![mob_settings_fields](https://github.com/hexlet-codebattle/codebattle/assets/128067636/38747646-c188-49cd-9ea9-523491e38004)
Внешний вид полей в настройках в мобильной версии

**Comment by AnnaGurina** [comment]
- summary: |
    Текст в разделе Settings не адаптирован в мобильной версии
  environment: |
    Google Chrome   Версия 115.0.5735.124 (Официальная сборка), (64 бит)
    iPhone 14
Cb version: bde75b
  steps-to-reproduce: |
    1. Зайти на страницу https://codebattle.hexlet.io/
    2. Авторизоваться
    3. Нажать на кнопку профиля и выбрать 'Settings'
  expected-result: |
    Текст в разделе Settings адаптирован в мобильной версии
  actual-result: |
    Текст в разделе Settings не адаптирован в мобильной версии: не помещается в поля полностью.
![Фото 12 08 2023, 13 29 44](https://github.com/hexlet-codebattle/codebattle/assets/62752547/bc355902-65e1-4f5f-aaa8-8bf6875aa37d)

**Comment by Va-khar** [comment]
**Summary**
Текст в разделе Settings на мобильной версии не адаптирован 

**steps**
    - Авторизоваться на сайте
    - Нажать на Settings
    - Запускаем DevTools 
    - Входим в мобильную версию 
   
**Expected result**
Текст в полях "Your name" и "Your weapon" полностью выводится 

**Actual result**
Текст не выводится полностью в данных полях 

![iphone SE](https://github.com/hexlet-codebattle/codebattle/assets/81294023/fcd293ef-67a5-403b-bfac-4f4fe0e7fbf5)
![iphone XR](https://github.com/hexlet-codebattle/codebattle/assets/81294023/a51e35c7-7f70-48c7-afdc-d111dae3b638)
![iphone 12 Pro](https://github.com/hexlet-codebattle/codebattle/assets/81294023/5ad17c38-9d1d-4a60-ae9f-c7e0feddffb6)
![Pixel 5](https://github.com/hexlet-codebattle/codebattle/assets/81294023/f672d448-5542-4c40-91e1-0990f6309ffc)
![Samsung Galaxy S8+](https://github.com/hexlet-codebattle/codebattle/assets/81294023/5c6eef4f-3b4e-455d-bb7d-670a508624b2)
![Samsung Galaxy S20 Ultra](https://github.com/hexlet-codebattle/codebattle/assets/81294023/75680884-3e2c-4707-a04e-e6d9ec3922b3)

**Enviroment**
Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
ОС Windows 10
Current version: 11610be
iphone SE
iphone XR
iphone 12 Pro
Pixel 5
Samsung Galaxy S8+
Samsung Galaxy S20 Ultra

**Comment by marinalinnik** [comment]
**Summary**
Текст в разделе "Settings" не адаптирован в мобильной версии 

**Steps**
- Авторизоваться на сайте
- Нажать на профильSettings
- Запустить DevTools
- Выбрать мобильную версию "iPhone 12 Pro"

**Expected result**
Текст в полях "Your name" и "Your weapon" помещается полностью в поля

**Actual result**
Текст не выводится полностью в полях "Your name" и "Your weapon"

**Environment:**
Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)
iPhone 12 Pro
ОС Windows 10
Current version: 11610be


![br pr 2 Settings](https://github.com/hexlet-codebattle/codebattle/assets/132447284/a7e3c7ab-c164-4ceb-96f5-3d2ebbaf8587)
