### ISSUE TITLE
Bug: Значения выходят за поля формы 

### ISSUE THREAD

**Issue by gagariq** [hexlet-codebattle/codebattle#1512]
### Summary

При создании турнира поле не отображается корректно

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать на изображение учетной записи
3. Нажать "Tournaments"
```

### Expected result

Значение поля " Starts at" не выходит за рамки поля

### Actual result

Значение поля " Starts at" выходит за рамки поля
![createtour3](https://github.com/hexlet-codebattle/codebattle/assets/130165746/e9a2b954-16f2-43a1-89c2-1614aaf14282)

** ENVIRONMENT!**
Google Chrome 114.0.5735.124
Apple IPhone 11 iOS 16.1.1
Версия сайта - https://github.com/hexlet-codebattle/codebattle/commit/d12525de3014512f061600948b62973506f69806 

### Browsers

Chrome

**Comment by AnnaGurina** [comment]
- summary: |
    Значения в разделе Create a new tournament выходят за рамки полей в мобильной версии
  environment: |
    Google Chrome   Версия 115.0.5735.124 (Официальная сборка), (64 бит)
    iPhone 14
Cb version: 6de75b
  steps-to-reproduce: |
    1. Зайти на страницу https://codebattle.hexlet.io/
    2. Авторизоваться
    3. Нажать на кнопку профиля и выбрать 'Tournaments'
  expected-result: |
    Поля в разделе Create a new tournament адаптированы в мобильной версии
  actual-result: |
    Поля в разделе Create a new tournament не адаптированы в мобильной версии: значения в 'Starts at' выходят за рамки полей.
![Фото 12 08 2023, 13 29 27](https://github.com/hexlet-codebattle/codebattle/assets/62752547/05b7d1d6-1f65-4622-b68c-b1a4c49fcdca)

**Comment by ReDBrother** [comment]
Fixed
