### ISSUE TITLE
Bug:  Необходимо заменить обратную связь на странице матча Slack на актуальную  (Поменять иконку)

### ISSUE THREAD

**Issue by Xtoseone** [hexlet-codebattle/codebattle#1513]
### Summary

так как Slack не поддерживается в РФ необходимо изменить виджет обратной связи на актуальный EX: telegram/email

### Reproduction steps

```bash
1. open https://codebattle.hexlet.io/
2. login
3. start any battle
4. use the feedback btn at the bottom right
```

### Expected result

ожидается что обратная связь будет актуальной, например через телеграм или email

### Actual result

сейчас используется slack, который не поддерживается в РФ, пользователь не может быть уверен, что его feedback дойдет до разработчика

### Browsers

Firefox, Chrome

### OS

Windows

Current version: 45e13e3

**Comment by ReDBrother** [comment]
Там нужно иконку поменять.

**Comment by 21aLeX** [comment]
беру!

**Comment by 21aLeX** [comment]
Теперь очень важный вопрос, на что поменять иконку?

**Comment by ReDBrother** [comment]
> Теперь очень важный вопрос, на что поменять иконку?

 Погугли RSS, не уверен что он есть в fontawesome, поэтому придется взять из интернета и добавить в assets/static

**Comment by 21aLeX** [comment]
> Погугли RSS, не уверен что он есть в fontawesome, поэтому придется взять из интернета и добавить в assets/static

Что то вроде этого? https://fontawesome.com/icons/square-rss?f=sharp&s=solid&pc=%23fb8423

**Comment by 21aLeX** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/26786537/e8b586db-2970-457d-8032-214394a7296a)
как то так 💁‍♀️

**Comment by ReDBrother** [comment]
Closed by #1530
