### ISSUE TITLE
Масштабирование страницы - некорректное отображение  (десктопная версия сайта)

### ISSUE THREAD

**Issue by FilimonPK** [hexlet-codebattle/codebattle#1517]
### Summary

Масштабирование страницы - некорректное отображение  (десктопная версия сайта)
Current version: 45e13e3

1. Страница /My profile - график прогресса масштабируется некорректно, обрезаются края (>110%)
2. Главная страница /Completed games - пропала колонка actions (=130%)
3. Страница /users (User ratings) - не полностью масштабируется белая подложка (>140%)
 
4. Страница /tournaments/...Выбрать текущий турнир: 
4.1 chat-ввод сообщения - не умещается подсказка поля “Write your message”;
4.2 поле “Total players” - выход за рамки имени пользователя (>110%);

<img width="1438" alt="Screenshot 2023-06-22 at 12 51 58 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/2dae5989-4445-4e5c-b181-5e8fc44a817c">
<img width="1508" alt="Screenshot 2023-06-23 at 2 00 37 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/35cd3b0c-624d-4794-b600-cdf12094d1c5">
<img width="1544" alt="Screenshot 2023-06-23 at 2 05 40 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/c9b2028b-e891-4ca3-984d-40f348370333">
<img width="1525" alt="Screenshot 2023-06-22 at 2 18 26 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/6a4379a1-f6a7-4e70-9e95-2a6d826d3461">

### Reproduction steps

```bash
Страница /My profile - график прогресса масштабируется некорректно, обрезаются края (>110%)
https://codebattle.hexlet.io/users/10845
Главная страница /Completed games - пропала колонка actions (=130%)
https://codebattle.hexlet.io/#completedGames
Страница /users (User ratings) - не полностью масштабируется белая подложка (>140%)
https://codebattle.hexlet.io/users

Страница /tournaments/...Выбрать текущий турнир (>110%)
```

### Expected result

Корректное масштабирование всех элементов на странице при любом разрешенном масштабе.

### Actual result

При масштабировании страницы >100% некоторые элементы обрезаются, смещаются или задвигаются за другие.

### Browsers

Safari
Google Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
Есть соответствующие страницам ишью
