### ISSUE TITLE
Всплывающие окна - некорректное отображение

### ISSUE THREAD

**Issue by FilimonPK** [hexlet-codebattle/codebattle#1518]
### Summary

Всплывающие окна - некорректное отображение. Страница турнира.
Current version: 45e13e3

1. Текущая игра /Games - всплывающее окно “карточка соперника” выходит наполовину за рамки экрана (десктопная версия сайта).
2. Текущая игра /Games/Open history - всплывающее окно настроек проигрывателя не отображется поверх других элементов (десктопная и мобильная версии сайта).

<img width="1547" alt="Screenshot 2023-06-22 at 1 17 03 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/c0113d7b-a9e6-4438-8457-cf8c2d5f3d01">

======
<img width="1374" alt="Screenshot 2023-06-22 at 1 18 49 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/047754d5-970f-4b08-851a-a7d698be0c32">

### Reproduction steps

```bash
Посмотреть текущую или сыгранную игру
https://codebattle.hexlet.io/games/.../
Навести курсор на Имя соперника

Посмотреть сыгранную игру
Нажать на кнопку "Open history"
Нажать на кнопку настроек проигрывателя
```

### Expected result

Всплывающие окна отображаются корректно (полностью в рамках экрана, поверх других элементов)

### Actual result

Всплывающее окно “карточка соперника” выходит наполовину за рамки экрана (десктопная версия сайта)
Всплывающее окно настроек проигрывателя не отображется поверх других элементов (десктопная и мобильная версии сайта).

### Browsers

Chrome, Safari

### OS

Mac

**Comment by FilimonPK** [comment]
Добавлю еще отсутствие всплывающих окон.
Хотелось бы при наведении на любое Имя пользователя видеть всплывающую карточку статистики игрока.

<img width="1043" alt="Screenshot 2023-06-23 at 6 25 23 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/5e8eb47b-9434-4cb4-ac0b-8126f0d3340e">
<img width="1233" alt="Screenshot 2023-06-23 at 6 21 16 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/96d14125-41d5-4de9-b98b-d70ebe0d5afc">
<img width="1551" alt="Screenshot 2023-06-23 at 6 06 59 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/53edcfce-2a43-481b-ae54-ec3199697e6b">
<img width="1553" alt="Screenshot 2023-06-23 at 6 03 22 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/120262443/6d921277-5daa-489c-b48a-9bc7874eda84">

**Comment by ReDBrother** [comment]
> Добавлю еще отсутствие всплывающих окон. Current version: [45e13e3](https://github.com/hexlet-codebattle/codebattle/commit/45e13e3a4b71833b89428ebde1980399bedcc874)
> 
> Хотелось бы при наведении на любое Имя пользователя видеть всплывающую карточку статистики игрока.
> 
> <img alt="Screenshot 2023-06-23 at 6 25 23 PM" width="1043" src="https://user-images.githubusercontent.com/120262443/248282821-5e8eb47b-9434-4cb4-ac0b-8126f0d3340e.png"> <img alt="Screenshot 2023-06-23 at 6 21 16 PM" width="1233" src="https://user-images.githubusercontent.com/120262443/248282849-96d14125-41d5-4de9-b98b-d70ebe0d5afc.png"> <img alt="Screenshot 2023-06-23 at 6 06 59 PM" width="1551" src="https://user-images.githubusercontent.com/120262443/248282856-53edcfce-2a43-481b-ae54-ec3199697e6b.png"> <img alt="Screenshot 2023-06-23 at 6 03 22 PM" width="1553" src="https://user-images.githubusercontent.com/120262443/248282862-6d921277-5daa-489c-b48a-9bc7874eda84.png">

Это намеренно, всплывающих окон в чате больше не будет

**Comment by ReDBrother** [comment]
Для чатов и Jon Doe (Неизвестного) никаих всплывающих окон не будет. Для чатов существует контекстное меню
