### ISSUE TITLE
Bug:  В турнире отсчет раундов начинается с 0. Ожидается, что отчет начнется с 1го раунда

### ISSUE THREAD

**Issue by Xtoseone** [hexlet-codebattle/codebattle#1520]
### Summary

В турнире отсчет раундов начинается с 0. Ожидается, что отчет начнется с 1го раунда

Current version: 45e13e3

https://github.com/hexlet-codebattle/codebattle/assets/114728833/4af95c16-e411-456f-8e30-36c614c311ec

### Reproduction steps

```bash
https://codebattle.hexlet.io/tournaments/758 турнир с видео

для воспроизведения:
1. открыть https://codebattle.hexlet.io/tournaments/
2. создать турнир командный с несколькими раундами
3. начать турнир выйграть или проиграть раунд
```

### Expected result

Ожидается что первый раунд будет 1ый

### Actual result

первый раунд начинается с цифры 0

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows

**Comment by ReDBrother** [comment]
В основном это фича, а не баг. Скорее это референс к индексации массивов в большинстве языков. Местами эта убрали
