### ISSUE TITLE
Bug: Опечатка в слове Хекслет

### ISSUE THREAD

**Issue by Tatyana8TA** [hexlet-codebattle/codebattle#1536]
### Summary

В меню. Вместо Хекслет, написано Гекслет
![image](https://github.com/hexlet-codebattle/codebattle/assets/123509744/4116734b-8b70-4f96-bc36-5712694ecd8c)

Google Chrome v1 120.2212.4190.0 64-разрядная операционная система, процессор x64 ОС Windows 10 Pro 12.2020

### Reproduction steps

```bash
Открываем меню
```

### Expected result

Хекслет

### Actual result

Гекслет

### Browsers

Chrome

**Comment by solar05** [comment]
Такая же история как и в https://github.com/hexlet-codebattle/codebattle/issues/1537
