### ISSUE TITLE
Bug: Опечтка в форме Создать новую игру

### ISSUE THREAD

**Issue by Tatyana8TA** [hexlet-codebattle/codebattle#1537]
### Summary

Когда создаешь новую игру https://codebattle.hexlet.io/tournaments Уровень средний , есть опечатка.
![image](https://github.com/hexlet-codebattle/codebattle/assets/123509744/7677ae0f-30ae-44a5-a07f-1c1e837bd60d)

Google Chrome v1 120.2212.4190.0 64-разрядная операционная система, процессор x64 ОС Windows 10 Pro 12.2020

### Reproduction steps

```bash
- Переходим на страницу Турниры  https://codebattle.hexlet.io/tournaments
- Создаешь новую игру
- Выбор уровня
```

### Expected result

Средний

### Actual result

Середний

### Browsers

Chrome

**Comment by solar05** [comment]
Это косяк перевода какого-то плагина в браузере или встроенного браузерного перевода, так как в кодбатле локализация сложности задач отсутствует
