### ISSUE TITLE
Bug: LEADERBOARD не адаптирована под мобильные устройства

### ISSUE THREAD

**Issue by cmeshnoy** [hexlet-codebattle/codebattle#1543]
### Summary

Не корректное отображение при просмотре рейтинговой таблицы с мобильного устройства Google Pixel 5A
![photo_2023-07-05_20-40-20](https://github.com/hexlet-codebattle/codebattle/assets/114485692/c98f7cc9-0641-4381-9097-f6559b174e91)
![photo_2023-07-05_20-40-22](https://github.com/hexlet-codebattle/codebattle/assets/114485692/b27435d9-d2ad-4f63-b299-c68bad04b92a)

### Reproduction steps

```bash
На главной странице внизу таблицы LEADERBORD нажимаем на Top list
```

### Expected result

Внизу экрана появляется ползунок для скролла

### Actual result

Таблица выходит за рамки верстки

### Browsers

Chrome

**Comment by ReDBrother** [comment]
Дубль от #1487

**Comment by AntonKondrat7** [comment]
Тот же баг IPhone 12 Pro

Google Chrome Версия 114.0.5735.199 (Официальная сборка), (64 бит)
Windows 10 Домашняя
Версия 22H2 Сборка 19045.3086
Current version: 764df7e
