### ISSUE TITLE
Bug: В разделе My settings диаграмма находится не посередине

### ISSUE THREAD

**Issue by ekaterinazhakupova** [hexlet-codebattle/codebattle#1545]
### Summary

В таблице в разделе My settings диаграмма находится не посередине. Ожидается, что она должна быть посередине

![Таблица не посередине](https://github.com/hexlet-codebattle/codebattle/assets/128256595/46e7275e-c3c8-4dc6-b0c0-e00fa46e242b)

### Reproduction steps

```bash
- Заходим на сайт https://codebattle.hexlet.io/
    - Нажимаем на значок профиля в правом верхнем углу
    - Нажимаем Settings
```

### Expected result

 Все элементы таблиц на странице выровнены посередине

### Actual result

Диаграмма находится с левого края. Ожидается, что она должна быть посередине

Current version: 764df7e

Яндекс Браузер Версия 23.5.4.674 (64-bit)
Майкрософт Windows 10 Корпоративная
Версия 10.0.19045 Сборка 19045

### OS

Windows

**Comment by ReDBrother** [comment]
Прикрепим к 1488
