### ISSUE TITLE
Bug: Не работает нумерация количества пользователей на странице в Users rating

### ISSUE THREAD

**Issue by ekaterinazhakupova** [hexlet-codebattle/codebattle#1546]
### Summary

На странице некорректно отображается нумерация пользователей.
![Неверная нумерация 30 2](https://github.com/hexlet-codebattle/codebattle/assets/128256595/4a689773-ae9d-4573-bbd2-65621eb95b76)
![Неверная нумерация 30](https://github.com/hexlet-codebattle/codebattle/assets/128256595/57bec517-a9d2-4360-962f-879db9496f91)

### Reproduction steps

```bash
- Заходим на сайт https://codebattle.hexlet.io/
    - Нажимаем Нажимаем на значок профиля в правом верхнем углу
    - Нажимаем Users rating 
    - C помощью фильтра меняем количество отображаемых пользователей на 30
```

### Expected result

Нумерация последовательна от 1 до 30 включительно

### Actual result

Дублируются числа 19 и 26. Нумерация оканчивается числом 27, а не 30
Current version: 764df7e

Яндекс Браузер Версия 23.5.4.674 (64-bit)
Майкрософт Windows 10 Корпоративная
Версия 10.0.19045 Сборка 19045

### OS

Windows

**Comment by Makarova94** [comment]
- summary: |
   На странице  Users rating некорректно отображается нумерация пользователей
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux. Current version: 764df7e
  steps-to-reproduce: |
   - Нажать на иконку профиля в правом верхнем углу
    - Нажать на раздел Users rating 
    - C помощью фильтра меняем количество отображаемых пользователей на 30
  expected-result: |
    Нумерация последовательна, немерация корректно отображается
  actual-result: |
   Дублируются числа 19 и 26
