### ISSUE TITLE
Bug: Изменение высоты окна "Create a game" при выборе уровня сложности

### ISSUE THREAD

**Issue by anastasiya-breusova** [hexlet-codebattle/codebattle#1550]
### Summary

Выбор уровня сложности влияет на высоту модального окна "Create a game"

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на кнопку "Create a game"
3. Выбрать 3 или 4 уровень сложности
```

### Expected result

Выбор уровня сложности не должен влиять на высоту модального окна

### Actual result

Высота модального окна меняется при выборе 3 или 4 уровня сложности

<img width="599" alt="Снимок экрана 2023-07-11 в 19 49 00" src="https://github.com/hexlet-codebattle/codebattle/assets/129413395/2fab0bb4-e71c-4554-bcaf-f785a537878f">

<img width="599" alt="Снимок экрана 2023-07-11 в 19 49 33" src="https://github.com/hexlet-codebattle/codebattle/assets/129413395/a96f4c81-f464-4eaa-9684-efbc3254a2c9">

**Comment by ReDBrother** [comment]
Исправили
