### ISSUE TITLE
Bug: В блоке "Create a new tournament" не выровнены поля ввода на мобильных устройствах

### ISSUE THREAD

**Issue by anastasiya-breusova** [hexlet-codebattle/codebattle#1551]
### Summary

Поля ввода данных находятся на разной высоте из-за переноса текста

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на изображение учетной записи
3. Перейти в раздел "Tournament"
```

### Expected result

Все поля ввода данных выровнены независимо от переноса текста

### Actual result

Поля ввода данных не выровнены по оси Y из-за переноса текста

<img width="289" alt="Снимок экрана 2023-07-11 в 20 07 44" src="https://github.com/hexlet-codebattle/codebattle/assets/129413395/7f35b564-f410-47c5-bbfa-123dcfb328b0">

**Comment by YukKaji** [comment]
![mob_tornaments_fields](https://github.com/hexlet-codebattle/codebattle/assets/128067636/e87ada7b-3eb0-48fe-812b-1c43dab92c5f)
Внешний вид полей на мобильной версии

**Comment by Makarova94** [comment]
Summary 
Подтверждение бага. Версия [764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5) 
    При переходи на мобильную версию, веб-сайт перестает корректно отображать верстку 
  environment: |
   Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит) ОС Linux
  steps-to-reproduce: |
   - Открыть главную страницу сайта 
    - Зайти в DevTools
    - Переключиться на мобильную версию 
    - Выбрать из списка Iphone 12 PRO
    - Нажать на изображение учетной записи
    - Выбрать раздел "Tournametns" в выпадающем списке
  expected-result: |
    На мобильных устройствах все поля ввода данных отображаются корректно, выровнены независимо от переноса текста
  actual-result: |
    Поля ввода данных не выровнены по высоте

**Comment by Nelect96** [comment]
<img width="289" alt="Снимок экрана 2023-07-28 в 13 53 50" src="https://github.com/hexlet-codebattle/codebattle/assets/120308613/8504e5a0-b3d1-4916-8e3e-93ce8fe3a900">
Steps:
Авторизоваться
1. В DevTools "Toggle device toolbar"
2. В "Dimensions" выбираем любые устройства для отображения
Нажать на изображение учетной записи
В выпадающем меню выбираем "Tournametns"

Browsers
Chrome Версия 115.0.5790.114 (Официальная сборка), (arm64)

OS
macOS Ventura Версия 13.4.1 (c) (22F770820d)
