### ISSUE TITLE
Bug: Отсутствует адаптация на мобильные устройства страницы турнирной сетки

### ISSUE THREAD

**Issue by anastasiya-breusova** [hexlet-codebattle/codebattle#1552]
### Summary

Отсутствует адаптация на мобильные устройства страницы турнирной сетки

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на изображение учетной записи
3. Перейти в раздел "Tournaments"
4. В таблице выбрать турнирную сетку
5. Нажать на кнопку "Show"
```

### Expected result

Страница турнирной сетки адаптирована на мобильные устройства

### Actual result

Адаптация на мобильные устройства отсутствует

1. Тип турнира = "team"
https://github.com/hexlet-codebattle/codebattle/assets/129413395/db3e2ee0-c50c-4bec-8931-18eb08619169

2. Тип турнира = "individual"
https://github.com/hexlet-codebattle/codebattle/assets/129413395/adc8a545-3e1e-4133-9a0a-43648ef85dcc

**Comment by YukKaji** [comment]
![mob_show_tournament](https://github.com/hexlet-codebattle/codebattle/assets/128067636/bc08545a-8095-4178-b087-cc0c3c02af2f)
Внешний вид турнирной сетки на мобильной версии

**Comment by ReDBrother** [comment]
Дубль от #1486
