### ISSUE TITLE
Bug: в мобильной версии, при просмотре страницы кнопки воспроизведения, настроек и "Send feedback" расположены не корректно

### ISSUE THREAD

**Issue by YukKaji** [hexlet-codebattle/codebattle#1555]
### Summary

Кнопки загораживают полосу воспроизведения, а так же иконки не по центру.

### Reproduction steps

```bash
1. Открыть сайт в мобильной версии
2. Нажать "completed games"
3. Нажать "show"
```

### Expected result

Кнопки не загораживают полосу воспроизведения, иконки по центру.

### Actual result

Кнопки загораживают полосу воспроизведения, иконки не по центру.
![mob_show_game](https://github.com/hexlet-codebattle/codebattle/assets/128067636/71d5ea01-47d9-4ca0-bedd-75d8f5244a9d)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль #1271
