### ISSUE TITLE
Bug: При загрузки страницы "tournaments" появляются ошибки

### ISSUE THREAD

**Issue by YukKaji** [hexlet-codebattle/codebattle#1556]
### Summary

При заходе на страницу "tournaments" в Issues DevTools появляются ошибки Incorrect use of <label for=FORM_ELEMENT>

### Reproduction steps

```bash
1. Нажать на свой профиль
2. Нажать "tournaments"
```

### Expected result

Ошибок не должно быть
![tournaments](https://github.com/hexlet-codebattle/codebattle/assets/128067636/a11588ba-999a-4061-92de-dad6b1da910e)

### Actual result

Ошибки есть

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Fixed
