### ISSUE TITLE
Bug: Некорректное отображение номера строки в игре

### ISSUE THREAD

**Issue by YukKaji** [hexlet-codebattle/codebattle#1559]
### Summary

https://github.com/hexlet-codebattle/codebattle/issues/1228
Баг все еще воспроизводится. Версия : 764df7e

![numb](https://github.com/hexlet-codebattle/codebattle/assets/128067636/f72de2ba-c965-432d-922b-4f1da0b41cda)

### Reproduction steps

```bash
1. Начать игру с любыми параметрами
2. Зажать кнопку "Enter" до появления строк с трехзначными значениями
```

### Expected result

Номера отображаются корректно.

### Actual result

Номера отображаются некорректно.

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by GrimRoge** [comment]
### **Summary**
Подтверждение бага. Версия [764df7e](https://github.com/hexlet-codebattle/codebattle/commit/764df7e3441c14d522417d24775d638d49019ca5)
![image](https://github.com/hexlet-codebattle/codebattle/assets/130750852/1f41d262-4f19-4823-ab7f-b44facff73f3)
### **Reproduction steps**

1. Начать игру с любыми параметрами
2. Зажать кнопку "Enter" до появления строк с трехзначными значениями

### **Expected result**
Номера отображаются корректно, в правильной числовой последовательности
### **Actutal result**
Номера отображаются некорректно. Нет трёхзначных чисел.
### **Browsers**
Google Chrome 115.0.5790.102
### **OS**
Windows 10

**Comment by vladimirart2811** [comment]
Баг не воспроизводится. Номера строк отображаются корректно
<img width="858" alt="Снимок экрана 2023-08-08 в 5 08 56 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/5b1b9c8d-e411-47c8-be24-30aedf395d7a">


Browsers 
Google Chrome Версия 115.0.5790.170 (Официальная сборка), (arm64)
Safari Версия 16.6 (18615.3.12.11.2)

OS
macOS Ventura 13.5

**Comment by ReDBrother** [comment]
Баг если и есть, то является багом редактора монако - это чужой проект
