### ISSUE TITLE
Bug: Баг в описании валидации к полю Псевдоним 

### ISSUE THREAD

**Issue by Makarova94** [hexlet-codebattle/codebattle#1561]
### Summary

Баг в описании валидации к полю Псевдоним (Псевдоним должен начинаться с латинской буквы). Если начать с латинской буквы, а потом перейти на кириллицу, выдает ошибку. 

### Reproduction steps

```bash
- Вводим псевдоним = Rальгог  
    - Вводим электронную почту = natali_shilina@internet.ru
    - Вводим пароль  = badpass 
    - Вводим пароль  = badpass 
    - Нажимаем кнопку «Submit»
```

### Expected result

 Пользователь должен быть зарегистрирован в системе

### Actual result

Регистрация не осуществляется
![Без имени](https://github.com/hexlet-codebattle/codebattle/assets/129146395/0d4e76bf-a77b-42fe-828b-e7f01d2d57cb)

### Browsers

Chrome

### OS

Linux

**Comment by ReDBrother** [comment]
Мы не можем отвечать за корректность автоматического перевода!
