### ISSUE TITLE
Bug: Не заменен Slack на Mattermost в окне Output

### ISSUE THREAD

**Issue by ekaterinazhakupova** [hexlet-codebattle/codebattle#1563]
### Summary

При вводе невалидных данных в поле редактора кода во время игры после нажатия check solution в окне output предлагается написать команде в слак, а не в маттермост

### Reproduction steps

```bash
- Заходим на сайт https://codebattle.hexlet.io/
    - Нажимаем Create a game
    - Выбираем Level - *
    - Выбираем Game time - with a bot
    - Выбираем Time control - 9 min
    - Выбираем Choose task by name or tags - random task
    - В Tags не выбираем ничего
    - Нажимаем Create battle
    - В окне редактора кода вводим Hello, world
    - Нажимаем Check solution
```

### Expected result

В окне Output появляется надпись Something went wrong! Please, write to dev team in our Mattermost

### Actual result

![негативный тест на код](https://github.com/hexlet-codebattle/codebattle/assets/128256595/9db227df-deed-44ed-9a89-0e0722bdeef3)
 В окне Output появляется надпись Something went wrong! Please, write to dev team in our Slack

Current version:764df7e

Яндекс Браузер Версия 23.5.4.674 (64-bit)
Майкрософт Windows 10 Корпоративная
Версия 10.0.19045 Сборка 19045

### OS

Windows

**Comment by ReDBrother** [comment]
Поменяли на телегу. В истории у нас такие сообщения остануться старыми - мы их поменять не можем
