### ISSUE TITLE
Bug:  Изменяется размер аватара в профиле, при переходе между вкладками 

### ISSUE THREAD

**Issue by fidilly** [hexlet-codebattle/codebattle#1568]
### Summary

На странице профиля изменяется размер аватара при переходе между вкладками

### Reproduction steps

```bash
1. Нажать на аватар
2. Нажать на кнопку "My profile"
3. Нажать на вкладку "Completed games"
```

### Expected result

Аватар должен быть одинакового размера

### Actual result

Аватар измеряет размер
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/d32569aa-d9ba-4e4f-b9a7-374d096e5df8)
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/f09aa0f0-3484-4800-942c-11522f05b537)

### Browsers

Firefox, Chrome

### OS

Linux

[Текущая версия: fd71526](https://github.com/hexlet-codebattle/codebattle/commit/fd71526086b97b7a700fb8ae09eab33f7a521dae)

**Comment by ReDBrother** [comment]
Нужно разобраться в том, как возникает зависимость от содержимого вкладки справа, на адаптивность аватар картинки во вкладке слева.
