### ISSUE TITLE
Bug: Приватный чат отсутствует в списке чатов при получении сообщения

### ISSUE THREAD

**Issue by fidilly** [hexlet-codebattle/codebattle#1569]
### Summary

Приватный чат отсутствует в списке чатов при получении сообщения.

### Reproduction steps

```bash
1. Получить приватное сообщение
2. Нажать на кнопку выбора чата
```

### Expected result

Можно выбрать чат с пользователем, от которого пришло сообщение

### Actual result

Отсутствует чат в списке чатов
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/d378bdf8-b834-4204-a010-a7141de1b9b9)
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/367cd2df-e081-4a30-a85f-295ebeb5e405)

### Browsers

Firefox

### OS
Linux

**Comment by ReDBrother** [comment]
Во всех онлайн играх комнату открывают по команде пользователя, не по факту прихода сообщения в чат
