### ISSUE TITLE
Bug: Некорректный сетап таймера игровой сессии

### ISSUE THREAD

**Issue by vladimirart2811** [hexlet-codebattle/codebattle#1571]
### Summary

При возвращении в игру таймер оставшегося времени не сразу отображает актуальное время

### Reproduction steps

```bash
- Нажать кнопку "Create a game"
- Выбрать Level "elementary"
- Выбрать Game Type "with a bot"
- Выбрать Time control "10 min"
- Выбрать Choose task by name or tags "random task"
- Нажать на кнопку "Create battle"
- В игровом режиме нажать "Back to home"
- На главной странице нажать "Continue"
```

### Expected result

При возвращении в игру на таймере обратного отсчета сразу должно отображаться актуальное оставшееся время

### Actual result

На протяжении нескольких секунд отображается изначально установленное время, а только потом актуальное
<img width="1719" alt="Снимок экрана 2023-08-07 в 7 43 13 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/964a31f5-1401-4b34-b755-e3f8c7d95497">
<img width="810" alt="Снимок экрана 2023-08-07 в 7 43 40 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/b672c5cb-de35-48f1-8644-b970a255919d">
<img width="1718" alt="Снимок экрана 2023-08-07 в 7 43 48 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/d2906e25-ddd7-4480-abc8-35771c39018e">
<img width="852" alt="Снимок экрана 2023-08-07 в 7 43 49 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/3b9e3c5b-1539-41fb-b4de-df2baf376304">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Если это отдельный режим таймера, то нужно будет добавить более явный признак (Например колесо загрузки), если нет, то починить отображение.

**Comment by ReDBrother** [comment]
Пофикшено
