### ISSUE TITLE
Feature: Нет сообщения об отсутствии возможности создать игру

### ISSUE THREAD

**Issue by vladimirart2811** [hexlet-codebattle/codebattle#1575]
### Summary

При попытке создать игру нет сообщения о необходимости завершить ранее созданную

### Reproduction steps

```bash
- авторизоваться на сайте
- нажать "create a game"
- нажать "Create battle"
- вернуться на главную страницу
- нажать "create a game"
- нажать "Create battle"
```

### Expected result

Появилось сообщение о необходимости завершить ранее созданную игру для начала новой

### Actual result

Окно создания игры закрывается, пользователь попадает на главный экран, никакого сообщения не появляется

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Это точно не баг, ведь в любом соревновании ты должен быть там и решать задачу, а не учавствовать в 10 параллельных.

С другой стороны, очень хочется понимать в лобби, что сейчас ты находишься в другой игре и не можешь создать новую, пока не завершишь другую: Нам нужно в интерфейсе посмотреть список текущих игр и если уже есть моя игра, то вместо Create Game, я должен увидить Continue, по клику на которую я перехожу к текущей игре.
