### ISSUE TITLE
Bug: Смещение полей формы создания игры

### ISSUE THREAD

**Issue by vladimirart2811** [hexlet-codebattle/codebattle#1576]
### Summary

При переключении уровня сложности создаваемой игры с Elementary и Easy на Medium и Hard происходит смещение полей формы

### Reproduction steps

```bash
- нажать "Create a game"
- выбрать Level "Medium"
```

### Expected result

Поля формы не смещаются, все элементы формы остаются на месте

### Actual result

Форма растягивается вниз, происходит смещение всех элементов формы
<img width="1722" alt="Снимок экрана 2023-08-08 в 2 53 45 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/77f5e56e-fb73-4693-a288-a8e2ed98731b">
<img width="1717" alt="Снимок экрана 2023-08-08 в 2 54 30 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/925df213-8c65-4506-87b6-1867c7a56619">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Нужно немного переделать стили переключалок сложности в активном и пассивном режимах, чтобы размеры не менялись
