### ISSUE TITLE
Bug: Надпись в океане чата турнира не адаптирована под поле ввода  

### ISSUE THREAD

**Issue by vladimirart2811** [hexlet-codebattle/codebattle#1578]
### Summary

Надпись "write your message" в окне чата турнира не помещается в поле ввода

### Reproduction steps

```bash
- войти во вкладку Tournaments
- нажать "You may want to create one"
- нажать "Create"
```

### Expected result

Все надписи адаптированы под размер полей форм

### Actual result

Часть надписи "write your message" в окне чата не видна
<img width="1138" alt="Снимок экрана 2023-08-08 в 4 11 14 PM" src="https://github.com/hexlet-codebattle/codebattle/assets/135047932/10be8ab1-578e-4e2d-97af-afdbe101131e">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Дубль от 1486
