### ISSUE TITLE
Bug: Масштабирование страницы - некорректное отображение  (десктопная версия сайта) retest #1517

### ISSUE THREAD

**Issue by Anastasia-Kim3** [hexlet-codebattle/codebattle#1579]
### Summary

Масштабирование страницы - некорректное отображение  (десктопная версия сайта)
[Current version: fd71526](https://github.com/hexlet-codebattle/codebattle/commit/fd71526086b97b7a700fb8ae09eab33f7a521dae)

1. Страница /My profile - график прогресса масштабируется некорректно, обрезаются края (>200%)
2.  Страница /tournaments/...Выбрать текущий турнир:
2.1.  chat-ввод сообщения - не умещается подсказка поля “Write your message” (>150%);
2.2.  поле “Total players” - выход за рамки имени пользователя, перечение окон чата и списка пользователей (>200%);

![image](https://github.com/hexlet-codebattle/codebattle/assets/133269405/a7d15789-f28c-477f-8ec6-dd3e8a0d6a5c)

![image](https://github.com/hexlet-codebattle/codebattle/assets/133269405/032b860b-04fd-49aa-8b03-9bf797778e42)

![image](https://github.com/hexlet-codebattle/codebattle/assets/133269405/96eb3e71-f8fa-4b83-8e36-c6f8c07d107e)

### Reproduction steps

```bash
Страница /My profile - график прогресса масштабируется некорректно, обрезаются края (>200%)
https://codebattle.hexlet.io/users/11129

Страница /tournaments/...Выбрать текущий турнир (>150%)
```

### Expected result

Корректное масштабирование всех элементов на странице при любом выбранном масштабе.

### Actual result

При масштабировании страницы >150% некоторые элементы обрезаются, смещаются или задвигаются за другие.

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1495 и #1486
