### ISSUE TITLE
Bug: Возможность изменить никнейм на нелатинские символы

### ISSUE THREAD

**Issue by Va-khar** [hexlet-codebattle/codebattle#1585]
**Summary**

Пользователь  может изменить свой никнейм на нелатинские символы

**Reproduction steps**

- Нажимаем на портрет 
    - Открывается окошко
    - Выбираем Settings
    - В поле Your name стираем старый никнейм
    - В это же поле вводим новый никнейм 
    - Нажимаем Save
   
**Expected result**

Появляется предупреждения  некорректном никнейме

**Actual result**

![Баг на нелатинский никнейм](https://github.com/hexlet-codebattle/codebattle/assets/81294023/18307718-61c7-4511-9209-1290cb4ef63b)

Current version: bde75cb

Google Chrome 115.0.5790.171 (Официальная сборка), (64 бит)
ОС Windows 10

**Comment by ReDBrother** [comment]
Не запрещено)

**Comment by kairina2020** [comment]
Тестировала сегодня, не запрещено, можно изменить на кириллицу)))

**Comment by ElenaSimanina** [comment]
Аналогично, не запрещено)))
