### ISSUE TITLE
Bug: Нельзя выделить и скопировать текст кода в игре в мобильной версии

### ISSUE THREAD

**Issue by AnnaGurina** [hexlet-codebattle/codebattle#1587]
### Summary

Нельзя выделить (например, для удаления) и скопировать текст кода в игре в мобильной версии. 
В десктопной версии такая возможность есть

environment: |
Google Chrome   Версия 115.0.5735.124 (Официальная сборка), (64 бит)
iPhone 14
Cb version: 6de75b

### Reproduction steps

```bash
1. Зайти на страницу https://codebattle.hexlet.io/
2. Авторизоваться
3. Нажать 'Create a game' (тип with a bot)
4. Нажать 'Create battle'
5. Выделить текст в своем окне с кодом 
6. Скопировать выделенный текст
```

### Expected result

Можно выделить и скопировать текст кода в игре в мобильной версии

### Actual result

Выделить текст либо не получается либо получается с ошибкой: появляется дополнительное меню, мешающее продолжить и редактировать выделение.
Нельзя скопировать скопировать выделенный текст
![Фото 10 08 2023, 17 44 03](https://github.com/hexlet-codebattle/codebattle/assets/62752547/355d7974-8d2e-483c-bf6e-6201f380573a)

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
Вот тут мы ограничены чужим онлайн редактором. который в своей основе отказался от полной поддержки мобильной версии.

Максимум, чего мы можем достичь, это достаточно адаптивный режим чтения содержимого на экране
