### ISSUE TITLE
Bug: Наложение кнопки Create a game на список игроков в чате в мобильной версии 

### ISSUE THREAD

**Issue by Va-khar** [hexlet-codebattle/codebattle#1588]
**Summary**
Наложение кнопки Create a game на список игроков в чате в мобильной версии 

**Steps**
    - Открыта страница авторизованного пользователя https://codebattle.hexlet.io/#lobby
    - Запускаем DevTools
  
**Expected result**
Кнопка Create a game не накладывается на список игроков в чате 

**Actual result**
![Наложение кнопки CREATE A GAME на список игроков в чате ](https://github.com/hexlet-codebattle/codebattle/assets/81294023/778c5375-0cbd-4a68-a7b0-a2d450d61f9f)

Current version: 11610be
Google Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит)
OC Windows 10

**Comment by marinalinnik** [comment]
**Summary**
Наложение кнопки "Create a game" на список игроков он-лайн в мобильной версии

**Steps**
Пользователь авторизован и открыта главная страница сайта
Запустить DevTools
Выбрать мобильную версию "iPhone 12 Pro"

**Expected result**
Кнопка "Create a game" находится отдельно от списка игроков и чата

**Actual result**
Кнопка "Create a game"  накладывается на список игроков он-лайн

**Environment:**
Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)
iPhone 12 Pro
ОС Windows 10
Current version: 11610be


![br pr 2 Create a game](https://github.com/hexlet-codebattle/codebattle/assets/132447284/9f9a4648-7546-421f-9c8c-55f78e3d06fd)

**Comment by allastrn** [comment]
Summary
Наложение кнопки "Create a game" на список игроков онлайн в мобильной версии

Steps
Пользователь авторизован 
Открыта главная страница сайта

Expected result
Кнопка "Create a game" закреплена под списком последних игр

Actual result
Кнопка "Create a game" находится под чатом и накладывается на список игроков онлайн
![2023-08-20 11 04 43](https://github.com/hexlet-codebattle/codebattle/assets/99401571/75c4a9fe-b81e-4e64-ac8d-433798a18fab)

Environment:
IOS 16.6
iPhone 11 Pro Max
Safari

**Comment by alexamuek** [comment]
Summary
Кнопки "Create a game" перекрывает список игроков на странице лобби

Steps
Пользователь авторизован
Открыта страница лобби

Expected result
Кнопка "Create a game" не перекрывает разделы страницы лобби

Actual result
Кнопка "Create a game" перекрывает раздел игроков страницы лобби
![ksnip_20230821-120901](https://github.com/hexlet-codebattle/codebattle/assets/41149837/d58ddd48-7fc9-4029-8850-6e88471b6b47)

**Comment by ReDBrother** [comment]
Пофикшено
