### ISSUE TITLE
Bug: Текст "Please be nice in the chat!" не адаптирован в мобильной версии

### ISSUE THREAD

**Issue by marinalinnik** [hexlet-codebattle/codebattle#1590]
### Summary

Текст "Please be nice in the chat!" не адаптирован в мобильной версии

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Запустить DevTools на главной странице сайта
3. Выбрать мобильную версию "iPhone 12 Pro"
```

### Expected result

Текст "Please be nice in the chat!" полностью выводится в поле

### Actual result

Текст не выводится полностью в форме

![br pr 2 Cha](https://github.com/hexlet-codebattle/codebattle/assets/132447284/71ac3158-1503-433e-9e74-d661e1c4bb8f)

### Browsers

Chrome

### OS

Windows

**Comment by St1leXX** [comment]
Баг воспроизводится

 prerequisites: 
    Открыта главная страница Codebattle с авторизованным пользователем
  test-data:
     Codebattle version: ef4c0b9
  steps:
    - Открываем DevTools
    - Нажимаем на кнопку "Toggle device toolbar"
    - Выбраем iPhone 12 Pro / Galaxy S9+
  expected-result:
    Текст "Please be nice in the chat!" полностью помещается в поле ввода
  actual result: 
    Текст не помещается в поле ввода
![чат 1](https://github.com/hexlet-codebattle/codebattle/assets/129951745/82872c05-3f1a-4212-86b7-1bfb1ba3b7ad)
![чат 2](https://github.com/hexlet-codebattle/codebattle/assets/129951745/9730469d-7be7-4ba9-bdf1-e280e3820f4c)

**Comment by denikeev** [comment]
беру в работу, попробую поправить

**Comment by denikeev** [comment]
создал МР
