### ISSUE TITLE
Bug: Отсутствует предупреждение о наличии у игрока активной игры при создании новой

### ISSUE THREAD

**Issue by alexamuek** [hexlet-codebattle/codebattle#1597]
### Summary

Пользователь создал игру с типом With other users. Затем нажимает снова Create a game. В форме создания игры выбирает тип With a bots. Подтверждает создание игры. Форма закрывается, никакое предупреждение не появляется.

### Reproduction steps

```bash
1. Пользователь имеет игру с типом With other users, в которую никто не присоединился еще.
2. Пользователь нажимает Create a game на странице лобби
3. В форме создания игры выбирает тип With a bots
4. Другие параметры в форме не меняет
5. В форме подтверждает создание игры
```

### Expected result

При подтверждении создания игры должно возникнуть сообщение already_in_game

### Actual result

Предупреждение already_in_game  не появляется, форма создания игры просто закрывается.
![ksnip_20230821-103402](https://github.com/hexlet-codebattle/codebattle/assets/41149837/c28b1e6b-40cf-4bb3-985b-9764dfa4ce81)
![ksnip_20230821-103431](https://github.com/hexlet-codebattle/codebattle/assets/41149837/23c2c619-e6cd-4f09-89bf-bade38021df0)

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by alexamuek** [comment]
Я бы в таком случае показывал сообщение об ошибке на этапе нажатия Create a game на странице лобби

**Comment by ReDBrother** [comment]
Не, мы не хотим вообще доступ давать к созданию новой игры. Где-то даже у нас валяется ишью, где описан такой кейс: Существует ограничение на создание активных игр - они всегда должна быть одна и если она уже есть, то мы вместо кнопки должны показывать "Сontinue" или вообще придумать отдельную панель для текущего нашего статуса (Нет игры и мы предложим создать новую игру или турнир, есть обычная активная игра, есть активный турнир, в котором участвуем и т.д.)

**Comment by ReDBrother** [comment]
Пофиксили
