### ISSUE TITLE
Bug: Медленно грузится лидерборд

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#1600]
### Summary

![image](https://github.com/hexlet-codebattle/codebattle/assets/697178/50c8a432-754c-4e61-b18f-02d0ab74c05a)

### Reproduction steps

```bash
1. заходим на главную
2. Открываем девтулс. Сбрасываем кеш
3. Смотрим на блок leaderboard
```

### Expected result

Лидерборд отображается сразу, как загрузилась страница

### Actual result

При самой первой загрузке 3-4 секунды занимала загрузка. Повторно почти две секунды (скрин девтулс)
![image](https://github.com/hexlet-codebattle/codebattle/assets/697178/3f284f04-4171-4fd1-9a4a-3b1e73ac7d40)

### Browsers

Chrome

### OS

Linux

**Comment by emp7yhead** [comment]
@ReDBrother, привет! Я хотел бы взяться за этот ишью

**Comment by ReDBrother** [comment]
@emp7yhead 
Вот оригинальный http запрос на недельный рейтинг:
<img width="568" alt="Screenshot 2023-12-24 at 07 30 55" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/ea015ecc-dd29-4c8f-9f3a-a1a127288cde">

Обрабатывается в этом [контроллере](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/apps/codebattle/lib/codebattle_web/controllers/api/v1/user_controller.ex#L9):
<img width="568" alt="Screenshot 2023-12-24 at 07 33 03" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/f1e01f2c-f14a-4246-9046-109525ca1e91">

Контроллер где нужно будет передать недельный рейтинг здесь, через [put_gon](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/apps/codebattle/lib/codebattle_web/controllers/root_controller.ex#L27):
<img width="694" alt="Screenshot 2023-12-24 at 07 46 09" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/bc38f94d-b51e-4847-947d-04a179e616da">

И уже в initials.js вытащить рейтинг из Gon данных.
