### ISSUE TITLE
Bug: Из игрового времени вычитается 53 секунды

### ISSUE THREAD

**Issue by MedJunior** [hexlet-codebattle/codebattle#1601]
### Summary

После создания игры из времени, которое было установлено, вычитается 53 секунды. Т.е. если на игру установлено 5 минут, то отсчёт начинается с 4мин 07сек.
![426](https://github.com/hexlet-codebattle/codebattle/assets/136447407/117c4f8a-d1d8-4eba-a716-abcac5c7e0b9)
![427](https://github.com/hexlet-codebattle/codebattle/assets/136447407/e4eefba8-3af4-4a13-a694-3e73c5600edd)

### Reproduction steps

```bash
1. Создать игру с ботом любой сложности, на любое время, с любым заданием
2. Посмотреть на таймер, когда откроется окно с игрой

Десктопная версия, Win 10 Pro 22Н2 официальная, браузер Chrome, Codebattle version: 11610be
```

### Expected result

Таймер начинает отсчитывать с установленного времени

### Actual result

Таймер начинает отсчитывать, вычитая 53 секунды от установленного значения

### Browsers

Firefox

### OS

Windows

**Comment by ReDBrother** [comment]
Не воспроизводится. Таймер отсчитывает от вашего текущего времени по фиксированному часовому поясу, который предоставляет ваш браузер - если в вашей системе по любой причине стоит некорректное время (Скорее всего выставленное вручную), то мы не можем это контролировать никак.
