### ISSUE TITLE
Bug: Пустое окно при нажатии кнопки "Show" в разделе "Tasks"

### ISSUE THREAD

**Issue by MedJunior** [hexlet-codebattle/codebattle#1602]
### Summary

Пустое окно при нажатии кнопки "Show" в разделе "Tasks"
![428](https://github.com/hexlet-codebattle/codebattle/assets/136447407/b8ea4825-d35e-43d2-96b4-3476b3ab3a15)
![429](https://github.com/hexlet-codebattle/codebattle/assets/136447407/fcec3edc-dbe4-40c7-8d11-13dc820565e4)

### Reproduction steps

```bash
1. Зайти в лобби Codebattle
2. Нажать на иконку/никнейм своего профиля
3. В выпадающем списке выбрать "Tasks"
4. Нажать на любую кнопку "Show"
```

### Expected result

Отображение какой-либо информации

### Actual result

Пустое окно

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Пофикшено

**Comment by Chebanya** [comment]
**summary:** 
    There is no task information on the page of any of the tasks that are located in the Tasks section
**environment:** 
    Google Chrome 129.0.6668.60 (Official build), (x86_64)
    MacOS Ventura 13.3.1
    Current version of the site: 3856424
**steps-to-reproduce:** 
    - In the header in the upper right corner, click on the user's nickname
    - In the window that appears, click on Tasks
    - Select any task from the list of tasks
    - Click on the Show button
**expected-result:** 
    A page with information about the selected task has opened
**actual-result:** 
    An empty page has opened, there is no information about the selected task

https://github.com/user-attachments/assets/b354deaf-a6c9-4b21-837b-531a319ec2d0
