### ISSUE TITLE
Bug: Сортировка задач по уровню сложности

### ISSUE THREAD

**Issue by MedJunior** [hexlet-codebattle/codebattle#1603]
### Summary

В разделе "Tasks" задачи нелогично сортируются по уровню сложности: сначала идут задачи с 2 звёздами, потом с 1 звездой, потом с 4 звёздами, и последние с 3 звёздами
![430](https://github.com/hexlet-codebattle/codebattle/assets/136447407/b2a48a4c-4a69-47b7-bc90-5931c596d00f)
![431](https://github.com/hexlet-codebattle/codebattle/assets/136447407/064c6715-5c32-4486-8450-48330a2528cc)
![432](https://github.com/hexlet-codebattle/codebattle/assets/136447407/5fbe7b3c-be68-4214-9f3c-9677866c322f)

### Reproduction steps

```bash
1. Зайти в лобби Codebattle
2. Нажать на иконку/никнейм своего профиля
3. В выпадающем списке выбрать "Tasks"

Десктопная версия, Win 10 Pro 22Н2 официальная, браузер Chrome, Codebattle version: 11610be
```

### Expected result

Сортировка по уровню сложности от меньшей к большей

### Actual result

Нет сортировки по уровню сложности

### Browsers

Chrome

### OS

Windows

**Comment by mari2666** [comment]
![2023-09-12 (2)](https://github.com/hexlet-codebattle/codebattle/assets/134852182/16fbc4e5-41ed-4b03-92ff-3a74cb0d417c)
![2023-09-12 (3)](https://github.com/hexlet-codebattle/codebattle/assets/134852182/ab1fffc4-ee09-4360-9f63-8e19b3608217)
![2023-09-12](https://github.com/hexlet-codebattle/codebattle/assets/134852182/ec543f77-b9f4-4b3d-9d87-28f1d84389d3)
Reproduction steps
1. Зайти в лобби Codebattle
2. Нажать на иконку/никнейм своего профиля
3. В выпадающем списке выбрать "Tasks"

Десктопная версия, Windows 11 Pro Version 21H2   официальная, браузер Chrome, Codebattle version: 11610be
Expected result
Сортировка по уровню сложности от меньшей к большей

Actual result
Нет сортировки по уровню сложности

Browsers
Chrome Версия 116.0.5845.188 

OS
Windows

**Comment by atolokoni** [comment]
Баг воспроизводится

environment: 
Chrome 117.0.5938.132(Официальная сборка) (64 бит) 
Windows 10 pro 19045.3448
Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/ef4c0b9710105f1cd878f8231195d43da590d11d

prerequisites:
Открыта страница Tasks

Expected result
Сортировка по уровню сложности от меньшей к большей

Actual result
Нет сортировки по уровню сложности

![image](https://github.com/hexlet-codebattle/codebattle/assets/68560789/344ef89a-f6c0-4610-9e53-d7097208017c)
![image](https://github.com/hexlet-codebattle/codebattle/assets/68560789/3b627602-7632-48a6-9490-cb6f4d5d071b)

**Comment by ElenaRedkina89** [comment]
Баг воспроизводится

environment: 
Chrome 117.0.5938.132(Официальная сборка) (64 бит) 
Windows 10 pro 19045.3448
Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/ef4c0b9710105f1cd878f8231195d43da590d11d

prerequisites:
Открыта страница Tasks

Expected result
Сортировка по уровню сложности от меньшей к большей

Actual result
Нет сортировки по уровню сложности

**Comment by St1leXX** [comment]
Баг воспроизводится
  
prerequisites: 
    Открыта главная страница Codebattle с авторизованным пользователем
  test-data:
     Codebattle version: ef4c0b9
  steps:
    - В правом верхнем углу нажать на свой никнейм
    - В выпадающем списке выбрать "Tasks"
  expected-result:
    Сортировка по уровню сложности от меньшей к большей
  actual result: 
    Нет сортировки по уровню сложности

![Снимок экрана 2023-10-11 140832](https://github.com/hexlet-codebattle/codebattle/assets/129951745/d6c613d8-1193-48ce-b8ef-2e4b9f91bc8b)

**Comment by ushachev** [comment]
взял в работу

**Comment by ushachev** [comment]
Ок, тогда отказываюсь

**Comment by vtm9** [comment]
done, will on prod soon
