### ISSUE TITLE
Bug: Ненужная полоса прокрутки

### ISSUE THREAD

**Issue by MedJunior** [hexlet-codebattle/codebattle#1604]
### Summary

Ненужная полоса прокрутки у заголовка лобби
![433](https://github.com/hexlet-codebattle/codebattle/assets/136447407/2c8ddb47-8a3d-447a-8712-3f89b3afe56f)

### Reproduction steps

```bash
Зайти в лобби Codebattle.

Десктопная версия, монитор FHD, Win 10 Pro 22Н2 официальная, браузеры Chrome и Firefox, Codebattle version: 11610be
```

### Expected result

Данный элемент не должен иметь полосу прокрутки

### Actual result

Полоса прокрутки есть

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by mari2666** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/134852182/1c69243b-318c-4d3e-96b3-41efe92ae66d)

Reproduction steps
Зайти в лобби Codebattle.


Expected result
Данный элемент не должен иметь полосу прокрутки

Actual result
Полоса прокрутки есть

Browsers 

Microsoft Edge
Версия 116.0.1938.62 

Выпуск	Windows 11 Домашняя
Версия	22H2
Дата установки	‎17.‎03.‎2023
Сборка ОС	22621.2134

**Comment by DyakovDD** [comment]
Reproduction steps
Зайти в лобби Codebattle.

Expected result
Данный элемент не должен иметь полосу прокрутки

Actual result
Полоса прокрутки есть

Browsers
Google Chrome Версия 114.0.5735.199 (Официальная сборка), (64 бит)

OC Windows 10 Pro 22H2

![Снимок](https://github.com/hexlet-codebattle/codebattle/assets/139456695/46e3fc15-90a0-4eaf-be82-fbc47dc61622)

**Comment by SabishiSenshi** [comment]
Reproduction steps
Зайти в лобби Codebattle.

Expected result
Данный элемент не должен иметь полосу прокрутки

Actual result
Полоса прокрутки есть

Browsers
Google Chrome Версия 116.0.5845.188 (Официальная сборка), (64 бит)

OC Windows 10 Pro 
![0](https://github.com/hexlet-codebattle/codebattle/assets/36118971/45cfdd41-f26e-400b-9897-0ad685a590c6)

**Comment by Midire99** [comment]
Reproduction steps
Зайти в лобби Codebattle.

Expected result
Данный элемент не должен иметь полосу прокрутки

Actual result
Полоса прокрутки есть

Safari   Версия 16.5.1 (18615.2.9.11.7)
    macOS Ventura 13.4.1

**Comment by SaharnyjBublik** [comment]
Баг воспроизводится

Chrome 115.0.5790.170 (Официальная сборка) (64 бит) 
MacOS Sonoma 14.0

**Comment by ElenaRedkina89** [comment]
Баг воспроизводится

Browsers
Chrome 117.0.5938.134 (Официальная сборка), (64 бит)

OS
Windows 10 Pro
Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/ef4c0b9710105f1cd878f8231195d43da590d11d

**Comment by pro0om** [comment]
summary: |
Лишняя полоса прокрутки 
environment: |
OS Windows 10
Google Chrome Версия 118.0.5993.89 (Официальная сборка), (64 бит)
https://codebattle.hexlet.io/
steps-to-reproduce: |

expected-result: |
Нет в ней необходимости, должна отсутствовать
actual-result: |
Полоса есть
![Screenshot (26)](https://github.com/hexlet-codebattle/codebattle/assets/132218049/fa28d32c-c981-42d1-92b3-19c958400bd3)

**Comment by Polina3477** [comment]
summary: |
Лишняя полоса прокрутки
environment: |
OS Windows 10
Google Chrome Версия Версия 118.0.5993.118 (Официальная сборка), (64 бит)
https://codebattle.hexlet.io/
Current version: 9500f74
steps-to-reproduce: |

expected-result: |
Её не должно быть,она не выполняет никакой функции
actual-result: |
Полоса прокрутки есть

![image](https://github.com/hexlet-codebattle/codebattle/assets/139889528/d533f8c6-5501-4eed-bdfa-ea65bccd462f)
