### ISSUE TITLE
Опечатка в названии меню на английском языке

### ISSUE THREAD

**Issue by WhiteD1** [hexlet-codebattle/codebattle#1609]
### Summary

В выпадающем меню авторизованного пользователя на английском языке опечатка в названии меню User's rating, пропущен апостроф.

![Issue_1](https://github.com/hexlet-codebattle/codebattle/assets/109975129/c876bb73-2578-4ddb-8503-b4dbdb3f8125)

Firefox Browser v 117.0, ОС Windows 10 Pro 19045.3324

### Reproduction steps

```bash
- Открыта страница сайта https://codebattle.hexlet.io/
- Нажать на никнейм или аватарку справа вверху
```

### Expected result

Название меню User's issue (с апострофом)

### Actual result

Users rating

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows

**Comment by ReDBrother** [comment]
Нет, `'s` нужен для формирования принадлежности одной сущности к чему-то. В данном случае идет ссылка на рейтинг всех пользователей, а не одного конкретного)
