### ISSUE TITLE
Bug: Некорректное отображение верстки на мобильных устройствах

### ISSUE THREAD

**Issue by WhiteD1** [hexlet-codebattle/codebattle#1610]
### Summary

На странице профиля пользователя "My profile" слова "Lost" и "Gave Up" выходят за края поля и обрезаются на устройствах iPhone 12/13 Pro Max iOS 14.6 как в вертикальном, так и в горизонтальном режиме

![Issue_2](https://github.com/hexlet-codebattle/codebattle/assets/109975129/ac9061ab-2767-48b3-9355-7cf72827d226)

![Issue_3](https://github.com/hexlet-codebattle/codebattle/assets/109975129/ce4f5e58-697f-49ef-8126-5d73bd7339af)

### Reproduction steps

```bash
- Открыть страницу сайта https://codebattle.hexlet.io и авторизоваться
- В выпадающем меню пользователя перейти на страницу "My profile"
- Открыть DevTools
- Выбрать Режим адаптивного дизайна и устройства iPhone 12/13 Pro Max iOS 14.6
```

### Expected result

Слова "Lost" и "Gave Up" переносятся

### Actual result

Слова "Lost" и "Gave Up" выходят за края и отображаются не полностью

### Browsers

Safari

**Comment by ReDBrother** [comment]
Дубль от https://github.com/hexlet-codebattle/codebattle/issues/1488
