### ISSUE TITLE
Bug: не обновляется имя в чате

### ISSUE THREAD

**Issue by nonambarneo** [hexlet-codebattle/codebattle#1614]
### Summary

Если пользователь оставил сообщение в чате, а после изменил имя профиля, то при копировании имени из чата будет копироваться новое имя, а не то, что в чате
![bug1](https://github.com/hexlet-codebattle/codebattle/assets/134539313/af293919-dd43-47b9-b0b1-7abd0b8a5abf)

### Reproduction steps

```bash
Авторизуемся на сайте
Пишем сообщение в чат
Меняем имя своего профиля
Возвращаемся на главную странцу
Копируем имя из чата функцией "Copy name"
```

### Expected result

Скопируется имя из чата

### Actual result

Копируется актуальное имя профиля

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
@vtm9 Если захочешь, то это беку нужно будет все сообщения пофиксить по факту смены ника)))

**Comment by shaolanx** [comment]
По-моему это не баг, а фича, ну т.е. не получится написать на уже неактуальный ник пользователя, будешь писать на тот что у него в данный момент.

**Comment by ReDBrother** [comment]
Свяжем с этим тикетом - #1624
