### ISSUE TITLE
Bug: Ошибка сервера при попытке начать матч-реванш после таймаута, при игре с другим игроком

### ISSUE THREAD

**Issue by fidilly** [hexlet-codebattle/codebattle#1616]
### Summary

Невозможно начать матч-реванш после таймаута при игре с другим игроком.

### Reproduction steps

```bash
1. Нажать на кнопку "Create a game"
2. Выбрать тип игры "With other users"
3. Установить таймер на 3 минуты
4. Нажать на кнопку "Create battle"
5. Нажать на кнопку "Fight" на главной странице с другого аккаунта
6. Дождаться окончания таймера
7. Нажать на кнопку "Rematch"
```

### Expected result

Игра перезапуститься

### Actual result

Сервер выдает ошибку: "Server is temporarily unavailable ¯\_(ツ)_/¯ :prod_is_down:"
![image](https://github.com/hexlet-codebattle/codebattle/assets/36198217/088a366f-276a-48ef-b3a0-17fb8d646e4e)

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by ElenaRedkina89** [comment]
Summary
Невозможно начать матч-реванш после таймаута при игре с другим игроком.

Reproduction steps
1. Нажать на кнопку "Create a game"
2. Выбрать тип игры "With other users"
3. Установить таймер на 3 минуты
4. Нажать на кнопку "Create battle"
5. Нажать на кнопку "Fight" на главной странице с другого аккаунта
6. Дождаться окончания таймера
7. Нажать на кнопку "Rematch"
Expected result
Игра перезапуститься

Actual result
Сервер выдает ошибку: "Server is temporarily unavailable ¯_(ツ)_/¯ :prod_is_down:"
![Ошибка сервера при попытке начать матч-реванш после таймаута, при игре с другим игроком](https://github.com/hexlet-codebattle/codebattle/assets/139364594/3dbb9ad4-94ce-4799-8fda-7eb6360baf34)

Browsers
Яндекс 

OS
Mac

**Comment by ReDBrother** [comment]
Рематч доступен только в активных играх. Если в игру долго не играть, мы утилизируем их, чтобы не тратить наши ресурсы. В сохраненных играх уже не может быть механизма рематча - считаем что пользователи уже давно решили не продолжать играть
