### ISSUE TITLE
Bug: Отсутствие кнопки назад после просмотра записи завершенных игр 

### ISSUE THREAD

**Issue by Midire99** [hexlet-codebattle/codebattle#1623]
### Summary

После просмотра записи завершенной игры можно только вернуться на главную страницу, чтобы просмотреть записи других игр, нужно снова перейти в "завершенные игры".

### Reproduction steps

```bash
1. Открываем "Завершенные игры"
2. Выбираем игру для просмотра
3. После просмотра не можем вернуться в "Завершенные игры"
```

### Expected result

Присутствует кнопка "Назад"

### Actual result

Присутствует только кнопка "Домой"

### Browsers

Safari

### OS

Mac

**Comment by mwmrv** [comment]
environment: 
Safari Версия 15.2 (17612.3.6.1.6)
Mac OS Monterey 12.1
Codebattle Current version:  ef4c0b9  (https://github.com/hexlet-codebattle/codebattle/commit/ef4c0b9710105f1cd878f8231195d43da590d11d)

1. Заходим в свой профиль
2. В лобби выбираем вкладку Completed games
3. Нажимаем Show в первой строчке списка

Ожидаемый результат:
Есть кнопка "Назад" для возвращения к списку завершенных игр

Полученный результат:
Есть кнопка "Домой",  нет кнопки "Назад"
<img width="1440" alt="Снимок экрана 2023-10-04 в 17 32 31" src="https://github.com/hexlet-codebattle/codebattle/assets/81579368/20e478b2-b5ab-421f-b98f-abbb021ba80f">
<img width="1440" alt="Снимок экрана 2023-10-04 в 17 32 23" src="https://github.com/hexlet-codebattle/codebattle/assets/81579368/13ba3cbd-d0a3-4073-ade5-c40366d43aac">

**Comment by ElenaRedkina89** [comment]
Баг воспроизводится

environment: 
Chrome 117.0.5938.132(Официальная сборка) (64 бит) 
Windows 10 
Codebattle Current version: https://github.com/hexlet-codebattle/codebattle/commit/ef4c0b9710105f1cd878f8231195d43da590d11d

prerequisites: 
Открыта страница записи игры

expected-result: 
Присутствует кнопка "Назад" для возвращения к списку завершенных игр

actual-result: 
Присутствует только кнопка "Домой"
![Отсутствие кнопки назад после просмотра записи завершенных игр](https://github.com/hexlet-codebattle/codebattle/assets/139364594/55f6e43d-4740-4697-8ac4-787942350b83)

**Comment by ReDBrother** [comment]
Это не баг, мы всегда открываем конкретную игру. В планах нет сделать историю записей всех игр - по хорошему, это не должно быть вообще общедоступно, потому что можно подсмотреть решение задачи и иметь преимущество перед другими игроками
