### ISSUE TITLE
Bug: Кнопка выбора смайла не активна

### ISSUE THREAD

**Issue by w1nson007** [hexlet-codebattle/codebattle#1626]
### Summary

При нажатии на кнопку смайла в чате, кнопка не активна, смайл не выбирается

### Reproduction steps

```bash
1.Входим в личный кабинет
2.В строке чата нажимаем на смайл
```

### Expected result

Появляется возможность выбрать смайл из предоставленных вариантов и отправить в чат

### Actual result

Кнопка смайла не активна

### Browsers

Firefox, Chrome, Opera

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1291
