### ISSUE TITLE
Bug: едет верстка после создания турнира в мобильной версии 

### ISSUE THREAD

**Issue by ygracoord** [hexlet-codebattle/codebattle#1635]
### Summary

После создания турнира в мобильной версии сайта, страница отображается некорректно, верстка плывет, появляется горизонтальная полоса прокрутки

### Reproduction steps

```bash
1. Авторизоваться на сайте используя мобильное устройтсво
2. Перейти на вкладку "TOURNAMENTS"
3. Кликнуть на ссылку "Tournaments Info"
4. В разделе "Create a new tournament" нажать кнопку "Create"
```

### Expected result

Страница отображается корректно, нет горизонтальной полосы прокрутки, все элементы на странице расположены четко, ничто никуда не сьезжает

### Actual result

![Screenshot from 2023-10-20 13-33-50](https://github.com/hexlet-codebattle/codebattle/assets/95632838/99e6d788-e6fb-48f0-821e-84645a97d702)
![Screenshot from 2023-10-20 13-33-59](https://github.com/hexlet-codebattle/codebattle/assets/95632838/06a3f37f-402a-42ab-befa-6ef5d5008c38)
![Screenshot from 2023-10-20 13-34-11](https://github.com/hexlet-codebattle/codebattle/assets/95632838/2ebc0845-3373-44ae-81c0-cee7d00e6cb7)

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by ReDBrother** [comment]
Дубль от #1486, ишью для всех багов с адаптивностью турниров
