### ISSUE TITLE
Bug: Current version ломает границы при ширине экрана меньше 465

### ISSUE THREAD

**Issue by pro0om** [hexlet-codebattle/codebattle#1642]
### Summary

При ширине экрана  465 и меньше "Current version " остается на месте, а сама страница сужается и остается черная полоса справа

### Reproduction steps

```bash
1. https://codebattle.hexlet.io/#lobby
2. DevTools
3. Мобильная версия (Samsung Galaxy a51)
```

### Expected result

Адаптация сайта прошла успешно

### Actual result

[Current version: 9500f74](https://github.com/hexlet-codebattle/codebattle/commit/9500f74ca5b14a73d1d09e638c9a6888f80d952f)

deployedAt UTC: 2023-10-27 10:09:15

Имеет свои границы 
Начиная с ширины экрана меньше 465 "Версия" остается на своем месте, а сайт сужается 

![Screenshot (30)](https://github.com/hexlet-codebattle/codebattle/assets/132218049/4cdfa3b9-fd4d-4b51-ac83-5a78e0b4683b)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Fixed
