### ISSUE TITLE
Bug: Создается турнир задним числом

### ISSUE THREAD

**Issue by pro0om** [hexlet-codebattle/codebattle#1643]
### Summary

Возможно создать новый турнир в прошлом

### Reproduction steps

```bash
1. Нажать "tournaments"
2. Нажать "You may want to create one"
3. Указать дату прошлого
4. Нажать "Create"

```

### Expected result

Должно запретить создавать турнир в прошлом

### Actual result

Турнир создан
![Screenshot (31)](https://github.com/hexlet-codebattle/codebattle/assets/132218049/4662c922-bb9b-459f-8922-e9fea41b4dd6)
![Screenshot (33)](https://github.com/hexlet-codebattle/codebattle/assets/132218049/c84f1d9d-fe34-4ecf-b3d8-d8ae48df1019)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Время начала турнира очень условное - оно нужно только для того чтобы выставить таймер для зрителей. Он не влияет на начало турнира

**Comment by MziyaUsubova** [comment]
Заднее установление времени может создать путаницу у зрителей и снизить интерес к трансляции, поскольку они могут пропустить начало соревнований. Важно, чтобы зрители были информированы заранее и могли настроиться на начало турнира. Если предусмотрена эта возможность для зрителей, надо ее реализовать четко.
Ненадлежащее управление временем начала турнира может негативно сказаться на рейтинге проекта и разработчиков

**Comment by MziyaUsubova** [comment]
> Время начала турнира очень условное - оно нужно только для того чтобы выставить таймер для зрителей. Он не влияет на начало турнира

Не согласна.  Время начала турнира на сайте играет важную роль, так как определяет, когда участники должны быть готовы к началу соревнования. Оно также служит для информирования зрителей о времени начала события.
