### ISSUE TITLE
Bug: При регистрации не работает валидация на ограничение на количество символов более 15 в поле "Password"

### ISSUE THREAD

**Issue by Mimicry56** [hexlet-codebattle/codebattle#1644]
### Summary

Баг переоткрыт #1429 
При регистрации пользователь может зарегистрировать пароль более 15 символов

### Reproduction steps

```bash
1. Открыть https://codebattle.hexlet.io/users/new?locale=en&next=%2F
2. В поле "Nickname" вводим qwertyuiopasdfg2
3. В поле "Email" вводим closedoor32@mail.ru
4. В поле "Password" 1234567890123456
5. В поле "Password Confirmation" вводим тот же пароль
6. Нажимаем на кнопку "Submit"
```

### Expected result

Пользователь не может зарегистрировать пароль более 15-ти символов, под полем "Password" появляется предупреждение, информирующее о том, что пароль должен состоять из 6-15 символов

### Actual result

Регистрация успешно произошла

### Browsers

Chrome

### OS

Windows

**Comment by smrkov** [comment]
При регистрации пользователь может зарегистрировать пароль более 15 символов

Открыта главная страница https://codebattle.hexlet.io

1. Нажать кнопку "Sign up"
2. В поле "Nickname" вводим Asdfghyt
3. В поле "Email" вводим Asdfgh@yandex.ru
4. В поле "Password" 12365434567890876543
5. В поле "Password Confirmation" вводим тот же пароль
6. Нажимаем на кнопку "Submit"

Expected result
Пользователь не может зарегистрировать пароль более 15-ти символов, под полем "Password" появляется предупреждение, информирующее о том, что пароль должен состоять из 6-15 символов

Actual result
Регистрация успешно произошла

Browsers
Yandex Версия
23.9.3.931 (64-bit)

OS
Windows 11

**Comment by ReDBrother** [comment]
Ребят, там в оригинальном ишью (последний комментарий) говорится что верхний предел это 16 символов и он сохраняется)
Ишью закрываю

**Comment by 4Jul** [comment]
При тестировании этого кейса, видно, что указанные требования к полю "Пароль" работают: при попытке ввести пароль длиннее 16 символов, выходит ошибка 
![issue 5](https://github.com/hexlet-codebattle/codebattle/assets/142840489/0b5326ce-5e04-46a4-a30c-66f5a6e26a73)
