### ISSUE TITLE
Bug: При нажатии кнопки Show завершенных турниров типа  (type) "team" открывается пустая страница

### ISSUE THREAD

**Issue by ASvetikova** [hexlet-codebattle/codebattle#1645]
![пустая страница](https://github.com/hexlet-codebattle/codebattle/assets/138698674/c598361f-0cf6-402f-be73-bd622815032f)
![не открываются](https://github.com/hexlet-codebattle/codebattle/assets/138698674/808146db-9e79-458c-8f5a-c5a6cdae1209)
### Summary

При просмотре завершенных турниров с Type "team" ничего не происходит, открывается пустая страница
environment: |
Google Chrome 107.0.5304.121 (Официальная сборка) (64 бит)
ОС MacOS Monterey 12.6.7
Current version: [a7bca01]

### Reproduction steps

```bash
1) Перейти на вкладку TOURNAMENTS https://codebattle.hexlet.io/#tournaments
2) Выбрать завершенный турнир для просмотра со типом (type) "team"
```

### Expected result

Пользователю открывается турнир для его просмотра 

### Actual result

Ничего не происходит, выходит пустая страница 

### Browsers

Chrome

### OS

Mac

**Comment by ArturNut** [comment]
# Summary

Действительно при просмотре прошедших груповых туриров открывается пустая страница

Current version Codebattle: https://github.com/hexlet-codebattle/codebattle/commit/a7bca01f50e9ee1e85b1c8438dfbd7afbe635e45

![empty page](https://github.com/hexlet-codebattle/codebattle/assets/68311979/e0dc8e9f-3c8e-4540-8836-15623b551b0b)

# Reproduction steps

На странице пользователя в таблице "Completed tournaments"  для Type team нажимаем на кнопку "Show" (смотри картинку)

# Expected result

Пользователь помет просмотреть прошедшие турниры Type team

# Actual result

Открывается пустая страница

# Browsers

Crome

# OS

Windows

**Comment by ReDBrother** [comment]
Пофиксили
