### ISSUE TITLE
Bug:  Не работает адаптивность редактора игры 

### ISSUE THREAD

**Issue by angelo4ek59** [hexlet-codebattle/codebattle#1648]
### Summary

Браузер Microsoft Edge автоматически переводит страницу игры, в связи с чем не корректно работает адаптивность при смене фона редактора игры. 

### Reproduction steps

```bash
- Визуально просматриваем редактор игры фон темный (страница игры автоматически переведена)
- Нажимаем на кнопку "светлый"
- Визуально просматриваем редактор игры
```

### Expected result

![Успешная адаптивность редактора игры_1](https://github.com/hexlet-codebattle/codebattle/assets/140711465/701c54a1-8b56-441c-bc2c-cf938d5262e5)

### Actual result

![Успешная адаптивность редактора игры_0](https://github.com/hexlet-codebattle/codebattle/assets/140711465/5b7d8a83-c31a-4690-9dd7-e0ba153925fa)

**Comment by ReDBrother** [comment]
Тут мы ничего сделать не можем, слишком мало места. Мы сейчас думает как переверстать всю игровую комнату целиком
