### ISSUE TITLE
В My Profile в разделе STATISTICS отсуствует диаграмма

### ISSUE THREAD

**Issue by ArturNut** [hexlet-codebattle/codebattle#1651]
### Summary

Ссылка на Bug: #1545 

Current version Codebattle: https://github.com/hexlet-codebattle/codebattle/commit/684cda2e170cf4bbece51d83a90b12f60bfe107e

![My Profile  STATISTICS](https://github.com/hexlet-codebattle/codebattle/assets/68311979/be2f626b-9e1a-4f9a-841c-11caef77ab77)

### Reproduction steps

```bash
1. В шапке на странице пользователя нажимаем на NickName
2. Выбираем "My Profile"
```

### Expected result

На странице My Profile есть диаграмма (смотри картинку)

### Actual result

На странице My Profile нет диаграммы (смотри картинку)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Скорее должно быть наоборот - это диаграмма должна отсуствовать, если нет сыгранных игр)

**Comment by ReDBrother** [comment]
Это не баг - это фича)
Одна игра со статусов give up так и отображается на диаграмме)
