### ISSUE TITLE
Bug:  Обрезаны изображения на страницах LOBBY,  TOURNAMENTS,  COMPLETED GAMES в мобильной версии сайта

### ISSUE THREAD

**Issue by Nastia1385** [hexlet-codebattle/codebattle#1652]
### Summary

При пролистывании данных на страницах LOBBY,  TOURNAMENTS,  COMPLETED GAMES в мобильной версии с помощью кнопок < > данные отображаются в обрезанном виде ( часть предыдущих данных и часть текущих данных). Тестирование адаптивности проводилось на ноутбуке с помощью DevTools.
Данные для тестирование:
- экран телефона в вертикал ном положении
- браузер Yandex  Версия 23.9.3.931 (64-bit)
- модели телефонов выбранные для тестирования : 
    Galaxy Note 20:landscape Android 11  width 412 height 915
     Galaxy S10/S10+:landscape  Android 11  width 360 height 760
     Pixel 5 landscape  Android 11  width 393 height 851
     iPhone 6/7/8:landscape iOS 11 width 375 width 667
     iPhone 6/7/8 Plus:landscape iOS 11 width 414 height 736
     iPad Pro (12.9-inch):landscape iPadOS 14.7.1 height 1024 width1366
     Realme 9 Pro 5G: Android 13, Модель RMX3472, размер экрана 6,59
-  версия Codebattle [Current version: 684cda2](https://github.com/hexlet-codebattle/codebattle/commit/684cda2e170cf4bbece51d83a90b12f60bfe107e)
deployedAt UTC: 2023-11-04 17:14:44

### Reproduction steps

```bash
1. Открыть сайт Codebattle 
2. Открыть DevTools
3. Открыть Network
4. Нажать Ctrl+Shift+M
5. Нажать Dimensions Responsive
6. Выбрать из списка телефон 
7. На странице LOBBY несколько раз нажать кнопку >
8. Нажать на TOURNAMENTS
9. На странице TOURNAMENTS несколько раз нажать кнопку >
10. Нажать на COMPLETED GAMES
11. На странице COMPLETED GAMES несколько раз нажать кнопку >
```

### Expected result

При пролистывании данных с помощью кнопок < > на страницах LOBBY,  TOURNAMENTS,  COMPLETED GAMES в мобильной версии просматриваемая информация отображается полностью и чётко.

### Actual result

При пролистывании данных с помощью кнопок < > на страницах LOBBY,  TOURNAMENTS,  COMPLETED GAMES в мобильной версии просматриваемая информация отображается в обрезанном виде .
![1](https://github.com/hexlet-codebattle/codebattle/assets/142580036/94933fa7-08bd-4d8b-be0a-5e711b13ecf5)
![2](https://github.com/hexlet-codebattle/codebattle/assets/142580036/cc611dde-bb74-4734-905c-a7d7851dc51c)
![3](https://github.com/hexlet-codebattle/codebattle/assets/142580036/64246a0d-837e-40b6-88f9-37a2d2d6faec)

### OS

Windows

**Comment by rthreyn6** [comment]
summary: |

Верстка страницы съезжает, кнопки обрезаются, текст выходит за рамки экрана при тестировании сайта с помощью  DevTools

environment: |
Google Chrome Версия 119.0.6045.200 (Официальная сборка), (64 бит)
Windows 11 Pro 23H2
Codebattle Current version: 3d3d57f


prerequisites: |
Пользователь находится в лобби

Reproduction steps:
- Открыть DevTools
- Нажать на кнопку "Toggle device toolbar" в верхнем левом углу
- Выбираем устройства с различными расширениями экрана
   Ipad Mini
   IPhone XR
   Nest Hub
   Samsung Galaxy A51/71

expected-result: |
Сайт отображается корректно, верстка не съезжает, текст не выходит за рамки экрана

actual result:
Страница сайта не адаптирована под различные разрешения экранов, верстка съезжает, текст выходит за рамки экрана

![samsung](https://github.com/hexlet-codebattle/codebattle/assets/145046750/ff2b7dc2-2644-4ffd-94c4-345ee8829d79)
![IPad Mini](https://github.com/hexlet-codebattle/codebattle/assets/145046750/5a904de3-f707-4080-9f58-87fb6ab5fb08)

**Comment by ReDBrother** [comment]
Мы не будем строить сложное поведение скролла карточек. Очень много сайтов работает по текущей схеме, скролл по кнопке переворачивает видимую часть, а не просто перекидывает на следующую карточку. Это не баг, а фича)
