### ISSUE TITLE
Bug: Выбор рандомной задачи при игре "With a friend" при выборе конкретной задачи

### ISSUE THREAD

**Issue by IgorUlitin** [hexlet-codebattle/codebattle#1656]
### Summary

При выборе "Game Type" = "With a friend" и выборе конкретной задачи "Choose task by name or tags" при входе в игру отображается рандомная задача

### Reproduction steps

```bash
1. Авторизоваться в браузере Firefox
2. Авторизоваться в браузере Chrome под другой учетной записью
3. Нажать кнопку "CREATE A GAME"
4. Во всплывающем окне выбрать "Game Type" = "With a friend"
5. В окне "Select..." формы "Choose opponent" ввести никнейм учетной записи Firefox
6. Во всплывающем списке формы "Choose opponent" выбрать никнейм учетной записи Firefox
7. Во всплывающем списке формы "Choose task by name or tags" выбрать конкретную задачу
8. Нажать кнопку "Create invite"
9. Перейти в браузер Firefox
10. Нажать на кнопку "Invites" (скрещенные мечи)
11. Нажать кнопку "Accept"
12. Сравнить выбранную задачу с загруженной задачей
```

### Expected result

Задачи совпадают

### Actual result

Задачи не совпадают
<img width="699" alt="Снимок экрана 2023-11-13 в 19 52 48" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/bbf7f98a-8eee-4295-882a-d92f21c041f0">
<img width="1492" alt="Снимок экрана 2023-11-13 в 19 54 34" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/b7fc48ac-90dc-4fb3-8144-d7468418a517">

Current version

c9988e0

### Browsers

Firefox 119.0.1 (64-разрядный)
Chrome Версия 119.0.6045.123 (Официальная сборка), (arm64)

### OS

Mac

**Comment by ReDBrother** [comment]
fixed
