### ISSUE TITLE
Bug: Не подсвечивается поле формы авторизации при вводе незарегистрированного email

### ISSUE THREAD

**Issue by IgorUlitin** [hexlet-codebattle/codebattle#1657]
### Summary

При вводе в поле "Email" формы авторизации незарегистрированного email и попытке авторизации - поле "Email" не подсвечивается

### Reproduction steps

```bash
1. Открыть страницу авторизации "https://codebattle.hexlet.io/session/new?locale=en&next=%2F"
2. Ввести незарегистрированный email
3. Ввести в поле "Password" от 6 до 16 символов
4. Нажать кнопку "Submit"
```

### Expected result

Поле "Email" подсвечивается красным

### Actual result

Поле "Email" не подсвечивается красным
<img width="583" alt="Снимок экрана 2023-11-13 в 20 12 59" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/1b7900f6-4713-4a72-9a6d-35b931e94828">

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
Cложим с #1658
