### ISSUE TITLE
Bug: Получена ошибка сервера и не подсветилось поле при вводе email незарегистрированного пользователя

### ISSUE THREAD

**Issue by IgorUlitin** [hexlet-codebattle/codebattle#1658]
### Summary

При вводе в поле "Email" формы авторизации незарегистрированного email и попытке авторизации получена ошибка сервера вместо ошибки валидации и поле не подсветилось красным

### Reproduction steps

```bash
1. Открыть страницу авторизации "https://codebattle.hexlet.io/session/new?locale=en&next=%2F"
2. Ввести незарегистрированный email
3. Ввести в поле "Password" от 6 до 16 символов
4. Нажать кнопку "Submit"
```

### Expected result

Получена ошибка валидации, поле подсвечено красным

### Actual result

Получена ошибка сервера, поле не подсвечено красным
<img width="915" alt="Снимок экрана 2023-11-14 в 12 48 15" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/feebe7c0-adad-41ad-aa52-30b80f7bd33e">

Current version

c9988e0

### Browsers

Chrome Версия 119.0.6045.123 (Официальная сборка), (arm64)

### OS

Mac

**Comment by po1inakoroleva** [comment]
Беру в работу

**Comment by Salim123Salim** [comment]
Версия 120.0.6099.217 (Официальная сборка), (64 бит)
ОС: Windows
![Uploading Снимок экрана 2024-01-17 151445.png…]()

**Comment by Salim123Salim** [comment]
![Uploading Снимок экрана 2024-01-17 151445.png…]()

**Comment by Salim123Salim** [comment]
Google Chrome Версия 120.0.6099.217 (Официальная сборка), (64 бит)
Windows 11 22H2

**Comment by Salim123Salim** [comment]
![Uploading Снимок экрана 2024-01-17 152330.png…]()

**Comment by VictorKuzenkin** [comment]
Баг актуален в версии 10f1d0a, браузер Google Chrome Версия 121.0.6167.140 (Официальная сборка), (64 бит)
OS Windows 11 Home

## Summary

При вводе незарегистрированного email на странице авторизации приходит сообщение об ошибке сервера (422), а поле email не подсвечивается красным.

![Незарегистрированный email](https://github.com/hexlet-codebattle/codebattle/assets/144316874/8f522115-5e1e-4d5e-b67b-3ff4f9d3156b)
