### ISSUE TITLE
Bug: Возможен ввод пароля на русском в мобильном браузере

### ISSUE THREAD

**Issue by IgorUlitin** [hexlet-codebattle/codebattle#1659]
### Summary

В мобильном браузере можно ввести пароль на русском, в то время как в браузере на ПК нет возможности переключения языка

### Reproduction steps

```bash
1. Открыть страницу регистрации в браузере на ПК "https://codebattle.hexlet.io/users/new?locale=en&next=%2F"
2. Нажать на поле "Password"
3. Переключить язык на русский
4. Открыть страницу регистрации в мобильном браузере Safari "https://codebattle.hexlet.io/users/new?locale=en&next=%2F"
5. Нажать на поле "Password"
6. Переключить язык на русский
```

### Expected result

В мобильном браузере язык при вводе пароля изменить невозможно

### Actual result

В мобильном браузере язык при вводе пароля изменить возможно
<img width="699" alt="Снимок экрана 2023-11-13 в 20 38 11" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/68b2e75f-1fe5-4494-9ce7-53f229f58c52">

Current version

c9988e0

### Browsers

Safari Версия 17.1 (19616.2.9.11.7)

### OS

Mac

**Comment by ReDBrother** [comment]
Не очень понял как мы можем воздействовать на виртуальную клавиатуру мобильного браузера)

**Comment by IgorUlitin** [comment]
@ReDBrother а на физическую клавиатуру пк? Просто зарегистрироваться с русским паролем с мобилки можно, а на пк его ввести возможности нет кроме как ctrl+paste. Если я например изменю этот баг как невозможность переключиться на русский с физической клавиатуры пк?

**Comment by ReDBrother** [comment]
Ничего не понял) Клавиатура полностью находится по контролем пользователя и только у пользователя.
Это точно не связано с нашим приложением
