### ISSUE TITLE
Bug: Обрезана форма обратной связи при горизонтальном расположении страницы в мобильном приложении

### ISSUE THREAD

**Issue by IgorUlitin** [hexlet-codebattle/codebattle#1660]
### Summary

Обрезано всплывающее окно формы обратной связи при горизонтальном расположении страницы в мобильном приложении

### Reproduction steps

```bash
1. Авторизоваться "https://codebattle.hexlet.io/session/new?locale=en&next=%2F"
2. Нажать кнопку "CREATE A GAME"
3. Во всплывающем окне выбрать "Game Type" = "With a bot"
4. Нажать кнопку "Create battle"
5. Нажать на кнопку "Send Feedback"
```

### Expected result

Всплывающее окно отображается полностью

### Actual result

Всплывающее окно отображается не полностью
<img width="839" alt="Снимок экрана 2023-11-14 в 12 20 47" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/c10ef1a7-89d3-44b1-918e-56521213ea34">
<img width="1258" alt="Снимок экрана 2023-11-14 в 12 28 32" src="https://github.com/hexlet-codebattle/codebattle/assets/115343794/b2cd3caf-5a3e-4792-b8af-bc4faca128d2">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Форма обратной связи не наша. Мы не можем контролировать разработку чужих решений
