### ISSUE TITLE
Bug: Таймер игры отображает некорректное время при игре с другом

### ISSUE THREAD

**Issue by DariaLeo13** [hexlet-codebattle/codebattle#1662]
### Summary

При игре с другим пользователем таймер оставшегося времени игры отображается некорректно для пользователя, если на его девайсе установленное время отстает или спешит на несколько минут по сравнению глобальным временем и не установлена синхронизация времени. 
Если часы на девайсе пользователя отстают, отображается больше времени, чем было задано изначально (например, 15 минут вместо 10), если часы спешат, то отображается меньше времени на разницу минут (например, 5 минут вместо 10).

Версия игры [Current version: c9988e0](https://github.com/hexlet-codebattle/codebattle/commit/c9988e01cfc5ccd00b6ccc01f153f68024699291)
Chrome 119.0.6045.134
Android 13; SM-G990B Build/TP1A.220624.014

### Reproduction steps

```bash
1. Отключить автоопределение времени и синхронизацию времени на девайсе пользователя №1
2. Перевести время на девайсе пользователя на 5 минут назад
3. Открыть браузер и залогиниться за пользователя №1 на сайте с данного девайса
4. Открыть браузер на другом девайсе и залогиниться за пользователя №2
5. Нажать на Create a game
6. Выбрать Game type - With a friend
7. Выбрать в списке пользователей пользователя №2
8. Установить время Time control на 10 минут
9. Выбрать любую сложность и любую задачу
10. Нажать Create battle
11. Принять приглашение Invite на игру пользователем №2
```

### Expected result

Для пользователя №1 при начале игры время на таймере должно отображаться истекающим с отметки 10 минут

### Actual result

Для пользователя №1 при начале игры время на таймере отображается истекающим с отметки 15 минут
![issue2-1](https://github.com/hexlet-codebattle/codebattle/assets/145145773/8d51a025-8ff3-4078-9115-2f1358d7cdbc)
![issue2-2](https://github.com/hexlet-codebattle/codebattle/assets/145145773/a6120d06-3a5e-495d-b816-0a5c7643c55f)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это будет очень сложная для реализации задача. Если мы с концами перейдем на трансляцию времени с бекенда, нам нужно очень много времени убить на постоянные синхронизации (таймер может отставать) и правильно реагировать на любые обрывы связи.

**Comment by rthreyn6** [comment]
summary: |
    Проверка работы таймера игры

 environment: |
 Google Chrome Версия 119.0.6045.200 (Официальная сборка), (64 бит)
 Windows 11 Pro 23H2
 Codebattle Current version: 6201d97

  prerequisites: |
    Пользователь находится в лобби

  steps: |
    - Нажать кнопку "CREATE A GAME"
    - Выбрать уровень сложности "Level"
    - Выбрать тип игры "With a bot"
    - Выставить длительность игры "8 min"
    - Выбрать задачу по названию или тегам "Choose task by name or tags"
    - Нажать на кнопку "Create battle"
  expected-result: |
    Пользователь видит таймер, который начинается с 00:08:00

 actual result:
  Время начинается на 5 секунд меньше
![Время](https://github.com/hexlet-codebattle/codebattle/assets/145046750/241c4a49-91eb-451b-97d9-bd343e338930)

**Comment by Elena-Yakovleva** [comment]
При создании новой игры, как с ботом, так и с другим игроком, таймер прибавляет к времени 5 мин. 30 сек.
В случае если дополнительное время дается на то, чтобы оба игрока подготовились к бою, то в этом случае стоит заблокировать поле редактора до момента отсчета таймером времени поединка, для того, чтобы поставить обоих игроков в равные условия.  Сейчас время поединка просто увеличивается и дополнительное время можно использовать для написания кода.

Current version: dbd0d89

-summary: |
   Таймер игры прибавляет дополнительное время к выбранному  при игре с ботом.
 environment: |
   PC Windows 11 Домашняя для одного языка. Версия 22H2. Сборка ОС 22621.3007
   Google Chrome Версия 120.0.6099.216 (Официальная сборка), (64 бит)
 prerequisites: |
   Открыть меню создания новой игры.
 steps:
   -   Выбрать "Level" - 1 звеpда.
   -   Выбрать "Game Type" - кнопка  "With a bot".
   -   Выбрать "Time control"- 8 минут.
   -   Выбрать задачу ("Choose task by name or tags") - polygon_angles_sum.
   -   Нажать на кнопку "Create battle".
actual result:
 Игра должна начаться с выбранного при создании времени - 8:00

-summary: |
   Таймер игры прибавляет дополнительное время к выбранному  при игре с другим игроком.
 environment: |
   PC Windows 11 Домашняя для одного языка. Версия 22H2. Сборка ОС 22621.3007
   Игрок 1 - Google Chrome Версия 120.0.6099.216 (Официальная сборка), (64 бит) 
   Игрок 2 - Microsoft Edge  Версия 120.0.2210.121 (Официальная сборка) (64-разрядная версия)
 prerequisites: |
   Открыть меню создания новой игры Игроком 1.
 steps:
   -   Выбрать "Level" - 1 звеpда.
   -   Выбрать "Game Type" - кнопка  "With a friend".
   -   Выбрать "Time control"- 8 минут.
   -   Выбрать задачу ("Choose task by name or tags") - polygon_angles_sum.
   -   Нажать на кнопку "Create battle".
   -   Принять игру игроком 2.
   -   Проверить отображение времени на таймере игры.
actual result:
 Игра должна начаться с выбранного при создании времени - 8:00

<img width="1082" alt="Снимок экрана 2024-01-10 -1" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/66b0428c-e960-40a8-aa05-791d36666b1d">
<img width="1227" alt="Снимок экрана 2024-01-10 -2" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/08a94e71-ceb0-4bd8-b154-36b71a6497fb">
<img width="1034" alt="Снимок экрана 2024-01-10 -3" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/c93ca0d3-a2f3-4099-bdd6-8b9cb425e3b1">
<img width="1199" alt="Снимок экрана 2024-01-10 -4" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/6ecb7876-09ae-4097-840d-e1e1fcb3ea9f">
<img width="1248" alt="Снимок экрана 2024-01-10 -5" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/a9bf44b3-7ca6-4ba2-bb9f-2273c63051ba">

**Comment by ReDBrother** [comment]
Ребят, изначальная проблема что мы ориентируемся на локальное время каждого пользователя в интерфейсе каждого. На сервере у игры время общее и оно для всех равное, без каких либо доп времени на условие задачи. Мы не будем вводить такой режим отсмотра - когда игра началась, то она началась

**Comment by ReDBrother** [comment]
Если переходить к оригинальному ишью, то некорректное время настроенное на компе/ноуте пользователя влияет на все наши таймеры. Так все наши таймеры работают - берут время начала и длительность матча, после чего время начала множится на текущую таймзону пользователя и сравнивается с настроенным временем у пользователя.

Именно разница с локальным временем пользователя и берется за основу того, сколько времени осталось до конца матча.

Альтернатива такому подходу будет сразу выдавать временную шкалу до окончание процесса, но это сильно будет завязано на скорости сети у пользователя. При высоком пинге у всех пользователей таких пользователей не будет корректного таймера.

**Comment by ReDBrother** [comment]
Решением будет просить пользователя настроить свои часы)
На механику игры эта деталь не влияет)
