### ISSUE TITLE
Bugreport: 

### ISSUE THREAD

**Issue by Evgenii-Stepanov** [hexlet-codebattle/codebattle#1664]
### Summary

https://github.com/hexlet-codebattle/codebattle/issues/1660

### Reproduction steps

```bash
1. Авторизоваться "https://codebattle.hexlet.io/session/new?locale=en&next=%2F"
2. Нажать кнопку "CREATE A GAME"
3. Во всплывающем окне выбрать "Game Type" = "With a bot"
4. Нажать кнопку "Create battle"
5. Нажать на кнопку "Send Feedback"
```

### Expected result

![image](https://github.com/hexlet-codebattle/codebattle/assets/128056237/1bbd87b3-ed34-4d45-bc9b-6e3573ff681d)

### Actual result

всё отображается корректно

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Повторю тейк из оригинального тикета:

Форма обратной связи не наша. Мы не можем контролировать разработку чужих решений
