### ISSUE TITLE
Bug: Отсутствует отображение онлайн-статуса пользователя на панели редактора 

### ISSUE THREAD

**Issue by Darejana** [hexlet-codebattle/codebattle#1668]
### Summary

Отсутствует отображение зеленого индикатора онлайн-статуса пользователя возле имени пользователя на панели редактора 

Safari Version 16.5.2 (18615.2.9.11.10)
macOS Ventura 13.4.1 (c)
version: https://github.com/hexlet-codebattle/codebattle/commit/946c18208d84da418858dd1b0d6d866ca4eeb1c0

### Reproduction steps

```bash
- На главной странице нажать “Create a game”
- Выбрать level = 1 звезда
- Выбрать Game Type = With a bot
- Нажать “Create battle”
- Проверить отображение онлайн-статуса пользователя
```

### Expected result

Отображается зеленый индикатор онлайн-статуса пользователя возле имени пользователя на панели редактора 

### Actual result

Отсутствует отображение зеленого индикатора онлайн-статуса пользователя возле имени пользователя на панели редактора 
<img width="1392" alt="Screenshot 2023-11-30 at 13 08 22" src="https://github.com/hexlet-codebattle/codebattle/assets/143718326/087c7ae2-70e2-46a4-a8a0-d115e318a8a8">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
fixed
