### ISSUE TITLE
Bug: Отсутствует отображение никнеймов пользователей в разделе "Online players" на главной странице

### ISSUE THREAD

**Issue by Darejana** [hexlet-codebattle/codebattle#1669]
### Summary

В разделе "Online players" на главной странице сайта не отображаются никнеймы пользователей, которые находятся в статусе "онлайн"

Safari Version 16.5.2 (18615.2.9.11.10)
macOS Ventura 13.4.1 (c)
version: https://github.com/hexlet-codebattle/codebattle/commit/946c18208d84da418858dd1b0d6d866ca4eeb1c0

### Reproduction steps

```bash
- Открыть главную страницу сайта
- Проверить отображение своего никнейма в разделе "Online players"
```

### Expected result

Отображается никнейм пользователя, который находятся в статусе "онлайн" 

### Actual result

Отсутствует отображение никнейма пользователя, который находится в статусе "онлайн"
<img width="1306" alt="Screenshot 2023-11-30 at 13 32 02" src="https://github.com/hexlet-codebattle/codebattle/assets/143718326/783ce408-3764-44d8-8920-313b4734fbcc">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Временно вырубили счетчик онлайна, дубль от #1672
