### ISSUE TITLE
Bug: Ошибка 500 при матч-реванше после проигрыша игры боту

### ISSUE THREAD

**Issue by Eatingsoup** [hexlet-codebattle/codebattle#1671]
### Summary

Появляется ошибка 500 при матч-реванше против игры с ботом

### Reproduction steps

```bash
1. Открыть DevTools
2. Нажать вкладку "Network"
3. Нажать кнопку "CREATE A GAME"
4. Выбрать любой уровень сложности
5. Выбрать "Game Type" = "With a bot"
6. Во всплывающем списке формы "Choose task by name or tags" выбрать любой параметр
7. Нажать кнопку "Create battle"
8. Нажать кнопку "Give Up"
9. Во всплывающем окне нажать кнопку "Give Up"
10. Во всплывающем окне нажать кнопку "I'll be back"
11. Нажать кнопку "Rematch"
```

### Expected result

Игра успешно перезапущена

### Actual result

Открыта страница с ошибкой
![2023-12-04_11-09-37](https://github.com/hexlet-codebattle/codebattle/assets/134435439/4e4b8afc-6159-420f-94f7-5271e2b75564)

### OS

Windows

**Comment by RomaMishchenko** [comment]
Аналогичная ситуация после сдачи игры боту при нажатие реванш ошибка 500
![2023-12-05_18-38-55](https://github.com/hexlet-codebattle/codebattle/assets/149249491/31b2a010-a663-40c7-97f9-718514d427ba)
 os windows 11 браузер хром

**Comment by ReDBrother** [comment]
fixed
