### ISSUE TITLE
Bug: Не отображается кол-во пользователей

### ISSUE THREAD

**Issue by RomaMishchenko** [hexlet-codebattle/codebattle#1672]
### Summary

Графа онлайн всегда = 0 , когда пользователи в онлайн

### Reproduction steps

```bash
1 Открыта страница лобби 
2 Посмотреть графу онлайн
```

### Expected result

Графа онлайн показывает кол-во  игроков на сайте 

### Actual result

Графа онлайн всегда показывает  0
![2023-12-04_16-02-45](https://github.com/hexlet-codebattle/codebattle/assets/149249491/4631f8eb-2e6a-4620-8470-a0a7e79a6eb8)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Временно вырубили счетчик онлайна, скоро вернем обратно)

**Comment by ReDBrother** [comment]
fixed
