### ISSUE TITLE
Bug: Ошибка при выборе языка 

### ISSUE THREAD

**Issue by RomaMishchenko** [hexlet-codebattle/codebattle#1674]
### Summary

Если перевести содержимое сайта с помощью авто перевода встроенного в браузер, то строка выбора языка будет показывать два одинаковых выбора

### Reproduction steps

```bash
1 Открыть завершенные игры 
2 Нажать show 
3 С помощью автоперевода в браузере перевести на русский язык
4 Нажать RU на сайте
```

### Expected result

В графе появиться выбор RU-EN

### Actual result

В графе появиться RU-RU
![2023-12-04_18-51-16](https://github.com/hexlet-codebattle/codebattle/assets/149249491/2e458569-88ca-4907-a37f-2f2386e7be5b)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы не можем управлять автопереводом в браузере)
