### ISSUE TITLE
Bug: При переводе сайта на русский язык не работает переключение в таблице лидеров 

### ISSUE THREAD

**Issue by RomaMishchenko** [hexlet-codebattle/codebattle#1675]
![2023-12-04_21-40-36](https://github.com/hexlet-codebattle/codebattle/assets/149249491/e0b4ff0a-6f3f-4ad6-9ab8-cc9c6beeadaf)
### Summary

Если перевести сайт на русский то в графе таблица лидеров не работает переключение между рейтингом за неделю, месяц и всё время.

### Reproduction steps

```bash
1. Нажать месяц или все
```

### Expected result

Рейтинг перейдёт на топ за месяц или за всё время 

### Actual result

Рейтинг не переходит на на топ за месяц или за всё время  

### Browsers

Сhrome

### OS

Windows

**Comment by ReDBrother** [comment]
Переключение работает, у нас сейчас именно плохо реализована реакция на переключение (Пользователь должен понимать что идет загрузка данных)

**Comment by RomaMishchenko** [comment]
Обратите внимание на скриншот данная функция не переключается только если страница переведена на русский язык

**Comment by ReDBrother** [comment]
Кажется понял, там переводчик в отдельных случая ломает кнопку и начинать слать множественные запросы. Попробуем придумать как обойти эту историю

**Comment by Darga113** [comment]
Summary:
    При переводе на русский язык, не работает переключени в таблице лидеров
Reproduction steps:
    1. Зайти на сайт
    2. Кликнуть правой кнопки мыши
    3.  Выбрать строку "translate to русский"
    4. Нажать месяц,неделя или все
Expected result:
    Рейтинг поменяется на неделю, месяц или все
Actual result:
   Изменения не происходят после нажатия

 Browsers
Сhrome

OS
Windows 10
![Screenshot_16](https://github.com/hexlet-codebattle/codebattle/assets/143105877/d22fbc46-b0d6-48bc-a3a3-fe0572c245a1)

**Comment by jullinn** [comment]
![Снимок экрана 2023-12-10 132258](https://github.com/hexlet-codebattle/codebattle/assets/143704764/cf2cd16e-c7e7-4856-8fac-0b9ea163abfa)
Summary
При переводе главной страницы на русский язык не срабатывает переключение по таблице лидеров

Environment:
Browsers
Chrome Версия 120.0.6099.71 (Официальная сборка), (64 бит)

OS
Windows 11

Codebattle версия https://github.com/hexlet-codebattle/codebattle/commit/3f95dac89cf5b1487ea3f6333c5f74d4a6fa1298.
[Текущая версия: 3f95dac.](https://github.com/hexlet-codebattle/codebattle/commit/3f95dac89cf5b1487ea3f6333c5f74d4a6fa1298)

Steps-to-reproduce:

1. Зайти в аккаунт на странице
2.Кликнуть правой кнопкой мышки на странице

3.Перевести сайт на русский язык

4. Нажать на неделя\месяц\все в таблице лидеров

Expected-result:
При переводе сайта на русский язык должны работать все переключения по таблицам 

Actual-result:
Переключение по таблице лидеров не работает при переводе сайта на русский язык

**Comment by ALexZzZay** [comment]
Проблема воспроизводится на устройствах MacOS:


**Summary:**
При переводе на русский язык, не работает переключени в таблице лидеров

**Reproduction steps:**
1. Зайти на сайт
2. Кликнуть правой кнопки мыши
3. Выбрать строку "translate to русский"
4. Нажать месяц,неделя или все

**Expected result:**
Рейтинг поменяется на неделю, месяц или все

**Actual result:**
Изменения не происходят после нажатия

**Browsers**
Safari LV and Arc LV

**OS**
MacOS Sanoma

**Codbattle version:**
[dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

**Comment by ReDBrother** [comment]
fixed

**Comment by BigZiano** [comment]
Если перевести сайт на русский то в графе таблица лидеров не работает переключение между рейтингом за неделю, месяц и всё время.
Воспроизвел в версии Current version: 6b220bb 
environment: |
Яндекс Браузер Версия 24.1.5.803 (64-bit) Windows 10 Pro Версия 22H2 Сборка ОС 19045.4291
[Current version: 6b220bb]
prerequisites: включен автоматический перевод страниц на Русский язык
steps:
•	Зайти на сайт
•	В таблице "LEADERBOARD" Нажать: месяц,неделя или все
![image](https://github.com/hexlet-codebattle/codebattle/assets/162887947/86583b29-bf26-4e06-9236-ae6ed77697a4)
![image](https://github.com/hexlet-codebattle/codebattle/assets/162887947/c7660be9-07e2-4283-bc41-558decd3edc6)
![image](https://github.com/hexlet-codebattle/codebattle/assets/162887947/95172942-865b-48a9-b793-15508b303ec9)
