### ISSUE TITLE
Bug: Страница TRY SIMPLE BATTLE недоступна с мобильной версии сайта 

### ISSUE THREAD

**Issue by RomaMishchenko** [hexlet-codebattle/codebattle#1676]
### Summary

При переходе по ссылке отправленной в вконтакте, с мобильного устройства на андроид в игру которой не требуется регистрация появляется ошибка HTTP ERROR 431. ( При открытие ссылки на IOS, TRY SIMPLE BATTLE работает)
![1z8Mrv-us1c (1)](https://github.com/hexlet-codebattle/codebattle/assets/149249491/64622a36-b430-4ac2-adf0-f263e1642228)

### Reproduction steps

```bash
1. Перейти на сайт игры по ссылке отправленной Вконтакте   
2. Нажать TRY SIMPLE BATTLE
```

### Expected result

Игра без регистрации откроется в браузере 

### Actual result

Игра без регистрации не открывается в браузере

### Browsers

Chrome

### OS

Android

**Comment by ReDBrother** [comment]
Нужно сбросить локальный кеш мобильного браузера. 431 эта ошибка запроса браузера
