### ISSUE TITLE
Bug: Адаптивность таблицы "завершённые игры"

### ISSUE THREAD

**Issue by RomaMishchenko** [hexlet-codebattle/codebattle#1677]
### Summary

При переводе таблицы на русский язык, кнопки показывать скрываются за рамками.
![2023-12-05_04-17-29](https://github.com/hexlet-codebattle/codebattle/assets/149249491/b6d9acc0-eb2c-453e-be7e-e92b3eefec5e)
  

### Reproduction steps

```bash
1. Нажать кнопку завершение игры 
2. Перевести на русский язык
```

### Expected result

Таблица ровная, кнопки не выходят за рамки.

### Actual result

Таблица ровная, кнопки выходят за рамки.

### Browsers

Chrome

### OS

Windows

**Comment by VoroshilovYuri** [comment]
При переводе страницы на русский язык с помощью встроенного переводчика в браузере Google Chrome.  Таблица "Лобби" с кнопками "Показать" и "Драться" сдвигается вправо под таблицу Лидеров. При этом функционал кнопок сохраняется. 
Баг воспроизводится в момент, когда пользователь нажимает на правую кнопку мышки, выбирает "перевести на русский язык". Происходит перевод элементов на странице и сдвиг кнопок в таблице Лобби. 

Browsers
Chrome Версия 120.0.6099.63 (Официальная сборка), (64 бит)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle
Current version: 6c30fce

<img width="940" alt="3" src="https://github.com/hexlet-codebattle/codebattle/assets/130492244/bb063079-2914-4550-810b-371a98232f48">

**Comment by Darga113** [comment]
Summary:
    При переводе страницы на русский язык с переводчика, страница не отображается адаптивно
Environment:
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10
Steps-to-reproduce:
    1. Зайти на сайт
    2. Нажать правую кнопку мыши
    3. Выбрать строку "translate to русский"
Еxpected-result:
   Страница переведа корректно и сайт адаптивен после перевода
Actual-result:
    Кнопки сдвинулись за таблицу лидеров
![Screenshot_15](https://github.com/hexlet-codebattle/codebattle/assets/143105877/66ebb9f0-cb9b-434d-8f85-13265426f17d)

**Comment by jullinn** [comment]
!
![Снимок экрана 2023-12-10 131158](https://github.com/hexlet-codebattle/codebattle/assets/143704764/28d38602-8b59-4780-a344-6cea3b47ee51)
Summary
При переводе главной страницы на русский язык элементы на странице изображаются некорректно 

Environment:
Browsers
Chrome Версия 120.0.6099.71 (Официальная сборка), (64 бит)

OS
Windows 11


Codebattle версия 3f95dac.
[Текущая версия: 3f95dac.](https://github.com/hexlet-codebattle/codebattle/commit/3f95dac89cf5b1487ea3f6333c5f74d4a6fa1298)

Steps-to-reproduce:

1. Зайти в аккаунт на странице
2.Кликнуть правой кнопкой мышки на странице
3.Перевести сайт  на русский язык

Expected-result:
 При переводе сайта на русский язык, верстка сайта должна адоптироваться

Actual-result:
Таблица "лобби" и "завершенные игры" смещается в право

**Comment by ReDBrother** [comment]
Нет, это нужно вообще всю страницу переделывать. в текущей итерации мы оставим такую таблицу - проскролить до кнопок есть возможность. Важно что функциональность есть и до нее можно добраться
