### ISSUE TITLE
Bug: Регулировщик контроля времени игры работает некорректно 

### ISSUE THREAD

**Issue by RomaMishchenko** [hexlet-codebattle/codebattle#1678]
### Summary

Если сайт переведён на русский язык то при перетягивания регулировщика графа выдаёт рандомные числа 
![2023-12-05_04-38-27](https://github.com/hexlet-codebattle/codebattle/assets/149249491/3f7f7476-58d4-44e3-9540-b0eaad5e841a)
![2023-12-05_04-37-26](https://github.com/hexlet-codebattle/codebattle/assets/149249491/6109b037-0aba-41a5-b4cf-86ef798360f4)

### Reproduction steps

```bash
1. Нажать кнопку создать игру 
2. Отрегулировать время
```

### Expected result

Время игры будет следовать порядку от 3 до 60 минут 

### Actual result

Контроль времени выдаёт рандомные числа 

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы не можем отвечать за работу автоматических переводчиков) Они работают как хотят)
