### ISSUE TITLE
Bug: Опечатка в слове Хекслет в меню пользователя

### ISSUE THREAD

**Issue by VoroshilovYuri** [hexlet-codebattle/codebattle#1679]
### Summary

При переводе страницы на русский язык в меню пользователя происходит опечатка в слове Хекслет

Environment:
Browsers
Chrome Версия 120.0.6099.63 (Официальная сборка), (64 бит)

OS
Windows 10 Домашняя

Версия 22H2
Codebattle
Current version:6c30fce

<img width="285" alt="89" src="https://github.com/hexlet-codebattle/codebattle/assets/130492244/fa391d82-ca1c-4d00-8602-a1ce0fdfd658">

### Reproduction steps

```bash
1.Быть авторизованным в https://codebattle.hexlet.io/
2.Кликнуть правой кнопкой мышки на странице
3.Выбрать перевести на русский
4.Кликнуть на имя пользователя
```

### Expected result

Выпадающее меню пользователя переведено корректно

### Actual result

Выпадающее меню пользователя переведено не корректно

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы не может отвечать за автоматический переводчик)
