### ISSUE TITLE
Bug: Невозможно удалить пользователя

### ISSUE THREAD

**Issue by jullinn** [hexlet-codebattle/codebattle#1681]
### Summary

Отсутствует кнопка удаления пользователя 

### Reproduction steps

```bash
1. Зайти в аккаунт на https://codebattle.hexlet.io/settings (не через гитхаб или дискорд)
2. Зайти в настройки профиля
```

### Expected result

Пользователь может удалить аккаунт

### Actual result

Возможность удалить аккаунт отсутствует 

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы точно удалять пользователей не будем
Но есть ишью по архивации аккаунтов 1472
