### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by kuza2509** [hexlet-codebattle/codebattle#1684]
### Summary

Не появляется тултип в поле ввода данных во вкладке Example при создании новой задачи.

### Reproduction steps

```bash
1. Перейдите в Tasks
2. Нажмите кнопку Create new task
3. Нажмите на знак + под надписью Input parameters types
4. Введите значение в поле Name, например a
5. Нажмите кнопку Submit
6. Нажмите на крестик
7. Нажмите на знак + под надписью Examples
```

### Expected result

Все поля не выделены красным и ожидают введения данных.

### Actual result

Поля для ввода значений светятся красным и нет тултипа

![2](https://github.com/hexlet-codebattle/codebattle/assets/139548003/976fbecc-7736-4764-92fc-6702df3ba273)

### Browsers

Chrome

### OS

Windows

**Comment by kuza2509** [comment]
[Current version: 3f95dac](https://github.com/hexlet-codebattle/codebattle/commit/3f95dac89cf5b1487ea3f6333c5f74d4a6fa1298)

deployedAt UTC: 2023-12-09 21:42:52

**Comment by ReDBrother** [comment]
Пойдет дублем в общее ишью - #1682
Нужно будет сделать тултип или сообщение прямо в карточке
