### ISSUE TITLE
Feature: replace font-mfizz on different stylish language icons

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#1685]
https://github.com/fizzed/font-mfizz is old icons library. We need something different and with safari support

**Comment by ReDBrother** [comment]
https://fpoumian.github.io/react-devicon/

**Comment by ReDBrother** [comment]
https://github.com/devicons/react-devicons

**Comment by ushachev** [comment]
беру себе задачу, будет продолжением начатого в #1683
