### ISSUE TITLE
Bug: Зависает игра в мобильной версии сайта в процессе редактирования кода.

### ISSUE THREAD

**Issue by Murahainen** [hexlet-codebattle/codebattle#1691]
### Summary

Зависает игра в мобильной версии сайта при попытке внести изменения в подгруженную системой в начале игры часть кода. 

Environment:
Android 13 TP1A.220624.014
MIUI Global 14.04.4.0(TLQRUXM)
Xiaomi 12T.

![Mob_gluk](https://github.com/hexlet-codebattle/codebattle/assets/118127849/051aa653-bed2-4549-8516-656ffaf42f62)

### Reproduction steps

```bash
1. Выбираем одну звезду (Level).
2. Выбираем игру с ботом "With a bot" (Game Type).
3. Выбираем игру "rect_area" (Choose task by name or tags).
4. Нажимаем кнопку "Submit".
5. Пытаемся отредактировать появившийся код: стереть "0" или оператор "return".
```

### Expected result

Загруженный код подвергается редакции. Все клавиши работают адекватно. Можно писать и редактировать код.

### Actual result

При попытке отредактировать загруженный в начале игры код, система зависает. Операторы и значения стереть не представляется возможным, или удается сделать это частично. Частично возможно написание некоторых слов. Появляется еще один мигающий курсор. Бекспейс, пробел и каретка перестают адекватно работать или не работают вовсе.

**Comment by ReDBrother** [comment]
Редактор кода не наш, и он не занимается поддержкой телефонов - только read-only режим сейчас
