### ISSUE TITLE
Bug: Некорректное отображение "rang"  впервые зарегистрированного пользователя

### ISSUE THREAD

**Issue by kseniya-zeti** [hexlet-codebattle/codebattle#1692]
### Summary

Summary
Некорректное отображение "rang"  впервые зарегистрированного пользователя
environment: |
Browsers
Google Chrome 116.0.5845.179 (Official Build) (arm64)
Safari Version 17.2 (19617.1.17.11.9)
macOS 14.2 (23C64)
Codebattle Current version: (0fb867e)

### Reproduction steps

```bash
1. Зайти на стр:  (https://codebattle.hexlet.io)
2. Выбрать "Sing up"
3. Ввести "Nickname"
4. Ввести  "Email"
5. Ввести  "Password"
6. Нажать "Submit"
```

### Expected result

Корректное отображение рейтинга пользователя после регистрации на сайте 

### Actual result

Некорректное отображение рейтинга пользователя после регистрации на сайте.

### Browsers

Chrome, Safari

### OS

Mac

**Comment by kseniya-zeti** [comment]
Подобный баг уже создавался, но был закрыт  #1220

**Comment by kseniya-zeti** [comment]
<img width="1286" alt="Screenshot 2023-12-15 at 14 00 39" src="https://github.com/hexlet-codebattle/codebattle/assets/82118927/b0383aad-19ca-45ff-9164-87fb7c0e3d9d">

<img width="1269" alt="Screenshot 2023-12-15 at 14 01 02" src="https://github.com/hexlet-codebattle/codebattle/assets/82118927/7efe6a8b-aa2b-4052-a624-1891a9283745">

**Comment by ReDBrother** [comment]
> Подобный баг уже создавался, но был закрыт https://github.com/hexlet-codebattle/codebattle/issues/1220
Угу, потому что не баг, а фича) В какой-то момент приняли такое решение для заглушки рейтинга)
