### ISSUE TITLE
Bug: Нет возможности поменять картинку пользователя без изменения аватара в GitHub

### ISSUE THREAD

**Issue by bglpvaa** [hexlet-codebattle/codebattle#1693]
### Summary

При редактировании информации о пользователе нет возможности изменить картинку

### Reproduction steps

```bash
1. Открыта главная страница
2. Переходим на страницу «Настройки»
```

### Expected result

Есть возможность редактировать аватар

### Actual result

Нет активной области, где мы можем поменять аватар пользователя
<img width="1255" alt="Screenshot 2023-12-18 at 10 43 07" src="https://github.com/hexlet-codebattle/codebattle/assets/144710773/ab3ac4cc-6439-467a-a597-400211e5f9f8">

### Browsers

Safari

### OS

Mac

**Comment by ReDBrother** [comment]
Это фича
Дубль от [#1320](https://github.com/hexlet-codebattle/codebattle/issues/1320)
