### ISSUE TITLE
Страница "Users Rating" не адаптивна для масштабируемости

### ISSUE THREAD

**Issue by bglpvaa** [hexlet-codebattle/codebattle#1695]
### Summary

Bug: При переходе на страницу общей статистики рейтинга пользователей "User Rating" выпадающие списки съезжают

### Reproduction steps

```bash
1. Перейти на https://codebattle.hexlet.io/users
2. В девтулз выбрать отображение с мобильного устройства «Samsung Galaxy S8+»
3. Нажать на кнопку «Users per page»
```

### Expected result

Выпадающий список будет появляться ровно под активной кнопкой «Users per page»

### Actual result

Выпадающий список улетает вверх экрана
<img width="395" alt="Screenshot 2023-12-18 at 11 11 53" src="https://github.com/hexlet-codebattle/codebattle/assets/144710773/cdcdba7c-7e1d-453a-a39a-019bde58934d">

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
Это селект браузера, мы его не контролируем и он очень часто зависит от вашей текущей версии)
