### ISSUE TITLE
Bug: Страница настроек (settings)  отображается некорректно

### ISSUE THREAD

**Issue by annastincher** [hexlet-codebattle/codebattle#1697]
### Summary

Страница настроек загружается, но отображается некорректно

### Reproduction steps

```bash
1. Нажать на юзерпик пользователя
2. В дроп-даун меню выбрать Settings (настройки)
```

### Expected result

Страница отображается корректно с пунктами для настройки

### Actual result

Страница отображаеся пустой
![упала страница настроек](https://github.com/hexlet-codebattle/codebattle/assets/145253493/29e29863-09e0-446c-8f1e-27194d0a1cf8)

### Browsers

Microsoft Edge

### OS

Windows

**Comment by annastincher** [comment]
![f12 settings](https://github.com/hexlet-codebattle/codebattle/assets/145253493/bd16f255-b2db-43ea-b738-28d4dd7ffa7c)

**Comment by ReDBrother** [comment]
fixed
