### ISSUE TITLE
Bug: Не корректно отображается меню пользователя при смене размера окна

### ISSUE THREAD

**Issue by annaportenko** [hexlet-codebattle/codebattle#1708]
### Summary

Не корректно отображается меню пользователя при смене размера окна

### Reproduction steps

```bash
1. Открыта страница https://codebattle.hexlet.io/#lobby
2. Окно браузера 990*858
3. Вкладка COMPLETED GAMES
4. Открыть меню пользователя
```

### Expected result

Элементы сайта отображаются корректно

### Actual result

Названия столбцов COMPLETED GAMES перекрывает часть меню пользователя
![1-1](https://github.com/hexlet-codebattle/codebattle/assets/145679052/21e62f10-75bf-426c-a0ef-b73b8b9c75ac)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
fixed
