### ISSUE TITLE
Bug: Не корректный title для кнопки Run

### ISSUE THREAD

**Issue by annaalexan** [hexlet-codebattle/codebattle#1709]
### Summary
Не корректный title для кнопки Run

### Reproduction steps
```bash
1. Открыт интерфейс баттла
2. Навести курсор на кнопку Run
```

### Expected result
Отображается корректный title

### Actual result
Отображается `Check solution&#013;Ctrl + Enter`

![18-1](https://github.com/hexlet-codebattle/codebattle/assets/145679052/2b4b08aa-370f-4b1f-83a5-34240609b8cd)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Он корректный, он поясняет что делает эта кнопка. Описание Run скорее нужно для того, чтобы эта кнопка умещалась на экране)
