### ISSUE TITLE
Bug: Не отображается привязанность GitHub в таблице рейтинга

### ISSUE THREAD

**Issue by lguana13** [hexlet-codebattle/codebattle#1711]
### Summary

В таблице рейтинга не отображается привязанность аккаунта GitHub к профилю пользователя

### Reproduction steps

```bash
1. Зайти на сайт, используя Discord
2. Зайти в свой профиль и привязать GitHub профиль
3. Перейти в таблицу лидеров за все время
4. Написать свой никнейм
```

### Expected result

Отображается, что пользователь подключил GitHub аккаунт

### Actual result

Отображается, что пользователь не подключил GitHub аккаунт

![QzKrHcq7ruY](https://github.com/hexlet-codebattle/codebattle/assets/130796872/928aa923-a620-40a3-8e7b-5543c6cee5ec)
![_6kT7Yg3HRQ](https://github.com/hexlet-codebattle/codebattle/assets/130796872/abadacf5-b61e-4e4d-ad03-c9c9cae7a7be)
![C6OnxEcpdtg](https://github.com/hexlet-codebattle/codebattle/assets/130796872/d5dd492c-347a-4070-96cb-3d5944639457)

### Browsers

Microsoft Edge

### OS

Windows

**Comment by ReDBrother** [comment]
Так он и не привязан) Все четко
"Link Github" это именно команда на привязку, а не статус
