### ISSUE TITLE
Bug: при создании новой задачи не отображается сообщение об ошибке в имени переменной

### ISSUE THREAD

**Issue by YavorskyS** [hexlet-codebattle/codebattle#1712]
Summary:
При создании новой задачи на шаге 2 (Step 2) при добавлении входных переменных на вкладке Input не отображается сообщение об ошибке при вводе в поле Name неправильного имени переменной. 

Browsers:
Chrome 109.0.5414.120, (64 бит)
Firefox 115.6.0esr (64 бит)

OS: Windows

Версия сайта:  dbd0d89 UTC: 2024-01-06 20:39:54

Reproduction steps:
1. Залогиниться на сайте
2. Кликнуть на логотип пользователя
3. В открывшемся меню кликнуть пункт  Tasks
4. Нажать Create new task
5. На вкладке STEP 1 заполнить поле Task
6. На вкладке STEP 1 заполнить поле Description
7. На вкладке STEP 2 нажать кнопку "+" для добавления новой входной переменной
8. В поле Name на вкладке INPUT ввести недопустимое имя переменой Var (или v1, или v_1)

Expected result:
Отображается сообщение об ошибке в имени переменной, рамка поля Name выделяется цветом

Actual Result:
Рамка поля Name выделяется цветом, в поле появляется значок ошибки, но текстовое сообщение, содержащее причину ошибки - не отображается
![image](https://github.com/hexlet-codebattle/codebattle/assets/145402177/cbb058a1-1b93-40cd-a179-1b5232dfb40b)

**Comment by ReDBrother** [comment]
Прикрепим к #1682
