### ISSUE TITLE
Bug: broken reload input signature button [task builder]

### ISSUE THREAD

**Issue by YavorskyS** [hexlet-codebattle/codebattle#1713]
### Summary

При создании пользователем новой задачи на шаге 2 (STEP 2) при нажатии кнопки Reload пропадает содержимое окна

![bug2](https://github.com/hexlet-codebattle/codebattle/assets/145402177/7a678c58-637b-4825-96f7-09e19e9fc5b6)

![image](https://github.com/hexlet-codebattle/codebattle/assets/145402177/fe40a60e-3256-4105-b2b1-6f6780bf127e)

### Reproduction steps

```bash
1. Залогиниться на сайте
2. Кликнуть на логотип пользователя
3. В открывшемся меню кликнуть пункт Tasks
4. Нажать Create new task
5. На вкладке STEP 1 заполнить поле Task
6. На вкладке STEP 1 заполнить поле Description
7. На вкладке STEP 2 нажать кнопку "+" для добавления новых входных переменных
8. В поле Name на вкладке INPUT ввести имя переменой a 
9. Нажать кнопку Submit
10. В поле Name на вкладке INPUT ввести имя переменой b 
11. Нажать кнопку Submit
12. Нажать кнопку Reload
```

### Expected result

Пользователь переходит к третьему шагу создания новой задачи (STEP 3)

### Actual result

Изображения всех вкладок пропадают (см рис.), продолжить процесс создания новой задачи невозможно

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by VictorKuzenkin** [comment]
Подтверждаю баг в версии приложения dbd0d89, браузер CCleaner (движок Chromium), ОС WIndows 11.

Предусловие: Пользователь авторизован

Шаги воспроизведения:
1. Кликнуть на имя профиля и зайти в Tasks
2. Нажать на Create new task
3. В поле Step 2 нажать кнопку перезагрузки

![Доп к открытому багу 1](https://github.com/hexlet-codebattle/codebattle/assets/144316874/4cc51986-36e7-44ea-bbd7-b24eba59ec20)
![Доп к открытому багу 2](https://github.com/hexlet-codebattle/codebattle/assets/144316874/6e3efac6-30e8-4dbe-aded-bb390ba2e550)

**Comment by Pyplee** [comment]
Беру себе задачу

**Comment by Pyplee** [comment]
Насколько я понял кнопка из за которой появляется ошибка, а именно кнопка сброса в правом верхнем блоке task2 должна корректно сбрасывать значения не приводя к ошибке?

До нажатия:
![image](https://github.com/hexlet-codebattle/codebattle/assets/113016827/32d67f32-00e6-4b50-ac13-ef18ad5dfcf7)

После нажатия:
![image](https://github.com/hexlet-codebattle/codebattle/assets/113016827/cf3f3ad0-e7cc-496f-a543-e0487c384424)

**Comment by Zofore** [comment]
Воспроизвел баг в версии [Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

environment: |
    Яндекс Браузер Версия 23.11.3.935 (64-bit) ОС Windows 11 Версия 22H2
    
Expected result
Пользователь переходит к третьему шагу создания новой задачи (STEP 3)

Actual result
Изображения всех вкладок пропадают (см рис.), продолжить процесс создания новой задачи невозможно

![задача](https://github.com/hexlet-codebattle/codebattle/assets/153725639/b9047951-dc2b-47c1-9c3e-0bea84dba4e0)
