### ISSUE TITLE
Bug: В мобильной версии сайта , при ширине экрана меньше 410 px,  окно  для выбора  и добавления смайлов в чат выходит за границы  экрана.

### ISSUE THREAD

**Issue by Elena-Yakovleva** [hexlet-codebattle/codebattle#1715]
### Summary

 В мобильной версии сайта , при ширине экрана меньше 410 px,  окно  для выбора  и добавления смайлов в чат выходит за границы  экрана.

### Reproduction steps

```bash
1. Открыть https://codebattle.hexlet.io/#lobby и пройти авторизацию.
2. Открыть DevTools.
3. В панели инструментов устройства выбрать мобильное устройство Galaxy Note 3.
4. Прокрутить сайт до блока чата пользователей.
5. Нажать на кнопку выбора смайлов для добавления их в текст сообщения.
```

### Expected result

Адаптация сайта прошла успешно

### Actual result

Current version: dbd0d89

deployedAt UTC: 2024-01-06 20:39:54

При ширине  экрана менее 410 px блок для выбора смайлов выходит за границы экрана. Чем меньше ширина экрана, тем дальше уходит блок за его границы.
<img width="430" alt="Снимок экрана 2024-01-11 203005" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/baf1f580-aada-49f8-90fe-62dacc8a8f02">
<img width="486" alt="Снимок экрана 2024-01-11 203140" src="https://github.com/hexlet-codebattle/codebattle/assets/97059804/fd9f4662-2beb-4903-9b9b-2c48d8269714">

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Не наш дропдаун, мы не можем это контролировать
