### ISSUE TITLE
Bug: При выборе некоторых ЯП прогон теста выдаёт результат "The solution cannot be executed"

### ISSUE THREAD

**Issue by VictorKuzenkin** [hexlet-codebattle/codebattle#1717]
### Summary

При смене языка программирования на Kotlin, Golang, C#, Haskell, Java 20, Python во время игры и нажатии на кнопку Run для прогона теста вместо Test failed появляется сообщение об ошибке "The solution cannot be executed". Поле для написания кода не содержит фактического решения задачи или каких-либо изменений, т.к. действие выполнялось не разработчиком :)

### Reproduction steps

```bash
1. Запускаем игру
2. Меняем язык программирования на Kotlin, Golang, C#, Haskell, Java 20 или Python
3. Не меняя изначальное поле с кодом, нажимаем на кнопку Run для проверки решения (кроме третьего скриншота, там были внесены изменения, но несмотря на это, фактический результат такой же)
```

### Expected result

Появляется надпись "Test failed", а в поле Output выводятся результаты проверки

### Actual result

Появляется сообщение с текстом "The solution cannot be executed", в поле Output вместо результатов проверки выводится информация об ошибках.

### Browsers

Chrome

### OS

Windows

Current version: dbd0d89

deployedAt UTC: 2024-01-06 20:39:54

**Comment by ReDBrother** [comment]
Так код и должен работать)

**Comment by VictorKuzenkin** [comment]
А не подскажите, почему на одних языках срабатывает тест в стандартном виде, а на этих нет? :) Можно вкратце :)
