### ISSUE TITLE
Bug: Не работает кнопка backspace на мобильном устройстве во время игры

### ISSUE THREAD

**Issue by VictorKuzenkin** [hexlet-codebattle/codebattle#1718]
### Summary

На мобильном устройстве Android при нажатии на кнопку удаления символов в поле для написания кода курсор остаётся на месте и не удаляет символы, из-за чего невозможно исправить ошибку или отредактировать написанное.

### Reproduction steps

```bash
1. Запустить любую игру на мобильном устройстве с операционной системой Android 9 (LLD-L31 Build/HONORLLD-L31) в браузере Chrome версии 120.0.6099.210
2. Написать что-нибудь в поле для решения задачи
3. Нажать кнопку backspace, чтобы удалить написанное
```

### Expected result

Написанные символы удаляются, курсор перемещается назад

### Actual result

Написанные символы не удаляются, в т.ч. имеющиеся по умолчанию, курсор остаётся на месте

### Browsers

Chrome

**Comment by ReDBrother** [comment]
Мы не будем поддерживать все мобильные устройства (только возможность доступа к контенту) - Авторы редактора кода не собираются поддерживать мобильные устройства
