### ISSUE TITLE
Bug: Лишняя буква "s" в тексте кнопки "With other user" модального окна с настройками игры

### ISSUE THREAD

**Issue by AnnaKotkova** [hexlet-codebattle/codebattle#1722]
### Summary

Лишняя буква "s" в тексте кнопки "With other user" настройки "Game Type" модального окна с настройками игры на главной странице

![Screenshot # 6](https://github.com/hexlet-codebattle/codebattle/assets/147257767/0948e139-cc31-44bf-86b6-78d71d7716c5)

**Environment**

Browser  Google Chrome  120.0.6099.225 (Официальная сборка, 64 бит)
ОS  Windows 10 Pro
Codebattle current version  [dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованным пользователем
2. Нажать на кнопку "CREATE A GAME"
```

### Expected result

На кнопке отображается текст "With other user"  

### Actual result

На кнопке отображается текст "With other users"

### Browsers

Chrome

### OS

Windows

**Comment by AnnaKotkova** [comment]
Считаю, что логичнее на данной кнопке указать текст "With other user", т.к. в игре участвуют только 2 пользователя.

**Comment by po1inakoroleva** [comment]
Беру в работу
