### ISSUE TITLE
Bug: У 13-ти задний уровня сложности "elementary" не отображается тег "rest" после выбора этих заданий по названию

### ISSUE THREAD

**Issue by AnnaKotkova** [hexlet-codebattle/codebattle#1723]
### Summary

У 13-ти задний уровня сложности "elementary", отображающихся в настройках игры по тегу "rest", не отображается этот тег в настройке игры "Choose task by name or tags" после выбора этих заданий по названию

![Screenshot # 7](https://github.com/hexlet-codebattle/codebattle/assets/147257767/d1f8c7f1-24a9-404e-808b-12295201abdd)

**Environment**

Browser  Google Chrome  120.0.6099.225 (Официальная сборка, 64 бит)
ОS  Windows 10 Pro
Codebattle current version  [dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованным пользователем
2. Нажать на кнопку "CREATE A GAME"
3. Выбрать задание с названием из списка:
    1. add_two_number
    2. age_to_days
    3. biggest_square_sum
    4. celsius_to_kelvin
    5. coffe_cups
    6. colour_invert
    7. farm_problem
    8. fps_calculation
    9. leap_year
    10. number_range
    11. on_off_switches
    12. power_calculator
    13. stickers_count
```

### Expected result

У задания отображается тег "rest" в настройке игры "Choose task by name or tags"

### Actual result

У задания не отображается тег "rest" в настройке игры "Choose task by name or tags"

### Browsers

Chrome

### OS

Windows

**Comment by AnnaKotkova** [comment]
Похожая ситуация:
[#1724](https://github.com/hexlet-codebattle/codebattle/issues/1724)
[#1725](https://github.com/hexlet-codebattle/codebattle/issues/1725)

**Comment by ReDBrother** [comment]
Не, выбор тегов нужен только когда мы берем рандомные игры и нам нужно ограничить список задач

**Comment by AnnaKotkova** [comment]
> Не, выбор тегов нужен только когда мы берем рандомные игры и нам нужно ограничить список задач

Согласна, что при создании игры это ни на что не влияет. Человек выберет тег и эти задания будут в списке.
Но, если обращаться к единообразию, то у всех других заданий после выбора задания отображается теги к которым они относятся, а у этих - нет.

**Comment by ReDBrother** [comment]
Не, они отображаются только если предварительно выбрать теги. Ок, я сейчас уберу теги вовсе, при выборе конретной задачи

**Comment by AnnaKotkova** [comment]
> Не, они отображаются только если предварительно выбрать теги. Ок, я сейчас уберу теги вовсе, при выборе конретной задачи

"Не, они отображаются только если предварительно выбрать теги." - Я тоже самое и сказала.
"Ок, я сейчас уберу теги вовсе, при выборе конретной задачи" - Простите, но я вас совсем не понимаю. Сейчас выглядит логичным, что после выбора задачи выделяются теги к которым они относятся.

**Comment by ReDBrother** [comment]
Нет, это лишнее усложнение, сейчас задача этой вкладки фильтровать задачи. Полную информацию по задачи мы не будем палить, даже такие условные, как теги задачи
