### ISSUE TITLE
Bug: У 8-ми задний уровня сложности "easy" не отображается тег "rest" после выбора этих заданий по названию

### ISSUE THREAD

**Issue by AnnaKotkova** [hexlet-codebattle/codebattle#1724]
### Summary

У 8-ми задний уровня сложности "easy", отображающихся в настройках игры по тегу "rest", не отображается этот тег в настройке игры "Choose task by name or tags" после выбора этих заданий по названию

![Screenshot # 8](https://github.com/hexlet-codebattle/codebattle/assets/147257767/c712d3bc-b938-435c-8689-fd46612fa7ee)

**Environment**

Browser  Google Chrome  120.0.6099.225 (Официальная сборка, 64 бит)
ОS  Windows 10 Pro
Codebattle current version  [dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованным пользователем
2. Нажать на кнопку "CREATE A GAME"
3. Выбрать уровень сложности "easy"
4. Выбрать задание с названием из списка:
    1. celsius_to_fahrenheit
    2. domino
    3. excel_sheet_column_number
    4. excel_sheet_column_title
    5. has_equal_zeros_count
    6. kinetic_energy
    7. leap_year_count
    8. snail_race
```

### Expected result

У задания отображается тег "rest" в настройке игры "Choose task by name or tags"

### Actual result

У задания не отображается тег "rest" в настройке игры "Choose task by name or tags"

### Browsers

Chrome

### OS

Windows

**Comment by AnnaKotkova** [comment]
Похожая ситуация:
[#1723](https://github.com/hexlet-codebattle/codebattle/issues/1723)
[#1725](https://github.com/hexlet-codebattle/codebattle/issues/1725)

**Comment by ReDBrother** [comment]
Не должно показывать никаких текущих тегов
