### ISSUE TITLE
Bug: У 3-х задний уровня сложности "medium" не отображается тег "rest" после выбора этих заданий по названию

### ISSUE THREAD

**Issue by AnnaKotkova** [hexlet-codebattle/codebattle#1725]
### Summary

У 3-х задний уровня сложности "medium", отображающихся в настройках игры по тегу "rest", не отображается этот тег в настройке игры "Choose task by name or tags" после выбора этих заданий по названию

![Screenshot # 9](https://github.com/hexlet-codebattle/codebattle/assets/147257767/c0d06343-c2fe-4ce9-b40e-e8c8a1dc3f12)

**Environment**

Browser  Google Chrome  120.0.6099.225 (Официальная сборка, 64 бит)
ОS  Windows 10 Pro
Codebattle current version  [dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованным пользователем
2. Нажать на кнопку "CREATE A GAME"
3. Выбрать уровень сложности "medium"
4. Выбрать задание с названием из списка:
    1. bulls_and_cows
    2. double_base_palindromes
    3. tic_tac_toe
```

### Expected result

У задания отображается тег "rest" в настройке игры "Choose task by name or tags"

### Actual result

У задания не отображается тег "rest" в настройке игры "Choose task by name or tags"

### Browsers

Chrome

### OS

Windows

**Comment by AnnaKotkova** [comment]
Похожая ситуация:
[#1723](https://github.com/hexlet-codebattle/codebattle/issues/1723)
[#1724](https://github.com/hexlet-codebattle/codebattle/issues/1724)

**Comment by ReDBrother** [comment]
Дубль от #1724
