### ISSUE TITLE
Bug: Отображение сообщения о выполнении задания за 7 минут от бота на странице игры после создания игры с уровнем сложности "elementary" и продолжительностью от 3 до 6 минут

### ISSUE THREAD

**Issue by AnnaKotkova** [hexlet-codebattle/codebattle#1726]
### Summary

Отображение сообщения о выполнении задания за 7 минут от бота пользователю с рейтингом равным 1200 в чате на странице игры после создания игры с уровнем сложности "elementary" и продолжительностью от 3 до 6 минут

![Screenshot # 11](https://github.com/hexlet-codebattle/codebattle/assets/147257767/d4978bc3-55e9-452c-9646-f7b364acb4c3)

**Environment**

Browser  Google Chrome  120.0.6099.225 (Официальная сборка, 64 бит)
ОS  Windows 10 Pro
Codebattle current version  [dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованным пользователем
2. Нажать на кнопку "CREATE A GAME"
3. Выбрать тип игры "With a bot"
4. Выбрать продолжительность игры от 3 до 6 минут
5. Нажать на кнопку "Create battle"
```

### Expected result

Отображается сообщение о выполнении задания за указанное время от бота в чате игры

### Actual result

Отображается сообщение о выполнении задания за 7 минут от бота в чате игры

### Browsers

Chrome

### OS

Windows

**Comment by AnnaKotkova** [comment]
Бот указывает время решения задачи в зависимости от уровня сложности игры и рейтинга оппонента.
Бот может просто писать, что постарается решить задание быстрее пользователя.
Или можно дополнительно установить зависимость от продолжительности игры.

**Comment by AnnaKotkova** [comment]
Похожая ситуация:
[#1727](https://github.com/hexlet-codebattle/codebattle/issues/1727)
[#1728](https://github.com/hexlet-codebattle/codebattle/issues/1728)
[#1729](https://github.com/hexlet-codebattle/codebattle/issues/1729)

**Comment by ReDBrother** [comment]
Дубль от #1724

**Comment by AnnaKotkova** [comment]
> Дубль от #1724

Можно пояснений, почему данный баг относится к дублю бага 1724?

**Comment by ReDBrother** [comment]
Поправка, все сведем к тикету #1728
