### ISSUE TITLE
Bug: Отображение сообщения о выполнении задания за 13 минут от бота на странице игры после создания игры с уровнем сложности "medium" и продолжительностью от 3 до 12 минут

### ISSUE THREAD

**Issue by AnnaKotkova** [hexlet-codebattle/codebattle#1728]
### Summary

Отображение сообщения о выполнении задания за 13 минут от бота пользователю с рейтингом равным 1200 в чате на странице игры после создания игры с уровнем сложности "medium" и продолжительностью от 3 до 12 минут 

![Screenshot # 13](https://github.com/hexlet-codebattle/codebattle/assets/147257767/675e1141-a9f5-4cb3-b773-55e7118f5588)

**Environment**

Browser  Google Chrome  120.0.6099.225 (Официальная сборка, 64 бит)
ОS  Windows 10 Pro
Codebattle current version  [dbd0d89](https://github.com/hexlet-codebattle/codebattle/commit/dbd0d8910a730a4dd9c4c371ab0870893ed54140)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованным пользователем
2. Нажать на кнопку "CREATE A GAME"
3. Выбрать тип игры "With a bot"
4. Выбрать уровень сложности игры "medium"
5. Выбрать продолжительность игры от 3 до 12 минут
6. Нажать на кнопку "Create battle"
```

### Expected result

Отображается сообщение о выполнении задания за указанное время от бота в чате игры

### Actual result

Отображается сообщение о выполнении задания за 13 минут от бота в чате игры

### Browsers

Chrome

### OS

Windows

**Comment by AnnaKotkova** [comment]
Похожая ситуация:
[#1726](https://github.com/hexlet-codebattle/codebattle/issues/1726)
[#1727](https://github.com/hexlet-codebattle/codebattle/issues/1727)
[#1729](https://github.com/hexlet-codebattle/codebattle/issues/1729)

**Comment by ReDBrother** [comment]
Дубль от #1724

**Comment by ReDBrother** [comment]
Это сообщение, что он выполнит задачу примерно за это время)

**Comment by ReDBrother** [comment]
Бот быстрее не может))
