### ISSUE TITLE
Bug: Нет информации о допустимых символах для названия входного параметра (input parameter) при создании нового задания

### ISSUE THREAD

**Issue by VictorKuzenkin** [hexlet-codebattle/codebattle#1730]
### Summary

Если название входного параметра содержит заглавные буквы или цифры, появляется восклицательный знак и красная подсветка, но отсутствует подсказка, какие символы можно/нельзя использовать.
![Баг 2 проекта нет указания на ошибку](https://github.com/hexlet-codebattle/codebattle/assets/144316874/813c6bdc-229a-4856-a79b-f9f26b4537a9)
![Баг new task creation](https://github.com/hexlet-codebattle/codebattle/assets/144316874/e8328afc-d338-4fdc-8862-00e164c51501)

### Reproduction steps

```bash
1. Кликнуть на имя профиля и зайти в раздел Tasks
2. Нажать Create new task
3. В поле Step 2 нажать на плюс под Input parameters types
4. Ввести в поле Name название, содержащее заглавную букву или цифру
```

### Expected result

Появляется подсказка о том, какие символы можно/нельзя использовать

### Actual result

Отображается только восклицательный знак и красная подсветка

### Browsers

Chrome

### OS

Windows

### Current version:

dbd0d89
           deployedAt UTC: 2024-01-06 20:39:54

**Comment by po1inakoroleva** [comment]
Беру в работу

**Comment by ReDBrother** [comment]
Дубль от #1682
