### ISSUE TITLE
Bug: Использование запрещённых символов в имени пользователя при авторизации через Discord

### ISSUE THREAD

**Issue by Nowskas** [hexlet-codebattle/codebattle#1731]
### Summary

Система допускает возможность использование запрещённых символов в имени пользователя при авторизации через Discord 

Prerequisites:
Открыта главная страница веб-игры https://codebattle.hexlet.io/. Авторизованы в Discord

Test-data: 
Аккаунт Discord с именем: hihexlet.__

Current version: dbd0d89

### Reproduction steps

```bash
1.Нажимаем на кнопку "Sign in"
2.Нажимаем на кнопку "Sign with Discord"
3.Нажимаем на кнопку "Авторизовать"
```

### Expected result

Система должна сгенерировать отображаемое имя пользователя в соответствии с разрешенными символами

### Actual result

Система правильно отрабатывает и разрешает авторизацию пользователя. При этом допускает использование запрещённых символов в имени пользователя
![Discord Запрещенные символы в имени пользователя 1](https://github.com/hexlet-codebattle/codebattle/assets/102961520/dd2cc424-b947-46e6-b7bf-777bef9cc18b)
![Discord Запрещенные символы в имени пользователя 2](https://github.com/hexlet-codebattle/codebattle/assets/102961520/c988f69a-7e42-47ea-94bb-fc6707af8126)
![Discord Запрещенные символы в имени пользователя 3](https://github.com/hexlet-codebattle/codebattle/assets/102961520/0e3fcf93-f82b-4cc3-8e23-9476e10e62e2)
![Discord Запрещенные символы в имени пользователя 4](https://github.com/hexlet-codebattle/codebattle/assets/102961520/f47e5f7c-db1c-47cc-ab24-e825f68b7874)

### Browsers

Firefox

### OS

Windows

**Comment by ReDBrother** [comment]
Не имеет значение, мы не можем запретить другому сервису какие имена разрешены)
