### ISSUE TITLE
Bug: При загрузке главной страницы, в Network появляются ошибки с кодом 429 и (canceled)

### ISSUE THREAD

**Issue by EvgeniyKauter** [hexlet-codebattle/codebattle#1734]
### Summary

Ошибки с кодами 429 (много запросов в единицу времени) и canceled, при загрузке главной страницы сайта. Пока пользователь находится на этой странице, ошибки постоянно повторяются с течением времени.
Клиент: Chrome Версия 121.0.6167.86 (Официальная сборка), (64 бит)
OC: Windows 10 Домашняя
Версия игры: ecfc661
![image](https://github.com/hexlet-codebattle/codebattle/assets/126510046/2f9a23fc-6465-4203-af02-c9324d1364ad)

### Reproduction steps

```bash
1. Открыть главную страницу с авторизованным пользователем.
2. Открыть DevTools, перейти во вкладку Network.
3. Обновить страницу.
```

### Expected result

При обновлении страницы ошибок не возникает

### Actual result

Появляются ошибки во время загрузки и повторяются с течением времени пока пользователь находится на страницу

### Browsers

Chrome

### OS

Windows

**Comment by elenalapshakova** [comment]
summary: 
При наведении курсора на имена пользователей отправляется слишком много запросов на сервер
![bug](https://github.com/hexlet-codebattle/codebattle/assets/150234130/266c5ac3-3d3c-4d9d-936b-ab1221878ae1)

environment: 
Google Chrome 119.0.6045.160 (Официальная сборка), (64 бит)
    OC Windows 10
 Codebattle current version: 10f1d0a

  steps-to-reproduce: 
   1. Зайти на главную страницу Codebattle 
   2. Открыть DevTools
   3. Перейти во вкладку Network
   4. Навести курсор на имена пользователей
   
expected-result:
При наведении курсора на имена пользователей сервер успешно обрабатывает запросы
 
actual-result:
Сервер отвечает ошибкой

**Comment by EvgeniyKauter** [comment]
@elenalapshakova спасибо за уточнения

**Comment by ReDBrother** [comment]
Если говорить про некую градацию, то водораздел всегда проходит в точке где баг ломает весь пользовательский экспирианс (Сломалась вся или часть страницы, страница заблокировалась или не показывает часть контента т.д.) и просто ошибки, которые всплывают из-за любого рассинхрона, как в случае с перемещением курсора но пользователь может в любой момент повторить действие и получить контент.

Если откроешь страницу ютуба на любом видео, то увидишь миллион ошибок из второй градации. Обычно их скорее в кучу складывают и заводят ишью по уменьшению алертов на странице. Можем пока оставить, если где-то еще это всплывает, то лучше сюда скинуть доп коммент.

**Comment by Tixon228** [comment]
**Краткое описание ошибки:**
При наведении на имена пользователей в Leaderboard, в Network появляются ошибки с кодом 429


![image](https://github.com/user-attachments/assets/b6482e1c-21a1-4ea4-9935-d963ca4d44e2)


**Шаги для воспроизведения бага:**
- Находиться в лобби https://codebattle.hexlet.io/#lobby
- Направлять курсор на разные имена пользователей в leaderboard

**Версии окружения:**
ОС: Windows 10 Домашняя 
Браузер: Chrome 131.0.6778.81 (официальная сборка)  (64-bit)
Версия Codebattle: bb44a99

**Ожидаемый результат:**
При наведении курсора на имена пользователей сервер обрабатывает запросы без ошибок

**Какой результат получился на самом деле:**
В Network появляются ошибки

**Comment by vtm9** [comment]
Two parts: the '(canceled)' errors are fixed in a619e8a41 (the hover popover no longer reports aborted requests as errors — see #2115). The remaining '429' is because the hover fires a request on every mouseenter with no debounce and no caching (the 'TODO: store stats in global redux state' in UserInfo.tsx), so sweeping across the lobby list bursts requests and trips a proxy-side rate limit. Re-scoping to enhancement-proposal: add a hover debounce (~300-500ms) and cache achievements per user id so rapid/repeat hovers don't refetch.
