### ISSUE TITLE
Bug: При повторной авторизации через Github, изменяется имя пользователя. Это имя не соответствует требованиям

### ISSUE THREAD

**Issue by EvgeniyKauter** [hexlet-codebattle/codebattle#1735]
### Summary

В случае, если авторизоваться через аккаунт Github, затем разъединить связь с этим аккаунтом и авторизоваться снова через Github, то будет зарегистрирован новый пользователь с именем, не соответствующим требованию "не более 16 знаков"
![image](https://github.com/hexlet-codebattle/codebattle/assets/126510046/d7d99340-9091-432b-a9d6-ad8078fd7227)
Имя в Github. При первой авторизации соответствовало
![image](https://github.com/hexlet-codebattle/codebattle/assets/126510046/1f359419-aad8-4003-b817-4a4bb0305eea)
При повторной авторизации, создан новый пользователь с именем, не соответствующим требованию "не более 16 знаков"

Клиент: Chrome Версия 121.0.6167.86 (Официальная сборка), (64 бит)
OC: Windows 10 Домашняя
Версия игры: https://github.com/hexlet-codebattle/codebattle/commit/ecfc661fb5799fee1138e12fd423887c7cf87f1b

P.S: Если при повторной авторизации через Github исключить создание нового пользователя, а продолжать с уже существующим, проблема будет исчерпана.

### Reproduction steps

```bash
1. Открыть страницу https://codebattle.hexlet.io/
2. Нажать Sign In
3. Выбрать Sign In with Github
4. Нажать на иконку профиля и выбрать Settings
5. Нажать Unlink Github
6. Нажать на иконку профиля и выбрать Sign Out
7. Нажать на Sing In
8. Выбрать Sign In with Github
```

### Expected result

Имя пользователя соответствует требованию "не более 16 знаков"

### Actual result

Имя пользователя не соответствует требованию "не более 16 знаков".

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нет, мы не можем контролировать это. Проверенные имена из других источников будут передаваться как есть.

**Comment by forestskysea** [comment]
https://github.com/hexlet-codebattle/codebattle/issues/1786
