### ISSUE TITLE
Bug: Лишняя буква P в уведомлении о запуске командного типа турнира

### ISSUE THREAD

**Issue by VictorKuzenkin** [hexlet-codebattle/codebattle#1736]
### Summary

При запуске турнира появляется окошко с текстом "Next match will be oppened. Show now?", где вторая p в слове opened является лишней.
![Лишняя буква P при создании командного турнира](https://github.com/hexlet-codebattle/codebattle/assets/144316874/8c024fed-6f78-48c8-bf0f-06f95d232f15)

### Reproduction steps

```bash
1. Авторизоваться в системе
2. Нажать на название профиля
3. В открывшемся меню кликнуть на Tournaments
4. В нижней части страницы создания турнира нажать Create
5. В открывшемся фойе запуска турнира нажать Join, а затем Start
6. В открывшемся окне нажать Confirm
```

### Expected result

Появляется уведомление о грядущем начале матча с текстом "Next match will be opened. Show now?"

### Actual result

В тексте уведомления в слове "opened" написана лишняя "p", что бросается в глаза таким занудам, как я :)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Фиксанул, чуть позже задеплоим)
