### ISSUE TITLE
Bug: Поле для настройки конфигурации раундов в формате json отображается после выбора другого вида турнира

### ISSUE THREAD

**Issue by VictorKuzenkin** [hexlet-codebattle/codebattle#1738]
### Summary

При выборе турниров stairway или swiss и параметре "per_round" в rounds config type и последующем изменении вида турнира на team, поле формата json для настройки конфигурации раундов продолжает отображаться
![Поле формата json 1](https://github.com/hexlet-codebattle/codebattle/assets/144316874/56308454-6fc1-461e-92bf-6ff503ac73be)
![Поле формата json 2](https://github.com/hexlet-codebattle/codebattle/assets/144316874/1fc0db89-250c-483e-ae96-9f128d9af10d)

### Reproduction steps

```bash
1. Авторизоваться в системе
2. Нажать на название профиля и перейти на вкладку Tournaments
3. Прокрутить до заголовка Create a new tournament
4. В поле Type выбрать stairway или swiss
5. В нижней части страницы в поле Rounds config type выбрать per_round
6. Затем в поле Type выбрать team
```

### Expected result

Поле формата json для настройки конфигурации раундов исчезло, отображаются только настройки командного вида турнира

### Actual result

Поле формата json для настройки конфигурации раундов продолжает отображаться, наряду с настройками командного вида турнира

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Поменяли на общий json meta, который можно редактировать в любом турнире
