### ISSUE TITLE
Bug: Нет возможности стереть текст решения в мобильной версии 

### ISSUE THREAD

**Issue by ProkhorovaPolina** [hexlet-codebattle/codebattle#1739]
### Summary

В мобильной версии в окне решения нет возможности стереть текст, в случае ошибки. 

### Reproduction steps

```bash
1. Создаем игру с ботом
2. Скролим вниз к окну ввода решения
3. Нажимаем на окно
4. Открывается клавиатура
5. Начинаем вводить решение
4. В случае ошибки стираем часть текста стрелкой
```

### Expected result

Текст успешно стерся, можем дальше писать решение

### Actual result

Нет возможности стереть текст. Возможно стереть только слово, которое еще не дописано. Как только нажимаешь пробел- текст становится серым, невозможно стереть ничего
![photo_2024-02-06_21-48-06](https://github.com/hexlet-codebattle/codebattle/assets/149536471/2223c2cf-9d0c-477b-8de5-2a17e05f98d3)

### Browsers

Qiaomi Redmi Note 12 Pro Plus

### OS

 Android 13

**Comment by ReDBrother** [comment]
Мы не отвечаем за разработку онлайн редактора и доступные нам варианты не поддерживают работу со смартфонами
