### ISSUE TITLE
Bug: Пользователь должен иметь возможность сменить язык с английского на русский в любой момент

### ISSUE THREAD

**Issue by Svetlana1618** [hexlet-codebattle/codebattle#1741]
### Summary

Пользователь должен в любой момент нахождения на сайте иметь возможность сменить язык с помощь выпадающего списка

### Reproduction steps

```bash
1. Заходим на главный страницу
2. Находим выпадающий список Language 
3. Меняем английский язык на русский
```

### Expected result

Пользователь видит поля и названия разделов на странице на русском языке

### Actual result

Отсутствует кнопка Language для смены языка

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нет, на сайте принято решение использовать общий для всех английский язык. Мультиязычность будет только на уровне контента (условия задач)
