### ISSUE TITLE
Bug: Основная страница сайта должна умещаться на один экран, без необходимости скролить

### ISSUE THREAD

**Issue by Svetlana1618** [hexlet-codebattle/codebattle#1742]
### Summary

Пользователь должен просматривать на экране монитора всю главную стараницу на одном экране без необходимсти скролить

### Reproduction steps

```bash
1. Переходим на главную страницу на веб-версиию сайта
2. Оцениваем весь ли контент размещен на одном экране
```

### Expected result

Пользователь видит все содержимое на одном экране, включая чат и "подвал"

### Actual result

Пользователь не видит всю информацию глафной странице на одном экране. Для того, чтобы увидеть чат и подвал, нужно скролить 
![Снимок экрана (76)](https://github.com/hexlet-codebattle/codebattle/assets/108014886/17b6766f-dec3-4eed-bc1b-d2aa0cd27b36)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это невозможно, слишком много элементов. В таких случаях это требование будет перебором
