### ISSUE TITLE
Bug: Пользователь должен иметь возможность выбрать несколько языков программирования  в настройках своего профиля

### ISSUE THREAD

**Issue by Svetlana1618** [hexlet-codebattle/codebattle#1744]
### Summary

Пользователь должен иметь возможность выбрать несколько языков программирования  в настройках своего профиля

### Reproduction steps

```bash
1. Нажимаем на иконку с фотографией
2. В открывшемся списке выбираем "Settings"
3. В открывшемся окне в списке "Your weapon" выбираем 2 языка программирования
```

### Expected result

Пользователь видит в списке "Your weapon" выбранными 2 языка программирования

### Actual result

Пользователь не имеет возможности указать второй язык программирования
![Снимок экрана (80)](https://github.com/hexlet-codebattle/codebattle/assets/108014886/ee2fe575-fbfe-49c1-8ac6-41eafc62244a)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нет, это у нас всего одна рука (один редактор кода), на нескольких языка сразу написать нельзя, всегда нужно взять один и сменить в редакторе кода, по необходимости
