### ISSUE TITLE
Bug: Поле Send Feedback не адаптировано на мобильном устройстве 

### ISSUE THREAD

**Issue by Yawerica** [hexlet-codebattle/codebattle#1748]
![Screenshot_2024-02-17-12-09-31-14_21da60175e70af211acc4f26191b7a77](https://github.com/hexlet-codebattle/codebattle/assets/148934630/cdd18a5f-e12b-41fd-bf0e-08e250ce603b)
### Summary

 Часть поля Send Feedback не помещается на экране мобильного устройства c разрешением монитора 1080х2400 и разрешением окна браузера 360х665

### Reproduction steps

```bash
1. Создать игру 
2. Кликнуть на кнопку Send Feedback

environment: Google Chrome, device realme 7 rmx2155, Android 10

Подобный баг ранее закрыт https://github.com/hexlet-codebattle/codebattle/issues/1660
```

### Expected result

Поле Send Feedback отображается полностью

### Actual result

Поле Send Feedback отображается частично

**Comment by ReDBrother** [comment]
Оно не наше) Мы используем стороннюю библиотеку компонентов)
