### ISSUE TITLE
Bug: Не работает ссылка из письма электронной почты для восстановления пароля 

### ISSUE THREAD

**Issue by Emik82** [hexlet-codebattle/codebattle#1749]
### Summary

При переходе по ссылке из письма сайт просит заново сбросить пароль 

Версия проекта:
[Current version: 93ddc8f](https://github.com/hexlet-codebattle/codebattle/commit/93ddc8f49be6cbab5b9bbb4509e4f047a0cb0168)
deployedAt UTC: 2024-02-14 13:02:00

### Reproduction steps

```bash
- Перейти на страницу авторизации https://codebattle.hexlet.io/session/new?locale=en&next=%2F
- Нажать на ссылку "Forgot your password?"
- Ввести email в поле "Email"
- Перейти по ссылке в письме электронной почты
```

### Expected result

 Пользователь успешно сбросил пароль и придумал новый

### Actual result

Ссылка не действительна 
Сайт просит заново сбросить пароль 
![Screenshot_1](https://github.com/hexlet-codebattle/codebattle/assets/149809192/fdde2f3b-d080-46a5-80bb-cdbecdbe386c)

При повторении операции ошибка повторяется

### Browsers

Chrome Версия 121.0.6167.185 (Официальная сборка), (64 бит)

### OS

Windows 11 Корпоративная Версия 22H2 Сборка 22621.3155

**Comment by diramiraz** [comment]
Yandex Browser
24.1.1.928 (64-bit)
Windows 11 Pro
23H2
22631.3155

Ошибка не подтвердилась если заново запросиль сброс. 
Скорее всего проблема в сроке давности ссылки.

**Comment by Emik82** [comment]
20 раз могу запросить сброс и результат будет тем же https://private-user-images.githubusercontent.com/149809192/305724519-fdde2f3b-d080-46a5-80bb-cdbecdbe386c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjMwMDYsIm5iZiI6MTcwODYyMjcwNiwicGF0aCI6Ii8xNDk4MDkxOTIvMzA1NzI0NTE5LWZkZGUyZjNiLWQwODAtNDZhNS04MGJiLWNkYmVjZGJlMzg2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNzI1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGQ5MDA5MzY2NzIwN2VhMDdjNmJlYzExNDU0ZTM4M2JmYzdjMGI3NmM3YjNlNWQ0MTBmM2YyMTRiNDhkMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ndXw3myqHvnnI9rLZp04DMM5fLeBG-kQWANIzc61gAk

**Comment by diramiraz** [comment]
На текущий момент я не смог повторить ваш баг. 3 из 3 - успешный сброс. 
Я подумал, а что если вы указываете почту которой нет? 
Оказывается проверка есть.

**Comment by Emik82** [comment]
проблема в регионе где я проживаю, с впн все работает

**Comment by ReDBrother** [comment]
Мы тут ничего не можем поделать, региональные ограничения не в нашей власти(
