### ISSUE TITLE
Feature: Неинформативное сообщение об ошибке привязки ранее зарегистрированного аккаунта github

### ISSUE THREAD

**Issue by OlgaSolodko** [hexlet-codebattle/codebattle#1753]
### Summary

Версия [93ddc8f](https://github.com/hexlet-codebattle/codebattle/commit/93ddc8f49be6cbab5b9bbb4509e4f047a0cb0168)
Неочевидно для пользователя, что чтобы привязать ранее зарегистрированные аккаунт github к новой почте нужно зайти через аккаунт гитхаб и в /settings нажать на unlink github, прежде чем привязывать его к другому аккаунту

### Reproduction steps

```bash
1. Авторизоваться под аккаунтом, привязанным к email, к которому не прилинкован гитхаб.
2. На странице https://codebattle.hexlet.io/settings нажать на Link github
3. Ввести данные аккаунта github, через который был вход раньше
```

### Expected result

Осуществляется привязка либо появляется модальное окно с объяснением, почему его нельзя привязать, либо сообщение, как его перепривязать

### Actual result

Появляется неинформативное сообщение во flash message: "github_id has been taken"
Привязки не происходит

### Browsers

Firefox, Chrome, Safari

### OS

Windows, Linux, Mac

**Comment by V-Leonteva-web** [comment]
summary:
Неинформативное сообщение об ошибке при попытке пользователя привязать аккаунт github, который уже привязан к другой учетной записи.

enviroment:
Google Chrome 121.0.6167.140 (Официальная сборка) (64 бит)
ОС Windows 10 Pro
Current version: 93ddc8f

test-data:
Почта: FreeViki@yandex.ru
Пароль: 1523434КtB1^hY

steps:
Вводим e-mail
Вводим пароль
Нажимаем на аватарку профиля
Нажимаем на "Setting"
Нажимаем на "Link Github"

expected-result:
Появилось сообщение с информацией о том, что этот аккаунт Github уже привязан к другому профилю

actual-result:
Появляется неинформативное сообщение "github_id has been taken"
![3](https://github.com/hexlet-codebattle/codebattle/assets/158027914/fe7e3b42-f450-454a-bc2e-e4b727ee15ce)
