### ISSUE TITLE
Bug: Лишний знак _ в выводе ошибки: INVALID_PASSWORD

### ISSUE THREAD

**Issue by diramiraz** [hexlet-codebattle/codebattle#1754]
### Summary

При вводе неправильного пароля высвечивается ошибка с лишним символом INVALID_PASSWORD

Yandex Browser
24.1.1.928 (64-bit)
Windows 11 Pro
23H2
22631.3155

![Снимок экрана 2024-02-21 194435](https://github.com/hexlet-codebattle/codebattle/assets/140488910/e89f2bfb-9f9f-4f52-881f-6ea0a0fd9f01)

### Reproduction steps

```bash
1. Sign in
2. Заполнить поля входа и ввести неправильный пароль
```

### Expected result

 INVALID PASSWORD

### Actual result

 INVALID_PASSWORD
![Снимок экрана 2024-02-21 194435](https://github.com/hexlet-codebattle/codebattle/assets/140488910/d12f14e8-5eb4-4367-8201-77429a8a9b6a)

### OS

Windows

**Comment by ReDBrother** [comment]
Нет такого правила) Это текстовый статус ошибки)
