### ISSUE TITLE
Bug: Лишний знак _ в выводе ошибки: TOO_MANY_ATTEMPTS_TRY_LATER

### ISSUE THREAD

**Issue by diramiraz** [hexlet-codebattle/codebattle#1755]
### Summary

При вводе неправильного пароля несколько раз подряд высвечивается ошибка с лишним символом TOO_MANY_ATTEMPTS_TRY_LATER

Yandex Browser
24.1.1.928 (64-bit)
Windows 11 Pro
23H2
22631.3155

### Reproduction steps

```bash
1. Sign in
2. Заполнить поля входа и ввести неправильный пароль несколько раз
```

### Expected result

TOO MANY ATTEMPTS TRY LATER

### Actual result

TOO_MANY_ATTEMPTS_TRY_LATER
![Снимок экрана 2024-02-21 200024](https://github.com/hexlet-codebattle/codebattle/assets/140488910/090f813f-2277-4d98-ba5b-df45cc1d46b3)

**Comment by ReDBrother** [comment]
Нет такого правила) Это текстовый код ошибки)

**Comment by diramiraz** [comment]
> Нет такого правила) Это текстовый код ошибки)

Есть визуальный шум. Однако, когда ты вводишь не верный email, то ты ссылаешь на какое-то правило и делаешь красиво. Получается: в одном месте у тебя по какому-то правилу, а по второму у тебя на от****сь. 
Как это понимать?

**Comment by ReDBrother** [comment]
Тогда дело точно не в числе нижних подчеркиваний)) Приведение всех кодов ошибок к литературному виду совершенно другая задача, и у нее есть минусы - она будет неинформативна для программистов, которые эту проблему будут решать, если это не ошибка на стороне пользователя)
