### ISSUE TITLE
Bug: Проверка вывода правильного сообщения об ошибке при вводе некорректного никнейма (на кириллице)

### ISSUE THREAD

**Issue by vishnevoe** [hexlet-codebattle/codebattle#1760]
### Summary

При регистрации нового пользователя выводится неправильное сообщение с требованиями к никнейму: "Can contain letters, numbers and underscores and **should begin** with a Latin letter".
Сообщение ошибочно, так как никнейм не должен содержать кириллических символов на любой позиции, а в тексте сообщения сейчас есть требование о том, что только первая буква никнейма должна быть латинской. 
![image](https://github.com/hexlet-codebattle/codebattle/assets/72604628/b6cf8771-e10d-430d-adde-44438aa005d6)

### Reproduction steps

```bash
- Открыть страницу регистрации
- Ввести никнейм нового пользователя, в котором первая буква будет латинской, а остальные — кириллица
- Ввести остальные данные для регистрации (адрес электронной почты, пароль, подтверждение пароля)
- Нажать кнопку Submit
```

### Expected result

Выводится сообщение о том, что никнейм не должен содержать кириллические символы/должен содержать только латинские символы, цифры, нижние подчеркивания

### Actual result

Выводится сообщение: "Can contain letters, numbers and underscores and should begin with a Latin letter"

Browsers
Chrome version 122.0.6261.69 (Official Build) (64-bit)

OS
Windows 10 Версия 22H2 (Сборка 19045.4046)

Site version
[93ddc8f](https://github.com/hexlet-codebattle/codebattle/commit/93ddc8f49be6cbab5b9bbb4509e4f047a0cb0168)

**Comment by diramiraz** [comment]
Yandex Browser
24.1.1.928 (64-bit)
Windows 11 Pro
23H2
22631.3155

- https://codebattle.hexlet.io/users/new
- Sign Up
![Снимок экрана 2024-02-27 170609](https://github.com/hexlet-codebattle/codebattle/assets/140488910/8ef31e60-ade4-4129-bc91-f4bb55522b46)

**Comment by KirillTheStranger** [comment]
Возьму в работу
