### ISSUE TITLE
Bug: Некоторые игры не привязаны ни к одной категории (tags)

### ISSUE THREAD

**Issue by no-twoo** [hexlet-codebattle/codebattle#1761]
### Summary

При создании игры и выборе ее по названию, не всегда выбирается категория (тег), которой соответствует игра

![баг с тегами](https://github.com/hexlet-codebattle/codebattle/assets/109661239/fa650b71-7c87-4928-98e0-750a8c7fcdac)
![баг с тегами 2](https://github.com/hexlet-codebattle/codebattle/assets/109661239/c30ed97a-5d6e-443a-8377-8b3d21a2d9af)

### Reproduction steps

```bash
1. Выбираем Level - 2
2. Выбираем игру с названием "excel_sheet_column_number"
3. Смотрим к какой категории относится игра
4. Выбираем Level - 3
5. Выбираем игру с названием "bulls_and_cows"
6. Смотрим к какой категории относится игра
```

### Expected result

Выбранная игра должна соответствовть каким-либо из предложенных категорий

### Actual result

Выбранная игра не соответствует ни одной из предложенных категорий

### Browsers

Chrome, Opera

### OS

Windows

**Comment by ReDBrother** [comment]
И не должны, это опциональная история
