### ISSUE TITLE
Bug: Не отображается дата начала турнира 

### ISSUE THREAD

**Issue by Serg71test** [hexlet-codebattle/codebattle#1763]
### Summary

На  стартовой странице турнира не отображается дата его начала

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать кнопку профиля игрока в шапке сайта
3. Нажать кнопку «Tournaments»
4. Листаем вниз до окна создания турнира «Create a new tournament»
5. В поле «Starts at» устанавливаем любую дату, можно оставить текущую
6. Нажать кнопку «Create»
7. Открылось окно старта турнира
```

### Expected result

В окне отображается установленная дата старта турнира
![1](https://github.com/hexlet-codebattle/codebattle/assets/152961158/7861cd71-64d7-4580-b035-d2a82dac15ea)
![2](https://github.com/hexlet-codebattle/codebattle/assets/152961158/feb1810b-764e-4f0f-94f1-ca9f2da852de)

### Actual result

Дата старта турнира не отображается

### Browsers

Firefox Browser 123.0 (64-разрядный)

### OS

Windows 10 Pro 22H2

Current version: https://github.com/hexlet-codebattle/codebattle/commit/93ddc8f49be6cbab5b9bbb4509e4f047a0cb0168

**Comment by ReDBrother** [comment]
Это значит что время прошло

**Comment by Serg71test** [comment]
Не значит ничего. Любую другую дату поставь попробуй. Не текущую.

**Comment by MziyaUsubova** [comment]
Не работает счетчик даты 

<img width="1008" alt="Screenshot 2024-03-07 at 10 52 28" src="https://github.com/hexlet-codebattle/codebattle/assets/152481283/84fb9017-3cbc-467f-a681-ff46e322fbf2">
<img width="1324" alt="Screenshot 2024-03-07 at 10 54 59" src="https://github.com/hexlet-codebattle/codebattle/assets/152481283/a494096d-8a35-4d18-8af6-669c03aabfc2">
