### ISSUE TITLE
Bug: Повторная игра с другом

### ISSUE THREAD

**Issue by diramiraz** [hexlet-codebattle/codebattle#1765]
### Summary

После нажатия на кнопку Rematch появляется сообщение: 
Server is temporarily unavailable ¯\_(ツ)_/¯ :prod_is_down:

Yandex Browser
24.1.1.928 (64-bit)
Windows 11 Pro
23H2
22631.3155
and
Google Chrome
22.0.6261.69 (Официальная сборка), (64 бит)
Windows 11 Pro
23H2
22631.3155

### Reproduction steps

```bash
1. Пригласить друга (в моем случае в два браузера) 
2. Дождаться, пока пройдет время
3. Нажать на кнопку Rematch
![Снимок экрана 2024-02-28 231843](https://github.com/hexlet-codebattle/codebattle/assets/140488910/a72caa2c-8a33-452a-b0b8-f79640422075)

```

### Expected result

Должна начаться новая игра с другом

### Actual result

Server is temporarily unavailable ¯\_(ツ)_/¯ :prod_is_down:
![Снимок экрана 2024-02-28 230304](https://github.com/hexlet-codebattle/codebattle/assets/140488910/26b38eee-4646-48d3-82e7-211cc6f2b8c7)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
У игры фиксированное время на рематч и он довольно плавающий
