### ISSUE TITLE
Bug: ошибка 429 при нажатии на Run в окне написания кода

### ISSUE THREAD

**Issue by MarinArinHolzy** [hexlet-codebattle/codebattle#1767]
### Summary

При нажатии на Run в окне написания кода возникает ошибка 429 и процесс Running становится бесконечным.
Windows 10 версия 22H2
Chrome версия 122.0.6261.94 (Официальная сборка), (64 бит)
Current version: 93ddc8f
![429](https://github.com/hexlet-codebattle/codebattle/assets/157614611/a86543b6-1548-4a0a-a741-59e8362d2278)

### Reproduction steps

```bash
1. Авторизоваться и создать игру с ботом
2. Открыть DevTools, перейти во вкладку Network
3. В окне написания кода нажать кнопку Run
```

### Expected result

Проверка написанного кода и завершение игры в случае правильного написания кода или продолжение игры в случае, если код содержит ошибки.

### Actual result

Процесс Running становится бесконечным, ошибка 429.

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Он точно не бесконечен, даже запущенная проверка работает максимум пару минут
Все запуски проверки решения идут по вебсокетам, не через fetch запрос, проблема связана с чем-то другим. Ошибка которую регистрируем выше связана с отправкой отчета в выделенный логер и он еще никогда не ломал нам интерфейс.

Воспроизвести не получается

**Comment by forestskseaforestskysea** [comment]
https://github.com/hexlet-codebattle/codebattle/issues/1789

повторяется при выборе звука Standard
