### ISSUE TITLE
Bug: Нельзя просмотреть лидеров "месяца" и "все" при русской локали

### ISSUE THREAD

**Issue by 07lu** [hexlet-codebattle/codebattle#1768]
### Summary

При переводе локали на русский язык, не открываются вкладки просмотра лидеров месяца и общий список лидеров ( при условии, что изначально были открыты лидеры недели)
Windows 10 версия 22H2
Chrome Версия 122.0.6261.94 (Официальная сборка), (64 бит)
Версия приложения: Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

### Reproduction steps

```bash
1. На главной странице перевести локаль на русский язык
2. Нажать на кнопку в таблице лидеров "месяц"
3. Нажать на кнопку в таблице лидеров "все"
```

### Expected result

![Снимок экрана 2024-03-01 165044](https://github.com/hexlet-codebattle/codebattle/assets/149497325/d86f855b-9d01-4bf4-a4ac-1132cc40b3c2)

### Actual result

При нажатии не происходит переход по параметрам

**Comment by ReDBrother** [comment]
fixed
