### ISSUE TITLE
Bug: В мобильной версии сайта интерфейс окна выбора смайла обрезан

### ISSUE THREAD

**Issue by MziyaUsubova** [hexlet-codebattle/codebattle#1778]
### Summary

Bug: В мобильной версии сайта левая сторона интерфейса окна при попытке выбрать смайл  обрезана
Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1
[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

### Reproduction steps

```bash
Главная страница 
Создать игру с ботом 
Начать игру 
Кликнуть в поле ввода сообщения в чате 
Кликнуть смайл
```

### Expected result

окно полностью видимо и чиатемо

### Actual result

Интерфейс слева не 
<img width="742" alt="Screenshot 2024-03-08 at 12 02 10" src="https://github.com/hexlet-codebattle/codebattle/assets/152481283/99f1836f-a710-4e07-80e9-72a01dc26728">
 полностью видим и чиатем

### OS

Mac

**Comment by argon06** [comment]
Проблема актуальна
https://github.com/hexlet-codebattle/codebattle/issues/1794

**Comment by ReDBrother** [comment]
Не наша либа, мы ее не контрлируем(
