### ISSUE TITLE
Bug:  Опечатка на стартовой странице ресурса

### ISSUE THREAD

**Issue by kondratievSE** [hexlet-codebattle/codebattle#1781]
### Summary

Опечатка на стартовой странице в словосочетание "each o**h**ter"
Environment:
Browsers
Яндекс Браузер
Версия
24.1.3.809 (64-bit)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle
Current version: a939c29

![opechatka](https://github.com/hexlet-codebattle/codebattle/assets/156944120/0da13e5e-7d91-4b34-a34c-169734377827)
 

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/
2. Scroll down to {{USER::TYPES}}
```

### Expected result

For friends who want to battle each **other**

### Actual result

For friends who want to battle each **ohter**

### Browsers

Chrome

### OS

Windows

**Comment by BrovkinaAlexandra** [comment]
Баг с опечаткой еще есть
[Current version: a939c29]
![Monosnap Hexlet Codebattle • Game for programmers ](https://github.com/hexlet-codebattle/codebattle/assets/152964007/f664f1d0-397a-47b2-b8f4-f7a7f44ff9e7)
