### ISSUE TITLE
Bug: Функция Х ("Close") выполняет сворачивание окна в руководстве. 

### ISSUE THREAD

**Issue by kondratievSE** [hexlet-codebattle/codebattle#1782]
### Summary

Environment:
Browsers
Яндекс Браузер
Версия
24.1.3.809 (64-bit)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle
Current version: https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8

В созданной игре при нажатии Show guide, всплывающее окно при нажатии на крест (close) сворачивается, а не закрывается как ожидается, оставляя мерцающую точку на одном из пунктов разъяснений правил. Что довольно не ожиданно и приводит к не пониманию, что следует сделать дальше. Чтобы полностью закрыть всплывающее руководство необходимо найти пункт Skip guide, что не совсем прямолинейно, по сравнению с пиктограммой "Крест".

![2024-03-13_14-41-05](https://github.com/hexlet-codebattle/codebattle/assets/156944120/d4e88e97-69c2-49b5-8fe1-474943d31a59)

![2024-03-13_14-41-37](https://github.com/hexlet-codebattle/codebattle/assets/156944120/82584991-fef2-4d94-9341-6ac7a577106e)

![2024-03-13_15-22-28](https://github.com/hexlet-codebattle/codebattle/assets/156944120/4a6e1c16-28d4-4d82-9460-bac70f9e5216)

### Reproduction steps

```bash
1. Open https://codebattle.hexlet.io/#lobby
2. Press "Create a Game"
3. Press "Show guide"
4. Press X ("CLOSE")
```

### Expected result

Закрытие всплывающего окна руководства

### Actual result

Сворачивание всплывающего окна руководства

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1356

**Comment by kondratievSE** [comment]
Дубль от #1356 констатирует о наличии артефакта в виде круга.  Issue #1782 открыт на bug о неправильном поведении кнопки "закрыть окно". Кнопка "закрыть окно" (Х) - фактически сворачивает окно, а не закрывает его.
