### ISSUE TITLE
Bug: Опечатка на стартовой странице ресурса

### ISSUE THREAD

**Issue by BrovkinaAlexandra** [hexlet-codebattle/codebattle#1783]
### Summary

Опечатка на стартовой странице в словосочетание "each ohter" 
Environment:
Browsers
Google Chrome
Версия 122.0.6261.112 (Официальная сборка), (64 бит)

OS
Windows 11

Закрытый баг 
https://github.com/hexlet-codebattle/codebattle/issues/1781

Codebattle
Current version: [a939c29]

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/
2. Scroll down to {{USER::TYPES}}
```

### Expected result

For friends who want to battle each other

### Actual result

For friends who want to battle each ohter
![Monosnap Hexlet Codebattle • Game for programmers ](https://github.com/hexlet-codebattle/codebattle/assets/152964007/e42f2818-c91f-491e-bb0d-8b611005d1ef)

### Browsers

Chrome

### OS

Windows

**Comment by argon06** [comment]
Google Chrome Версия 121.0.6167.85 (Официальная сборка), (64 бит)
ОС Windows 10 Pro 22H2
![Снимок экрана 2024-03-16 132420](https://github.com/hexlet-codebattle/codebattle/assets/1496422/8c74b901-a6de-4cee-b75c-e575f4de9f0d)

**Comment by ReDBrother** [comment]
Fixed
Deploy later

**Comment by BrovkinaAlexandra** [comment]
"Версия приложения на которой проводились тесты -  a939c29"
