### ISSUE TITLE
Bug: Не обрезаются символы поля Nickname при регистрации через Github и Discord

### ISSUE THREAD

**Issue by forestskysea** [hexlet-codebattle/codebattle#1786]
### Summary

Не обрезаются символы поля Nickname при регистрации через Github и Discord

### Reproduction steps

```bash
Предусловие: Есть аккаунт на Github или Discord с именем пользователя более 16 символов, например, forestkyseaforestskysea

1. Зарегистрироваться на сайте через Github или Discord
2. Развернуть меню профиля в шапке сайта, открыть Settings
3. Изменить одну из настроек, например, Select sound type
```

### Expected result

Ник обрезается автоматически до допустимого количества символов и удается сохранить настройки

### Actual result

Ник не обрезается из-за чего пользователь не может менять настройки

![chrome_zeTszTUpLg](https://github.com/hexlet-codebattle/codebattle/assets/157843220/94accd1e-0bdf-4509-ac65-dac433a89cf3)

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows

**Comment by forestskysea** [comment]
[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

deployedAt UTC: 2024-03-04 10:09:46

**Comment by ReDBrother** [comment]
Не, мы не будем обрезать имена сами, это слишком неочевидная штука. Мы попробуем отключить валидацию, если имя не было изменено в настройках

**Comment by ReDBrother** [comment]
Fixed
Deploy later
