### ISSUE TITLE
Bug: Не обрезается количество символов при добавлении автосгенерированного кода в существующий Nickname

### ISSUE THREAD

**Issue by forestskysea** [hexlet-codebattle/codebattle#1787]
### Summary

Не обрезается количество символов в существующем Nickname с добавлением автосгенерированного кода при регистрации через Github и Discord 

### Reproduction steps

```bash
1. Зарегистрироваться на сайте с ником более 12 символов
2. Зарегистрироваться на сайте через Github или Discord с таким же ником
3. Развернуть меню профиля в шапке сайта, открыть Settings
4. Изменить одну из настроек, например, Select sound type
```

### Expected result

Символы в поле Nickname обрезаются согласно допустимому значению, можно сохранить настройки

### Actual result

При регистрации через Github или Discord под пользователем с существующем на сайте Nickname к нику добавляется пятизначный код, и количество символов не обрезается, невозможно сохранить настройки 
![image](https://github.com/hexlet-codebattle/codebattle/assets/157843220/2f956799-aae7-4c60-bec3-0ab90d4b60ab)

### Browsers

Chrome, Mozila, Edge, Opera

### OS

Windows

**Comment by forestskysea** [comment]
[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

deployedAt UTC: 2024-03-04 10:09:46

**Comment by ReDBrother** [comment]
Такие скрытые возможности формы недопустимы. Мы поменяли правила валидации, чтобы старые имена не ломали сохранение настроек, только если имя пытаются поменять.
