### ISSUE TITLE
Bug: Не выполняется регистрация с 1 символом перед @ в поле email

### ISSUE THREAD

**Issue by forestskysea** [hexlet-codebattle/codebattle#1788]
### Summary

Нельзя выполнить регистрацию с 1 символом перед @ в поле email

### Reproduction steps

```bash
1. На главной странице нажать кнопку Sign up
2. Заполнить поле Nickname
3. В поле Email ввести любой адрес с 1 символом перед @, например, S@hg.ru
4. Заполнить поле Password
5. Подтвердить пароль в поле Password Confirmation
6. Нажать кнопку Submit
```

### Expected result

Регистрация с email с 1 символом перед @ выполняется успешно

### Actual result

Регистрация не выполняется с email с 1 символом перед @

![image](https://github.com/hexlet-codebattle/codebattle/assets/157843220/f6cd3c45-7659-4ed0-9489-7e2fb421f2c1)

### Browsers

Firefox, Chrome, Opera

### OS

Windows

**Comment by forestskysea** [comment]
[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

deployedAt UTC: 2024-03-04 10:09:46

**Comment by ReDBrother** [comment]
fixed
Deploy later

**Comment by BigZiano** [comment]
Воспроизвел в версии Current version: 6b220bb 
environment: |
Яндекс Браузер Версия 24.1.5.803 (64-bit) Windows 10 Pro Версия 22H2 Сборка ОС 19045.4291
[Current version: 6b220bb]
steps:
1. На главной странице нажать кнопку Sign up
2. Заполнить поле Nickname
3. В поле Email ввести любой адрес с 1 символом перед @, например, S@hg.ru
4. Заполнить поле Password
5. Подтвердить пароль в поле Password Confirmation
6. Нажать кнопку Submit
![image](https://github.com/hexlet-codebattle/codebattle/assets/162887947/ac52bf91-06f1-4f6a-a508-3520b8ba192f)
Ожидаемый результат
Регистрация с email с 1 символом перед @ выполняется успешно
Фактический результат
Регистрация не выполняется с email с 1 символом перед @
