### ISSUE TITLE
Bug: Не выполняется регистрация с Nickname , начинающимся с цифр

### ISSUE THREAD

**Issue by forestskysea** [hexlet-codebattle/codebattle#1790]
### Summary

Не выполняется регистрация с Nickname , начинающимся с цифр

[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

deployedAt UTC: 2024-03-04 10:09:46

### Reproduction steps

```bash
1. На главной странице сайта нажать на кнопку Sign up
2. В поле Nickname ввести ник с цифрами в начале, например, 88888jjkk
3. В поле email ввести email
4. Заполнить поле Password
5. Подтвердить пароль в поле Password confirmation
6. Нажать кнопку Submit
```

### Expected result

Регистрация выполняется успешно

### Actual result

Регистрация с Nickname с цифрами в начале не выполняется, выводится сообщение Should contain Latin letters only, also can contain numbers and underscores

![image](https://github.com/hexlet-codebattle/codebattle/assets/157843220/f08bd0b5-475e-4401-aa8c-a98f5640c1c5)

![image](https://github.com/hexlet-codebattle/codebattle/assets/157843220/f5a49f48-f7d3-4e7c-a04c-a04c7921016a)

### Browsers

Firefox, Chrome, Opera

### OS

Windows

**Comment by forestskysea** [comment]
[Current version: a939c29](https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8)

deployedAt UTC: 2024-03-04 10:09:46

**Comment by ReDBrother** [comment]
Не уточнено правило что имя должно начинаться с латинского символа.
Fixed
