### ISSUE TITLE
Не отображается графическое выделение функциональной кнопки создания турнира ( "цветной прямоугольник" )

### ISSUE THREAD

**Issue by kondratievSE** [hexlet-codebattle/codebattle#1792]
### Summary

 Не отображается графическое выделение кнопки создания турнира ( "цветной прямоугольник" ) либо графически не выполнено цветовое выделение функциональной кнопки перехода к созданию турнира.
    Environment:
Browsers
Яндекс Браузер
Версия
24.1.3.809 (64-bit)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle  Current version: https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8

### Reproduction steps

```bash
steps-to-reproduce: |
    1. Авторизоваться
    2. Перейти на вкладку Tournaments
```

### Expected result

    Функциональная кнопка перехода к созданию турнира визуально легко идентифицируется 
![2024-03-15_18-22-56](https://github.com/hexlet-codebattle/codebattle/assets/156944120/a0842e04-c8b9-4ba2-ae18-73a8a1cac848)

### Actual result

 Функциональная кнопка перехода к созданию турнира "You may want to create one" не визуабельна.
![2024-03-15_18-22-47](https://github.com/hexlet-codebattle/codebattle/assets/156944120/a0cf0fa8-1190-4e9d-8e52-da7be9324889)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Fixed
Deploy it later
