### ISSUE TITLE
Bug: Ошибка в тексте кнопки Create invate

### ISSUE THREAD

**Issue by argon06** [hexlet-codebattle/codebattle#1793]
### Summary

При отправке приглашения на дуэль пользователь  написано "Create invate", а должно быть "Create an invate"

### Reproduction steps

```bash
1. В разделе Лобби выбираем любого пользователя
2. В открывшемся меню выбираем "Send an invite"
3. Нажимаем "Create invite"
```

### Expected result

Текст на кнопке в шаге 3 "Create an  invite"

### Actual result

Текст на кнопке в шаге 3 "Create 
![Снимок экрана 2024-03-16 122246](https://github.com/hexlet-codebattle/codebattle/assets/1496422/37b2350e-42b5-4589-8251-24b785e2e46e)
invite"

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Правильного не существует)
Прилагательные типа a(n) или the нужен исключительно для уточнения принадлежности. В этом контексте это не требуется и только кнопку утолщает)
