### ISSUE TITLE
Bug: В мобильной версии сайта интерфейс окна выбора смайла обрезан

### ISSUE THREAD

**Issue by argon06** [hexlet-codebattle/codebattle#1794]
### Summary

В мобильной версии сайта интерфейс окна выбора смайла обрезан
Android 14; SM-G991B Build/UP1A.231005.007
Chrome 122.0.6261.119

### Reproduction steps

```bash
1. На главной находим чат
2. Кликаем на смайл
```

### Expected result

окно полностью видимо и чиатемо

### Actual result

Интерфейс обрезан слева
![photo_2024-03-16_13-30-38](https://github.com/hexlet-codebattle/codebattle/assets/1496422/930c2096-622e-40cd-b40d-521c2c0839de)

### Browsers

Chrome

### OS

Linux

**Comment by ReDBrother** [comment]
fixed
Deploy later
