### ISSUE TITLE
Bug: Не отправляется GET запрос при наведении курсора на никнеймы игроков, которые находятся Онлайн

### ISSUE THREAD

**Issue by kondratievSE** [hexlet-codebattle/codebattle#1799]
### Summary

Summary
Не отправляется GET запрос при наведении курсора на никнеймы игроков, которые находятся Онлайн, для получения информации о пользователе.

Environment:
Browsers
Яндекс Браузер
Версия
24.1.3.809 (64-bit)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle
Current version: https://github.com/hexlet-codebattle/codebattle/commit/a939c2911545c6e6081ba29fb6c7aaf698f1f7a8

![2024-03-18_14-30-20](https://github.com/hexlet-codebattle/codebattle/assets/156944120/c60e4242-ac55-45f6-8fce-ec4114d4bd65)

### Reproduction steps

```bash
1. Авторизоваться
2. В лобби наводим курсор на пользователей "онлайн"
```

### Expected result

Отправляется GET запрос. Появляется всплывающее окно (как при наведении в рейтинге) с краткой информацией о пользователе.

![2024-03-18_14-31-26](https://github.com/hexlet-codebattle/codebattle/assets/156944120/8c3f6349-cbf7-4bab-8c17-f3215d0860be)

### Actual result

GET запрос не отправляется при наведении курсора. Всплывающее окно (как при наведении в рейтинге) с краткой информацией о пользователе не появляется.

![2024-03-18_14-32-22](https://github.com/hexlet-codebattle/codebattle/assets/156944120/11b9207a-f335-47ac-822a-8f810908b11f)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Оно ломает другой юзкейс открытия контекстного меню
