### ISSUE TITLE
Заменить brunch на webpack2

### ISSUE THREAD

**Issue by mokevnin** [hexlet-codebattle/codebattle#18]
http://www.phoenixframework.org/docs/static-assets

**Comment by sashashakun** [comment]
Буду пилить в среду вечером, если кто раньше возьмется - welcome

**Comment by krivtsov** [comment]
https://habrahabr.ru/post/331598/

**Comment by lazycoder9** [comment]
Я берусь за этот issue, под присмотром @sashashakun

**Comment by lazycoder9** [comment]
Done https://github.com/hexlet-codebattle/codebattle/commit/bfc2d4d9cc2bda6267c8164cde333e74fcc604dc
