### ISSUE TITLE
Bug: Нет возможности закрыть private channel

### ISSUE THREAD

**Issue by kondratievSE** [hexlet-codebattle/codebattle#1801]
### Summary

Нет возможности удалить из списка (закрыть) личный чат.

Environment:
Browsers
Яндекс Браузер
Версия
24.1.3.809 (64-bit)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle
Current version: https://github.com/hexlet-codebattle/codebattle/commit/bff4aa73d0a2c8f1018c26927964071871ad1ae7

### Reproduction steps

```bash
1. ПМК нажать на никнейм игрока онлайн
2. Выбрать "отправить сообщение"
3. Открыть список чатов
```

### Expected result

Есть возможность закрыть личный чат (контекстное меню, пиктограмма "крест" на против никнейма)

![2024-03-19_14-04-08](https://github.com/hexlet-codebattle/codebattle/assets/156944120/630c4721-60e7-4946-8ffd-0492043d8499)

### Actual result

Нет возможности закрыть личный чат 

![2024-03-19_14-04-08](https://github.com/hexlet-codebattle/codebattle/assets/156944120/06401b51-4dd8-459e-95f3-1a2a57b37206)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы не хотим создавать полноценный чат
Все чаты удаляются со временем, если ими не пользуются (На сколько я помню, там неделя поставлена)
