### ISSUE TITLE
Bug: Список private channel растет до бесконечности. Возможно нужен скролл внутри списка

### ISSUE THREAD

**Issue by kondratievSE** [hexlet-codebattle/codebattle#1802]
### Summary

Личные чаты накапливаются до бесконечности сдвигая лобби вниз

Environment:
Browsers
Яндекс Браузер
Версия
24.1.3.809 (64-bit)

OS
Windows 10 Домашняя
Версия 22H2

Codebattle
Current version: https://github.com/hexlet-codebattle/codebattle/commit/bff4aa73d0a2c8f1018c26927964071871ad1ae7

### Reproduction steps

```bash
1. ПМК нажать на никнейм игрока онлайн
2. Выбрать "отправить сообщение"
3. Повторить шаг 1 и 2 20-30 раз, не повторяя никнеймы
```

### Expected result

Список чатов выводит 10 никнеймов с сортировкой по частоте использования ( никнейму ), следующие никнеймы (private channel) можно скроллить.

### Actual result

Список чатов выводит все никнеймы (private channel). Список растет вниз со скроллингом основной страницы бесконечно.

![2024-03-19_14-12-12](https://github.com/hexlet-codebattle/codebattle/assets/156944120/0f618934-b2b1-48ac-82af-5a3234700e77)

**Comment by ReDBrother** [comment]
Общительный)
Ок, чуть подрежем список)

**Comment by MaratSalakh** [comment]
Беру в работу.
