### ISSUE TITLE
Bug: Некорректно отображаются турниры при прокрутке в мобильной версии

### ISSUE THREAD

**Issue by Zofore** [hexlet-codebattle/codebattle#1805]
### Summary

Некорректно отображаются турниры при прокрутке в мобильной версии 
Iphone XR
Версия [Current version: bff4aa7](https://github.com/hexlet-codebattle/codebattle/commit/bff4aa73d0a2c8f1018c26927964071871ad1ae7)

### Reproduction steps

```bash
1. На главной странице переходим в турниры
2. Листаем турниры вправо
```

### Expected result

Турниры должны корректно отображаться в рамках прокрутки и быть читаемы

### Actual result

Некорректно отображаются, сразу два турнира на экране
![турниры11](https://github.com/hexlet-codebattle/codebattle/assets/153725639/d66d4fc4-708d-4630-b746-94125b3005bf)

**Comment by ReDBrother** [comment]
Они корректно отображаются и что самое главное, нет никаких препятствий, чтобы полностью контент увидеть
