### ISSUE TITLE
Bug: Current version ломает границы при ширине экрана меньше 300

### ISSUE THREAD

**Issue by 2laexe** [hexlet-codebattle/codebattle#1811]
### Summary

https://github.com/hexlet-codebattle/codebattle/issues/1642#issue-1966505811

При ширине экрана 300 и меньше "Current version " остается на месте, а сама страница сужается и остается черная полоса справа

### Reproduction steps

```bash
1. https://codebattle.hexlet.io/#lobby
2. DevTools
3. Мобильная версия (Responsive)
```

### Expected result

Адаптация сайта прошла успешно

### Actual result

https://github.com/hexlet-codebattle/codebattle/commit/85a7a93e3da39e9b4d05a460667cbcd4aeb7f695

Имеет свои границы
Начиная с ширины экрана меньше 300 "Версия" остается на своем месте, а сайт сужается

### Browsers

Chrome

### OS

Windows

![Без имени](https://github.com/hexlet-codebattle/codebattle/assets/100873772/748518ec-d6fa-46b5-b1a5-8fdf50786edc)

**Comment by ReDBrother** [comment]
Мы не будем даже пытаться на такие мелкие размеры ориентироваться.
Если хотите проверить мобильную верстку, то используйте характеристики существующих мобильных устройств и не устаревших моделей.
