### ISSUE TITLE
Code erasing does not work in mobile Chrome

### ISSUE THREAD

**Issue by LazataknesSoftware** [hexlet-codebattle/codebattle#1814]
I want to play Codebattle in Chrome on Android. Game runs, all showing, text typing works - OK, but there is huge problem: backspace to delete code does not work.

**Comment by ReDBrother** [comment]
Hi, Thanks for report

Our online editor (Monaco) doesn't support mobile. More details: https://github.com/microsoft/monaco-editor/issues/246
