### ISSUE TITLE
Bug: В блоке "копирайт" год не соответствует текущему

### ISSUE THREAD

**Issue by AndyVish** [hexlet-codebattle/codebattle#1815]
### Summary

В блоке "копирайт" год не соответствует текущему

Browsers: Firefox 115.6.0esr (64-разрядный)
OS: Windows 7 Профессиональная
![bad-year](https://github.com/hexlet-codebattle/codebattle/assets/44895790/f035e810-434d-40ed-bfd8-3aaac41b9db5)

### Reproduction steps

```bash
Перейти на страницу https://codebattle.hexlet.io
 Перейти в footer страницы
 Сравнить, что год указанный в блоке "копирайт" соответствует текущему году
```

### Expected result

Пользователь должен видеть актуальный год в блоке "копирайт", т.е. 2024

### Actual result

Год 2023

### Browsers

Firefox

### OS

Windows

**Comment by Maicuduc-123** [comment]
На странице codebattle дата и время не соответствуют реальным
Яндекс Браузера
Версия
24.6.1.766 (64-bit)
![Uploading 2024-07-09_13-38-17.png…]()
