### ISSUE TITLE
Bug: Бот не играет

### ISSUE THREAD

**Issue by AIonLisa** [hexlet-codebattle/codebattle#1818]
### Summary

При создании игры с ботом, бот не участвует в игре, решает задачу только пользователь

### Reproduction steps

```bash
1. Нажать Create a game
2. Выбрать любой уровень сложности
3. Нажать With a bot
4. Выбрать Time control - 3 мин
5. Нажать Create battle
6. Обратить внимание на окно редактора бота
```

### Expected result

Бот решает задачу

### Actual result

Бот не решает задачу

### Browsers

Chrome

### OS

Windows

[Current version: 5876eae](https://github.com/hexlet-codebattle/codebattle/commit/5876eaeafb7b02558fa8acaa25fef615291e71a9)

**Comment by Azraillier** [comment]
- summary: 
    Во время игры бот не решает задание 
    
-  environment: 
    Google Chrome Версия 122.0.6261.95 (Официальная сборка), (64 бит)
    Mozilla Firefox Версия 124.0.2 (64-разрядный)
    Yandex Browser Версия 24.1.5.736 (64-bit)
    Mozilla Firefox Snap for Ubuntu Версия 124.0.2 (64-разрядный)
    ОС Windows 10
    ОС Ubuntu
    Current version: [2a3d15d](https://github.com/hexlet-codebattle/codebattle/commit/2a3d15d82f1b38cbfc9f7964f2ac5e967c0c013c)
    deployedAt UTC: 2024-04-03 12:22:16    

-  prerequisites: 
    Авторизоваться в Codebattle
    
-  steps-to-reproduce: 
    1. Создать игру с ботом по сценарию
    - Level 1
    - Game Type with a bot 
    - Time control 3 
    - Name rect_area
    2. Решить задание
    3. Дождаться окончания игры
    4. Обратить внимание на редактор кода бота
    
-  expected-result: 
    К концу игры в редакторе бота готов код с решением задания

-  actual-result: 
    Бот не решает задание на протяжении всего времени игры
    В независимости от результата игры бот не выполняет никаких действий
    
![1](https://github.com/hexlet-codebattle/codebattle/assets/75273530/b74c2af9-00f8-4d57-823c-b8f2b6f93a73)
![2](https://github.com/hexlet-codebattle/codebattle/assets/75273530/3f37b362-717f-4554-a6cc-354d12cd2a40)

**Comment by Sh3rlock-git** [comment]
**Summary**
Бот не решает задачу в созданной игре

**Reproduction steps**

1. Нажать на кнопку Create a game
2. Выбрать любой уровень сложности
3. Установить game type - with a bot
4. Установить time control 3 мин
5. Нажать на кнопку Create battle

**Expected result**
Бот решает задание.
В редакторе кода бота отображается написанный им код

**Actual result**
Бот не решает задачу
В редакторе кода бота не отображается написанное решение

**Reproduced in version**
 [b2aa41d](https://github.com/hexlet-codebattle/codebattle/commit/b2aa41d1deb34a9dc06d44586057eb4c6095d051)

*Environment**
OS Windows 10 Pro x64
Yandex.Browser 24.1.5.736 (64-bit)
![codebattle_game_with_bot](https://github.com/hexlet-codebattle/codebattle/assets/158310621/f204fac5-a76d-49ee-8512-a78dadcf0407)

**Comment by GhArKn** [comment]
- summary: |
     Бот не играет
  environment: |
       Yandex 120.0.6099.736 (64-разрядная версия)
       Windows 11 Version 23H2 (Build 22631.3447)
   steps-to-reproduce: |
    - Создаем игру нажав на кнопку "Create a game"
    - Выбираем параметр "Game Type" c значением "With a bot", остальные параметры произвольно
    - Запускаем игру нажав на кнопку "Create batlte"
  expected-result: |
    Игра корректно запускается, в качестве соперника играет бот
  actual result
    Бот не играет в качестве соперника, не пишет решение задачи

**Comment by RuslanKhashiev** [comment]
Та же ситуация
summary: |
Бот не работает
environment: |
Chrome 123.0.6312.107 (64-разрядная версия)
Windows 11  
Current version: 6b220bb
steps-to-reproduce: |
Создаем игру нажав на кнопку "Create a game"
Выбираем "Game Type" c значением "With a bot"
Запускаем игру с помощью кнопки "Create battle"
expected-result: |
Игра запускается, а бот выполняет задачу и соревнуется с игроком
actual result
Бот ничего не делает, не решает задачу

**Comment by RuslanKhashiev** [comment]
![Снимок экрана 2024-04-15 100105](https://github.com/hexlet-codebattle/codebattle/assets/129076117/9b32b6f1-4bd0-4f30-a2a1-baac7abafdaf)

**Comment by Kemiokuro** [comment]
В созданной игре бот не решает задание

Шаги:
- Нажать на кнопку "Create a game"
- Выбрать тип игры "With a Bot"
- Нажать кнопку «Create battle»

ОР: Бот решает задание. В редакторе кода бота отображается написанный им код.
ФР: Бот не решает задачу. В редакторе кода бота не отображается написанное решение. 

Browsers
Google Chrome версия 124.0.6367.60 (Официальная сборка), (64 бит)
OS
Windows 10 Pro Version 22H2
Версия проекта codebattle: 6b220bb

**Comment by vtm9** [comment]
fiexd

**Comment by Maicuduc-123** [comment]
Бот не реагирует на игру
