### ISSUE TITLE
Bug: Невозможно просматривать завершенную игру в записи 

### ISSUE THREAD

**Issue by AIonLisa** [hexlet-codebattle/codebattle#1821]
### Summary

Вместо истории игры система выдает предупреждение, что этот контент только для премиум подписчиков, при этом стать премиум подписчиком невозможно

![For premium subscribers only](https://github.com/hexlet-codebattle/codebattle/assets/152636776/9e171414-6ee3-4ec1-a59d-46704f1272b6)
 

### Reproduction steps

```bash
1. Залогиниться в системе
  test-data:
    Email = testt@yandex.ru Password = 123456
2. Перейти во вкладку History на главной странице сайта
3. Нажать Show на рандомной битве
```

### Expected result

Открывается история игры в записи 

### Actual result

Открывается предупреждение Sorry! This content for Premium Subscribers only.
Стать премиум подписчиком невозможно, можно только нажать кнопку Close

### Browsers

Chrome

### OS

Windows

[Current version: 5876eae](https://github.com/hexlet-codebattle/codebattle/commit/5876eaeafb7b02558fa8acaa25fef615291e71a9)

**Comment by SanDiego6677** [comment]
summary: |
Невозможно просматривать завершенную игру в записи
environment: |
Microsoft Edge Версия 121.0.2277.98 (Официальная сборка) (64-разрядная версия)
ОС Windows 11 pro
steps-to-reproduce: |
Авторизовываемся на сайте
Перейти во вкладку "HISTORY"
У любого игрока нажимаем на кнопку "Show" для просмотра истории битвы
expected-result: |
Открывается история игры в записи
actual-result: |
Открывается предупреждение Sorry! This content for Premium Subscribers only.
Стать премиум подписчиком невозможно, можно только нажать кнопку Close
![history](https://github.com/hexlet-codebattle/codebattle/assets/157375150/93618486-9354-4cfc-bf8e-305bffcd4f95)

**Comment by potemkina-e** [comment]
Баг воспроизводится

**summary**: |
Завершенная игра недоступна в записи
**environment**: |
Google Chrome версия 123.0.6312.124 (Официальная сборка), (arm64)
Safari версия 17.4.1 (19618.1.15.11.14)
macOS Sonoma версия 14.4.1 (23E224)
**steps-to-reproduce**: |
- На главной странице нажимаем на Nickname
- Переходим в "My Profile"
- Нажимаем "Completed Games"
- В строчке с завершенной игрой нажимаем кнопку "Show"
        или
- На главной странице выбираем вкладку "History"
- В строчке с завершенной игрой нажимаем кнопку "Show"
**expected-result**: |
Пользователь просматривает завершенную игру
**actual-result**: |
Открывается окно Restricted Content с сообщением: "Sorry! This content for Premium Subscribers only."
Оформить премиум-подписку не предлагается
<img width="1440" alt="playback" src="https://github.com/hexlet-codebattle/codebattle/assets/156904691/6692d418-8da8-4258-850b-3fe557de5797">
<img width="1437" alt="playback2" src="https://github.com/hexlet-codebattle/codebattle/assets/156904691/6ad63bbe-6e27-43e1-8b06-1f74a1d8a471">

**Comment by ReDBrother** [comment]
Ну блин, да) Это для премиум пользователей
Если об этом написано, значит это фича)

**Comment by AIonLisa** [comment]
Вообще-то предлагается также подписаться на премиум: "Subscribe to Premium and you'll get...", а самой возможности подписаться на премиум нет. Зачем тогда предлагается премиум подписка? Значит уберите этот баннер, пока не сделаете возможность подписаться на премиум. В моем баге описана суть: "Вместо истории игры система выдает предупреждение, что этот контент только для премиум подписчиков, **при этом стать премиум подписчиком невозможно**. Читайте внимательнее.

**Comment by ReDBrother** [comment]
Я понимаю к чему вы ведете и я прочитал весь тред полностью

Но это изначально так было устроено, с момента введения этого ограничения, поэтому это не баг. Части пользователей, премиум доступ выдается уже нами. Акаунты с премиум подпиской существует, и сейчас возможность оплатить подписку еще на стадии разработки
