### ISSUE TITLE
Reopened bug: Нет проверки пароля на надежность при регистрации

### ISSUE THREAD

**Issue by AIonLisa** [hexlet-codebattle/codebattle#1823]
### Summary

Воспроизводится закрытый баг : https://github.com/hexlet-codebattle/codebattle/issues/1379

Отсутствие
проверки пароля на надежность

### Reproduction steps

```bash
1. Нажать Sign Up на лендинге страницы
2. В открывшейся форме ввести рандомный Nickname и Email
3. В поле Password ввести 123456
4. Повторить 123456 в поле Password Confirmation
5. Нажать Submit
```

### Expected result

Появилось предупреждение,  о том, что пароль небезопасный и прописаны условия для выбора безопасного пароля

### Actual result

Происходит регистрация пользователя с небезопасным паролем

### Browsers

Chrome

### OS

Windows

[Current version: 5876eae](https://github.com/hexlet-codebattle/codebattle/commit/5876eaeafb7b02558fa8acaa25fef615291e71a9)

**Comment by ReDBrother** [comment]
Проверки на надежность нет в больше половины сайтов)
Это не может быть требованием для браузерной игры)

**Comment by m0t999** [comment]
1. Нажать Sign Up на лендинге страницы
2. В открывшейся форме ввести рандомный Nickname и Email
3. В поле Password ввести 123456
4. Повторить 123456 в поле Password Confirmation
5. Нажать Submit
Google Chrome   Версия 122.0.6261.129 (Официальная сборка), (x86_64)
    MacOs Monterey 12.1
