### ISSUE TITLE
В мобильной версии отсутствует функция удаления текста решения.

### ISSUE THREAD

**Issue by NikitaVasev** [hexlet-codebattle/codebattle#1825]
### Summary

В мобильной версии приложения отсутствует функция стирания текста в окне решения, из-за чего возникает проблема, если пользователь допустил ошибку.

### Reproduction steps

```bash
1. Создаем игру с ботом
2. Скролим вниз к окну ввода решения
3. Нажимаем на окно
4. Открывается клавиатура
5. Начинаем вводить решение
4. В случае ошибки стираем часть текста стрелкой
```

### Expected result

Текст решения успешно удален, теперь вы можете продолжать писать.

### Actual result

В текущей версии приложения нет возможности стереть весь текст решения. Вы можете удалить только то слово, которое не было закончено. Как только вы нажимаете пробел, текст становится недоступным для редактирования и становится серым.
<img width="421" alt="Безымянный" src="https://github.com/hexlet-codebattle/codebattle/assets/158546785/7654e6db-c890-4540-bfce-c1a3ef46f6b2">

### Browsers

Chrome 121.0.6167.101

### OS

Android 9, номер сборки 9.1.0.189, оболочка EMUI 9.1.0

**Comment by NikitaVasev** [comment]
Данный баг является дубликатом уже существующего бага, ссылка на описание которого указана на странице https://github.com/hexlet-codebattle/codebattle/issues/1718

**Comment by ReDBrother** [comment]
Мобильная адаптация будет только на уровне read only. Текущий редактор не наш и он не планирует полной поддержки всех мобильных устройств и всех фичей для них
