### ISSUE TITLE
Bug: Допустима отвязка аккаунта Discord от профиля, в случаи авторизации только через Discord

### ISSUE THREAD

**Issue by GhArKn** [hexlet-codebattle/codebattle#1830]
### Summary

Если пользователь авторизован исключительно через Discord, система не должна позволять отвязать аккаунт Discord

### Reproduction steps

```bash
- Войти в систему нажав на "Sign in with Discord"
- Нажать на никнейм учетной записи
- Выбрать раздел "Settings"
- Нажать кнопку Unlink Discord
```

### Expected result

Отвязка не должна происходить, так как кроме Discord нет других привязок

### Actual result

Появляется сообщение об успешной отвязки аккаунта 

https://github.com/hexlet-codebattle/codebattle/assets/103883865/b637bcc4-8e69-4b34-a221-6b528191db45

### Browsers

Yandex 120.0.6099.736 (64-разрядная версия)

### OS

Windows 11 Version 23H2 (Build 22631.3447)

**Comment by Sh3rlock-git** [comment]
**Summary**
Unlink аккаунта Github используемого как единственный вариант авторизации

**Reproduction steps**
1. Открыть [страницу](https://codebattle.hexlet.io/session/new?locale=en&next=%2F)
2. Кликнуть на кнопку Sign in with Github
3. Открыть вкладку [Settings](https://codebattle.hexlet.io/settings)
4. Нажать Unlink Github
5. Обновить страницу

**Expected result**
Возможность отвязать аккаунт Github должна быть заблокирована (неактивна)

**Actual result**
Аккаунт отлинкован от учетной записи. Сообщение об успешном изменении настроек аутентификации (Successfully unbinded authentication settings.)

**Environment**
OS Windows 10 Pro x64
Yandex.Browser 24.1.5.736 (64-bit)

**Reproduced in version**
 [6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)
![codebattle_unlink_git](https://github.com/hexlet-codebattle/codebattle/assets/158310621/4780b532-eac4-491a-bcba-05b040d53db7)

**Comment by ReDBrother** [comment]
Дубль от #1829
Правило такое, что отвязать можно только если другие привязки есть

**Comment by Sh3rlock-git** [comment]
> Дубль от #1829 Правило такое, что отвязать можно только если другие привязки есть

Других привязок в профиле нет. Для авторизации используется только аккаунт Github'a. Если отвязать аккаунт и удалить cookie в браузере, получается доступ к аккаунту теряется без каких-либо подтверждений/уведомлений со стороны сайта
