### ISSUE TITLE
Bug: Не отображается дата завершенной игры в "My profile"

### ISSUE THREAD

**Issue by GhArKn** [hexlet-codebattle/codebattle#1835]
### Summary

В "My profile" в разделе "Completed Games" не видна дата игры (Current version: 6b220bb)

### Reproduction steps

```bash
1. Открыть главную страницу авторизованного пользователя
2. В шапке страницы нажать на Nickname 
3. В выпадающем меню выбрать "My profile"
4. Перейти в раздел "Completed Games"
```

### Expected result

Все данные из таблицы завершенных игор корректно отображаются

### Actual result

Дата не отображается, текст ошибки "Invalid date"
![image](https://github.com/hexlet-codebattle/codebattle/assets/103883865/527e92e6-a301-4911-97bd-7a47f057a7cf)

### Browsers
Yandex 120.0.6099.736 (64-разрядная версия)
         

### OS

Windows 11 Version 23H2 (Build 22631.3447)

**Comment by JS-Demi** [comment]
Задача еще актуальна? В моем профиле корректно отображается

**Comment by ludwig-the-cat** [comment]
Дополнительная информация:
1. Открыть главную страницу авторизованного пользователя
2. В шапке страницы нажать на Nickname 
3. В выпадающем меню выбрать "My profile"
4. Перейти в раздел "Completed Games"
Actual result:
Дата не отображается, текст ошибки "Invalid date"
![Снимок экрана 2024-04-17 204125](https://github.com/hexlet-codebattle/codebattle/assets/102757651/65a354ee-3530-4075-af98-14c5c60d854b)
Некоторые да
Browsers
Версия 123.0.6312.123 (Официальная сборка), (64 бит)
OS
Windows 10 Version 22H2

**Comment by Kemiokuro** [comment]
В профиле пользователя некорректно отображена дата игр

Шаги:
- В шапке страницы на никнейм
- В выпадающем меню выбрать "My profile"
- Перейти во вкладку "Completed Games"

ОР: Дата окончания игры отображена в формате ДД.ММ.ГГ в столбце "Data"
ФР: В столбце "Data" пишется значение "Invalid date"
![1](https://github.com/hexlet-codebattle/codebattle/assets/157710988/03ac07fa-71db-4d0b-a19a-e5cb7bfa5b14)

Browsers
Google Chrome версия 124.0.6367.60 (Официальная сборка), (64 бит)
OS
Windows 10 Pro Version 22H2
Версия проекта codebattle: 6b220bb

**Comment by ReDBrother** [comment]
К сожалению мы сломали в свое время сохранение игр в которых участник сдался
Мы уже не сможем восстановить эти данные, поэтому для прошлых игр останется как есть(

Фиксом будет не допустить такое сохранение в будущем, это уже выйдет в близжайшем релизе
