### ISSUE TITLE
Bug: Не выполняется регистрация с 1 символом перед @ в поле email

### ISSUE THREAD

**Issue by Azraillier** [hexlet-codebattle/codebattle#1836]
[#1800(comment)](https://github.com/hexlet-codebattle/codebattle/issues/1800)
Невозможно выполнить регистрацию с одним символом перед @ в поле Email

### Environment 
Google Chrome Версия 123.0.6312.122 (Официальная сборка), (64 бит)
Mozilla Firefox Версия 124.0.2 (64-разрядный)
ОС Windows 10
[Current version: b2aa41d](https://github.com/hexlet-codebattle/codebattle/commit/b2aa41d1deb34a9dc06d44586057eb4c6095d051)
deployedAt UTC: 2024-04-11 09:48:48

### Reproduction steps

```bash
1. Перейти на страницу регистрации https://codebattle.hexlet.io/users/new?locale=en&next=%2F
2. Ввести любой Nickname
3. Ввести в поле Email любой адрес с одним символом перед @, например, 5@gmail.com
3. Ввести любой пароль в поле Password
4. Подтвердить пароль в поле Password Confirmation
5. Отравить данные кнопкой Submit
```

### Expected result

Регистрация выполнена успешна

### Actual result

Валидация поля Email  не выполняется  с одним символом перед @

![54](https://github.com/hexlet-codebattle/codebattle/assets/75273530/459d28dd-10d7-4ba9-950a-1c3f4267dd15)

**Comment by JS-Demi** [comment]
Взял в работу

**Comment by Sh3rlock-git** [comment]
Баг воспроизводится

**Environment**
OS Windows 10 Pro x64
Yandex.Browser 24.1.5.803 (64-bit)

**Reproduced in version**
[6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)
![codebattle_email_1_letter](https://github.com/hexlet-codebattle/codebattle/assets/158310621/c49cd08b-7cbe-4156-931c-e7a52e3a55e9)

**Comment by SpaYkeR696** [comment]
Выполнение еще идет? или можно взять?

**Comment by JS-Demi** [comment]
Я уже выполнил задачу, тестировщик проверил еще раз еще не проверенные и соответсвенно не мердженные на основную ветку изменения

**Comment by vtm9** [comment]
thx

**Comment by burd-up** [comment]
Не воспроизвёл.
OS Windows
Current version: https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4
Browser Chrome

**Comment by Sofushkins** [comment]
баг переоткрыт [https://github.com/hexlet-codebattle/codebattle/issues/1803#issue-2194756611](url)
