### ISSUE TITLE
Bug: Неактивный пункт копировать контекстного меню в поле Password

### ISSUE THREAD

**Issue by Sh3rlock-git** [hexlet-codebattle/codebattle#1837]
### Summary

Нет возможности скопировать содержимое поля Password в Password Confirmation при регистрации нового аккаунта
![codebattle_copy_password](https://github.com/hexlet-codebattle/codebattle/assets/158310621/ce83e2ef-ff81-46fa-99e0-979566b51fd4)

### Reproduction steps

1. Открыть [страницу](https://codebattle.hexlet.io/users/new?locale=en&next=%2F)
2. В поле Password ввести пароль от 6 до 16 символов, например 123456
3. Выделить содержимое поля Password и нажать 1 раз ПКМ

### Expected result

В открывшемся контекстном меню пункт "копировать" - активный

### Actual result

В открывшемся контекстном меню пункт "копировать" неактивный

**Environment**
OS Windows 10 Pro x64
Yandex.Browser 24.1.5.736 (64-bit)

**Reproduced in version**
[6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)

**Comment by ReDBrother** [comment]
Запрет валидный
