### ISSUE TITLE
Bug: Отсутствует валидация поля your name на вкладке settings, на допустимые символы

### ISSUE THREAD

**Issue by Sh3rlock-git** [hexlet-codebattle/codebattle#1838]
### Summary

Отсутствует валидация поля your name на вкладке settings, на допустимые символы

### Reproduction steps

1. Открыть [страницу](https://codebattle.hexlet.io/settings)
2. В поле your name ввести адрес сайта, например https://vk.com
3. Нажать на кнопку Save

### Expected result

Поле your name валидирует на спец.символы (://.?\)
Спец.символы не вводятся в поле

### Actual result

Отсутствует валидация поля your name
В поле сохраняется указанная ссылка

**Environment**
OS Windows 10 Pro x64
Yandex.Browser 24.1.5.736 (64-bit)

**Reproduced in version**
[6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)
![codebattle_not_validation_name](https://github.com/hexlet-codebattle/codebattle/assets/158310621/ae6e4b53-1507-4017-bed0-5f5474b0b4fa)

**Comment by ReDBrother** [comment]
Если у нас нет этого правила (Нигде у нас не сказано что недопустимо), то его и нет)

**Comment by Sh3rlock-git** [comment]
> Если у нас нет этого правила (Нигде у нас не сказано что недопустимо), то его и нет)

Разве это неочевидное требование к форме? Можно ведь указать ссылку на сомнительный сторонний ресурс, чат/контакт в Telegram. Как минимум, будет бесплатная реклама)
