### ISSUE TITLE
Bug: Поле Choose task by name or tags не валидирует на спец.символы

### ISSUE THREAD

**Issue by Sh3rlock-git** [hexlet-codebattle/codebattle#1839]
### Summary

Поле Choose task by name or tags не валидирует на спец.символы

### Reproduction steps

```bash
1. Нажать на кнопку Create a game
2. Установить любой уровень сложности
3. Установить game type - with a freind
4. Выбрать пользователя из выпадающего списка Choose opponent
5. Ввести в поле Choose task by name or tags <h1>lets play</h1>
6. Нажать на кнопку Create invite
```

### Expected result

Валидация поля choose task by name or tags уведомляет пользователя о недопустимых символах.
В выпадающем списке появляются подсказки доступных заданий
Не отправляется инвайт выбранному пользователю

### Actual result

Поле Choose task by name or tags не валидирует. Отправляется инвайт выбранному пользователю

**Environment**
Windows 10 Pro x64
Yandex.Browser 24.1.5.736 (64-bit)

**Reproduced in version**
[6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)
![codebattle_validate_name_task](https://github.com/hexlet-codebattle/codebattle/assets/158310621/7b2a48b6-b5f6-4c37-a89a-19257610d854)
![codebattle_validate_name_task2](https://github.com/hexlet-codebattle/codebattle/assets/158310621/270f0e45-20c6-42aa-ac53-059b7eb2f340)

**Comment by ReDBrother** [comment]
И не должен, просто выбираете задачу и все
