### ISSUE TITLE
Bug: Верстка не адаптируется в режиме батла, в альбомной ориентации экрана на бекпоинтах 740*360

### ISSUE THREAD

**Issue by Sh3rlock-git** [hexlet-codebattle/codebattle#1840]
### Summary

Содержимое страницы не адаптируется под экран в альбомной ориентации, на бекпоинтах 740*360

### Reproduction steps

```bash
1. Создать игру с другом, ботом или другим пользователем, с любыми параметрами игры
2. Открыть Devtools
3. Активировать Toggle device toolbar
4. В качестве устройства выбрать Samsung S8+
5. Выбрать альбомную ориентацию экрана
```

### Expected result

Верстка страницы адаптируется под размеры экрана.
Контент целиком помещается на экране

### Actual result

Страница не адаптирована под ориентацию экрана. Содержимое страницы не помещается на экране

**Environment**
OS Windows 10 Pro
Yandex.Browser 24.1.5.736 (64-bit)

**Reproduced in version**
[6b220bb](https://github.com/hexlet-codebattle/codebattle/commit/6b220bbfa3657c1c9b881f2eef14a953edc90c96)
![codebattle_not_adaptive_album](https://github.com/hexlet-codebattle/codebattle/assets/158310621/ec2891a7-d9e9-450f-b9ca-09df9f056a70)

**Comment by ReDBrother** [comment]
Не воспроизводится
Если перезагрузишь страницу, то он нормально отобразится
