### ISSUE TITLE
Bug: Регулятор громкости становится активным только после нажатия на кнопку save

### ISSUE THREAD

**Issue by RuslanKhashiev** [hexlet-codebattle/codebattle#1841]
### Summary

Громкость звукового эффекта в настройках можно сменить только после нажатия на кнопку "save", иначе он просто остается прозрачным 

### Reproduction steps

```bash
1. Зайти на главную страницу сайта
2. Нажать на ник в правом верхнем углу
3. Перейти в настройки
4. Выбрать любой звук
```

### Expected result

После выбора звука, ползунок с выбором уровня звука должен быть доступным

### Actual result

Ползунок не работает, чтобы он стал доступным нужно нажать на кнопку "save"

### Browsers

Chrome Версия 123.0.6312.124 (Официальная сборка), (64 бит)

### OS

Windows 11 pro(64-bit)

**Comment by RuslanKhashiev** [comment]
![Uploading Баг сайта_3.png…]()

**Comment by RuslanKhashiev** [comment]
![Uploading Баг звука.png…]()

**Comment by RuslanKhashiev** [comment]
![Баг звука](https://github.com/hexlet-codebattle/codebattle/assets/129076117/96f0b9a9-99cf-49ed-8047-cadc315569aa)

**Comment by SpaYkeR696** [comment]
Могу взять в работу

**Comment by BigZiano** [comment]
Summary:
При выборе настройки звука "Select sound type" не отображается активной радиокнопка после сохранения настроек
Environment:
Яндекс Браузер Версия 24.1.5.803 (64-bit) Windows 10 Pro Версия 22H2 Сборка ОС 19045.4291
[Current version: 6b220bb]
Prerequisites:
Пользователь авторизован, открыто меню настроек https://codebattle.hexlet.io/settings
Reproduction steps:
Выбрать любой звук в поле Select sound type
Нажать кнопку Save
![image](https://github.com/hexlet-codebattle/codebattle/assets/162887947/2e96336a-92cc-4d6a-97a8-33f0b43610b5)
Expected-result:
На странице настроек активна радиокнопка напротив выбранного звука в поле Select sound type
Actual-result:
На странице настроек неактивна радиокнопка напротив выбранного звука в поле Select sound type
![image](https://github.com/hexlet-codebattle/codebattle/assets/162887947/adea540b-c1ec-4d96-8309-8acaeeba673d)

**Comment by ReDBrother** [comment]
Закрываем)
