### ISSUE TITLE
Bug: Громкость звукового эффекта не сохраняется после изменений

### ISSUE THREAD

**Issue by ludwig-the-cat** [hexlet-codebattle/codebattle#1844]
### Summary

Громкость звукового эффекта не сохраняется после изменений

### Reproduction steps

```bash
1. Зайти на главную страницу сайта
2. Нажать на ник в правом верхнем углу
3. Перейти в настройки
4. Изменить громкость звука
5. Нажать кнопку Save
6. Обновить страницу
```

### Expected result

Уровень громкости должен измениться 

### Actual result

Уровень громкости на уровне по умолчанию
![Измененной состояние
![Снимок экрана 2024-04-17 193601](https://github.com/hexlet-codebattle/codebattle/assets/102757651/c740dfe3-514d-43c9-84b4-cf220595b48e)
](https://github.com/hexlet-codebattle/codebattle/assets/102757651/3a723312-aa75-47a2-8b8a-cfad53362d42)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by ludwig-the-cat** [comment]
Скриншот после обновления страницы
![Uploading Снимок экрана 2024-04-17 193601.png…]()

**Comment by SpaYkeR696** [comment]
уже выполнено, ожидается проверка

**Comment by Kemiokuro** [comment]
Уровень громкости в настройках не сохраняется

Шаги:
- Нажать на никнейм в шапке страницы
- Выбрать "My profile" в выпадающем меню
- Перейти во вкладку "Settings"
- Изменить громкость звука
- Нажать на кнопку "Save"
- Обновить страницу

ОР: Уровень громкости изменен
ФР: Уровень громкости установлен по умолчанию

Browsers
Google Chrome версия 124.0.6367.60 (Официальная сборка), (64 бит)
OS
Windows 10 Pro Version 22H2
Версия проекта codebattle: 6b220bb

**Comment by SanDiego6677** [comment]
Прошёл кейс по шагам, при сохранении громкости всплывает оповещение что настройки были изменены,
громкость звукового эффекта сохраняется при обновлении страницы.

Browsers
Microsoft Edge Версия 121.0.2277.98 (Официальная сборка) (64-разрядная версия)

OS
Windows 11 Pro
![громкость](https://github.com/hexlet-codebattle/codebattle/assets/157375150/587a300a-dc9a-459a-9042-d42d79926088)
![громкость2](https://github.com/hexlet-codebattle/codebattle/assets/157375150/bc541324-f8ac-4bcc-b79c-973d6f9f3021)

**Comment by ReDBrother** [comment]
Закрываю)
И спасибо отдельно за фикс)

**Comment by Lilu-Zakolodyajnaya** [comment]
[Не сохраняются изменения при смене "sound type" на "Standart" ](https://github.com/hexlet-codebattle/codebattle/issues/1809#top)
