### ISSUE TITLE
Bug: Некорректная ссылка для восстановления пароля

### ISSUE THREAD

**Issue by Kemiokuro** [hexlet-codebattle/codebattle#1849]
### Summary

При открытии ссылки для смены пароля выдается ошибка "Срок действия вашего запроса на сброс пароля истек или ссылка уже использовалась"

### Reproduction steps

```bash
Предусловие:
На тестируемом проекте есть зарегистрированный аккаунт с существующей почтой

1. Нажать на кнопку "Sign in"
2. Нажать на кнопку "Forgot your password?"
3. Ввести почту из предусловия
4. Нажать на кнопку "Submit"
5. Открыть почту из предусловия и найти письмо с текстом "Reset your password for Codebattle"
6. Перейти по ссылке в письме
```

### Expected result

Представлена форма для введения нового пароля

### Actual result

При переходе по ссылке из письма выдается ошибка
![555](https://github.com/hexlet-codebattle/codebattle/assets/157710988/a0fbea9f-26c2-4180-8df5-9a8fd2f958f7)

### Browsers

Google Chrome версия 124.0.6367.60 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Version 22H2

Версия проекта codebattle: 6b220bb

**Comment by SpaYkeR696** [comment]
![Снимок экрана от 2024-04-22 10-07-51](https://github.com/hexlet-codebattle/codebattle/assets/119116971/cdf8d3a5-2aef-43fb-b225-8d567ccad30b)
![Снимок экрана от 2024-04-22 10-07-34](https://github.com/hexlet-codebattle/codebattle/assets/119116971/5c6ec5ba-7997-42dd-ad4a-376e8a15ddea)
Не заметил проблемы с ссылкой, переходит на страницу, и есть возможность изменить пароль

**Comment by ludwig-the-cat** [comment]
Прошел по шагам, письмо пришло сразу, пароль сменен успешно - не баг. Посмотрите письмо в спаме или рассылках

**Comment by SanDiego6677** [comment]
![смена пароля](https://github.com/hexlet-codebattle/codebattle/assets/157375150/83aec576-bcfa-4e80-9a78-f7b25259f6c7)
![смена пароля 2](https://github.com/hexlet-codebattle/codebattle/assets/157375150/82458444-9723-4f38-adab-159781451a3e)
Так же прошёл воспроизведение бага по шагам, проблем с восстановлением пароля нет , пароль можно успешно восстановить.

Browsers
Microsoft Edge Версия 121.0.2277.98 (Официальная сборка) (64-разрядная версия)

OS
Windows 11 Pro

**Comment by ReDBrother** [comment]
Всем большое спасибо что проверили багу)
