### ISSUE TITLE
Bug: Невозможно воспользоваться Premium-подпиской

### ISSUE THREAD

**Issue by SanDiego6677** [hexlet-codebattle/codebattle#1850]
### Summary

Пользователь не может воспользоваться подпиской Premium

### Reproduction steps

```bash
1.Авторизоваться на сайте
2.Нажимаем на иконку своего аккаунта в правом верхнем углу
3.Нажимаем на кнопку "My profile"
4.Переходим в раздел "COMPLETED GAMES"
5.Нажимаем на кнопку "Show"
```

### Expected result

1.Открывается модальное окно с предупреждением что этот контент только для премиум-подписчиков с предложением подписаться
2.Нажимем на кнопку "Yes"
3.После просматриваем историю игроков с премиум-подпиской

### Actual result

После нажатия кнопки "Yes" открывается такое же окно , но уже без кнопок с надписью "работаем над этим".
По итогу подписка не произошла.
![completed games](https://github.com/hexlet-codebattle/codebattle/assets/157375150/6647b81e-d3fe-4cad-90a2-759bb0ceb61c)
![completed games 2](https://github.com/hexlet-codebattle/codebattle/assets/157375150/a2df30a0-8866-49b9-81d5-ebb6e3e8a1c3)

### Browsers

Firefox

### OS

Windows

**Comment by ludwig-the-cat** [comment]
Ну так не баг, раз надпись есть работает над этим)

**Comment by SanDiego6677** [comment]
Хорошо, для чего тогда спрашивает хочу ли я подписаться если я этого не могу сделать по итогу?)

**Comment by ludwig-the-cat** [comment]
Это было запланировано на стадии дизайна, но до реализации, допустим не дошли, ну и как вишенка есть сообщение, что работа ведется. Если бы не было сообщения - можно было бы смело считать багом.
Но ежели это баг - предлагаете вырезать все модальное окно или полностью функционал (в каком бы то не было состоянии) истории?

**Comment by SanDiego6677** [comment]
Предлагаю оставить только одно модальное окно с надписью что работаем над этим, чтобы не вводить в заблуждения пользователей, лично моё мнение)

**Comment by ReDBrother** [comment]
Нет, смысл этой модалки в том, чтобы брать статистику по ребятам, которые бы хотели премиум или нет
Правда тут нашу статистику очень люто убивают тестеры, которые почему отвечают утвердительно)

Нам при любом раскладе нужно как-то объяснить отсутствие части функционала - отсюда модалка
