### ISSUE TITLE
Bug: Ошибка 429 при переходе по кнопке "CONTINUE" в созданную игру с другим пользователем 

### ISSUE THREAD

**Issue by SanDiego6677** [hexlet-codebattle/codebattle#1851]
### Summary

При проверке сайта в режиме разработчика есть ошибка с кодом 429

### Reproduction steps

```bash
1.Открыть режим разработчика F12
2.Авторизоваться на сайте
3.Нажать на кнопку "Create a game"
4.В открывшемся окне нажать "With other user"
5.Нажать на кнопку "Create Invite"
6.После во вкладке "LOBBY" появится наша созданная игра
7.Нажать кнопку "CONTINUE"
```

### Expected result

Все данные получены без ошибок

### Actual result

Есть ошибка с кодом 429
![ошибка 429](https://github.com/hexlet-codebattle/codebattle/assets/157375150/e9b596fb-101b-4839-a754-ae53f908d368)

### Browsers

Microsoft Edge

### OS

Windows

**Comment by ludwig-the-cat** [comment]
У вас касперский стоит на пк?

**Comment by ludwig-the-cat** [comment]
Возможно он реквестит, у меня была так же с касперским

**Comment by ReDBrother** [comment]
Не, item ошибка не влияющая ни на что
Скорее всего там неработающий доступ к внешнему логеру
