### ISSUE TITLE
Bug: При переключении раскладки с меню описании задачи с русского на английский, не переводится текст

### ISSUE THREAD

**Issue by IbrahimHaniff** [hexlet-codebattle/codebattle#1855]
### Summary

При попытки переключится с русского на английский с меню описании задачи в игре кодбатл, не переводится текст
![Снимок экрана 2024-05-05 105819](https://github.com/hexlet-codebattle/codebattle/assets/159468166/7848a383-4814-42f6-b051-22fb3b2a5f18)

### Reproduction steps

```bash
Открыта главная странийца сайта кодбатл
Переходим на вкладку "Попроубуйте просто бой"
В левом верхнем меню нажимаем на меню переключения языков
Выбираем английский язык
```

### Expected result

При переключении языка с русского на английский, тект должен отобразиться на выбранном языке

### Actual result

Текст не отображается на английском языке

### Browsers

Chrome

### OS

Windows

**Comment by Loyrens** [comment]
При выполнении шагов не нашёл баг. Скорее всего браузер по умолчанию перевёл английский текс на русский, что и вызвало баг.
- Reproduction steps
1. Открыть главную страницу веб-сайта CodeBattle по следующей ссылке - https://codebattle.hexlet.io/
2. Нажать на кнопку "Try simple battle"
3. В окне "Task" Переключить язык на английский язык
- Expected-result:
При переключении языка с русского на английский, текст задачи должен отобразиться на выбранном языке
- Actual-result:
Текст успешно отобразился на выбранном языке
- Browsers
Google Chrome, Версия 124.0.6367.119 (Официальная сборка), (64 бит)
- OS
Windows 10 Домашняя, Версия 22H2 (сборка ОС 19045.4291)
- Screenshot
![en-1](https://github.com/hexlet-codebattle/codebattle/assets/158618528/42d5c9a2-7392-4bb1-ac52-14f870058e6c)
![ru-1](https://github.com/hexlet-codebattle/codebattle/assets/158618528/0cecc920-f34d-4ce2-920c-5ecddf93162a)

**Comment by ReDBrother** [comment]
Мы не собираемся поддерживать другиt языки на основной платформе
