### ISSUE TITLE
Bug:  При переключении на "Попробуй просто пой" сайт зависнул

### ISSUE THREAD

**Issue by IbrahimHaniff** [hexlet-codebattle/codebattle#1856]
### Summary

При попытке перейти на на вкладку "Попробуй просто бой" сслыка не отркрвается и выдает ощибку : "429 (Too Many Requests)" 
![Снимок экрана 2024-05-05 110326](https://github.com/hexlet-codebattle/codebattle/assets/159468166/f153b550-73e9-4f17-afea-e71e848ebca9)

### Reproduction steps

```bash
Открыта главная страница сайта кодбатл
Переходим на вкладку "Попробуй просто побой"
```

### Expected result

После переключения на вкладку "Попробуй просто бой" должна была открыться ссылка перехода на онлайн бой

### Actual result

Ссылка перехода не открывается и выдает ощибку "429 (Too Many Requests)"

### Browsers

Chrome

### OS

Windows

**Comment by Loyrens** [comment]
Попробовал воспроизвести баг выполняя след шаги:
1. Открыть главную страницу веб-сайта CodeBattle по следующей ссылке - https://codebattle.hexlet.io/
2. Нажать на кнопку "Try simple battle"
Expected-result:
- После нажатия на кнопку "Try simple battle", игрок перешел в бой без регистрации
Actual-result:
- При нажатии на кнопку "Try simple battle", я успешно перешел  в бой
Browsers
- Google Chrome, Версия 124.0.6367.119 (Официальная сборка), (64 бит)
OS
- Windows 10 Домашняя, Версия 22H2 (сборка ОС 19045.4291)

Screenshot
![2024-05-06 22_00_51-Window](https://github.com/hexlet-codebattle/codebattle/assets/158618528/e3fd135c-8c68-4d30-9ec2-85553fb60adf)

**Comment by ReDBrother** [comment]
Воспроизвести не удается, даже с включенным переводчиком(
