### ISSUE TITLE
Кнопка "Run" не становится неактивной после выйгрыша

### ISSUE THREAD

**Issue by Svetalto** [hexlet-codebattle/codebattle#1858]
Summary
После того, как игрок выйграл, он может изменить свой код и проверить его
Test-data: |
    -  "const solution = (width, length) => {
  return width * length; 
   };
"
Reproduction steps
    - Нажать на кнопку "Create a game"
    - Выбрать самый легкий уровень игры
    - Выбрать режим "with a bot"
    - Выбрать задачу "rect_area"
    - Нажать на кнопку "Create battle"
    - Ввести в поле для игры тестовые данные
    - Нажать на кнопку "Run"
    - Закрыть окно с оповещением о выгрыше
    - Нажать на кнопку "Run"
    - 
Expected result
Кнопка "Run" неактивна

Actual result
C помошью кнопки "Run" возможно заново проверить свой код

Browsers
Chrome.
Версия 124.0.6367.93 

OS
MacOS Версия 12.3.1 (21E258)

**Comment by ReDBrother** [comment]
Она и должна остаться активной
Наши игры позволяют произвести еще проверки после выйгрыша - поэксперементировать с решением после

**Comment by Svetalto** [comment]
тогда нужно переписать требование к игре (требование №2)
<img width="932" alt="Снимок экрана 2024-05-05 в 13 14 35" src="https://github.com/hexlet-codebattle/codebattle/assets/163977276/bbfbd122-ba90-456c-8eec-2c97a6590999">

**Comment by Svetalto** [comment]
тогда нужно пересмотреть условия игры

ср, 8 мая 2024 г. в 08:36, Dmitriy Bataev ***@***.***>:
