### ISSUE TITLE
Bug: Ошибка 429 при переходе по кнопке «ПРОДОЛЖИТЬ» в созданную игру другим пользователем

### ISSUE THREAD

**Issue by IbrahimHaniff** [hexlet-codebattle/codebattle#1859]
### Summary

Не исправлена ошибка #1851 [https://github.com/hexlet-codebattle/codebattle/issues/1851#issue-2258308388](url)

### Reproduction steps

```bash
1.Открыть режим разработчика F12
2.Авторизоваться на сайте
3.Нажать на кнопку "Create a game"
4.В открывшемся окне нажать "With other user"
5.Нажать на кнопку "Create Invite"
6.После во вкладке "LOBBY" появится наша созданная игра
7.Нажать кнопку "CONTINUE"
```

### Expected result

Все данные получены без ошибок

### Actual result

Есть ошибка с кодом 429
![Снимок экрана 2024-05-07 171652](https://github.com/hexlet-codebattle/codebattle/assets/159468166/12203039-183e-42d2-990e-36cb081fbbdc)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Потому что эта ошибка никак не связана с работой сайта)
Когда вы создали игру и ждете своего оппонента, то страница появляется корректна и на ней полная информация о дальнейших действиях - проблемы нет)
