### ISSUE TITLE
Не работает выход из режима "Настройки"

### ISSUE THREAD

**Issue by Svetalto** [hexlet-codebattle/codebattle#1861]
Summary
Невозможно вернуться на домашнюю страницу после захода в "Настройки"

Reproduction steps
- Кникнуть на ник на главной странице
- Выбрать режим "Настройки"
- Нажать на поле вне поля "Настройки"
<img width="1440" alt="Снимок экрана 2024-05-09 в 17 01 28" src="https://github.com/hexlet-codebattle/codebattle/assets/163977276/fcb43c8f-c8fd-41c4-b28c-667086eab71b">

Expected result
Поле "Настройки" закрывается

Actual result
Выход из режима "Настройки" невозможен

Browsers
Chrome.
Версия 124.0.6367.93

OS
MacOS Версия 12.3.1 (21E258)

**Comment by MarSam7** [comment]
Если нажать на иконку Codebattle, то нас перенесёт в лобби

**Comment by Svetalto** [comment]
Тогда это нужно уточнить в инструкции к игре. И да, может тогда данный баг рассматривать как фичу. Пользователю удобно будет нажимать на кнопку, закрывающую настройки, либо просто нажимать на любое место вне поля "настройки"

**Comment by ReDBrother** [comment]
У нас сейчас отсуствует боковая навигация, кроме выше упомянутой иконки кодбатла
О чем речь в тикете, это присутствует по большей части в приложениях (мобильных/десктопных) - наш сайт таковым не является
