### ISSUE TITLE
Бот не активен во время игры

### ISSUE THREAD

**Issue by Svetalto** [hexlet-codebattle/codebattle#1862]
Summary
При выборе игры с ботом бот не активен. Закрытый баг https://github.com/hexlet-codebattle/codebattle/issues/1818
Reproduction steps
- Нажать "Create a game"
- Выбрать любой уровень сложности
- Нажать "With a bot"
- Нажать "Create battle"
- Ввести любые данные в свое решение
Expected result
В поле бота высвечивается активная игра бота

Actual result
В поле бота не видно никакой активности
<img width="1433" alt="Снимок экрана 2024-05-10 в 06 51 00" src="https://github.com/hexlet-codebattle/codebattle/assets/163977276/838e5a93-66e8-49c4-a89f-b3ff2c6dd510">
<img width="1440" alt="Снимок экрана 2024-05-10 в 06 56 21" src="https://github.com/hexlet-codebattle/codebattle/assets/163977276/9c21f05b-ee7a-4cbb-846f-9835a0001b8d">

Browsers
Chrome.
Версия 124.0.6367.93

OS
MacOS Версия 12.3.1 (21E258)

**Comment by Sergei033** [comment]
**Summary**
 
При игре с пользователем, бот не ведет активность 

**Reproduction steps**

1.  Нажать на "Create a game"
2.  Выбрать игру с ботом
3.  Нажать "Create battle"

**Expected result**
 
Бот должен вести активность 


**Actual result**

У бота нет никакой активности 
![p2screen4](https://github.com/hexlet-codebattle/codebattle/assets/168745397/631ae01e-a8e5-44a4-a494-956c2e21b3ac)
![p2screen5](https://github.com/hexlet-codebattle/codebattle/assets/168745397/663991f0-d597-4126-a783-cab08248fea0)



**Browsers**

Chrome, FireFox

**OS**

Windows

**Comment by ReDBrother** [comment]
Это очень странная фича)
Нет особого смысла в этом - игра уже закончилась)

**Comment by Svetalto** [comment]
Бот и не начинал игру. Прилагаются скрины начала и конца игры. Как видно из скринов, бот на протяжении всей игры не сделал ни одного хода

**Comment by ReDBrother** [comment]
А ок, сорян, скорее всего он начал бы писать сильно позже
Я вижу что в чате он онлайн и у него редактор не в дефолтном состоянии (язык java вместо js) - а это значит, что как минимум он нашел решение, но по своей логике пишет ее сильно позже

**Comment by ReDBrother** [comment]
Бот используют решения других участников, они тоже могут писать с сильным запозданием

**Comment by kufex** [comment]
Summary
При игре с пользователем, бот не всегда кодит

Reproduction steps
1. Нажать на "Create a game"
2. Выбрать игру с ботом
4. Заполнить другие поля любыми данными
5. Нажать "Create battle"

Expected result
Бот должен кодить

Actual result
У бота ничего не делает

**Comment by dentest1** [comment]
Summary
Бот не активен во время режима игры "Игра с ботом"

Steps
Нажать Create a game
Выбрать With a bot
Выбрать любой уровень сложности
Нажать Create battle

Expected result
Бот пишет код во время игры

Actual result
Бот не активен (не пишет код)

**Comment by anastas250** [comment]
Summary
В режиме "Игра с ботом" бот не всегда ходит

Steps
Нажать кнопку "Create a game"
Выбрать "With a bot"
Нажать "Create battle"

Expected result
Бот ходит

Summary
Бот не активен во время режима игры "Игра с ботом"

Steps
Нажать Create a game
Выбрать With a bot
Выбрать любой уровень сложности
Нажать Create battle

Expected result
Бот пишет код во время игры

Actual result
Бот не пишет код во время игры

**Comment by yana-fesenko** [comment]
**Summary**
В Игре с ботом, бот не активен

**Reproduction steps**
    - Нажимаем на кнопку «Create a game»
    - Выбираем уровень игры
    - Выбираем «with a bot»
    - Выбираем время игры
    - Выбираем задание
    - Нажимаем на кнопку «Create battle»

**Expected result**
Бот кодит во время игры

Actual result
Бот не активен
<img width="1238" alt="Снимок экрана 2024-06-16 в 15 19 08" src="https://github.com/hexlet-codebattle/codebattle/assets/142812556/d0672278-ccb5-4208-b78f-df1d0fcd0d1c">
<img width="1250" alt="Снимок экрана 2024-06-16 в 15 21 58" src="https://github.com/hexlet-codebattle/codebattle/assets/142812556/6b6556fb-a435-4375-a4b9-a2b32892adc2">


**Browsers**

Chrome
OS
Mac
