### ISSUE TITLE
Не отображается иконка для RUST в профиле юзера после изменения ЯП в настройках

### ISSUE THREAD

**Issue by akhoroshavin** [hexlet-codebattle/codebattle#1863]
### Summary

Иконка яп RUST в My Profile не отображается, вместо нее пользователь видит иконку битого изображения.  

Версия сайта:
[Current version: e9cfc50](https://github.com/hexlet-codebattle/codebattle/commit/e9cfc5079cd2994efa3887471cb8e88347022fe9)
deployedAt UTC: 2024-04-22 12:48:14

Environment:

Браузер:
Chrome 124.0.6367.201 
Mozilla Firefox, 125.0.3 
Mircosoft Edge, 124.0.2478.80

ОС: 
Windows 10 

В инструментах разработчика Chrome, после сохранения выбранного языка и перехода в профиль, видим статус 404. 

![rust_png_не_загружается_в_хроме](https://github.com/hexlet-codebattle/codebattle/assets/160062088/617cf81f-cb47-40b4-a1be-1c58d2f5e835)

Аналогично в Firefox:

![rust_png_не_загружается_в_мозилле](https://github.com/hexlet-codebattle/codebattle/assets/160062088/e715506c-dd6e-43e4-8ec6-dd14efd9de64)

И в Edge:

![rust_png_не_загружается_в_эдже](https://github.com/hexlet-codebattle/codebattle/assets/160062088/7a4572da-e3d5-40d2-9355-0801aeac61af)

### Reproduction steps

```bash
1. Нажать на меню профиля 
2. Перейти в Settings
3. Выбрать в поле Your Weapon: RUST
4. Нажать Save
5. Нажать на меню профиля
6. Перейти в My Profile
```

### Expected result

Пользователь видит в профиле иконку RUST.

### Actual result

Пользователь видит иконку битого изображения. 

### Browsers

Firefox, Chrome, Microsoft Edge

### OS

Windows

**Comment by YuSpbPsb** [comment]
Summary

Иконка яп RUST в My Profile не отображается, вместо нее пользователь видит иконку битого изображения.

Версия сайта:
Current version: 09d0f4c
deployedAt UTC: 2024-05-19 08:18:24

Environment:

Браузер:
Safari 17.3

ОС:
macOS Sonoma

В инструментах разработчика Safari, после сохранения выбранного языка и перехода в профиль, видим статус 404.
![rust_err_1](https://github.com/hexlet-codebattle/codebattle/assets/159926105/b4c864c6-dea4-4ccf-a7d1-fc3bb5fbb679)
![rust_err_4](https://github.com/hexlet-codebattle/codebattle/assets/159926105/321e493d-e4d9-4b5d-9d78-db4d9dbee372)
Reproduction steps

1. Нажать на меню профиля 
2. Перейти в Settings
3. Выбрать в поле Your Weapon: RUST
4. Нажать Save
5. Нажать на меню профиля
6. Перейти в My Profile

Expected result

Пользователь видит в профиле иконку RUST.
Actual result

Пользователь видит иконку битого изображения.
Browsers

Safari 17.3
OS

macOS Sonoma
