### ISSUE TITLE
Не работают ограничения на просмотр завершенной игры с мобильного устройства при первой сессии в браузере

### ISSUE THREAD

**Issue by akhoroshavin** [hexlet-codebattle/codebattle#1865]
### Summary

При первой авторизации в браузере через смартфон у пользователя есть возможность просматривать историю любой игры без Премиум подписки.

Версия сайта:
[Current version: e9cfc50](https://github.com/hexlet-codebattle/codebattle/commit/e9cfc5079cd2994efa3887471cb8e88347022fe9)
deployedAt UTC: 2024-04-22 12:48:14

Environment:

Мобильный браузер:
Яндекс Браузер 24.4.0
Via 4.7.0

Смартфон:
HUAWEI Mate 50 Pro
Версия: Android 4.14.116, EMUI 13.0.0.288

Яндекс Браузер:

https://github.com/hexlet-codebattle/codebattle/assets/160062088/1300bbd3-ea47-49f7-9386-efc342bee2ed

Via:

https://github.com/hexlet-codebattle/codebattle/assets/160062088/33fb2be5-9faa-4925-94bc-c3f930cf7487

### Reproduction steps

```bash
1. Открыть на мобильном устройстве браузер, в котором пользователь до этого не авторизовался в Codebattle
2. Зайти на сайт и авторизоваться
3. Перейти в History 
4. Нажать Show под любой завершенной игрой
```

### Expected result

Пользователя редиректит на страницу игры и он видит всплывающее сообщение Restricted Content 

### Actual result

Открываются всплывающие окна с гайдом и после их закрытия пользователю доступен весь ход игры, содержимое редактора кода и аутпута.

**Comment by ReDBrother** [comment]
Эти игры можно смотреть, они не участвуют в рейтинге и сами задачи тестовые, специально под тренировку
