### ISSUE TITLE
Bug: На электронную почту не приходит ссылка-подтверждение адреса, при регистрации на сайте по "Email"

### ISSUE THREAD

**Issue by annakremneva** [hexlet-codebattle/codebattle#1866]
### Summary

Отсутствует подтверждение "Email", при регистрации пользователя на сайте

### Reproduction steps

```bash
1. Нажать на кнопку "Sing up"
2. Ввести "Nickname"
3. Ввести "Email"
4. Ввести "Password"
5. Ввести "Password Confirmation"
6. Нажать на кнопку "Submit"
```

### Expected result

На странице должно выводиться сообщение, что на указанную при регистрации почту, пользователю была отправлена ссылка, для подтверждения "Email" адреса

### Actual result

Ссылка-подтверждение не приходит, регистрация без подтверждения "Email"прошла успешно, пользователь переходит на главную страницу.

Без ссылки-подтверждения, пользователи могут использовать вымышленную электронную почту

Google Chrome
Version 6.1 (сборка 7601: Service Pack 1)
ОС Windows 7
Current version: e9cfc50
deployedAt UTC: 2024-04-22 12:48:14

### Browsers

Chrome

### OS

Windows

**Comment by m0t999** [comment]
1. Нажать на кнопку "Sing up"
2. Ввести "Nickname"
3. Ввести "Email"
4. Ввести "Password"
5. Ввести "Password Confirmation"
6. Нажать на кнопку "Submit"
Google Chrome   Версия 122.0.6261.129 (Официальная сборка), (x86_64)
    MacOs Monterey 12.1

**Comment by danism76** [comment]
Нажать на кнопку "Sing up"
Ввести "Nickname"
Ввести "Email"
Ввести "Password"
Ввести "Password Confirmation"
Нажать на кнопку "Submit"
Yandex Browser Версия 124.7.0.2379 (64-bit)
Windows 8
