### ISSUE TITLE
Bug: Нельзя оформить подписку для просмотра записей своих завершенных игр

### ISSUE THREAD

**Issue by annakremneva** [hexlet-codebattle/codebattle#1867]
### Summary

Отсутствует возможность оформить подписку для просмотра записей своих завершенных игр

### Reproduction steps

```bash
1. Навести курсор на свой никнейм в правом углу страницы и кликнуть на него, открывается контекстное меню
2. Выбрать "My profile"
3. Нажать на "Completed games"
4. Выбрать любую игру из списка
5. Нажать кнопку "Show", выводится окно "Restricted Content" с сообщением "Sorry! This content for Premium Subscribers only."
6. В строке "Not a Premium subscriber?Want subscribe?" нажать на кнопку "Yes"
```

### Expected result

Отображается форма с полями для заполнения личных данных для оформления подписки

### Actual result

Подписка не оформлена. Просмотр записей своих завершенных игр не доступен. Отображается сообщение "Working on it."

 Google Chrome
 Version 6.1 (сборка 7601: Service Pack 1)
 ОС Windows 7
Current version: e9cfc50
deployedAt UTC: 2024-04-22 12:48:14

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это не баг, а фича)
