### ISSUE TITLE
Bug: Кнопка "X" (Close) не закрывает гайд игры, а сворачивает его 

### ISSUE THREAD

**Issue by Karina1605ing** [hexlet-codebattle/codebattle#1868]
### Summary

Кнопка "X" (Close) не закрывает гайд игры, а сворачивает его 

### Reproduction steps

```bash
1. Пользователь авторизован
2. Открыта страница https://codebattle.hexlet.io/#lobby
3. Нажимаем Fight на доступную игру в лобби
4. В открывшейся игре нажимаем Show gide
5. В открывшемся модальном окне нажимаем "X"(Close)
```

### Expected result

Окошко гайда закрывается

### Actual result

Окошко гайда сворачивается
![гайд баг1](https://github.com/hexlet-codebattle/codebattle/assets/159001364/b1f691f4-dda8-4772-9bc1-8b337af53cbd)
![гайд баг2](https://github.com/hexlet-codebattle/codebattle/assets/159001364/a913858a-c98f-4740-9a79-441011b72eb0)

### Browsers

Firefox, Chrome, Safari, Opera

### OS

Windows

**Comment by MarSam7** [comment]
Я подумала, что это так и задумано, потому что есть кнопка skip guide, которая пропускает шаги и закрывает гайд

**Comment by ReDBrother** [comment]
Да, так работает этот гайд - не на нашей стороне мяч, а на авторов этого внешней либы
