### ISSUE TITLE
Bug: Ошибка при нажатие "Sign up" на первоначальной странице

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-codebattle/codebattle#1869]
### Summary

Ошибка при попытки регистрации идет возврат на главную страницу не обрабатывается запрос 
![photo1715618296](https://github.com/hexlet-codebattle/codebattle/assets/165492069/063e4a4f-c8be-4cf9-9a3a-03de7978a6e9)
![photo1715618296(1)](https://github.com/hexlet-codebattle/codebattle/assets/165492069/9f58816e-1581-4eee-8aa4-f11bc0aad01c)
![photo1715618296(2)](https://github.com/hexlet-codebattle/codebattle/assets/165492069/ac0c4e08-ad26-4504-8fa0-c97307df82ce)
![photo1715618296(3)](https://github.com/hexlet-codebattle/codebattle/assets/165492069/64aa55a4-994d-4066-bb56-68170d911026)

### Reproduction steps

```bash
1. Перейти по ссылке (https://codebattle.hexlet.io/)
 2. Нажать на кнопку «Sing up»
```

### Expected result

Открывается форма регистрации

### Actual result

Происходит возврат на главную страницу о

### Browsers

Firefox

### OS

Linux

**Comment by m0t999** [comment]
1. Перейти по ссылке (https://codebattle.hexlet.io/)
 2. Нажать на кнопку «Sing up»
Expected result
Открывается форма регистрации

Actual result
Происходит возврат на главную страницу 

Browsers
Google Chrome   Версия 122.0.6261.129 (Официальная сборка), (x86_64)

OS
MacOs Monterey 12.1

**Comment by Linchuki** [comment]
Summary
Ошибка регистрации и авторизации на сайте.

Reproduction steps

Перейти по ссылке https://codebattle.hexlet.io/
Нажать кнопку 'Sign in' или 'Sign up'
Expected result
Открылась главная страница сайта

Actual result
Поехала верстка формы регистрации и авторизации
![Sign in](https://github.com/hexlet-codebattle/codebattle/assets/151373511/81256aa3-30fc-42cb-85c6-7cf62958cea4)

Версия сайта: Current version: https://github.com/hexlet-codebattle/codebattle/commit/132a513ce9ee127a9266343dd8dc430f0d58a751
OS: Windows 10 Корпоративная, 64-разрядная операционная система, процессор x64

Browsers: Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
Yandex Версия 24.4.2.887 (64-bit)

**Comment by akhoroshavin** [comment]
В дополнение к багу по верстке: 

Едет верстка в заголовке сайта ("Codebattle by Hexlet's Community") при попытки авторизоваться или зарегистрироваться.

Environment:

[Current version: df0d252](https://github.com/hexlet-codebattle/codebattle/commit/df0d2525a34729da63be7d71e10ba02b91618c07)

Браузер:
Chrome 124.0.6367.201
Mozilla Firefox, 125.0.3
Mircosoft Edge, 124.0.2478.80
Яндекс Браузер 24.4.0
Opera One (версия: 109.0.5097.80)
Reproduction steps

1. Открыть сайт
2. Нажать Sign In/Sign Up

Expected result:
Заголовок выглядит ровно, надпись by Hexlet's Community под надписью Codebattle

Actual result:
Верстка едет 

![поехала_верстка_в хроме](https://github.com/hexlet-codebattle/codebattle/assets/160062088/4dd614f9-e768-4e32-a3ee-d82ccb837b1b)

Mozilla Firefox, 125.0.3
Mircosoft Edge, 124.0.2478.80
Яндекс Браузер 24.4.0
Opera One (версия: 109.0.5097.80)

OS: Windows

**Comment by ReDBrother** [comment]
fixed
