### ISSUE TITLE
Bug: ошибка при нажатии  sign in на главной странице 

### ISSUE THREAD

**Issue by m0t999** [hexlet-codebattle/codebattle#1870]
### Summary

Ошибка при попытке входа на главной старнице 

### Reproduction steps

```bash
1. Перейти по ссылке (https://codebattle.hexlet.io/)
 2. Нажать на кнопку «Sing in»
```

### Expected result

Откроется страница логина

### Actual result

Страница обновляется и возвращается на главную
![Снимок экрана 2024-05-14 в 13 05 22](https://github.com/hexlet-codebattle/codebattle/assets/162465345/2e85f647-0dfb-48d7-9533-930483380d87)

### Browsers

Chrome

### OS

Mac

**Comment by Linchuki** [comment]
Summary
Ошибка регистрации и авторизации на сайте.

Reproduction steps
1.  Перейти по ссылке https://codebattle.hexlet.io
2. Нажать кнопку 'Sign in' или 'Sign up'

Expected result
Открылась главная страница сайта

Actual result
Поехала верстка формы регистрации и авторизации
![Sign in](https://github.com/hexlet-codebattle/codebattle/assets/151373511/c1ca53fe-252f-4ea3-b0cf-37a1a3c3f04d)

Версия сайта: Current version: 132a513
OS: Windows 10 Корпоративная, 64-разрядная операционная система, процессор x64

Browsers: Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
Yandex Версия 24.4.2.887 (64-bit)

**Comment by ReDBrother** [comment]
Дубль от #1869
