### ISSUE TITLE
Bug: Ошибка расположения окон и полей в sign in

### ISSUE THREAD

**Issue by Loyrens** [hexlet-codebattle/codebattle#1871]
### Summary

В десктопной версии сайта, при заходе в sign in, окна и поля имеют нестандартный размер и смещены вправо. 
Надписи нечитаемые. 

Версия сайта:
[Current version: 132a513](https://github.com/hexlet-codebattle/codebattle/commit/132a513ce9ee127a9266343dd8dc430f0d58a751)
deployedAt UTC: 2024-05-14 08:19:09

Environment:
Google Chrome, Версия 124.0.6367.119 (Официальная сборка), (64 бит)
Windows 10 Домашняя, Версия 22H2 (сборка ОС 19045.4291)

test-data:
Ссылка веб-сайта: https://codebattle.hexlet.io/

![Bug 1](https://github.com/hexlet-codebattle/codebattle/assets/158618528/d77b2f39-e37f-402a-a497-1dd0b2bf3819)
![bug 2](https://github.com/hexlet-codebattle/codebattle/assets/158618528/81d9f58c-42b5-43a5-b345-553d180add0b)
![bug 3](https://github.com/hexlet-codebattle/codebattle/assets/158618528/f1048f51-36da-464d-85be-546f3f9d2e87)

### Reproduction steps

```bash
1. Зайти на сайт codebattle
2. Перейти в sign in
```

### Expected result

Окна и поля ввода расположены по середине страницы и не заужены.
Информация в окнах и надписи над полями читаемая.

### Actual result

Окна и поля ввода располагаются в правой части страницы и заужены. Информация в полях и надписи нечитаемые. 

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1869
