### ISSUE TITLE
Bug: На сайте можно зарегистрироваться с никнеймом, не соответствующим требованиям

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1873]
### Summary

Если вписать в поле ‘Nickname’ 3 латинские буквы, без цифр и подчеркиваний, регистрация проходит успешно

### Reproduction steps

```bash
1. Перейти по ссылке https://codebattle.hexlet.io/
2. Нажать кнопку 'Sign up'
3. Ввести Nickname, например zzz
4. Ввести Email, например test@mail.ru
5. Ввести Password, например 111111
6. Ввести Password Confirmation, например 111111
7. Нажать кнопку 'Submit'
```

### Expected result

Вышло сообщение об ошибке в поле ‘Nickname’:
Should contain Latin letters, numbers and underscores. Only begin with latin letter

### Actual result

Регистрация прошла успешно. Открылась главная страница авторизованного пользователя.

![Регистрация_Nickname](https://github.com/hexlet-codebattle/codebattle/assets/151373511/ebeff593-b896-472d-80cd-adb0971e39cf)
![Регистрация_Nickname_2](https://github.com/hexlet-codebattle/codebattle/assets/151373511/b34dd3c5-5cb4-4879-a117-8cebe5e0c691)

Environment:
Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
Yandex Версия 24.4.2.887 (64-bit)
OS: Windows 10 Корпоративная

Current version: df0d252

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нет, имя может состоять и просто из букв)
Иначе обычные имена не смогут проходить, а это валидные имена)
