### ISSUE TITLE
Bug: Отсутствует подтверждение почты

### ISSUE THREAD

**Issue by MarSam7** [hexlet-codebattle/codebattle#1874]
### Summary

При регистрации на почту не приходит сообщение с подтверждением создания аккаунта

### Reproduction steps

```bash
1. Перейти по ссылке (https://codebattle.hexlet.io/)
2. Нажать на кнопку "Sing up"
3. Ввести Nickname = "iii"
4. Ввести Email = "a@a.ru"
5. Ввести Password = 123456
6. Ввести Password Confirmation = 123456
7. Нажать кнопку "Sumbit"
```

### Expected result

На почту должно прийти подтверждение регистрации 

### Actual result

Нас переносит сразу в созданный аккаунт
![Снимок экрана (48)](https://github.com/hexlet-codebattle/codebattle/assets/158337020/1f1d6244-bfe1-4775-a8be-d4e812edcf21)
![Снимок экрана (49)](https://github.com/hexlet-codebattle/codebattle/assets/158337020/4f1d6df6-2cfe-4adc-82b6-1e74a24b4349)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль #1827
