### ISSUE TITLE
Bug: Ненадёжный пароль

### ISSUE THREAD

**Issue by MarSam7** [hexlet-codebattle/codebattle#1875]
### Summary

Для создания пароля слишком мало требований
![Ненаджный пароль](https://github.com/hexlet-codebattle/codebattle/assets/158337020/632bc529-a816-4f73-b5b0-0034af41b468)

### Reproduction steps

```bash
1. Перейти по ссылке (https://codebattle.hexlet.io/)
2. Нажать на кнопку "Sing up"
3. Ввести Password = 123456
```

### Expected result

Пароль не подходит под требования(пр. должны присутствовать латинские буквы разного регистра, цифры, специальные символы, пароль должен состоять не менее, чем из 6 символов, не более, чем из 16 символов)

### Actual result

Пароль подходит под требования

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы не банк или социальная сеть с милионами пользователей и стараемся не хранить приватные данные
К нам не могут быть таких требований

**Comment by ReDBrother** [comment]
У пароля другие правила, как и отображены на интерфейсе

**Comment by MarSam7** [comment]
> У пароля другие правила, как и отображены на интерфейсе

![Безопасные данные](https://github.com/hexlet-codebattle/codebattle/assets/158337020/241c39df-e22f-41f7-b5ad-468e188dbed9)
В проекте просто есть пункт о безопасности данных и я немного заволновалась из-за простых требований
