### ISSUE TITLE
Bug: Бот пассивный во время игры 

### ISSUE THREAD

**Issue by MarSam7** [hexlet-codebattle/codebattle#1876]
### Summary

Бот работает в одном и том же медленном режиме
![Бот 1_05](https://github.com/hexlet-codebattle/codebattle/assets/158337020/c71e7e93-8405-4c69-83b1-6a4973b819d4)
![Бот 2_08](https://github.com/hexlet-codebattle/codebattle/assets/158337020/257270bf-0913-429d-8ba2-220777348f2e)
![Бот 3_20](https://github.com/hexlet-codebattle/codebattle/assets/158337020/b986897c-113c-445c-ab3e-cc13b5071b02)
![Бот 4_34](https://github.com/hexlet-codebattle/codebattle/assets/158337020/a01279b0-8409-43a4-8069-2fdaf067728a)
![Бот 7_56](https://github.com/hexlet-codebattle/codebattle/assets/158337020/d905ac5f-fd45-48f2-94ce-738ba46f9194)

### Reproduction steps

```bash
1. Быть зарегистрированным 
2. Нажать кнопку "Create a game"
3. Level = "1 звезда"
4. Game Type = "With a bot"
5. Time control = "8 min"
6. Choose task by name or tags = "rect_area"
7. Tags = "math"
8.  Нажать кнопку "Create battle"
```

### Expected result

У ботов есть несколько скоростных режимов, в которых с ними соревнуются игроки

### Actual result

Бот работает в одном скоростном режиме. На режиме времени 3 минуты бот не делает ничего. На режиме 8 минут бот стартует спустя ~3,5 минуты

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Ну так можно сказать и про живых участников, которые не успевают решить задание вовремя)
Мы не будем ботов подгонять под временные рамки

**Comment by MarSam7** [comment]
> Ну так можно сказать и про живых участников, которые не успевают решить задание вовремя) Мы не будем ботов подгонять под временные рамки

А как с тем, что если установить временной лимит при игре с ботом в 3 минуты, то он не начинает ничего делать?
