### ISSUE TITLE
Bug:  Ошибка при создании турнира с жетоным типом доступа

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-codebattle/codebattle#1878]
### Summary
Проверка возможности создания турнира  с жетоным типом доступа

### Reproduction steps

```bash
- Нажать кнопку "You may to create one"(Tournaments Info)
- Пролистать до нижней части страницы
- Выбрать Access type "token" 
- Нажать  "Create"
```

### Expected result

Открывается турнирная сетка 

### Actual result

Турнирная сетка не открывается, серый экран:
![photo1715779084](https://github.com/hexlet-codebattle/codebattle/assets/165492069/128a899c-80bc-4f45-8cca-2b97567736cf)
В devtools ошибка обработки метода "post": 
![photo1715779139](https://github.com/hexlet-codebattle/codebattle/assets/165492069/d5ea5fa5-3eb5-4bef-a571-66314db54e64)
В консоле выводится такое сообщение: 
![photo1715779108](https://github.com/hexlet-codebattle/codebattle/assets/165492069/4ff2c3ac-6192-4b9f-b412-f3685154d400)
![photo1715779127](https://github.com/hexlet-codebattle/codebattle/assets/165492069/11b3592b-4e29-49a4-9df9-79b9a8e573d8)

### Browsers

Firefox

### OS

Linux

**Comment by isyambo** [comment]
Summary
Ошибка при создании турнира (с данными по умолчанию)
Reproduction steps:
- В разделе Tournaments нажимаем на гипер-ссылку "Tournaments info"
- Проматываем страницу вниз и нажимаем кнопку "Create"
Expected-result
открывается турнирная сетка 
Actual-result
Отображается пустой экран
![Снимок экрана 2024-05-19 191233](https://github.com/hexlet-codebattle/codebattle/assets/140921537/a95d0c4a-51e7-4e05-b66c-18f5d0d1785a)
![Снимок экрана 2024-05-19 191244](https://github.com/hexlet-codebattle/codebattle/assets/140921537/96d53e33-a308-4c58-b102-e278397fbb17)

**Comment by ReDBrother** [comment]
Fixed
