### ISSUE TITLE
Bug:  При установке таймера игры актуальное время игры меньше установленного

### ISSUE THREAD

**Issue by Josssei** [hexlet-codebattle/codebattle#1879]
### Summary

 Проверка возможности установить таймер в игре

### Reproduction steps

```bash
1. Открыть сайт https://codebattle.hexlet.io/#lobby
2. Нажать кнопку "Create a game"
3. Установить таймер на 35 минут
4. В созданной игре актуальный таймер на 2:55 меньше установленного
```

### Expected result

Установленный и актуальный таймер одинаковы 

### Actual result

Установленный и актуальный таймеры не совпадают
![Установка таймера игры](https://github.com/hexlet-codebattle/codebattle/assets/159802114/4da6c02e-29ae-4fd5-a186-a866b0699440)
![Установка таймера игры 3](https://github.com/hexlet-codebattle/codebattle/assets/159802114/24d5b16b-3ba3-40b1-93e3-6eb7142cd848)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Таймер всегда установлен относительно времени, установленного на компе/ноуте - если он некорректен, то и таймер будет спешить/отставать. Делать таймер по всем канонам очень дорого по разработке, мы к такому не готовы пока

**Comment by Esetik** [comment]
Такая же ситуация:
![установка таймера](https://github.com/hexlet-codebattle/codebattle/assets/162605028/aeefa49f-f6fa-4a80-998b-da401a8389b5)
![неверный таймер](https://github.com/hexlet-codebattle/codebattle/assets/162605028/61a48bd7-c4fe-40b4-a67b-6f110da092c2)
environment:
Google Chrome 122.0.6261.129 (Официальная сборка), (64 бит)
Windows 10 Pro

**Comment by burd-up** [comment]
Не воспроизвёл.
OS Windows
Current version: https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4
Browser Chrome

**Comment by yana-fesenko** [comment]
Баг не воспроизводится
[Current version: 0ba780d](https://github.com/hexlet-codebattle/codebattle/commit/0ba780dfd087979ff79f615ae67f4e7deae2d58b)
Browsers
Chrome
OS
Mac
<img width="676" alt="Снимок экрана 2024-06-16 в 16 27 22" src="https://github.com/hexlet-codebattle/codebattle/assets/142812556/6ef142b6-3de7-45cd-8255-26ddb3b1fc6a">
<img width="614" alt="Снимок экрана 2024-06-16 в 16 28 06" src="https://github.com/hexlet-codebattle/codebattle/assets/142812556/8f17fe7d-f955-4a9f-845e-c030274b9eea">

**Comment by NekoStyleOo** [comment]
Summary:
Таймер работает некорректно.

Шаги:

Открыта страница https://codebattle.hexlet.io/#lobby; 
Пользователь авторизован в сети;
Нажать кнопку "Create a game"
Создана игра с таймером на 3 минуты
В созданной игре актуальный таймер на 01:01 меньше установленного
Окружение:
Opera —116.0.5366.71 
Windows 10 Pro

Ожидаемый результат
Установленный и актуальный таймер совпадают

Фактический результат:
Установленный и актуальный таймеры разнятся: 

![Image](https://github.com/user-attachments/assets/f6704560-9736-41b6-a1f9-118827639677)
![Image](https://github.com/user-attachments/assets/289301d5-01b6-40f2-8c02-31ca6ec87a62)
