### ISSUE TITLE
Bug: Проблема с авторизацией ошибка 404

### ISSUE THREAD

**Issue by ViktorSmiryagin** [hexlet-codebattle/codebattle#1880]
### Summary

Проверка успешной авторизации

### Reproduction steps

```bash
1.Нажимаем на "sign in"
```

### Expected result

Открывается форма авторизации

### Actual result

Открывается главная страница с проблемной версткой из-за ошибки загрузки страницы (404) 
![signinbug3](https://github.com/hexlet-codebattle/codebattle/assets/165492069/a91517f0-c871-4551-b44d-51a25055c92e)
![signinbug2](https://github.com/hexlet-codebattle/codebattle/assets/165492069/c32d78bb-5fcd-4031-a009-ed1d651ecb56)
![bug4](https://github.com/hexlet-codebattle/codebattle/assets/165492069/4f766f47-ba25-4062-b5af-f8fb2e712282)

### Browsers

Firefox

### OS

Linux

**Comment by ReDBrother** [comment]
Ошибка никак не связана с авторизацией
Продакшен упал, чиним

**Comment by ViktorSmiryagin** [comment]
> Ошибка никак не связана с авторизацией Продакшен упал, чиним

Понял, буду иметь ввиду) спасибо
