### ISSUE TITLE
Bug: Кнопки 'Сражаться' и 'Отправить' на главной странице отображаются на русском языке.

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1881]
### Summary

На главной странице авторизованного пользователя в таблице в Lobby  кнопка 'Сражаться' - на русском языке.
В общем чате на главной странице кнопка 'Отправить' - на русском языке.
При этом весь сайт написан на английском языке.

### Reproduction steps

```bash
1. Авторизоваться на сайте
```

### Expected result

Весь сайт написан на английском языке

### Actual result

В таблице в Lobby  кнопка 'Сражаться' - на русском языке.
В общем чате на главной странице кнопка 'Отправить' - на русском языке.
![Кнопки на русском](https://github.com/hexlet-codebattle/codebattle/assets/151373511/793dd2fd-bc9f-4fc9-a68d-acf5830ac686)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1882
