### ISSUE TITLE
Bug: В игре некоторые кнопки отображаются на русском языке

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1882]
### Summary

В открытой игре некоторые кнопки отображаются на русском языке

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Дождаться пока в таблице в Lobby появится текущая игра
3. Нажать кнопку 'Show' в любой строке с текущей игрой
```

### Expected result

Открылась страница текущей игры. Все кнопки и текст отображаются на английском языке 

### Actual result

Кнопки: 'Задача', 'Тесты', 'Игра завершена', 'Смотреть историю', 'На главную' и 'Отправить'отображаются на русском языке.
![Кнопки в игре на русском](https://github.com/hexlet-codebattle/codebattle/assets/151373511/92a3dc91-f0ab-477c-9d5a-ff265b96fc70)
![Кнопки в игре 2](https://github.com/hexlet-codebattle/codebattle/assets/151373511/35c45326-dfc3-4f77-9cff-cc288b4f4962)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
fixed, скоро задеплоим
