### ISSUE TITLE
Bug: Не осуществляется переход в Discord по ссылке из личного профиля

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1884]
### Summary

При попытке присоединиться к Discord из личного профиля, появляется сообщение с кнопкой 'Принять приглашение'. После нажатия на эту кнопку, появляется сообщение: "Не удается принять приглашение"

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать кнопку входа в личный профиль
3. Нажать 'Join Discord'
4. Нажать кнопку 'Принять приглашение'
```

### Expected result

Открылся чат игроков в Discord

### Actual result

Появилось сообщение "Не удается принять приглашение'
Environment:
Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
OS: Windows 10 Корпоративная
Current version: 09d0f4c
![Discord](https://github.com/hexlet-codebattle/codebattle/assets/151373511/269effed-830c-4e44-9984-dc82b8e756d0)

### Browsers

Chrome

### OS

Windows

**Comment by Linchuki** [comment]
У меня тоже больше нет ошибки, все работает

**Comment by raiden-creator** [comment]
Проверка присоединения к сервису "Discord"
требования: |
Пользователь может присоединиться к сервису "Discord"
предварительные условия:
Пользователь уже зарегистрирован и вошёл через Sign in
тестовые данные: |
Кнопка "Join Discord""
среда: |
Google Chrome версии 132.0.6834.83 (64-разрядная)
Windows 11
шаги:
- Нажать "Join Discord""
ожидаемый результат: |
Пользователь переходит на сайт: https://discord.gg/dTpFXrYU3v
фактический результат: |
Сайт не открывается и возникает ошибка

![Image](https://github.com/user-attachments/assets/e5c38f35-26a3-4e6d-83da-bde4815af0a6)
