### ISSUE TITLE
Bug: При создании игры с ботом, язык программирования в игре не соответствует языку игрока

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1885]
### Summary

Игра открывается не на языке пользователя, а на другом. Изменить язык на нужный не получается, т.к. его нет в списке

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать  кнопку ‘Create a game’
3. Нажать  кнопку ‘With a bot’
Нажать  кнопку ‘Create battle’
```

### Expected result

Язык программирования в игре совпадает с языком игрока, указанном в личном профиле

### Actual result

Язык программирования не соответствует языку игрока, указанному в личном профиле. Нужный язык отсутствует в списке языков.

Environment:
Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
OS: Windows 10 Корпоративная
Current version: 1a8c00b

https://github.com/hexlet-codebattle/codebattle/assets/151373511/ae05874f-be87-40da-830a-08b692a065c9

### Browsers

Chrome

### OS

Windows

**Comment by Linchuki** [comment]
ошибка

**Comment by burd-up** [comment]
Не воспроизвёл.
OS Windows
Current version: https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4
Browser Chrome
