### ISSUE TITLE
Bug: В мобильной версии при перелистывании турниров, они не полностью отображаются на странице

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1890]
### Summary

В мобильной версии, при вертикальном экране, при перелистывании турниров, невозможно увидеть один турнир на странице, он съезжает частично на следующую страницу. 

### Reproduction steps

```bash
1. Открыть панель разработчика, нажав клавишу F12
2. Нажать на значок мобильного телефона в панели инструментов 
3. Из списка мобильных устройств выбрать модель iPhone 12Pro
4. Нажать кнопку ‘Sign in’
5. Ввести Email
6. Ввести Password
7. Нажать кнопку ‘Submit’
8. Нажать вкладку ‘Tournaments’
9. Листать турниры, нажимаю стрелочку вправо
```

### Expected result

Турниры отображаются целиком - один на странице

### Actual result

Турниры смещаются на следующую страницу, прочитать описание невозможно. Во вкладке 'History' так же

Environment:
Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
OS: Windows 10 Корпоративная
Current version: f616d68

![турниры-мобила](https://github.com/hexlet-codebattle/codebattle/assets/151373511/3d9f290d-3f42-4c43-9d43-960837a91e90)
https://github.com/hexlet-codebattle/codebattle/assets/151373511/1592f92b-643f-406e-8b24-a7c790e89ba9

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Во первых, они могут уместиться - слайдер доступен и точечно управляем.
Багой это будет только в том случае, если абсолютно все возможные способы достучатся до контента не помогут.
