### ISSUE TITLE
Bug: Нет возможности удалить свой профиль с сайта

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1892]
### Summary

После регистрации на сайте, нет возможности удалить свой профиль

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать кнопку входа в личный профиль
3. Нажать 'Ny Profile'
4. Нажать 'Settings'
```

### Expected result

Должна быть функция "Удалить профиль"

### Actual result

Функция "Удалить профиль" отсутствует на сайте

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1472
