### ISSUE TITLE
Bug: После выигрыша, у игрока кнопка 'run' продолжает быть активной

### ISSUE THREAD

**Issue by Linchuki** [hexlet-codebattle/codebattle#1894]
### Summary

После окончания игры кнопка 'run' должна стать неактивной у победителя. Но при клике по ней, включается музыка, потом открывается вкладка Output с информацией, что решение не получается проверить

### Reproduction steps

```bash
1. Авторизоваться на сайте
2. Нажать кнопку ‘Create a game’
3. Нажать кнопку ‘With a bot’
4. В разделе ‘Choose task by name or tags’ выбрать задание ‘rect_area’ из списка
5. Нажать кнопку ‘Create battle’
6. Написать код “return width * length;” без кавычек в соответствующее поле в редакторе кода
7. Нажать кнопку ‘run’
8. Закрыть модальное окно с сообщением о выигрыше, нажав на крестик в правом верхнем углу
9. Нажать кнопку ‘run’
```

### Expected result

Кнопка  ‘run’ неактивна 

### Actual result

Кнопка активна и вновь запускает проверку

Environment:
Opera One(версия: 109.0.5097.80)
Google Chrome Версия 124.0.6367.201 (Официальная сборка), (64 бит)
OS: Windows 10 Корпоративная
Current version: f616d68

![run](https://github.com/hexlet-codebattle/codebattle/assets/151373511/47f0272c-ef44-42e1-9137-c9fa1ccc3d03)
https://github.com/hexlet-codebattle/codebattle/assets/151373511/aa25f26a-6883-463f-9fbd-91cfa4f73e36

### Browsers

Chrome, Opera

### OS

Windows

Ссылка на закрытый баг по этой теме:
https://github.com/hexlet-codebattle/codebattle/issues/1858

**Comment by ReDBrother** [comment]
Это фича, мы оставляем за участниками возможность поэкспериментировать с кодом
