### ISSUE TITLE
Bug: Отсутствуют варианты сложности при игре с ботом.

### ISSUE THREAD

**Issue by kufex** [hexlet-codebattle/codebattle#1895]
### Summary

При создание игры есть только сложность задачи, но нету сложности бота. Пользователь не может сделать игру более или менее сложной.

### Reproduction steps

```bash
1. Нажать кнопку "Create a game
```

### Expected result

В настройках к создаваемой игре должны быть вариации сложности бота.

### Actual result

![33333333](https://github.com/hexlet-codebattle/codebattle/assets/162039662/f8302ff1-48c1-4b65-904b-11091b75e952)
В настройках к игре нету возможности выбрать сложность бота. 

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
И не будет такой фичи
Боты подбирают свою скорость решения базируясь на вашем рейтинге и чем он больше, тем сложнее бот будет
