### ISSUE TITLE
Bug: Бот не всегда начинает кодить.

### ISSUE THREAD

**Issue by kufex** [hexlet-codebattle/codebattle#1896]
### Summary

Бот не начал кодить и игра закончилась без победителя, когда закончилось время.

### Reproduction steps

```bash
1. Нажать кнопку "Create a game"
2. Создать игру с настройками : 4 звезды, игра с ботом, 20 минут, задача "number_to_english"
3. Нажать кнопку "Create battle"
```

### Expected result

Будет создана игра в которой пользователь будет соперничать с ботом на время.

### Actual result

[
![4](https://github.com/hexlet-codebattle/codebattle/assets/162039662/3635204c-bea8-4c4a-b395-7991bce3f4b4)
](url)
Бот не кодил, даже с учетом что сам пользователь пытался решить задачу. Время закончилось, но бот не написал ни одной строчки кода.

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
И правильно, не зачем участвовать в битве, которая уже проиграна
Бот ведет себя как человек
