### ISSUE TITLE
Bug: Возможность создания турнира с датой начала в прошлом

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1898]
### Summary

Пользователь может установить дату начала турнира в прошлом, что не должно быть возможным.

### Reproduction steps

```bash
1. Открыть страницу с турнирами.
2. Пролистать до формы создания турнира.
3. Ввести дату и время в поле "starts at", указывая дату из прошлого (например, 1990 год).
4. Нажать кнопку "create".
```

### Expected result

Турнир не должен быть создан. Должна появиться подсказка, указывающая на невозможность ввода даты и времени из прошлого.

### Actual result

Турнир успешно создается с датой начала из прошлого, указанной в поле 'starts at'.

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дата начала очень условная штука, она не влияет на то, когда начнется турнир фактически
Этим управляет пользователь, который нажал кнопку старт

**Comment by burd-up** [comment]
@ReDBrother , спасибо за ответ.

Я понимаю, что дата начала турнира сейчас условна и не влияет на фактический старт. Однако, в таком случае возникает вопрос: какой смысл несет поле "Дата начала", если оно не влияет ни на что и можно выбрать любую дату и время, даже из прошлого?

Если поле "Дата начала" не имеет значения для логики приложения, может быть стоит его убрать или, как минимум, ограничить выбор дат, чтобы избежать путаницы. 

Возможность выбирать даты из прошлого может привести к недопониманию и недоразумениям среди пользователей.

Прошу вас переоткрыть баг для дальнейшего обсуждения и поиска лучшего решения.

Спасибо!
