### ISSUE TITLE
Bug: Несоответствие стилей валидации полей в одной форме

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1899]
### Summary

В форме для создания и изменения task pack используется различный стиль валидации для разных полей. В форме для создания турниров также наблюдается несоответствие стилей валидации полей.

### Reproduction steps

```bash
1. Открыть форму для создания task pack.
2. Очистить поля "name" и "task_ids".
3. Нажать на кнопку "save".
```

### Expected result

Срабатывает валидация полей. Появляются подсказки, выполненные в **одном** стиле, о том, что поля не могут быть пустыми.

### Actual result

Срабатывает валидация полей. Появляются подсказки, выполненные в **разных** стилях, о том, что поля не могут быть пустыми.

![image](https://github.com/hexlet-codebattle/codebattle/assets/78302371/8da358f4-a6de-43d4-8d57-181c6777e49c)
![image](https://github.com/hexlet-codebattle/codebattle/assets/78302371/ba620b0c-078a-41c9-9c79-4f878b323c95)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Эм, это внутрибраузерная подсказка, которой мы не управляем
Мы не может задать ей свой уникальный стиль

**Comment by burd-up** [comment]
@ReDBrother спасибо за ответ! 

Я понимаю, что вы хотите сказать, но суть моего баг-репорта заключалась немного в другом. Извиняюсь за недопонимание.

Логично было бы у всех полей обязательных для заполнения писать в html атрибут "required".
Так же и в обратную сторону у всех полей обязательных для заполнения с атрибутом "required" в html делать (или не делать) подсказку "can't be blank" (см. пример с формой для создания турнира). В общем сделать валидацию более единообразной.
<img width="1666" alt="image" src="https://github.com/hexlet-codebattle/codebattle/assets/78302371/6fa5d267-04b1-4b94-817f-f891fbb2bd37">
<img width="1569" alt="Снимок экрана 2024-05-27 192242" src="https://github.com/hexlet-codebattle/codebattle/assets/78302371/c49e92c0-43db-456c-bf06-c30388e526e1">
Прошу переоткрыть баг для дальнейшего обсуждения и поиска решения, чтобы у нас был единый стиль валидации.

Спасибо!
