### ISSUE TITLE
Bug: В списке User rating разбивка аккаунтов на ботов и пользователей работает не правильно

### ISSUE THREAD

**Issue by LitvinDmitry** [hexlet-codebattle/codebattle#1900]
### Summary

В списке User rating часть пользователей выводится только с включенным чекбоксом 'With bots'

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на никнейм в шапке
3. Нажать User rating
4. Нажать на чекбокс With bots
5. Два раза нажать на Joined
5. Долистать до конца списка ботов (на момент составления #109 последний бот) (скрин 1)
6. Скопировать никнейм первого пользователя после ботов 
7. В диапазоне от 110 до 136 пользователя в списке скопировать любой ник
8. Убрать галочку с чекбокса 
9. Вставить в поиск скопированный ник (скрин 2)
```

### Expected result

Пользователь появился в списке 

### Actual result

Пользователя в списке нет

1. ![изображение_2024-05-26_231725414](https://github.com/hexlet-codebattle/codebattle/assets/167113820/8b68596d-e57e-4a85-83bd-00ae1c31807f)

2. ![изображение_2024-05-26_231817829](https://github.com/hexlet-codebattle/codebattle/assets/167113820/38c160ba-bac8-4f91-b476-5c3d00701b1c)

### Browsers

Opera

### OS

Windows

**Comment by ReDBrother** [comment]
В поиске вбито имя бота)

**Comment by LitvinDmitry** [comment]
> В поиске вбито имя бота)

Тогда нужно их как то обозначить, 
потому что сейчас они выглядят так 
![image](https://github.com/hexlet-codebattle/codebattle/assets/167113820/f8458a3b-6b56-43b3-af88-a1b7b8fbe2fc)
