### ISSUE TITLE
Bug: Сортировка с учетом ботов по Joined выводит ботов в начало списка

### ISSUE THREAD

**Issue by LitvinDmitry** [hexlet-codebattle/codebattle#1901]
### Summary

Сортировка по Joined от раннего к позднему, в User rating, с активным чекбоксом With bot - выводит ботов в начало списка, сортируя их при этом от позднего к раннему

![изображение_2024-05-26_233210314](https://github.com/hexlet-codebattle/codebattle/assets/167113820/52051d0e-b3fe-4b5a-8fc3-dc41966ebc0e)

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на никнейм в шапке
3. Нажать User rating
4. Нажать на чекбокс With bots
5. Два раза нажать на Joined
```

### Expected result

Список начинается с самого первого зарегистрированного аккаунта 

### Actual result

Список начинается с последнего зарегистрированного бота

### Browsers

Opera

### OS

Windows

**Comment by ReDBrother** [comment]
Ничего не понял, почему? Там по алфавиту идет список)

**Comment by LitvinDmitry** [comment]
Боты отсортиргованы от 2024 года к 2019 ![image](https://github.com/hexlet-codebattle/codebattle/assets/167113820/b69626a5-ad99-4055-adb0-224141c7bc78)

Люди отсортированы от 2017 к 2024 (то есть наоборот) 
![2Opera Снимок_2024-05-28_234914_codebattle hexlet io](https://github.com/hexlet-codebattle/codebattle/assets/167113820/30bffd5a-c8eb-4e12-9d28-1e9eac7d5df7)
