### ISSUE TITLE
Bug: Невозможно узнать ID задачи для ввода в поле task_ids при создании пакета задач

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1902]
### Summary

При создании task pack пользователя просят ввести ID задач, которые он хочет включить в пакет. Проблема заключается в том, что эта информация отсутствует в приложении (в том числе на странице со списком задач). Предлагаю в качестве решения добавить в таблицу со списком задач столбец с ID задачи.

### Reproduction steps

```bash
1. Открыть страницу создания task pack.
2. Обратить внимание на поле task_ids, куда необходимо ввести ID задач.
3. Перейти на страницу со списком задач, чтобы попытаться найти нужные ID.
```

### Expected result

Пользователь может найти ID задач на странице со списком задач и ввести их в поле task_ids при создании task pack.

### Actual result

В таблице со списком задач отсутствует столбец ID, и пользователь не имеет возможности узнать ID задач, которые ему необходимы.
![image](https://github.com/hexlet-codebattle/codebattle/assets/78302371/d82cb532-af26-42c9-abfa-3783f33189d2)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Добавил, при следующем деплоя сайта выкатим
