### ISSUE TITLE
Bug: Возможность сохранить задачу с менее чем тремя примерами в списке Examples при редактировании 

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1904]
### Summary

При создании новой задачи существует требование добавить минимум 3 примера (examples) для возможности сохранения задачи. Однако при редактировании существующей задачи это ограничение отсутствует, что позволяет удалить все примеры и сохранить задачу без них.

### Reproduction steps

```bash
1. Открыть ранее созданную задачу.
2. Удалить все элементы из списка Examples.
3. Нажать на кнопку Save.
4. В открывшемся окне подтверждения нажать на кнопку Confirm.
```

### Expected result

Кнопка Save должна быть неактивна, так как не выполнено условие по наличию минимум трех примеров в списке Examples.

### Actual result

Задача пересохранилась с пустым списком Examples.

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Нет, такого не будет))
Это сознательная фича
