### ISSUE TITLE
Bug: Возможность создания задачи без заполнения 3 и 4 шага

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1907]
### Summary

В интерфейсе для создания задач после корректного заполнения шагов 1 и 2 у пользователя появляется возможность сохранить задачу без заполнения шагов 3 и 4, что не должно быть возможным. 

### Reproduction steps

```bash
1. Открыть интерфейс для создания задач.
2. Заполнить корректно шаги 1 и 2.
3. Нажать кнопку Save.
```

### Expected result

Кнопка Save должна быть не активна, так как пользователь не заполнил все шаги.

### Actual result

Пользователь сохраняет задачу без заполнения шагов 3 и 4, и задача может быть выбрана для игр.

![image](https://github.com/hexlet-codebattle/codebattle/assets/78302371/4c22bf57-7ef2-4949-8f64-39e64b2043bd)

**Comment by ReDBrother** [comment]
Нет, для задач 3 и 4 пункт являются дополнительными
