### ISSUE TITLE
Bug: Несуществующая почта после авторизации через Github

### ISSUE THREAD

**Issue by BeoWolf61** [hexlet-codebattle/codebattle#1909]
### Summary

После авторизации через Github, почта, привязанная к нему становится не доступной для регистрации на кодбаттле.

[Current version](https://github.com/hexlet-codebattle/codebattle/commit/eedb0703fc2bfdc18b2d844998e39e7c58a651d7)
deployedAt UTC: 2024-05-30 13:18:31

### Reproduction steps

```bash
1. Авторизоваться через гитхаб на сайте https://codebattle.hexlet.io/
2. Разлогиниться
3. Нажать кнопку "Sign UP" 
4. Попробовать пройти регистрацию на такую почту, которая привязана к Github
```

### Expected result

Должна быть зарегистрирована новая учетная запись, привязанная к почте

### Actual result

Регистрация не проходит, появляется ошибка - Email is already taken.
При попытке восстановления пароля по данной почте - EMAIL_NOT_FOUND.
![Desktop Screenshot 2024 05 30 - 17 32 47 39](https://github.com/hexlet-codebattle/codebattle/assets/115353329/894ca48d-baae-40ea-90b1-b1a2fb66d7ec)
![Desktop Screenshot 2024 05 30 - 17 32 59 53](https://github.com/hexlet-codebattle/codebattle/assets/115353329/e4c8a0e1-6e72-4c40-acae-3deb27325bce)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Мы не планируем отделять аккаунты в социальных от привязанных почт.
Мы не готовы уделять этому большое внимание
