### ISSUE TITLE
Bug: В окне "Copy task JSON model" переключатель "Show JSON" имеет атрибут "disabled"

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1912]
### Summary

В окне "Copy task JSON model" присутствует переключатель "Show JSON", который должен скрывать или отображать JSON задачи. Однако переключатель имеет атрибут "disabled", что делает его неактивным и функционально бесполезным.
![image](https://github.com/hexlet-codebattle/codebattle/assets/78302371/a838440c-e416-4ab5-98bf-9ebe72fe2f03)

### Reproduction steps

```bash
1. Перейти в интерфейс редактирования ранее созданной задачи.
2. Нажать кнопку "Copy" на панели "Step 2".
3. Переключить слайдер "Show JSON" в противоположное положение.
```

### Expected result

Слайдер должен изменить свое состояние, а JSON задачи должен скрываться или отображаться в зависимости от положения слайдера.

### Actual result

Слайдер неактивен, у пользователя нет возможности скрыть JSON задачи в окне "Copy task JSON model".

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это не имеет смысла
Мы всегда копируем текст, а не визуальное представление

**Comment by burd-up** [comment]
@ReDBrother спасибо за ответ!

Тогда возникает вопрос зачем там нужен этот элемент интерфейса ?

**Comment by ReDBrother** [comment]
Он присутствует и в других частях системы, которые показывают в разных форматах текущую таску

**Comment by ReDBrother** [comment]
Это общая панель, которая в разных режимах работает и в разном контексте

**Comment by burd-up** [comment]
@ReDBrother, спасибо за пояснения! Понимаю, что данная панель реализована как типовой компонент, который используется в разных частях системы.

Мне пришла в голову идея, которую я хотел бы предложить. Если компонент реализован с использованием React, возможно, стоит рассмотреть возможность его кастомизации через пропсы. Это позволило бы передавать аргумент boolean, который бы управлял отображением слайдера в зависимости от контекста. Таким образом, если в конкретной части интерфейса слайдер не требуется, его можно было бы скрыть, что помогло бы разгрузить интерфейс и сделать его более интуитивно понятным для пользователя.

Понимаю, что разработчики могут иметь свои соображения на этот счет, но подумал, что моя идея могла бы оказаться полезной. Спасибо за внимание!

**Comment by ReDBrother** [comment]
Да, это хорошая идея и реализовано в этом компоненте. Только не булеан, а нормальный стейт, потому что режимов может быть больше двух)

<img width="393" alt="Untitled 44" src="https://github.com/hexlet-codebattle/codebattle/assets/24855537/cad015ea-e0da-4ac7-ae17-58f0a05d8570">

**Comment by burd-up** [comment]
@ReDBrother, ооо прикольно! Спасибо за пояснения.

У меня возник вопрос: почему в данном контексте вы решили задизэйблить этот элемент, а не убрать его вовсе?

**Comment by ReDBrother** [comment]
В UI/UX одного компонента стараются держать интерфейс единым. Если часть функционала по тем или иным причинам зафиксирована в одной точке, то это должно быть явно показано и даже через disabled контролы

Элементы интерфейса стараются не скрывать без необходимости (Например если мало места для доступного управления). Если компонент еще и может переключаться между режимами, то из-за появления новых элементов остальной контент может скакать, что вызывает гораздо больше раздражения, чем disabled переключатель.

**Comment by ReDBrother** [comment]
По факту, можно так и так. Но это точно не баг - ну никак) Этот контрол ничего не ломает)

**Comment by burd-up** [comment]
@ReDBrother, спасибо большое за такое подробное разъяснение! 
Это действительно помогает лучше разобраться в том, как и почему могут быть устроены интерфейсы.
