### ISSUE TITLE
Bug: Несоответствие данных между таблицей Leaderboard и страницей Users при фильтрации по week и month

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1913]
### Summary

При выборе режима отображения week или month в таблице Leaderboard данные не совпадают с данными на странице Users при использовании фильтрации weekly или monthly соответственно. Это несоответствие приводит к различиям в ранжировании пользователей между этими двумя панелями.

### Reproduction steps

```bash
1. Открыть страницу https://codebattle.hexlet.io/#lobby с панелью leaderboard.
2. Открыть страницу https://codebattle.hexlet.io/users с рейтингом пользователей.
3. Установить режим отображения данных в таблице leaderboard на "week".
4. Установить фильтрацию данных на странице users на "weekly".
5. Сравнить данные из таблицы leaderboard с данными со страницы users.
6. Повторить шаги 3-5, установив режим отображения данных в таблице leaderboard на "month" и фильтрацию данных на странице users на "monthly".
```

### Expected result

Данные на панели leaderboard и странице users должны совпадать при одинаковых настройках фильтрации (week/weekly и month/monthly). 

### Actual result

Данные на панели leaderboard и странице users не совпадают при одинаковых настройках фильтрации (week/weekly и month/monthly). 

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1752
Ошибка в общей таблице
