### ISSUE TITLE
Bug: Нарушена сортировка игроков по рейтингу в таблице 'Users rating' (графы 'monthly', 'weekly')

### ISSUE THREAD

**Issue by Olgatestonline** [hexlet-codebattle/codebattle#1915]
### Summary

В таблице 'Users rating' при попытке отсортировать игроков по рейтингу в порядке убывания или возрастания, в графах 'monthly' и 'weekly' порядок сортировки нарушен.

### Reproduction steps

```bash
осуществлён вход на сайт https://codebattle.hexlet.io/ под зарегистрированным пользователем
  test-data: |
    email = testiss1@yandex.ru Пароль = 1234567t
  steps:
    - Нажимиаем на никнейм учётной записи
    - внизу таблицы 'Leaderboard' нажимаем на ссылку 'Top list'
    - выбираем закладку 'monthly', сортируем игроков по рейтингу (убывание, возрастание)
    - выбираем закладку 'weekly', сортируем игроков по рейтингу (убывание, возрастание)
```

### Expected result

Производится сортировка игроков по рейтингу в порядке возрастания или убывания

### Actual result

В графах 'monthly' и 'weekly' порядок сортировки нарушен
![BG_rating_montlysort](https://github.com/hexlet-codebattle/codebattle/assets/138977424/f169043f-19ff-45ed-a048-e1ee2c161ae6)
![BG_rating_weeklysort](https://github.com/hexlet-codebattle/codebattle/assets/138977424/b9a62865-ef2a-4569-bcd4-7e8d38a80d20)

**Environment:**
Browser: Chrome Версия 125.0.6422.142 (Официальная сборка), (64 бит)
OS: Windows 10 Home Версия 22H2
[Current version: 500e062](https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1752
