### ISSUE TITLE
Bug: Отсутствует возможность редактирования настроек в профиле (аватар, email, password)

### ISSUE THREAD

**Issue by Olgatestonline** [hexlet-codebattle/codebattle#1916]
### Summary

В настройках профиля не предусмотрена возможность изменения аватара, адреса электронной почты и пароля у зарегистрированного пользователя.

### Reproduction steps

```bash
Вход на сайт https://codebattle.hexlet.io/ под зарегистрированным пользователем
   test-data: |     email = testiss1@yandex.ru Пароль = 1234567t 
1. Нажать на никнейм учётной записи
2. Перейти в раздел 'Settings'
```

### Expected result

Открывается окно настроек с наличием полей, где возможно изменить email  пользователя, пароль, аватар. 

### Actual result

В окне настроек отсутствуют поля, в которых возможно изменить email  пользователя, пароль, аватар. 
Environment:
![BG_settings](https://github.com/hexlet-codebattle/codebattle/assets/138977424/958c1e88-c872-4b0e-9243-e1fe0f147c50)

Browser: Firefox 126.0.1 (64-разрядный)
OS: Windows 10 Home Версия 22H2
[Current version: 500e062](https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4)

### Browsers

Firefox

### OS

Windows

**Comment by Maicuduc-123** [comment]
Так же отсутствует возможность редактирования учетной записи в настройках.

**Comment by McCenzly** [comment]
**Summary**
Отсутствует возможность поменять в настройках профиля пароль, email, аватар

**Reproduction steps**
Нажимаем на значёк своего профиля
Нажимаем "Settings"
Изменяем необходимые данные

**Expected result**
Пользователь может поменять пароль, email, аватар

**Actual result**
Отсутствует возможность для изменения данных пользователя (пароль, email, аватар)

**Browsers**
Версия 126.0.6478.128 (Официальная сборка), (64 бит)

**![Uploading Change_Information_About_User.jpg…]()**
Windows 10 Pro

**Comment by AntonyDn** [comment]
MacOS 15.6.1 (24G90)
Safari 18.6 (20621.3.11.11.3)
Version: 68f356b
