### ISSUE TITLE
Bug: Наличие неиспользуемых JS и CSS на странице 

### ISSUE THREAD

**Issue by Olgatestonline** [hexlet-codebattle/codebattle#1917]
### Summary

Проверка через DevTools обнаруживает неиспользуемые JS и CSS на странице. 

### Reproduction steps

```bash
1. Авторизуемся под зарегистрированным пользователем
   test-data: |     email = testiss2@yandex.ru Пароль = 1234567t2 
2. открываем панель разработчика DevTools 
3. вызываем командное меню (Ctrl+Shift+P) 
4. вводим в строку Show Coverage 
5. на панели Coverage (Покрытие) нажимаем Start instrumenting coverage and reload page
```

### Expected result

Отсутствует неиспользуемый код CSS и JS на странице. 

### Actual result

Есть неиспользуемые JS и CSS на странице, обнаружены ошибки.

Environment:

Browser: Chrome Версия 125.0.6422.142 (Официальная сборка), (64 бит)
OS: Windows 10 Home Версия 22H2
[Current version: 500e062](https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4)
![BG_JS_CSS](https://github.com/hexlet-codebattle/codebattle/assets/138977424/b0c5338e-46d3-4a69-b84e-4f6558906550)
![BG_JS_CSS_Error](https://github.com/hexlet-codebattle/codebattle/assets/138977424/37ec6e93-cd70-48c6-a52e-7b2e060c0928)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это вообще ни на что не влияет
Это так же ранее загруженные скрипты из других страниц или часть текущего интефейса, по которой вы как пользователь может еще не перешли (например модалки)
