### ISSUE TITLE
Bug: низкая производительность сайта

### ISSUE THREAD

**Issue by Olgatestonline** [hexlet-codebattle/codebattle#1918]
### Summary

При отчёте 'Lighthose' в DevTools выявлены предупреждения. Показатели отчёта находятся в оранжевой зоне.

### Reproduction steps

```bash
открыта главная страница сайта https://codebattle.hexlet.io/    
1. открываем панель разработчика DevTools 
2. выбираем вкладку Lighthouse 
3. нажимаем на кнопку Analyse page load
```

### Expected result

Все показатели сформированного отчёта о загрузке страницы находятся в зелёной зоне.

### Actual result

Показатели сформированного отчёта находятся в оранжевой зоне.  Выявлены предупреждения.
[download.pdf](https://github.com/user-attachments/files/15751897/download.pdf)

Environment:

Browser: Chrome Версия 125.0.6422.142 (Официальная сборка), (64 бит)
OS: Windows 10 Home Версия 22H2
[Current version: 500e062](https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Это все в тикет с lighthouse правками #1523
