### ISSUE TITLE
Bug:  Присутствуют битые ссылки

### ISSUE THREAD

**Issue by Olgatestonline** [hexlet-codebattle/codebattle#1919]
### Summary

При проверке обнаружены битые ссылки на сайте.

### Reproduction steps

```bash
1. Открываем главную страницу сайта https://www.drlinkcheck.com
2. В поле проверки вставляем URL нашего приложения https://codebattle.hexlet.io/
3. Анализируем данные отчета на странице
```

### Expected result

Отчёт показал отсутствие битых ссылок на сайте

### Actual result

На сайте присутствуют битые ссылки.

Environment:
Browser Google Chrome Версия 125.0.6422.142 (Официальная сборка), (64 бит)
Windows 10 Home Версия 22H2 
[Current version: 500e062](https://github.com/hexlet-codebattle/codebattle/commit/500e06200b34a29d0d2f0db1d289eb7276f20ef4)
![BG_broken_links](https://github.com/hexlet-codebattle/codebattle/assets/138977424/0e298dbc-a572-4a76-9122-4ec477743619)
![BG_broken_links_404](https://github.com/hexlet-codebattle/codebattle/assets/138977424/3fad3047-ee8a-43f1-b615-174b29eb3888)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Удалили, чуть позже задеплоим
Thanks a lot)
