### ISSUE TITLE
Bug: Невозможность отвязать аккаунты GitHub и Discord для пользователей, зарегистрированных через почту

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1920]
### Summary

Невозможность отсоединения аккаунтов Discord/GitHub у пользователей с привязанными Discord/GitHub и не привязанными противоположным сервисом (GitHub/Discord), зарегистрированными через почту.

### Reproduction steps

```bash
1. Авторизуйтесь в аккаунте пользователя, зарегистрированного через почту и привязавшего к аккаунту один из сервисов.
2. Перейдите на страницу настроек.
3. Нажмите на ссылку "Unlink Discord" или "Unlink GitHub".
```

### Expected result

Аккаунт Discord или GitHub должен быть отсоединен от аккаунта пользователя.

### Actual result

- Ссылка "Unlink Discord" не активна, если у пользователя привязан Discord и не привязан GitHub.
- Ссылка "Unlink GitHub" не активна, если у пользователя привязан GitHub и не привязан Discord.

### Browsers

Chrome

### OS

Windows

**Comment by El-MetD** [comment]
- summary: |
    Не работает ссылка Unlink Github и Unlink Discord
  environment: |
    Версия 126.0.6478.182 (Официальная сборка), (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce: |
    1. Авторизоваться с помощью Github
    2. Нажать на иконку пользователя в шапке
    3. Нажать на Settings
    4. Нажать на Unlink Github
  expected-result: |
    Выход из приложения
  actual-result: |
    Ссылка Unlink Github не работает
    Примечание: если привязать к аккаунту и гитхаб, и дискорд. Тогда ссылки Unlink Github и Unlink Discord работают
![image](https://github.com/user-attachments/assets/33324fd9-f2fa-4c8c-a99a-ea41c36b034c)
Если нажать на одну из ссылок, то вторая становится неактивной
![image](https://github.com/user-attachments/assets/50bdc685-fdaa-45c6-a205-c1cc6be4785a)

**Comment by Talmens** [comment]
- summary:
Не работает ссылка Unlink Github и Unlink Discord
- environment:

Версия сайта: 8a20565
Версия Chrome 127.0.6533.122 (Официальная сборка), (64 бит)
ОС Windows 10 Pro
- steps-to-reproduce:
1 Авторизоваться через аккаунт Github
2 Нажать на пользователя в шапке
3 Нажать на Settings в выпадающем меню
4 Нажать Unlink Github
- expected-result:
GitHub отсоединен от аккаунта пользователя, произошел выход с сайта
- actual-result:
Ссылка Unlink Github не активна

**Comment by ReDBrother** [comment]
Исторически сложилось, что мы не храним знаения о регистрации через email/password и не можем синхронизировать это знание с подписками в соц сетях

Мы не можем убрать это сознательное ограничение
