### ISSUE TITLE
Bug: Не создается новый турнир после отправки формы создания нового турнира

### ISSUE THREAD

**Issue by burd-up** [hexlet-codebattle/codebattle#1921]
### Summary

Не создается новый турнир после отправки формы создания нового турнира

### Reproduction steps

```bash
1. Авторизуйтесь в аккаунте пользователя.
2. Откройте страницу со списком турниров.
3. Перейдите на форму для создания турнира.
4. Заполните форму создания турнира.
5. Нажмите на кнопку "Create".
```

### Expected result

Турнир должен быть создан с параметрами, указанными в форме.

### Actual result

На странице начинается загрузка, которая не заканчивается, турнир не создается.

### Browsers

Chrome

### OS

Windows

**Comment by AnnaMozulko** [comment]
- summary: |
    После нажатия на кнопку "Create" в окне создания турнира происходит бесконечная загрузка
  environment: |
    Codebattle Current version: e6ec4dc
    Яндекс Браузер   Версия 24.6.2.786 (64-bit)
    ОС Windows 11 Pro
  steps-to-reproduce: |
     1.  Авторизоваться в аккаунте
     2. Перейти на страницу https://codebattle.hexlet.io/tournaments
     3. Заполнить произвольными данными поля формы создания турнира
     4. Нажать "Create"
  expected-result: |
    Турнир успешно создан с параметрами пользователя
  actual-result: |
    В поля формы возвращаются значения по умолчанию, начинается бесконечная загрузка
    приложения Screen3,Screen4
![Screen3](https://github.com/user-attachments/assets/7a64d312-1fe2-4108-b70f-30bf1ac29e19)
![Screen4](https://github.com/user-attachments/assets/7c18cd34-d935-4097-a645-df94490e678b)

**Comment by El-MetD** [comment]
- summary: |
    Не создается новый турнир
  environment: |
    Версия 126.0.6478.182 (Официальная сборка), (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce: |
    1. Авторизоваться
    2. Нажать на иконку пользователя в шапке
    3. Нажать на Tournaments
    4. Создать турнир
  expected-result: |
    Создается новый турнир
  actual-result: |
    Турнир не создается
![image](https://github.com/user-attachments/assets/5cc9cde5-56f6-445a-bda1-577cd935e617)
![image](https://github.com/user-attachments/assets/86706a6e-148f-44b4-a85a-95b8ca6a27f8)

**Comment by Judasstein** [comment]
Бесконечная загрузка после создания турнира
1. Нажать на аватар
2. Нажать "Tournamens"
3. Задать любые настройки 
4. Нажать "Create"
![Снимок экрана 2024-07-29 072427](https://github.com/user-attachments/assets/494362d6-e191-43d9-b548-47206ff3ae5f)

Browser Chrome
OC Windows
Current version: 11a596a

**Comment by Daryais** [comment]
Бесконечная загрузка после отправки формы создания турнира, турнир не создается 

1. Нажать Tournamens
2. В форме создания задать любые настройки
3. Нажать Create

Яндекс.Браузер Версия 24.4.5.506 (64-bit),  Google Chrome Версия 127.0.6533.101 (Официальная сборка), (x86_64)
macOS Monterey Версия 12.7
[Current version: 8a20565]

**Comment by Wa11en** [comment]
**- Summary:**
  Не создается новый турнир, бесконечная загрузка
**- environment:**
  Версия Chrome 128.0.6613.120 (Официальная сборка), (64 бит)
  ОС Windows 11 Pro, версия 21H2
**- steps:**
  1. Перейти в Tournaments
  2.  Заполнить необходимые поля произвольными данными
  3. Нажать кнопку "Create"
**- expected-result:**
  Турнир успешно создан, открыта страница турнира
**actual-result:**
  Появляется загрузка бесконечная, турнир не создан

![oIBw2bJIdD4](https://github.com/user-attachments/assets/a2b748bb-7e90-47b2-9a85-3f7e84199fd8)
![yqMrOG1hH7I](https://github.com/user-attachments/assets/8336e49a-a10a-49ea-857e-c881396030dc)

**Comment by AnnaAnPetrova** [comment]
Ошибка создания нового турнира 
  requirement: 
    Пользователь должен иметь возможность создать турнир
  prerequisites:
    Пользователь авторизован
  test-data: |
    No data
environment: |
Google Chrome 126.0.6478.127 (Официальная сборка) (64 бит)
ОС Windows 11
  steps:
    - Нажать кнопку «Tournaments»
    - Нажать кнопку «Tournaments Info»
    - Назвать турнир
    - Выбрать интересующие настройки
    - Нажать кнопку «Create»
  expected-result: |
    Должен быть создан новый турнир с выбранными настройками
actual-result: |
Турнир не создается, идет бесконечная загрузка

**Comment by ZaurJordi** [comment]
- summary: |
    Ошибка создания нового турнира
  environment: |
    Safari   17.6
    macOS Sonoma 14.6.1
  steps-to-reproduce: |
    1.  Пользователь авторизован
    2. Зайти во вкладку "Tournaments"
    3. Нажать кнопку "Tournaments Info"
    4. Ввести параметры нового турнира
    5. Нажать кнопку «Create»
  expected-result: |
    Должен быть создан новый турнир с выбранными параметрами
  actual-result: |
    Новый турнир не создается, идет бесконечная загрузка

**Comment by ReDBrother** [comment]
Это турниры не создаются по причине того, у нас есть ограничения на количество одновременных турниров(
Тестеры насоздавали турниров и не снесли их, отсюда и ошибка

Отдельной фичой отрежем возвожность создания турниров, когда мы достигнем лимитов
