### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by yana-fesenko** [hexlet-codebattle/codebattle#1925]
### Summary

Пользователь не может отменить созданную игру с ботом, может только сдаться

### Reproduction steps

```bash
1. Нажимаем на кнопку "Create a game"
2. Выбираем уровень игры
3. Выбираем "with a bot"
4. Выбираем время игры
5. Выбираем задание
6. Нажимаем на кнопку "Create battle"
```

### Expected result

На поле игры пользователь должен иметь возможность отменить созданную игру с ботом при нажатии соответствующей кнопки (не только сдаться)

### Actual result

У пользователя нет возможности отменить созданную игру с ботом при нажатии соответствующей кнопки (не только сдаться). Может, конечно, в этом и идея?)

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
Да, это по сути и есть отмена)
