### ISSUE TITLE
Bug, reopened: По-прежнему отсутствует возможность редактирования учётной записи в настройках профиля(нет возможности изменить аватар или пароль учётной записи).

### ISSUE THREAD

**Issue by RedBeduin** [hexlet-codebattle/codebattle#1926]
### Summary

По-прежнему отсутствует возможность редактирования учётной записи в настройках профиля: нет возможности изменить аватар, нет возможности изменить пароль учётной записи).
Баг-репорт об этом дефекте уже был и на данный момент закрыт, но возможность менять аватар и пароль так и не была добавлена. Ссылка на изначальный баг-репорт:
https://github.com/hexlet-codebattle/codebattle/issues/1916

### Reproduction steps

```bash
1. Войти в свою учётную запись
2. В правом верхнем углу нажать на свой аватар
3. В открывшемся списке выбрать "My Profile"
4. Снова нажать на свой аватар в этом же месте страницы
5. В открывшемся списке выбрать "Settings"

В качестве альтернативного варианта можно выполнить шаги из изначального баг-репорта:
https://github.com/hexlet-codebattle/codebattle/issues/1916
```

### Expected result

Присутствует возможность поменять аватар и пароль либо в разделе "My Profile", либо в разделе "Settings"

### Actual result

Ни в разделе "My profile", ни в разделе "Settings" нет возможности поменять аватар или пароль учётной записи

### Browsers

Chrome

### OS

Windows

**Comment by yana-fesenko** [comment]
Баг на месте
[Current version: 0ba780d](https://github.com/hexlet-codebattle/codebattle/commit/0ba780dfd087979ff79f615ae67f4e7deae2d58b)

**Reproduction steps**

1. Авторизоваться
2. В правом верхнем углу нажать на свой аватар
3. В выпадающем списке выбрать My profile
4. Снова нажать на свой аватар в правом верхнем углу 
5. Выбрать Settings

**Expected result**
Пользователь должен иметь возможность изменить аватар и пароль в "My Profile" или в "Settings"

**Actual result**
У пользователя нет возможности изменить аватар и пароль в "My Profile" или в "Settings"
<img width="1158" alt="Снимок экрана 2024-06-16 в 16 19 40" src="https://github.com/hexlet-codebattle/codebattle/assets/142812556/d51ab6a1-5f46-4735-8510-a45ea72b0c34">
<img width="1144" alt="Снимок экрана 2024-06-16 в 16 19 52" src="https://github.com/hexlet-codebattle/codebattle/assets/142812556/093d9030-c065-4649-b33e-9ea23e0d1f30">



**Browsers**
Chrome
OS
Mac

**Comment by Alena007S** [comment]
summary:
У пользователя нет возможности поменять аватар, почту и пароль 
environment:
Google Chrome 101.0.4951.67 (Официальная сборка), (64 бит)
ОС Windows
steps-to-reproduce:
1. Зайти на главную страницу сайта
https://codebattle.hexlet.io/#lobby
2. Нажать на свой аватар
3. Выбрать в списке "My profile" или "Settings"
expected-result:
Есть возможность поменять информацию
actual-result:
Возможно поменять только ник.

**Comment by DinaNeumann** [comment]
- summary: |
    Невозможность изменения почты в настройках аккаунта
  environment: |
    Google Chrome Версия 124.0.6367.207 (Официальная сборка), (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    - Перейти в раздел настроек аккаунта
    - Изменить указанный адрес почты
    - Подтвердить указанный адрес почты
  expected-result: |
    Изменение почты после ее проверки посредством подтверждающего письма
  actual-result: |
    Отсутствует возможность изменения почты пользователя

**Comment by DaryaBondarevaa** [comment]
summary: |
    Возможность изменения личных данных 
environment: |
    Microsoft Edge 126.0.2592.68 (Официальная сборка) (64-разрядная версия)
    ОС Windows 23H2
steps-to-reproduce: |
    1. Авторизоваться
    2. В правом верхнем углу нажать на свой никнейм
    3. Нажать "My Profile"
    4. В правом верхнем углу нажать на свой никнейм
    5. Нажать "Settings"
expected-result: |
Есть возможность изменения личных данных пользователя
actual-result: |
Отсутствует возможность изменения личных данных пользователя

**Comment by lintxj** [comment]
summary: |
В профиле невозможно изменить электронную почту, пароль и юзерпик

environment: |
Версия сайта: https://github.com/hexlet-codebattle/codebattle/commit/8a2056558639bda3a9f133fd09a31e4d57810750
Yandex Browser 24.4.1.899 (64-bit)
OC Windows 10 22H2

steps-to-reproduce: |
1. Нажать на иконку рядом с ником
2. Нажать на "Settings"

expected-result: |
В настройках можно изменить ник, электронную почту, пароль, юзерпик

actual-result: |
Из всего вышеперечисленного можно сменить только ник
![bugbattle5](https://github.com/user-attachments/assets/efa95b9b-23a8-49e2-922a-a9b919114ba5)

**Comment by FROSTECKI31** [comment]
summary: |
You cannot change your email, password, and username in your profile

environment: |
Версия сайта: [8a20565](https://github.com/hexletcodebattle/codebattle/commit/8a2056558639bda3a9f133fd09a31e4d57810750)
Browser: Yandex Browser 24.4.1.899 (64-bit)
OS: Windows 10 

steps-to-reproduce: |

1. open https://codebattle.hexlet.io
2. Authorize
3. In the upper right corner, click on your nickname
4. Click “My Profile”

actual-result: |
No fields, only possible to change “Nickname”
![Снимок23](https://github.com/user-attachments/assets/ef917e54-c7c6-4cc6-8d8d-10299ce2b14a)

**Comment by Luorika** [comment]
**Summary:**
У пользователя нет возможности поменять аватар, почту и пароль.
**Environtment:**
Current version: 8a20565
Chrome версия 128.0.6613.120 (Официальная сборка), (64 бит)
ОС: Windows 10
**Reproduction steps:**
1. Авторизоваться
2. В правом верхнем углу нажать на иконку
3. Нажать "My Profile"
4. Выбрать "Settings"

**Expected-result:** 
Есть возможность изменения аватара пользователя
**Actual-result:** 
Отсутствует возможность изменения аватара пользователя

**Comment by ReDBrother** [comment]
Это не баг

Фича по разработке описана тут: https://github.com/hexlet-codebattle/codebattle/issues/1733
