### ISSUE TITLE
Bug: Отсутствует кнопка перевода условия задачи в игре (Ru/En)

### ISSUE THREAD

**Issue by Olgatestonline** [hexlet-codebattle/codebattle#1927]
### Summary

В меню активной игры исчезла кнопка переключения языка для перевода условия игры (Ru/En)

### Reproduction steps

```bash
1. Заходим на сайт https://codebattle.hexlet.io зарегистрированным пользователем
2. Нажимаем на кнопку "Create a game"
3. В настройках игры выбираем:
         Level=1, Game Type = with a bot, Choose task = power calculator
4. Нажимаем: Create battle
```

### Expected result

Рядом с кнопкой описания есть кнопка переключения языка для перевода условия игры (Ru/En)

### Actual result

Рядом с кнопкой описания **отсутствует** кнопка переключения языка для перевода условия игры (Ru/En)

Env:
Current version: https://github.com/hexlet-codebattle/codebattle/commit/0ba780dfd087979ff79f615ae67f4e7deae2d58b
Browsers
Chrome Версия 125.0.6422.176 (Официальная сборка), (64 бит)
Firefox 126.0.1 (64-разрядный)
OS
Windows 10 Home 22H2
![BG_En1](https://github.com/hexlet-codebattle/codebattle/assets/138977424/de90a879-b4e4-48e1-a88d-4056d455559e)
![BG_Ru1](https://github.com/hexlet-codebattle/codebattle/assets/138977424/391151a1-7e7b-4555-b785-3e51c6786cc4)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Вернули
