### ISSUE TITLE
Bug, reopened: Часть интерфейса сайта снова отображается на русском языке 

### ISSUE THREAD

**Issue by RedBeduin** [hexlet-codebattle/codebattle#1928]
### Summary

Часть интерфейса сайта снова отображается на русском языке. Ранее этот баг уже упоминался в https://github.com/hexlet-codebattle/codebattle/issues/1882
а также в Issue 1881, дополнявшем соседнее сообщение о дефекте.
Проблема была решена, весь сайта снова начал отображаться на английском языке, а Issue, описывающий проблему, под номером 1882, был закрыт как решённый. Сейчас проблема появилась снова.

### Reproduction steps

```bash
1. Войти в свою учётную запись
2. Изучить открывшуюся при входе в аккаунт основную страницу сайта
3. Создать игру против бота
4. Изучить открывшуюся страницу игры

В качестве другого варианта можно использовать алгоритмы из
https://github.com/hexlet-codebattle/codebattle/issues/1882
и соседнего сообщения Issue 1881.
```

### Expected result

Основная страница сайта и страница игры против бота отображаются целиком на английском языке.

### Actual result

На основной странице сайта кнопки "Сражаться" и "Отправить" отображаются на русском языке, весь основной интерфейс отображается на английском. На странице игры против бота часть интерфейса отображается на русском, а часть на английском. "General" в шапке чата напечатано на английском. При данном обстоятельстве "Смотреть историю" справа от чата написано на русском.

### Browsers

Chrome

### OS

Windows

**Comment by Alena007S** [comment]
- summary: 
      Сайт одновременно отображается на двух языках
- environment:
      Google Chrome 101.0.4951.67 (Официальная сборка), (64 бит)
       ОС Windows
- steps-to-reproduce: 
      1. Зайти на главную страницу сайта 
      https://codebattle.hexlet.io/#lobby
      2. Создать игру против бота
- expected-result: 
      Весь текст на сайте должен быть на английском языке
- actual-result: 
    Часть текста отображается на русском.
![igra](https://github.com/hexlet-codebattle/codebattle/assets/162182505/24694f09-ffc2-4e2e-a92b-73497ce3224f)
![lobby](https://github.com/hexlet-codebattle/codebattle/assets/162182505/3ebff6d2-5190-4f6d-afb9-9dbfeb13c42f)

**Comment by inevitable123455** [comment]
Summary:
Сайт одновременно отображается на двух языках

Environment:
Yandex 24.6.0.1874 (64-bit) OC Windows 11

Steps-to-reproduce:
1. Авторизоваться 

Expected-result:
Сайт должен отображаться на одном языке

Actual-result:
Сайт отображается одновременно на двух языках
![image](https://github.com/hexlet-codebattle/codebattle/assets/165788229/6228301f-1dfa-4ce2-8ccd-4797c77b9555)

**Comment by DinaNeumann** [comment]
summary: |
Отсутствует смена языка после начала баттла
environment: |
Codebattle Current version: [0ba780d]
Google Chrome Версия 124.0.6367.207 (Официальная сборка), (64 бит)
ОС Windows 11
steps-to-reproduce: |
    - Создать баттл с любыми условиями
expected-result: |
Появится кнопка смены языка сайта
actual-result: |
Отсутствует кнопка смены языка сайта

**Comment by vitklimin** [comment]
**Summary:**
При участии в баттле, отсутствует возможность смены языка

**Environment:**
Yandex 24.6.1.766 (64-bit) OC Windows 11
**Steps-to-reproduce:**
Создать баттл
В выпадающем списке задачи выбираем "RU" или "EN"
**Expected-result:**
Сайт должен отображаться на выбранном языке
**Actual-result:**
Сайт отображается только на английском языке
![Screenshot_1](https://github.com/hexlet-codebattle/codebattle/assets/154010123/b8b62944-29b0-4c99-a96d-78e98ea14ab9)

**Comment by Maicuduc-123** [comment]
summary:
Сайт одновременно отображается на двух языках
environment:
 Яндекс Браузер  24.4.2.887 (64-bit)
ОС Windows
steps-to-reproduce:
1. Зайти на главную страницу сайта
https://codebattle.hexlet.io/#lobby
2. Зайти в мой профиль
expected-result:
Весь текст на сайте должен быть на одном языке
actual-result:
Часть текста отображается на русском часть на английском
![Снимок экрана (40)](https://github.com/hexlet-codebattle/codebattle/assets/167531162/68c6afde-57f2-4ded-8a34-434521cae996)
![Снимок экрана (39)](https://github.com/hexlet-codebattle/codebattle/assets/167531162/7f55509b-0685-4812-a2e5-21c00f026b70)

**Comment by Luorika** [comment]
**Summary**

При выборе русского языка на странице игрового поля на русском отображается только текст задачи, все остальные надписи остаются на английском. 

**Reproduction steps**
1. Авторизоваться
2. Создать игру с любыми параметрами
3. Перейти в игровое поле
4. Выбрать русский язык на панели переключения языков

**Expected result**
Все надписи отображаются на русском языке.

**Actual result**
На русском языке отображается только задача, остальные надписи остаются на английском.

**Environment:**
Current version: https://github.com/hexlet-codebattle/codebattle/commit/8a2056558639bda3a9f133fd09a31e4d57810750
Chrome версия 128.0.6613.120 (Официальная сборка), (64 бит)
ОС: Windows 10

![screen06](https://github.com/user-attachments/assets/7e35e937-b9cb-4bac-9c2a-d6b4ec416542)

**Comment by ReDBrother** [comment]
Поддержка русского языка не будет, и нигде не показываем как настраивать локаль.
