### ISSUE TITLE
Bug: Гайд не открывается повторно после его закрытия на "крестик" 

### ISSUE THREAD

**Issue by SvetlanaSku** [hexlet-codebattle/codebattle#1929]
### Summary

В активной игре Гайд не открывается повторно после его закрытия на "крестик" 

### Reproduction steps

```bash
1. Создать новую игру
2. Нажать кнопку "Гайд"
3. Закрыть на "крестик"
4. Снова нажать на кнопку "Гайд"
5. Баг - ничего не происходит
```

### Expected result

После нажатия кнопки "гайд" - Гайд открывается снова

### Actual result

После нажатия кнопки "гайд" - ничего не происходит

### Browsers

Chrome

### OS

Windows

**Comment by SvetlanaSku** [comment]
[
![issues](https://github.com/hexlet-codebattle/codebattle/assets/151746008/115643af-a5d1-4e8f-8ce2-e2eec05bbbf3)
](url)

**Comment by El-MetD** [comment]
- summary: |
    Проверка отображения всех товаров каталога
  environment: |
    Версия 126.0.6478.182 (Официальная сборка), (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce: |
    1. Авторизоваться
    2. Создать игру
    3. Нажать на Show guide
    4. Закрыть  Show guide
    5. Нажать на Show guide
  expected-result: |
    Открывается Show guide повторно
  actual-result: |
    Не открывается Show guide повторно

**Comment by Linahzhzhz** [comment]
По нажатию на крестик окно с текстом закрывается, но сам гайд остается активным
    macOS Ventura 13.0.1 (22A400) 
    Google Chrome Версия 124.0.6367.207 (Официальная сборка), (arm64)
    Версия CodeBattle 8a20565 
По нажатию на крестик окно с текстом закрывается, но сам гайд остается активным. Если нажать на синий кружок, то текстовое окно снова появляется и гайд продолжает работу

Uploading Запись экрана 2024-08-04 в 01.34.46.mov…

**Comment by Talmens** [comment]
- summary: 
Гайд не открывается повторно после закрытия
- environment:
Версия сайта: 8a20565
Версия Chrome 127.0.6533.122 (Официальная сборка), (64 бит)
ОС Windows 10 Pro
- steps-to-reproduce: 
1 Авторизоваться
2 Создать игру
3 Нажать Show guide
4 Закрыть Show guide
5 Нажать Show guide
- expected-result: 
Открывается Show guide
- actual-result: 
Show guide не открывается

**Comment by ReDBrother** [comment]
Это сознательная фича этой библиотеки гайдов

Она закрывает гайд только по нажатию на кнопку Skip guide
