### ISSUE TITLE
Bug: Смена задания при нажатии кнопки "Rematch"

### ISSUE THREAD

**Issue by inevitable123455** [hexlet-codebattle/codebattle#1931]
### Summary

Изменяется задание при нажатии кнопки "rematch"

### Reproduction steps

```bash
1. Авторизируемся
2. Нажимаем кнопку "Create a game"
3. Создаём игру с параметрами, например (Уровень-1, Тип игры-with a bot, время-8 min, название-rect_area)
4. Нажимаем кнопку "Give up"
5. Нажимаем кнопку "rematch"
```

### Expected result

При нажатии кнопки "Rematch" матч должен начаться заново с теми же параметрами

### Actual result

При нажатии кнопки "Rematch" матч начинается с другим заданием

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Не планируем такого
