### ISSUE TITLE
Bug: Отсутствие валидации при изменении ника

### ISSUE THREAD

**Issue by SvetlanaSku** [hexlet-codebattle/codebattle#1933]
### Summary

При изменении ника возможно использовать русский алфавит, а также имя может начинаться с цифр. Что не соответствует условиям при регистрации.

### Reproduction steps

```bash
1. Открыть страница настроек 
2. Сменить ник в поле "Your name" недопустимыми символами (русский алфавит или цифры вначале имя)
3. Нажать кнопку "Save"
4. Обновить страницу
```

### Expected result

Ошибка, недопустимые символы.

### Actual result

Имя пользователя сменилось.
![валидация](https://github.com/hexlet-codebattle/codebattle/assets/151746008/6e153ab5-c223-4180-bed3-55949a6349d0)
![нет валидации](https://github.com/hexlet-codebattle/codebattle/assets/151746008/3fbf6c36-fa6b-4f68-b7a3-7b83f1721ef0)

### Browsers

Chrome

### OS

Windows

**Comment by Kaiseridze** [comment]
Hello, I would like to take part in the project and help with solving this problem

**Comment by McCenzly** [comment]
**Summary:**
При изменении имени пользователя валидация не учитывается

**Environtment:**
CodeBattle current version: https://github.com/hexlet-codebattle/codebattle/commit/11a596a6ba84e4a7ef4470e98daf5af6a820462f
Chrome Версия 126.0.6478.128 (Официальная сборка), (64 бит)

**Reproduction steps:**
- Нажать на панель с UserName пользователя
- Нажать Settings
- Изменить имя пользователя на имя написанное русскими буквами
- Нажать Save

**Expected result:**
Появляется сообщение с ошибкой - Should contain Latin letters

**Actual result:**
Имя пользователя изменилось, валидация проигнорировалась

**OS:
Windows 10 Pro

![Change_NickName](https://github.com/user-attachments/assets/f9f8fbf2-4443-4a7f-9f22-314b8e098000)
**

**Comment by danism76** [comment]
Summary
При изменении ника возможно использовать первым символом не латинскую букву, а подчеркивание, что не соответствует условиям при регистрации.

Reproduction steps
1. Открыть страница настроек 
2. Сменить ник в поле "Your name" недопустимыми символами (начать имя не с латинской буквы)
3. Нажать кнопку "Save"
4. Обновить страницу
Expected result
Ошибка, недопустимые символы.

Actual result
Имя пользователя сменилось.

![8](https://github.com/user-attachments/assets/93a2580e-08f6-4f8e-8e1d-910ba3eac9a7)

**Comment by Luorika** [comment]
**Summary**
When you change the name, validation does not work. 

**Steps-to-reproduce**

1. Log in.
2. Click on the user's avatar in the upper right corner.
3. Press "Settings".
4. Enter invalid characters. 
5. Click "Save"
    
**Environment:**
Google Chrome 107.0.5304.121 (Официальная сборка) (64 бит)
Mozilla Firefox 129.0.2 (64 бит)
ОС: Windows 10

**Expected-result**
A message should appear that invalid characters have been entered. 

**Actual-result**
The changes are successfully saved. 

![screen09](https://github.com/user-attachments/assets/d216e460-6113-4a92-b2c7-a8ed30076405)
![screen08](https://github.com/user-attachments/assets/32efe2f9-1b7e-4b87-8599-f3ca9e4c751e)

**Comment by ReDBrother** [comment]
We don't need that kind restrictions
