### ISSUE TITLE
Bug: Часть функционала в баттле скрыта

### ISSUE THREAD

**Issue by DinaNeumann** [hexlet-codebattle/codebattle#1938]
### Summary

Часть функционала в баттле скрыта

### Reproduction steps

```bash
1. Создать баттл с любыми условиями
```

### Expected result

Функционал в баттле полностью отображается

### Actual result

Часть функционала в баттле отображается лишь после обновления страницы
![iss2](https://github.com/hexlet-codebattle/codebattle/assets/168723256/ccb4f170-8cd2-4fa0-905f-6ae762a13c8d)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Я вообще не понял баги)) Если есть функционал, то и проблемы нет)
