### ISSUE TITLE
Bug: Некорректно отображается интерфейс сайта на главной странице без авторизации

### ISSUE THREAD

**Issue by Eris1389** [hexlet-codebattle/codebattle#1942]
### Summary

Картинка выходит за поля рамки 

 environment: |  
    Firefox  23H2 (Официальная сборка) (64 бит)
    ОС Windows 11

### Reproduction steps

```bash
1. Открыть главную страницу веб-сайта CodeBattle по следующей ссылке - https://codebattle.hexlet.io/
 2. Без авторизации
```

### Expected result

Корректно отображается интерфейс сайта, а именно  картинки находится ровно в рамке

### Actual result

Некорректно отображается интерфейс, а именно картинка выходит за поля рамки
![Снимок экрана 2024-07-04 223611](https://github.com/hexlet-codebattle/codebattle/assets/165949545/1437d64c-f44b-415c-a6f4-667bd2a67bff)

### Browsers

Firefox

### OS

Windows

**Comment by Chebanya** [comment]
**summary:** 
    Borders (frames) of images in {{COMMENTS}} section on the start page of the site (without registration) are displayed incorrectly
**environment: **
    Google Chrome 129.0.6668.60 (Official build), (x86_64)
    macOS Ventura 13.3.1 
    Project version of the site: 3856424
**steps-to-reproduce:** 
    - Open the page of the site (without registration) - https://codebattle.hexlet.io.
    - Scroll down to the {{COMMENTS}} section.
**expected-result:**
    Borders (frames) of images should be strictly placed around the perimeter of images
**actual-result:** 
   Image borders (frames) are offset 

<img width="1792" alt="Снимок экрана 2024-10-08 в 17 50 42" src="https://github.com/user-attachments/assets/2bf67141-1bcb-4505-ac3d-2a32753ab3d0">

**Comment by ReDBrother** [comment]
No comments)
