### ISSUE TITLE
Bug: Создание турнира с прошедшей датой

### ISSUE THREAD

**Issue by McCenzly** [hexlet-codebattle/codebattle#1949]
### Summary

При создании турнира можно выбрать дату начала в прошедшем времени

### environment
[Current version: 11a596a](https://github.com/hexlet-codebattle/codebattle/commit/11a596a6ba84e4a7ef4470e98daf5af6a820462f)

### Reproduction steps

```bash
1. Нажать на выпадающее меню 
2. Нажать Tournaments
3. Задать необходимые настройки турнира и выбрать дату начала 2014-02-23
4. Нажать Create
```

### Expected result

Турнир не должен быть создан

### Actual result

Турнир создан
![Tournament_2014](https://github.com/user-attachments/assets/98d3b9ff-a6a1-4ebb-928c-0cded7364d32)

### Browsers

Chrome Версия 126.0.6478.183

### OS

Windows

**Comment by lintxj** [comment]
summary: |
Турнир можно создать в прошедшую дату

environment: |
Версия сайта: https://github.com/hexlet-codebattle/codebattle/commit/8a2056558639bda3a9f133fd09a31e4d57810750
Yandex Browser 24.4.1.899 (64-bit)
OC Windows 10 22H2

steps-to-reproduce: |
1. Зайти на страницу просмотра/создания турниров
2. При создании нового турнира указать прошедшую дату
3. Нажать на "Create"

expected-result: |
Турнир не создан, высветилось предупреждение, что нельзя создать турнир с прошедшей датой

actual-result: |
Турнир создан и отобразился в общем списке турниров
![bugbattle4](https://github.com/user-attachments/assets/97ffbbd7-3dcd-4c2c-9b7c-26078e4ad8ea)

**Comment by ReDBrother** [comment]
Это условная дата, она никак не влияет на старт турнира
