### ISSUE TITLE
Bug: На почту не приходит уведомление об успешной регистрации

### ISSUE THREAD

**Issue by Crusher24** [hexlet-codebattle/codebattle#1950]
### Summary

После успешной регистрации, не приходит на почту сообщение об этом.
https://github.com/hexlet-codebattle/codebattle/issues/1866

### Reproduction steps

```bash
1. Нажать кнопку "Sign up"
2. Заполнить форму для регистрации
3. Нажать кнопку "Submit"
```

### Expected result

На почту должно прийти письмо о регистрации с подтверждением email.

### Actual result

Пользователь зарегистрирован, но письмо с подтверждение не приходит.

### Browsers

Chrome

### OS

Windows

**Comment by lintxj** [comment]
summary: |
На почту не приходит письмо с уведомлением об удачной регистрации

environment: |
Версия сайта: 8a20565
Yandex Browser 24.4.1.899 (64-bit)
OC Windows 10 22H2

steps-to-reproduce: |
1. Пройти успешную регистрацию на сайте
2. Проверить почту, указанную при регистрации

expected-result: |
В указанную почту пришло письмо об успешной регистрации

actual-result: |
Письмо не пришло

**Comment by FROSTECKI31** [comment]
summary: |
На почту не приходит письмо с уведомлением о успешной регистрации

environment: |
Версия сайта: https://github.com/hexlet-codebattle/codebattle/commit/8a2056558639bda3a9f133fd09a31e4d57810750
Yandex Browser 24.4.1.899 (64-bit)
OC Windows 10 

steps-to-reproduce: |

Пройти успешную регистрацию на сайте
Проверить почту, указанную при регистрации
expected-result: |
В указанную почту пришло письмо об успешной регистрации

actual-result: |
Не приходит письмо

**Comment by ReDBrother** [comment]
Мы сознательно отключили такую функцию, мы не готовы вкладывать ресурсы в полноценную почтовую интеграцию с firebase
