### ISSUE TITLE
Bug: Нарушена адаптивность сайта на мобильных устройствах

### ISSUE THREAD

**Issue by DaryaBondarevaa** [hexlet-codebattle/codebattle#1951]
### Summary

Эмблема сайта не адаптируется под мобильные устройства
[Документ Microsoft Word.pdf](https://github.com/user-attachments/files/16373120/Microsoft.Word.pdf)

### Reproduction steps

```bash
1. Авторизоваться
2. Открыть DevTools
3. Выбрать любое мобильное устройство - например iPhone 14 pro max
```

### Expected result

Эмблема сайта адаптируется под мобильное устройство

### Actual result

Эмблема сайта не адаптируется под мобильное устройство

### Browsers

Microsoft Edge

### OS

Windows

**Comment by Natali1602** [comment]
Эмблема сайта не адаптируется под мобильные устройства
environment: |
Firefox Версия 130.0.1 (64-разрядный)
ОС Windows 10 
steps-to-reproduce: |
    1. Открыть DevTools
    2. Выбрать любое мобильное устройство - например Galaxy note 20 ultra Android 11
expected-result: |
    Эмблема сайта адаптируется под мобильное устройство
actual-result: |
    Эмблема сайта не адаптируется под мобильное устройство

![изображение](https://github.com/user-attachments/assets/0b0da62f-c003-4ef8-b364-c6b8f8323dc8)

**Comment by ReDBrother** [comment]
А можете расскрыть что значит адаптивность эмблемы?

Не очень понял смысл баг репорта, потому что эмблема доступна и не имеет каких либо лишних артефактов, по отношению к полноразмерной версии

**Comment by Natali1602** [comment]
имелось ввиду отсутствие заголовка рядом с эмблемой в мобильной версии

[image: изображение.png]
[image: изображение.png]
если заголовок не является частью эмблемы и не должен отображаться в
мобильной версии, тогда да, в баг-репорте нет смысла



ср, 16 окт. 2024 г. в 23:41, Dmitriy Bataev ***@***.***>:

**Comment by ReDBrother** [comment]
Вот заголовок невозможно вписать в более мелкие экраны - поэтому его сознательно убирают
Это не баг, а фича)
