### ISSUE TITLE
Bug: Некорректная работа ползунка Time control

### ISSUE THREAD

**Issue by Judasstein** [hexlet-codebattle/codebattle#1952]
### Summary

Если выделить область ползунка, ползунок перестает перемещаться свободно. 
Версия браузера Chrome 127.0.6533.89 (Официальная сборка), (64 бит)
Версия ОС 22H2, Сборка ОС 19045.4651

https://github.com/user-attachments/assets/9f11923a-713e-488a-85ba-932855de0b46

### Reproduction steps

```bash
1. Нажать "Create a game"
2. Выделить курсором ползунок
3. Передвинуть ползунок
```

### Expected result

Ползунок должен регулироваться свободно независимо от выделения области

### Actual result

Ползунок двигается на один шаг

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Этот инпут браузерный, если в этом браузере у него неадекватное поведение, то мы ничего не сможем сделать(
