### ISSUE TITLE
Нарушается верстка игрового поля

### ISSUE THREAD

**Issue by Judasstein** [hexlet-codebattle/codebattle#1953]
При уменьшении окна редактора кода плывет верстка

**Comment by Judasstein** [comment]
https://github.com/user-attachments/assets/968774b3-b5b3-4117-9488-c4cf57728ae7

**Comment by kideki-kideki** [comment]
**summary**
    The ‘editor’ button and the other player's ‘tick or click up’ button disappear when the browser window shrinks down
  **environment**
    browser: Microsoft Edge 127.0.2651.86 (Official Build) (64-bit version)
    OS: Windows 11 23H2
    website version: Current version: 8a20565
  **steps-to-reproduce**
    1. Open the home page https://codebattle.hexlet.io/
    2. Press the ‘Try simple battle’ button
    3. Shrink the browser window
  **expected-result**
    The ‘editor’ button and the other player's ‘tick or click up’ button have been adapted to the page
  **actual-result**
    The ‘editor’ button and the other player's ‘tick or click up’ button do not appear on the page

![editor](https://github.com/user-attachments/assets/5dc8278f-0d85-4ab5-80db-8f761fd33165)
