### ISSUE TITLE
Bug: При нажатии кнопки Show завершенных турниров любого типа открывается пустая страница

### ISSUE THREAD

**Issue by Kreidl** [hexlet-codebattle/codebattle#1959]
### Summary

#1645
При нажатии кнопки Show завершенных турниров любого типа часто открывается пустая страница

### Reproduction steps

```bash
1. Авторизоваться
2. Нажать на профиль
3. Нажать 'Tournaments'
4. Выбрать любой прошедший турнир и нажать "Show"
5. Если не сработало, повторить последние 2 пункта еще раз
```

### Expected result

Открывается информация о прошедшем турнире

### Actual result

Открывается пустая страница
![reopissue](https://github.com/user-attachments/assets/f4575695-36b3-46e3-b7cd-682a0cac21e5)

https://github.com/user-attachments/assets/8bdb0da0-86ae-4e72-8cc2-051534dc5b42

### Browsers

Chrome

### OS

Windows

**Comment by kideki-kideki** [comment]
**summary**
    Completed user game record does not open
  **environment**
    browser: Microsoft Edge 127.0.2651.86 (Official Build) (64-bit version)
    OS: Windows 11 23H2
    website version: Current version: 8a20565
  **steps-to-reproduce**
    1. Open the home page
    2. Press the ‘Sign In’ button
    3. Enter authorisation data ( email = testing_01@mail.ru  password = 123456)
    4. Click the ‘Submit’ button
    5. Click on the nickname (igrok_01) at the top of the page
    6. Click the ‘My Profile’ button
    7. Click the ‘Completef games’ button
    8. Select the first game
    9. Click the ‘Show’ button
  **expected-result**
    The game recording page opens
  **actual-result**
    A blank page opens
![screenshot](https://github.com/user-attachments/assets/2c000303-1604-4461-8213-e22490ac405e)

**Comment by kideki-kideki** [comment]
**summary**
    The record of the completed game of other players is not opened
  **environment**
    browser: Microsoft Edge 127.0.2651.86 (Official Build) (64-bit version)
    OS: Windows 11 23H2
    website version: Current version: 8a20565
  **steps-to-reproduce**
    1. Open the home page https://codebattle.hexlet.io/
    2. Press the ‘Sign In’ button
    3. Enter authorisation data ( email = testing_01@mail.ru  password = 123456)
    4. Click the ‘History’ button
    5. Pick any game 
    6. Click the ‘Show’ button
  **expected-result**
    The game recording page opens
  **actual-result**
    A blank page opens
![screenshot_2](https://github.com/user-attachments/assets/2df36a8a-24a3-4dcb-a8bf-63fb166d07c8)

**Comment by Chebanya** [comment]
- summary: |
No access to the record of the completed game in which the user participated
environment: |
Google Chrome 129.0.6668.60 (Official build), (x86_64)
MacOS Ventura 13.3.1
Current version of the site: 3856424
steps-to-reproduce: |
- In the header in the upper right corner, click on the user's nickname
- In the window that appears, click on My Profile
- Click on the COMPLETED GAMES tab
- Select any game from the list of completed games
- Click on the Show button
expected-result: |
The transition to the page with the tournament record of the completed game has been made
actual-result: |
The page does not contain a record of the completed game

https://github.com/user-attachments/assets/bdf1014b-b83d-4c00-92a3-85883aa9681a

**Comment by ReDBrother** [comment]
Fixed

**Comment by ZaurJordi** [comment]
Изначально баг был про просмотр турниров, а наполнение про невозможность просмотра завершенных игр. И не совсем понятно, какой именно баг пофиксили. Но последние комменты по поводу отсутствия просмотра игры.

- summary: |
    Нельзя просмотреть завершенные игры (ни свои, ни чужие)
  environment: |
    Gooole Chrome 127.0.6533.120 (официальная сборка) (64 бит)
    ОС Windows 10 PRO
    Current version: ddf1389
