### ISSUE TITLE
Bug: Созданный турнир не открывается 

### ISSUE THREAD

**Issue by Daryais** [hexlet-codebattle/codebattle#1961]
### Summary

Страница созданного турнира не прогружается
<img width="1680" alt="Снимок экрана 2024-08-25 в 23 25 43" src="https://github.com/user-attachments/assets/e0dab433-2659-4ca9-8aa9-cebd57b3d2c7">

### Reproduction steps

```bash
1. Перейти в Tournaments
2. Кликнуть на show созданного вами турнира
```

### Expected result

Открывается страница с описанием и чатом турнира 

### Actual result

Страница турнира не открывается

### Browsers

Chrome Версия 128.0.6613.113 (Официальная сборка), (x86_64)

### OS

Mac 12.7 (21G816)

**Comment by ReDBrother** [comment]
Fixed
