### ISSUE TITLE
Bug: Incorrect layout of the mobile version of the “Task” view page

### ISSUE THREAD

**Issue by HEAMY7QA** [hexlet-codebattle/codebattle#1963]
### Summary

Incorrect layout of the mobile version of the “Task” view page

____________________________________________________________________________________________

Некорректная верстка мобильной версии страницы просмотра "Task"

____________________________________________________________________________________________

### Prerequisites: 
1. DevTools:
Toggle device toolbar: Surface Pro 7
3. Open https://codebattle.hexlet.io/
4. Authorize 

### Environment:
Yandex Browser 24.7.1.1076 (64-bit)
ОС Windows 10 22H2
Version: https://github.com/hexlet-codebattle/codebattle/commit/d1efd63e6a79f79fff4b4fd4273f6757f5df8cdb

### Reproduction steps

```bash

1. Click on the profile icon
2. From the list, select "Tasks"
3. Click on the "Show" button

____________________________________________________________________________________________

1. Нажать на иконку профиля
2. Из списка выбрать "Tasks"
3. Нажаnь на кнопку "Show"
```

### Expected result

Correct display of the mobile version of the page

____________________________________________________________________________________________

Корректное отображение мобильной версии страницы

![task mobile 4](https://github.com/user-attachments/assets/caebb07d-52f8-4cd1-87f5-868b66cff593)

### Actual result

Incorrect display of the mobile version of the page. 
Step 2 is rendered not in the template logic. Step 4 is missing.  

The bug appears when setting the width parameter 991 to 496.

____________________________________________________________________________________________

Некорректное отображение мобильной версии страницы. 
Шаг 2 отрисовывается не в логике шаблона. Шаг 4 отсутсвует.  

Баг проявляется при выставлении параметра ширина 991 до 496.

![task mobile](https://github.com/user-attachments/assets/c96ca88a-9222-4a2c-9c63-d67c11425b3e)
![task mobile 2](https://github.com/user-attachments/assets/ec07c67d-d87b-4295-a0c4-ffb72a988d3d)
![task mobile 3](https://github.com/user-attachments/assets/9728601b-df77-4d4b-b23f-b7dc98d0b125)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
We don't need trying adapt interfaces for all possible dimensions, it's insane amount of work
