### ISSUE TITLE
Bug: в мобильной версии сайта на некоторых устройствах не корректно отображается интерфейс во время матча

### ISSUE THREAD

**Issue by FROSTECKI31** [hexlet-codebattle/codebattle#1965]
### Summary

Fields are not correctly displayed during the match, namely a black bar on the right, on which some elements such as “Score” protrude

### Reproduction steps

```bash
1. Open the project page https://codebattle.hexlet.io/
2. Authorize
3. Open the DevTools developer tool (F12)
4. In the developer toolbar select toggle divice toolbar (ctr+shfit+m)
5. Select Iphone SE (for example)
6. Start the game with the bot at any level.
```

### Expected result

The playing field should be on the whole screen without a black bar, all elements should not protrude beyond the playing field boundaries

### Actual result

Incorrect display of the interface, the “Score” field protrudes behind the interface
![5 SE выхд за рамки (поля)](https://github.com/user-attachments/assets/7508f129-b420-4d30-800a-026296f26a79)

### Browsers

Chrome

### OS

Windows

Current version

8a20565

**Comment by ReDBrother** [comment]
Fixed
