### ISSUE TITLE
Bug: The bot won't start playing

### ISSUE THREAD

**Issue by HEAMY7QA** [hexlet-codebattle/codebattle#1966]
### Summary

When creating a game with a bot, the bot doesn't participate in the game, only the user solves the task, the bot doesn't even start.

A message appears: 
I won't start writing code. Only after you :)
I'll solve this task in about 11 minutes. Good luck!

____________________________________________________________________________________________________________________

При создании игры с ботом, бот не участвует в игре, решает задачу только пользователь, бот даже не начинает.

Появляется сообщение от бота: 
I won't start writing code. Only after you :)
I'll solve this task in about 11 minutes. Good luck!

Environment:
Yandex Browser 24.7.1.1076 (64-bit)
ОС Windows 10 22H2
Version: https://github.com/hexlet-codebattle/codebattle/commit/d1efd63e6a79f79fff4b4fd4273f6757f5df8cdb

Баг с закрытой ветки: 
https://github.com/hexlet-codebattle/codebattle/issues/1818

### Reproduction steps

```bash
1. Click Create a game
2. Select any difficulty level
3. Click With a bot
4. Select Time control - 3 min
5. Press Create battle

________________________________________________________________________________________

1. Нажать Create a game
2. Выбрать любой уровень сложности
3. Нажать With a bot
4. Выбрать Time control - 3 мин
5. Нажать Create battle
```

### Expected result

The bot begins to solve the task

### Actual result

The bot notifies the opponent that it will start playing after the opponent starts writing its code. 

But even at the end of time, the bot will not write a single character. 

________________________________________________________________________________________

Бот оповещает соперника о том, что начнет играть после того, как соперник начнет писать свой код. 

Но даже под конец времени, бот не напишет ни одного символа. 

![The bot won't start playing](https://github.com/user-attachments/assets/1fb40443-a372-41cb-9f02-6e6e251ff093)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Hi, bot not always starts typing code right away, like any human being
