### ISSUE TITLE
Bug: No warning about an already taken nickname 

### ISSUE THREAD

**Issue by fraythe** [hexlet-codebattle/codebattle#1968]
### Summary

No warning about an already taken nickname if you enter an invalid email during registration

### Reproduction steps

```bash
1. Open the main page of the site
2. Click on 'sign up'
3. Enter your already taken nickname (thayfre)
4. Enter invalid email
5. Enter the password
6. Repeat the password
```

### Expected result

Warning about invalid email and already taken nickname

### Actual result

Warning about invalid email, no warning about already taken nickname

### Current version

8a20565

### Browsers

Chrome

### OS

Mac

**Comment by julia-ju25** [comment]
The bug is still reproducing with same steps
Tested on the device:  PC Windows 10 - Google Chrome(130.0.6723.92 )
![image](https://github.com/user-attachments/assets/675f23f3-b262-443e-b3a9-b68b405e4d34)

**Comment by ReDBrother** [comment]
We don't need check name, before you send all valid data
