### ISSUE TITLE
Bug: No warning about an already taken email

### ISSUE THREAD

**Issue by fraythe** [hexlet-codebattle/codebattle#1970]
### Summary

No warning about an already taken email if passwords don't match during registration

### Reproduction steps

```bash
1. Open the main page of the site
2. Click on 'sign up'
3. Enter your already taken email (joohndee@mail.ru)
4. Enter the nickname
5. Enter the password
6. Enter a different password
```

### Expected result

Warning 'Passwords must match' and 'Email is already taken'

### Actual result

Warning 'Passwords must match'

### Current version

8a20565

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
I don't understand this issue
No reason we must showing that
