### ISSUE TITLE
Bug: The game recording cannot be played

### ISSUE THREAD

**Issue by fraythe** [hexlet-codebattle/codebattle#1971]
### Summary

The game recording cannot be played

### Reproduction steps

```bash
1. Open the main page of the site
2. Click on 'My profile'
3. Click on 'Completed games'
4. Click on 'Show'
```

### Expected result

A game recording is playing

### Actual result

Description of the game status
![Снимок экрана 2024-09-05 в 23 11 39](https://github.com/user-attachments/assets/2e157247-8b24-44d1-929d-45f4a85a019d)

### Current version

8a20565

### Browsers

Chrome

### OS

Mac

**Comment by ReDBrother** [comment]
Hello, we not always saves history previous games. If that happens, we showing this page
