### ISSUE TITLE
Problem with no header on the mobile version of the site

### ISSUE THREAD

**Issue by mil-stack** [hexlet-codebattle/codebattle#1972]
Problem with no header on the mobile version of the site

Reproduction steps
1. log in
2. Open DevTools
3. Select any mobile device - e.g. Samsung Galaxy S8+

Expected result
The title “Codebattle by Hexlet's community” should be displayed in the header of the site.

Actual result
The header is missing, which violates the adaptability and cosmetics of the mobile version of the site.

Browsers
Google Chrome

OS
Windows

Translated with DeepL.com (free version)
![photo_5388772411639456270_y](https://github.com/user-attachments/assets/45f64b3d-cedc-457e-9d4b-93d1b4dcbc44)

**Comment by ReDBrother** [comment]
I try recreate conditions with certain parameters and i see this icon
<img width="803" alt="Untitled 17" src="https://github.com/user-attachments/assets/76f8c3b6-3f5d-460f-94df-e9ebc244d130">


Try refresh browser or open app in real mobile browser
