### ISSUE TITLE
Bug: Authorization with invalid email

### ISSUE THREAD

**Issue by Andrey-khb** [hexlet-codebattle/codebattle#1973]
### Summary

Authorization of user with invalid email address

### Reproduction steps

```bash
1. Open the main page of the site
2. Click on 'sign up'
3. Enter the nickname = Test_Cbattle
4. Enter email = khaba@yan1234567890.com
5. Enter the password = 123456
6. Enter Password Confirmation = 123456
7. Enter button "Submit"
```

### Expected result

Message "Invalid email"

### Actual result

The user is logged in and has gone to the main game page
![bug2](https://github.com/user-attachments/assets/0355e54f-597b-48ea-a3ed-36b1643343dc)
![bug3](https://github.com/user-attachments/assets/5c71b613-2271-47e2-8f3e-441c974b1de1)

### Browsers

Chrome

### OS

Windows

**Comment by Natalia-hub4** [comment]
Short description: |
Error displaying the display on the site when entering non-existent data 
Steps to play: |
Go to the main page of the game https://codebattle.hexlet.io /
steps:
- Press the "Sign in" button
- Enter the user's name in the "Nickname" field (Avt)
- Enter the email address in the "Email" field (Xoxo@xoxo.com)
- Enter the password in the "Password" field
- Confirm the password in the "Confirm password" field
- Click the "Submit"button 
expected result: |
A new user has been registered. The main page
of the actual result opens: |
there is no "Error" sign, no signature"The data is incorrect"

Browser: Google Chrome, version 24.10.2.706 (64-bit)
Operating system: Windows 11, version 21 H2
Codebattle from the Hexlet community is the current version: ddf1389
![несуществ_данные2024-11-16 152237](https://github.com/user-attachments/assets/abbe1250-24a4-4922-9468-791880c798d0)

**Comment by LuckyStrike34R** [comment]
![2024-12-05_15-53-53](https://github.com/user-attachments/assets/8aa3d791-4b34-40cf-a188-35f22f35bb84)
![2024-12-05_15-54-06](https://github.com/user-attachments/assets/35d663e4-c2aa-4cbd-92ae-23ed36b8b401)
Summary
Authorization of user with invalid email address

Reproduction steps
1. Open the main page of the site
2. Click on 'sign up'
3. Enter the nickname = abyrvalg
4. Enter email = 1231432455@hubabuba.com
5. Enter the password = 123qwe123
6. Enter Password Confirmation = 123qwe123
7. Enter button "Submit"

Expected result
Message "Invalid email"

Actual result
The user is logged in and has gone to the main game page

**Comment by ReDBrother** [comment]
it's valid email
We used firebase, who don't have that restrictions

**Comment by raiden-creator** [comment]
требование: |
Пользователь не должен иметь возможности создать учетную запись с несуществующим адресом электронной почты.
предварительные условия:
Страница входа открыта
тестовые данные: |
Nickname = Test1000
Email = [Test1000@mail.ru](mailto:Test1000@mail.ru)
Password = qwerty12345
Password Confirmation = qwerty12345
среда: |
Google Chrome версия 132.0.6834.83, (64-бит)
Windows 11
шаги:

Вводим Nickname
Вводим Email
Вводим Password
Вводим Password Confirmation
Нажимаем кнопку "Submit"
ожидаемый результат: |
Должно появиться сообщение о том, что такого адреса электронной почты не существует.
фактический результат: |
Пользователь успешно зарегистрирован

![Image](https://github.com/user-attachments/assets/fdc46821-a26a-4008-885b-6c1c222c64a1)
![Image](https://github.com/user-attachments/assets/9a0ed02c-fb01-4e09-817d-872c13d56fbe)
