### ISSUE TITLE
Bug: Отсутствие изменения личного аватара пользователя

### ISSUE THREAD

**Issue by MaxMad446** [hexlet-codebattle/codebattle#1974]
### Summary

Проверка изменения личного аватара пользователя

### Reproduction steps

```bash
- Авторизоваться
- В правом верхнем углу нажать на свой никнейм
- Нажать "My Profile"
```

### Expected result

Возможно изменить личное аватара пользователя

### Actual result

Отсутствует возможность изменения аватара пользователя

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Планы на такую фичу есть #1733

**Comment by Sofushkins** [comment]
FireFox Version 141.0.3 (64-bit)
macOS Sonoma 14.7.1
[Current version: 4df7e60](https://github.com/hexlet-codebattle/codebattle/commit/4df7e60be39e67d283db40cdaa37f148718d2837)
