### ISSUE TITLE
Bug: Адаптивность сайта ломается на мобильных устройствах 

### ISSUE THREAD

**Issue by MaxMad446** [hexlet-codebattle/codebattle#1975]
### Summary

Проверка адаптивности сайта к мобильной версии
![1](https://github.com/user-attachments/assets/361f2b52-163d-4b8b-a67d-24f622204958)

### Reproduction steps

```bash
- Открываем DevTools(Исследовать элемент)
- Проверить адаптивность к любому мобильному устройству, например - iPhone 12 pro
```

### Expected result

Сайт адаптируется к мобильным устройствам

### Actual result

Адаптивность сайта ломается на мобильных устройствах 

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль от #1951

**Comment by ilya-astakhov** [comment]
summary: |
it is impossible to register for iPhone 12 pro, the adaptability is broken
environment: |
Opera One(version: 115.0.5322.119)
Windows 10 Pro 64
steps-to-reproduce: |
log out of your profile
Open Devtools in browser
Select mobile phone Phone 12 pro
push on Sing up
Expected result: |
the registration window opens
actual-result: |
the window does not appear
