### ISSUE TITLE
Bug: User login page with correct login and correct password does not work

### ISSUE THREAD

**Issue by Wadim71** [hexlet-codebattle/codebattle#1983]
### Summary

User login page with correct login and correct password does not work.

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io
2. Click on the Sign in button in the upper right corner
3. Enter your email in the Email field after you go to the login page
4. Enter your password in the Password field
5. Click the Submit button
```

### Expected result

The user goes to the lobby page, with their nickname in the top right corner

### Actual result

Nothing happens, the user remains on the login page

### Browsers

Firefox

### OS

Windows

Current version: 3856424

**Comment by ReDBrother** [comment]
I see you profile login via github - it doesn't require password
