### ISSUE TITLE
Bug: A user cannot accept a game invitation from another player

### ISSUE THREAD

**Issue by Wadim71** [hexlet-codebattle/codebattle#1984]
### Summary

Accepting a new game invitation from another user does not work. 

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/#lobby
2. Receive an invitation from another user (a red dot with a number in the middle appears on the button with two swords in the upper right corner)
3. click on the button with two swords (invitation to the game) in the upper right corner.
4. Click on the Accept button from the window that opens
```

### Expected result

A user accepts an invitation from another user to start a new game

### Actual result

The Accept button does not work

### Browsers

Firefox

### OS

Windows

Current version: 3856424

**Comment by ReDBrother** [comment]
i can't recreate this issue - invites working

**Comment by ZairalISU** [comment]
- summary: |
    Нельзя начать игру по приглашению другого пользователя
  environment: |
    Google Chrome 131.0.6778.108 (Официальная сборка), (64 бит)
    Windows 10 Домашняя
  steps-to-reproduce: |
    - перейти на другой аккаунт
    - нажать на скрещенные мечи
    - нажать Accept
  expected-result: |
    Пользователь присоединился к игре по приглашение от другого пользователя
  actual-result: |
    Страница с ошибкой

![Image](https://github.com/user-attachments/assets/83da2670-5a15-4940-8e6f-5988204002e8)
