### ISSUE TITLE
Bug: The button for declining an invitation to a new game from another player does not work

### ISSUE THREAD

**Issue by Wadim71** [hexlet-codebattle/codebattle#1985]
### Summary

Uninviting a new game from another user does not work. Current version: 3856424

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/#lobby
2. Receive an invitation from another user (a red dot with a number in the middle appears on the button with two swords in the upper right corner)
3. Click on the button with two swords (invitation to the game) in the upper right corner
4. Click on the Decline button from the window that opens.
```

### Expected result

When the Decline button is clicked, the user declines the invitation to start a new game from another user.

### Actual result

Nothing is happening, the invitation is still valid.

### Browsers

Firefox

### OS

Windows

**Comment by ReDBrother** [comment]
i can't recreate this issue - invites working
