### ISSUE TITLE
Bug: Incorrect translation when changing localization to Russian on registration and authorization pages

### ISSUE THREAD

**Issue by Chebanya** [hexlet-codebattle/codebattle#1988]
### Summary

On the registration and authorization pages the page content is incorrectly displayed when changing the localization from English to Russian in the address bar 

### Reproduction steps

```bash
1. Open the registration page - https://codebattle.hexlet.io/users/new?locale=en&next=%2F
2. In the address bar change the localization from en to ru and see if all the content of the page is translated into Russian
3. - Click on Sign in (open the authorization page - https://codebattle.hexlet.io/session/new?locale=en&next=%2F)
4. Change localization from en to ru in the address bar and see if all page content is translated into Russian
```

### Expected result

The content of the registration and authorization pages is displayed in Russian

### Actual result

The content of the registration and authorization pages is partially displayed in Russian - only the Sign up button located on the site header has been translated (Сurrent version of the site: 3856424)

### Browsers

Google Chrome 129.0.6668.60 (Официальная сборка), (x86_64)
Safari Версия 16.4 (18615.1.26.110.1)

### OS

Mac

https://github.com/user-attachments/assets/9d59edf7-a604-4925-8b36-3fd99d9dddff

https://github.com/user-attachments/assets/e4305021-703e-4d54-87c0-6b7942ce7200

**Comment by ReDBrother** [comment]
We don't have russian translation for our project and we don't planing having it
