### ISSUE TITLE
Обозначить начало игры

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#199]
Как вариант сделать звуковое оповещение, push в браузер. Так как человек может быть в другой вкладке.

**Comment by AnnaTerekhina93** [comment]
при нажатии на кнопку 'начать игру' нет никакого оповещения

Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

OS:
Windows 10 64-разрядная операционная система, процессор x64

**Comment by Xtoseone** [comment]
звуковое оповещение только в момент проигранной схватки или выйгранной, при начале баттла до сих пор нет оповещения

Browser: Brave Beta/FireFox Develop
OS: Win11
