### ISSUE TITLE
Bug: No error message output when specifying a non-existent domain name in the E-mail field when registering 

### ISSUE THREAD

**Issue by Chebanya** [hexlet-codebattle/codebattle#1990]
### Summary

No error message output when specifying a non-existent domain name in the E-mail field when registering a user on the site

### Reproduction steps

```bash
1. Open the user registration page on the site - https://codebattle.hexlet.io/users/new?locale=en&next=%2F
2. Enter an alias, for example - User1234
3. Enter e-mail, for example - user@user.ru
4. Enter password, e.g. 123456
5. Enter password confirmation (passwords must match) - 123456.
6. Press Submit button
```

### Expected result

Under the E-mail field appears the validation error text about incorrect e-mail. The user is not registered

### Actual result

Validation error text about an invalid e-mail address does not appear under the E-mail field. The user is not registered

Safari Версия 16.4 (18615.1.26.110.1)
Google Chrome 129.0.6668.60 (Official Build), (x86_64)
macOS Ventura 13.3.1 
Project version of the site: 1c3e2ba

### Browsers

Safari Версия 16.4 (18615.1.26.110.1)

https://github.com/user-attachments/assets/bef6a68c-3350-47ce-b2bd-e633223b1d0b

Google Chrome 129.0.6668.60 (Official Build), (x86_64)

https://github.com/user-attachments/assets/2621085a-7a11-43dc-a9f7-d7e9874023ce

### OS

Mac

**Comment by ReDBrother** [comment]
That restrictions not existed in firebase auth
We used only that rules of existing email's
