### ISSUE TITLE
Bug: Ошибка 500 при попытке авторизации пользователя с незарегистрированным email

### ISSUE THREAD

**Issue by AnnaAnPetrova** [hexlet-codebattle/codebattle#1998]
### Summary

requirement: |
При неправильном email пользователь должен получить сообщение об ошибке
prerequisites:
Открыта страница логина  
test-data: |
Email = hexlet@gmail.com Password = password
environment: |
Google Chrome 126.0.6478.127 (Официальная сборка) (64 бит)
ОС Windows 11

### Reproduction steps

```bash
1. Ввести email
2. Ввести Password
3. Нажать кнопку «Submit»
```

### Expected result

Пользователь должен получить сообщение об ошибке

### Actual result

Пользователь не авторизован. Сообщения об ошибке не высвечивается. Ошибка 500
![unreal email](https://github.com/user-attachments/assets/0f3cd668-0cba-4b13-854c-b252578dff30)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Дубль #1991
