### ISSUE TITLE
Bug: Mobile version: When trying to create a new task, empty page is shown

### ISSUE THREAD

**Issue by RomannRoss** [hexlet-codebattle/codebattle#2002]
### Summary

Windows 10 Pro, Version 10.0.19045, assembly 19045
Google Chrome, Version 130.0.6723.92
Codebattle, Version ddf1389

### Reproduction steps

```bash
1. Open Devtools in browser
2. Select mobile phone
1. Go to main page of the game https://codebattle.hexlet.io/#lobby
2. Click on nickname button
3. Click on "Tasks" button
4. Click on "Create a new task" button
```

### Expected result

Detailed information about creating a new task should be displayed.

### Actual result

Empty page is shown.
![4](https://github.com/user-attachments/assets/cb1a14b3-4d37-4f82-9010-1156bee59c1e)

### Browsers

Chrome

### OS

Windows

**Comment by ilya-astakhov** [comment]
summary: |
it is not possible to create a tournament in the mobile version
environment: |
Opera One(version: 115.0.5322.119)
Windows 10 Pro 64
steps-to-reproduce: |
1. Open Devtools in browser
2. Select mobile phone
1. Go to main page of the game https://codebattle.hexlet.io/#lobby
2. Click on nickname button
3. Click on "Tasks" button
4. Click on "Create a new task" button
Expected result: |
the tournament is being created the 
actual-result: |
tournament is not being created

![Image](https://github.com/user-attachments/assets/463d0597-b68a-4c1c-beaf-8f4888cf7c4f)
