### ISSUE TITLE
Bug: When viewing a past game, there is no way to see the progress of the decision and the final answer (other players)

### ISSUE THREAD

**Issue by ZaurJordi** [hexlet-codebattle/codebattle#2003]
Summary

When viewing a past game, there is no way to see the progress of the decision and the final answer

Reproduction steps

1.Go to the home page, https://codebattle.hexlet.io/#lobby
2.Open the History tab
3.Select any game 
4.Click ‘Show’.

Expected result

You can see the winner, the progress of the game (how players wrote the code), the final decision

Actual result

Only the game status, winner and loser, date and time are displayed

### Browsers

Chrome
Safari

### OS

Windows
MacOs

Current version: ddf1389
![Ошибка просмотра прошедших игр](https://github.com/user-attachments/assets/017cdb83-8a3e-4d70-87c2-f8c27e660f48)

**Comment by ReDBrother** [comment]
Not all games recorded and will be no recorded after finishing the game
We see valid page on this
