### ISSUE TITLE
Bug: Unable to use code editors in Safari

### ISSUE THREAD

**Issue by MrMiroLev** [hexlet-codebattle/codebattle#2015]
### Summary

When joining a game in the Safari browser, both code editors are empty, and it is impossible for a user to type anything into their code editor

![Screenshot 2024-11-27 at 7 05 45 PM](https://github.com/user-attachments/assets/5fd55106-f128-420e-89cf-d634ac7637d6)

### Environment

OS: MacOS 14.7 (23H124)
Browser: Safari 18.0.1 (19619.1.26.111.11, 19619)
Codebattle version: [bb44a99](https://github.com/hexlet-codebattle/codebattle/commit/bb44a9968fb9127fd66cfa235b64c4456ce6493c)

### Reproduction steps

```bash
1. Open Safari browser
2. Go to https://codebattle.hexlet.io/
3. Click the "TRY SIMPLE BATTLE" button to join a game
```

### Expected result

- The user's and rival's code editors display the code
- The user can type into their code editor

### Actual result

- Both code editors are empty
- The user cannot type anything into their code editor

**Comment by ReDBrother** [comment]
Try to reload games
I try recreate this conditions and i can modify code
