### ISSUE TITLE
Bug, reopened: Broken links

### ISSUE THREAD

**Issue by MrMiroLev** [hexlet-codebattle/codebattle#2016]
### Summary

During the check, broken links have been found on the site
Link to the original bug report: #1919 

![Screenshot 2024-11-27 at 20-27-13 Overview – Dr  Link Check](https://github.com/user-attachments/assets/010cdb5a-c76d-457c-a387-78ccbfaade44)
![Screenshot 2024-11-27 at 20-27-22 All Issues – Dr  Link Check](https://github.com/user-attachments/assets/69d446ad-46d8-48ea-8f00-8dd61e9edd9d)

### Environment

OS: MacOS 14.7 (23H124)
Browser: Firefox 133.0 (aarch64)
Codebattle version: [bb44a99](https://github.com/hexlet-codebattle/codebattle/commit/bb44a9968fb9127fd66cfa235b64c4456ce6493c)

### Reproduction steps

```bash
1. Go to https://www.drlinkcheck.com
2. In the verification field, insert the URL of the Codebattle website https://codebattle.hexlet.io/
3. Analyze page report data
```

### Expected result

The report shows that there are no broken links on the site

### Actual result

There are broken links on the site

**Comment by LuckyStrike34R** [comment]
![2024-12-05_12-49-34](https://github.com/user-attachments/assets/4473fa14-7bed-49a0-8f9d-41ad73a1c47b)
Environment: 
OS: Windows 10 Pro (22h2)
Browser: Yandex Browser 24.10.4.756 (64-bit)
Codebattle version: 6f0737f

**Comment by ddrsn** [comment]
### Environment

OS: Windows 10 Pro, Android 13
Browser: Chrome 131.0.6778.82
Codebattle version: [6f0737f]

![link_issue](https://github.com/user-attachments/assets/a85f1069-b4b1-4690-8050-c3fbfd11dbac)

**Comment by ReDBrother** [comment]
Линки участников мы не можем контролировать и не будем. Их выставляют сами игроки
