### ISSUE TITLE
Bug: Unable to see the history of a completed game (reopened)

### ISSUE THREAD

**Issue by LuckyStrike34R** [hexlet-codebattle/codebattle#2021]
### Summary

When attempting to view the history of a completed game (i.e., replaying the code-writing progress and test output in the playback interface), only text information about the game state, winner/loser, and the event date is displayed

### Reproduction steps

```bash
Open the link to any completed game: https://codebattle.hexlet.io/games/id, replacing "id" with a valid game number (e.g., https://codebattle.hexlet.io/games/100000)
```

### Expected result

The page displays the playback interface, allowing the user to replay the progress of the game, including code-writing steps and test output

### Actual result

The page only shows the game state, the winner/loser, and the date of the event in text format. The playback interface is not displayed

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
No all games have history to play
