### ISSUE TITLE
Bug: No error message output when specifying a non-existent domain name in the E-mail field when registering

### ISSUE THREAD

**Issue by LuckyStrike34R** [hexlet-codebattle/codebattle#2022]
### Summary

No error message output when specifying a non-existent domain name in the E-mail field when registering a user on the site

### Reproduction steps

```bash
1. Open the user registration page on the site - https://codebattle.hexlet.io/users/new?locale=en&next=%2F
2. Enter an alias, for example - User1234
3. Enter e-mail, for example - user@user.ru
4. Enter password, e.g. 123456
5. Enter password confirmation (passwords must match) - 123456.
6. Press Submit button
```

### Expected result

Under the E-mail field appears the validation error text about incorrect e-mail. The user is not registered

### Actual result

Validation error text about an invalid e-mail address does not appear under the E-mail field. The user is not registered

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
We don't have that restrictions
We used Firebase for sign up new users and they pass that kind email's
