### ISSUE TITLE
Bug: No notification to generate a strong password during registration

### ISSUE THREAD

**Issue by ddrsn** [hexlet-codebattle/codebattle#2023]
### Summary

The system does not suggest to generate a strong password during registration.

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/
2. Press Sign Up
3. Fill Email field
4. Click Password field
```

### Expected result

System notification to generate a strong password – a combination of uppercase letters, lowercase letters, numbers, symbols

### Actual result

There is no system notification about generation a strong password (pic_1)
![pic_1 password](https://github.com/user-attachments/assets/65b9ad88-d7c9-4fe4-b487-ec9a76467f2e)

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
It's not a bug
It's feature and we don't have plans for this
