### ISSUE TITLE
Bug: Password visibility.  There is no a clickable icon to show/hide a password.

### ISSUE THREAD

**Issue by ddrsn** [hexlet-codebattle/codebattle#2024]
### Summary

There is no a clickable icon to show/hide a password.

### Environment

OS: Windows 10 Pro, Android 13
Browser: Chrome 131.0.6778.82
Codebattle version: [6f0737f]

### Reproduction steps

1. Go to https://codebattle.hexlet.io/
2. Press Sign In/Sign Up
3. Fill Email field
4. Fill Password
5. Confirm password (in case of registration)

### Expected result

There is a clickable icon which toggles the value of show password

### Actual result

There is no clickable icon. User cannot show/hide a password (pic_1)
![pic_1 password](https://github.com/user-attachments/assets/c84f7ae1-815a-47c7-9ba4-074b7e977fe3)

**Comment by ReDBrother** [comment]
It's standart password input, and we won't extends from default
