### ISSUE TITLE
Bug: Unable to edit a profile picture

### ISSUE THREAD

**Issue by ddrsn** [hexlet-codebattle/codebattle#2025]
### Summary

User cannot edit a profile picture.

### Environment

OS: Windows 10 Pro, Android 13
Browser: Chrome 131.0.6778.82
Codebattle version: [6f0737f]

### Reproduction steps

1. After authorization click your profile in the right up corner
2. Choose “My Profile”
3. After redirection to the profile page try to edit the profile picture

### Expected result

There is a clickable icon to edit the profile picture

### Actual result

There is no clickable icon to edit the profile picture (pic_4)
![pic_4 unable to edit profile picture](https://github.com/user-attachments/assets/b2878699-3c09-4b2a-ace2-afa7bf4e4c40)

**Comment by ReDBrother** [comment]
Мы завели отдельный тикет для этого
