### ISSUE TITLE
Bug:  Creating a new tournament with a past date and time

### ISSUE THREAD

**Issue by ddrsn** [hexlet-codebattle/codebattle#2026]
### Summary

User can create a new tournament with a past date and time.

### Environment

OS: Windows 10 Pro, Android 13
Browser: Chrome 131.0.6778.82
Codebattle version: [6f0737f]

### Reproduction steps

1. After authorization click “Tournaments” and then “Tournaments Info” on the main page
2. Create a new tournament
3. Set a past date and time

### Expected result

Unable to create a tournament with a past date and time

### Actual result

The tournament is created with a past date and time and users can join to participate (pic_6)
![pic_6 tournament with past date](https://github.com/user-attachments/assets/d7744e51-bb82-4e53-80db-bfd640031176)

**Comment by ReDBrother** [comment]
We don't have that restrictions anywhere
