### ISSUE TITLE
Bug: Unable to delete the user’s nickname from the search field

### ISSUE THREAD

**Issue by ddrsn** [hexlet-codebattle/codebattle#2027]
### Summary

Unable to delete the user’s nickname from the search field with a game type “With a friend”

### Environment

OS: Windows 10 Pro, Android 13
Browser: Chrome 131.0.6778.82
Codebattle version: [6f0737f]

### Reproduction steps

1. After authorization click “Create a game” on the main page
2. Choose game type “With a friend”
3. Fill an username in a search field
4. Choose the user
5. Try to delete the username

### Expected result

Username can be deleted

### Actual result

Unable to delete the username from the search field (pic_7)
![pic_7 unable to delete user from search field](https://github.com/user-attachments/assets/b90dc194-2de7-4e19-95ce-34a42cec761e)

**Comment by ReDBrother** [comment]
Это не никнейм, это выбранная позиция, а не текст
