### ISSUE TITLE
Bug: При выборе типа звука "Стандарт" выбранный уровень громкости не сохраняется

### ISSUE THREAD

**Issue by Katya11061994** [hexlet-codebattle/codebattle#2029]
### Summary

Если в настройках выбрать тип звука "Стандарт", а затем изменить уровень громкости и попробовать сохранить, то сохранение не просиходит

### Reproduction steps

```bash
1. Зайти в профиль пользователя
2. Зайти в настройки профиля
3. Выбрать тип звука "Стандарт"
4. Выбрать любой уровень громкости
5. Сохранить изменения
```

### Expected result

Изменения сохраняться

### Actual result

Изменения не сохраняются, уведомление о сохранении не приходит, при обновлении страницы выставленных настроек нет

### Browsers

Chrome

### OS

Linux

**Comment by Katya11061994** [comment]
> ### Summary
If you select the sound type "Standard" in the settings, and then change the volume level and try to save, the saving does not occur
> 

environment: | Google Chrome 128.0.6613.138 (Official Build) (64 bit) Windows 11

> ### Reproduction steps
> ```shell
> 1.Login to user profile
> 2. Go to profile settings
> 3. Select sound type "Standard"
> 4. Select any volume level
> 5. Save changes
> ```
> 
> ### Expected result
> Changes are saved

> 
> ### Actual result

Changes are not saved. There is no notification about saving. When refreshing the page, the settings are not relevant

> ### Browsers
> Chrome
> 
> ### OS
> Linux

**Comment by Katya11061994** [comment]
> > ### Summary
> 
> If you select the sound type "Standard" in the settings, and then change the volume level and try to save, the saving does not occur
> 
> > 
> 
> environment: | Google Chrome 128.0.6613.138 (Official Build) (64 bit) Windows 11
> 
> > ### Reproduction steps
> > ```shell
> > 1. Login to user profile
> > 2. Go to profile settings
> > 3. Select sound type "Standard"
> > 4. Select any volume level
> > 5. Save changes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected result
> >    
> > Changes are saved
> 
> > ### Actual result
> 
> Changes are not saved. There is no notification about saving. When refreshing the page, the settings are not relevant
> 
> > ### Browsers
> > Chrome
> > ### OS
> > Linux

**Comment by Katya11061994** [comment]
> ### Summary
> Если в настройках выбрать тип звука "Стандарт", а затем изменить уровень громкости и попробовать сохранить, то сохранение не просиходит
> 
> ### Reproduction steps
> ```shell
> 1. Зайти в профиль пользователя
> 2. Зайти в настройки профиля
> 3. Выбрать тип звука "Стандарт"
> 4. Выбрать любой уровень громкости
> 5. Сохранить изменения
> ```
> 
> ### Expected result
> Изменения сохраняться
> 
> ### Actual result
> Изменения не сохраняются, уведомление о сохранении не приходит, при обновлении страницы выставленных настроек нет
> 
> ### Browsers
> Chrome
> 
> ### OS
> Linux

**Comment by KrisTak05** [comment]
Summary
  Checking whether the sound type "Standard" can be selected
Reproduction steps

   - Open settings 
    - In the "Select sound type" column select the "Standard" sound type
    - Press "Save" button
    - Refresh the page

Expected result
-the "Settings" page displays the selected sound type
Actual result

changes have not been saved 
Browsers

Chrome
OS

Linux
