### ISSUE TITLE
Bug: The header of the site is translated partially.

### ISSUE THREAD

**Issue by BlazeBud** [hexlet-codebattle/codebattle#2031]
### Summary

When you go to the site, the site title is partially translated into Russian.

### Reproduction steps

```bash
1. Go to https://codebattle.hexlet.io/.
2. Translate the page using the “Translate” button to another language or the browser will do it automatically.
```

### Expected result

When translating the site automatically or forcibly into Russian. The site title should be translated in full.
![2](https://github.com/user-attachments/assets/66130453-8ed1-4866-a29e-e9727db72937)

Current version: 6f0737f
Google Chrome Version 131.0.6778.140 (64 bit)
ОС Windows 10 22H2

### Actual result

The site header is partially translated when you go to the site. In case of automatic or forced translation of the site into Russian..
![1](https://github.com/user-attachments/assets/40387603-06a3-4807-b99c-46bc73431af8)

Current version: 6f0737f
Yandex Browser Version 24.10.4.756 (64-bit)
ОС Windows 10 Version 22H2 

### OS

Windows

**Comment by ReDBrother** [comment]
We don't support browsers translators - this process always unpredictable
