### ISSUE TITLE
Bug: The photo cards in the comments section are not placed correctly.

### ISSUE THREAD

**Issue by BlazeBud** [hexlet-codebattle/codebattle#2032]
### Summary

When you go to the home page of the site and scroll down to the comment section, you can see the misalignment of the photo cards. 

### Reproduction steps

```bash
1. Open the page https://codebattle.hexlet.io/
2. Scroll to the {{Comments}} section.
3. Pay attention to the photos
```

### Expected result

Фотокарточки должны находиться в рамках как это указано в верстке сайта.
![3](https://github.com/user-attachments/assets/bc9b83cc-c0c5-4f39-a3b3-3d634a4bec99)
Current version: 6f0737f
Google Chrome Version 131.0.6778.140 (64 bit)
ОС Windows 10 22H2

### Actual result

The photo cards are not in frames as specified in the site layout.

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
This is design choice
