### ISSUE TITLE
Bug: The layout in the comments section is broken.

### ISSUE THREAD

**Issue by BlazeBud** [hexlet-codebattle/codebattle#2033]
### Summary

Violation of layout when changing the language in the browser.

### Reproduction steps

```bash
1.Open the page https://codebattle.hexlet.io/
2.Scroll down to the {{Comments}} section.
3.Pay attention to the comment name SHERSHNYAG Senior frontend dev when translating the site into Russian.
```

### Expected result

The page layout should remain unchanged, elements should be properly aligned and displayed without distortion in the new language.
![5](https://github.com/user-attachments/assets/65e37099-2ace-479f-b62a-44b6690d4508)

Current version: 6f0737f
Google Chrome Version 131.0.6778.140 (64 bit)
ОС Windows 10 22H2

### Actual result

There are layout issues on the page, the text shifts the comment name.
![4](https://github.com/user-attachments/assets/e9048c5f-4ab6-4308-a558-1cba0b3b2b88)

Current version: 6f0737f
Google Chrome Version 131.0.6778.140 (64 bit)
ОС Windows 10 22H2

### Browsers

Chrome

### OS

Windows

**Comment by ReDBrother** [comment]
Не, мы не будем что-то подстраивать под автоматические переводчики - это слишком непредсказуемый процесс и во всех сайтах он что-то свое ломает
