### ISSUE TITLE
Bug: White field when trying to create a task in Russian language

### ISSUE THREAD

**Issue by MarcusKar** [hexlet-codebattle/codebattle#2037]
### Summary

When trying to create a new task, no text is displayed.

### Reproduction steps

```bash
1. Switch the language to Russian
2. Open tasks in the profile menu.
3. Create a new task.
```

### Expected result

A task must be created

### Actual result

When trying to create a new task, no text is displayed

### Browsers

Chrome

### OS

Windows

**Comment by raiden-creator** [comment]
Проверка создания новой задачи
требования: |
Пользователь может создать новую задачу
предварительные условия:
Пользователь уже зарегистрирован и вошёл через Sign in
тестовые данные: |
Кнопка "Tasks"
среда: |
Google Chrome версия 132.0.6834.83, (64-разрядная)
Windows 11
шаги:
- Нажать на профиль "hexlet2025"
- Нажать "Tasks"
- Нажать "Create new task"
ожидаемый результат: |
Пользователь создал новую задачу
фактический результат: |
Отражается пустая страница. Пользователь не может создать новую задачу

![Image](https://github.com/user-attachments/assets/bd2247f1-5db5-472b-b743-e52fe37e06f7)
![Image](https://github.com/user-attachments/assets/22f8c288-07de-4c5f-8405-122d9675d648)

**Comment by ZairalISU** [comment]
- summary: |
    Пустое окно при нажатии на кнопку "Create new task"
  environment: |
    Google Chrome 131.0.6778.108 (Официальная сборка), (64 бит)
    Windows 10 Домашняя
  steps-to-reproduce: |
    - нажать на кнопку вызова навигационного меню
    - выбрать "tasks"
    - нажать "Create task"
  expected-result: |
    Задача создана
  actual-result: |
    Страница неправильно открывается, открывается пустое окно

![Image](https://github.com/user-attachments/assets/9cd5c21c-efa2-4798-83cd-0b468d52b353)

![Image](https://github.com/user-attachments/assets/7550e9d0-dcfd-48f6-9b30-eaf5641a6930)
