### ISSUE TITLE
Обновление страницы при нажатии кнопки сдаться

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#213]
Конпка убирает пользователя из игры и убирает ему немного рейтинг

**Comment by vtm9** [comment]
#304

**Comment by vtm9** [comment]
#304

**Comment by AnnaTerekhina93** [comment]
во время игры при нажатии на кнопку "сдаться" страница не обновляется

Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

OS:
Windows 10 64-разрядная операционная система, процессор x64
