### ISSUE TITLE
Отключить возможность ввода текста и выбор языка для наблюдателей

### ISSUE THREAD

**Issue by imamatory** [hexlet-codebattle/codebattle#217]
Третьи лица могут писать в левый редактор. Запретить!

**Comment by vtm9** [comment]
прикольно)))

**Comment by imamatory** [comment]
Вносимые изменения не затрагивают сервер, и с виду ничего не происходит, но запросы идут

**Comment by lazycoder9** [comment]
Хм, вроде сделали же. Может закрыть?

**Comment by imamatory** [comment]
#241
