### ISSUE TITLE
Добавить возможность использовать ЯП Rust для решения.

### ISSUE THREAD

**Issue by Nexmean** [hexlet-codebattle/codebattle#299]
Rust - компилируемый язык программирования со строгой статической типизацией и полным отсутствием runtime рефлексии. В связи с этим возникают трудности, а именно:
* во время компиляции чекера и модуля с функцией `solution` невозможно знать количество аргументов, которое должна принимать функция `solution`
* во время компиляции чекера невозможно точно знать типы аргументов функции `solution` и её возвращаемого значения
В связи с этим такое решение задачи: писать нужно не сам код чекера, а код для генерации кода чекера.

Пока схема всего этого для меня выглядит так:
1) Читаем из `stdin` JSON для тестирования, на его основе узнаём количество и типы входящих аргументов `solution` и тип возвращаемого значения.
2) Генерируем библиотечный пакет. Хардкодим в сгенерированный исходный файл `lib.rs` аргументы функции `solution`, возвращаемые значения и тест для проверки.
3) Хардкодим в модуль `solution` сгенерированный бойлерплейт(сигнатура функции и все недостающие типы).
4) Отдаём модуль solution для редактирования игроку.
5) По нажатию кнопки `Check result` вызываем `cargo test` и смотрим завершился ли тест успешно.

В итоге мы будем иметь полноценную возможность решать задачи использую Rust и его стандартную библиотеку, без необходимости использования сторонних библиотек игроком.

Есть ещё 2 варианта, но они слегка неполноценные:
1) Всё ещё с генерацие кода, но (практически) без необходимости сувать какой-то бойлерплейт в `solution`. В данном случае кодогенерация используется только для определения количества аргументов `solution`. В таком случае решение будет иметь примерно такой вид:
```
extern crate serde_json;

use serde_json::Value;

pub fn solution(first: Value, second: Value) -> Value {
    ...
}
```
2) Вариант без кодогенерации: функция `solution` всегда имеет только 1 входящий аргумент, который является массивом аргументов типа `serde_json::Value`, то есть решение будет выглядеть всегда вот так:
```
extern crate serde_json;

use serde_json::Value;

pub fn solution(args: Vec<Value>) -> Value {
    ...
}
```

**Comment by Nexmean** [comment]
Готов взяться за любой из вариантов, хотя предпочёл бы остальным именно первый, но к сожалению, насколько я понимаю, пока приложение не готово к такому сценарию.

**Comment by Abbath** [comment]
Та же проблема, что и в Haskell. Будет время - запилю какую-никакую кодогенерацию хаскеля, потому что один аргумент это не спортивно :trollface:

**Comment by vtm9** [comment]
Круто.

**Comment by mellonges** [comment]
Так почему rust отклонили для добавления?

**Comment by ReDBrother** [comment]
> Так почему rust отклонили для добавления?

Для этого нужно, чтобы кто-то взял и написал реализацию запуска и возврат ответов к задачам. И все это реализовать в докер контейнере, по аналогии  с ruby: https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/dockers/ruby/runner.rb

**Comment by vtm9** [comment]
![image](https://github.com/hexlet-codebattle/codebattle/assets/16337910/a97a0c15-c869-48db-9505-985d5d069c2a)
thx @kjubybot
