### ISSUE TITLE
Создать логотип для codebattle

### ISSUE THREAD

**Issue by antonazgarovich** [hexlet-codebattle/codebattle#3]
Нужно нарисовать уникальный логотип.
Варианты можно скидывать ниже в комментарии.

**Comment by antonazgarovich** [comment]
Один из вариантов логотипа
![ogcover](https://user-images.githubusercontent.com/8579262/28524409-06fcceb4-7089-11e7-9436-5124889a26b7.jpg)
[code_battle_logo.svg.zip](https://github.com/hexlet-codebattle/codebattle/files/1169863/code_battle_logo.svg.zip)

**Comment by freetonik** [comment]
Логотипы уже есть

![](http://i.imgur.com/OoBxz8C.png)

![](http://i.imgur.com/gEJiWe0.png)

**Comment by antonazgarovich** [comment]
Если уже есть, то можно просто добавить в организацию(у меня прав нет) и закрыть таску.

**Comment by heyas** [comment]
![7778705229370f68e64f5accbdedd1fd0589a257d0a8e4ae56 pimgpsh_mobile_save_distr](https://user-images.githubusercontent.com/8567107/28525630-8092024a-708d-11e7-82c7-5f6eb2934030.jpg)

**Comment by heyas** [comment]
@freetonik Посмотри на мой вариант.

**Comment by antonshwab** [comment]
Мне вот нравится прошлый лого. Он лаконичнее. 
Есть ли возможность прикрепить лого в нашу организацию на гитхабе вместо унлылой дефолтной?
