### ISSUE TITLE
Неверно парсится markdown в описании задачи. Парсятся ссылки

### ISSUE THREAD

**Issue by imamatory** [hexlet-codebattle/codebattle#311]
Ссылки не должны парситься.

task id:  30

![image](https://user-images.githubusercontent.com/5245508/38779083-275b6440-40cc-11e8-820b-f3b08e0f59f5.png)

![image](https://user-images.githubusercontent.com/5245508/38779065-e69da4ea-40cb-11e8-895a-236c0843826e.png)

**Comment by mettled** [comment]
Добрый день
Возьму данное issue в работу.
