### ISSUE TITLE
Сохранять игру, с проигрыванием игры, после завершения

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#328]
После завершения игры - созранять код. Чтобы его можно было посмотреть после игры.

**Comment by vtm9** [comment]
можно так же сохранить чат

**Comment by vtm9** [comment]
Необходимо придумать, в какой момент мы считаем игру завершенной. И сохраняем ее

**Comment by vtm9** [comment]
Возможно объеденить ботов и сохранение игр

**Comment by vtm9** [comment]
@thepry , вот жту штуку можно сделать, после завершения игры

**Comment by vtm9** [comment]
просто игру в базу класть

**Comment by thepry** [comment]
@vtm9 А сейчас код не сохраняется? Как же боты работают? (Если работают)

**Comment by vtm9** [comment]
Боты работают. Только вот для них отдельно плейбук пишется. А сама игра живёт в памяти. Если процесс завершить, то ее нельзя будет увидеть

**Comment by vtm9** [comment]
Можно просто этот жсон с состоянием игры  сохранять в постгресс, да и чат туда же

**Comment by vtm9** [comment]
А при показе игры просто жсно в реакт отдавать

**Comment by thepry** [comment]
Может при завершении игры все сохранять? А в процессе забить?

**Comment by vtm9** [comment]
Да, при завершении. Как раз в твоём процессе
