### ISSUE TITLE
Выводить результаты по всем тестам во время баттла

### ISSUE THREAD

**Issue by aarefiev** [hexlet-codebattle/codebattle#329]
Сейчас проблема есть, что проверка выкидывает сообщение об ошибке по первому попавшемуся тесту. Так как проверка не такая уж и быстрая, возникает ненужный лаг, когда фиксишь кот и жмешь проверку еще раз. 
Нужно выводить тесты списком, которые прошли и те которые нет и подитог.
@vtm9 помнишь обсуждали

**Comment by vtm9** [comment]
Круто,  отличная идея.  У нас возвращается json. Его можно подпилить для всех языков.

**Comment by ReDBrother** [comment]
Пока придумал отдельную вкладку с asserts и обычным выводом (+ процент пройденных). ![success](https://user-images.githubusercontent.com/24855537/61172481-afce1080-a58d-11e9-8583-d6d2c99ca348.png)
![output](https://user-images.githubusercontent.com/24855537/61172482-b2c90100-a58d-11e9-85a0-2602c8bb8e67.png) Нужно подумать как быть с информацией о конкретных тестах и нужны ли ее 
выводить полностью\не полностью или вовсе не выводить.
