### ISSUE TITLE
Селфи-баг

### ISSUE THREAD

**Issue by Melodyn** [hexlet-codebattle/codebattle#356]
1. Создать новый баттл.
2. Скопировать ссылку на него.
3. На главной странице отменить его, пока не вступили новые участники.
4. Перейти по прямой ссылке и заджойниться в свой же баттл.

Результат: http://codebattle.hexlet.io/games/1382

**Comment by vtm9** [comment]
надо на cancel грохать  процесс с игрой. Задача в одну строчцу
