### ISSUE TITLE
Улучшить описание входных/выходных данных

### ISSUE THREAD

**Issue by Semigradsky** [hexlet-codebattle/codebattle#371]
Например задание:
> Compute how long after their deparature two trains will meet. Assume that the trains travel between two points, along a single section of track, going in opposite directions. The function should consume the trains' speeds and the starting distance between the trains.
>
> Example: 1.0 == solution(50, 50, 100)

Из описания в принципе понятно что нужно найти, но это ещё нужно вчитаться. А какие входные данные - нужно догадаться.

Например, можно было сделать так:
> Example of input: solution(v1, v2, distance)
> -- v1: number - speed of first train
> -- v2: number - speed of second train
> -- distance: number - distance between two trains

**Comment by vtm9** [comment]
В другую репу
