### ISSUE TITLE
Добавить i18n

### ISSUE THREAD

**Issue by imamatory** [hexlet-codebattle/codebattle#39]
Все строки должны быть интернационализированы

**Comment by lazycoder9** [comment]
А так ли это нужно, если проект будет только на английском?

**Comment by PeresvetS** [comment]
Кирилл мне говорил, что даже если 1 язык в проекте, всё равно через i18n всё делается.

**Comment by imamatory** [comment]
Каким проект будет в будущем сложно сказать, но использование i18n можно принять за стандарт. Почему бы не сделать русскую версию, к примеру, если если сервис станет популярным в России. Будет ли это бизнес требование актуальным покажет время, но с i18n добавить новый язык добавляется невероятно легче чем без него.

**Comment by krivtsov** [comment]
34

**Comment by lazycoder9** [comment]
https://github.com/hexlet-codebattle/codebattle/pull/44
