### ISSUE TITLE
Реализовать регистрацию и аутентификацию пользователей

### ISSUE THREAD

**Issue by mokevnin** [hexlet-codebattle/codebattle#4]
Только через гитхаб, без паролей и форм.

**Comment by antonshwab** [comment]
Эту штуку использовать https://github.com/ueberauth/ueberauth ?

**Comment by antonshwab** [comment]
Или может https://github.com/ueberauth/guardian звезд в три раза больше) 
Как правильно выбирать?

**Comment by staskjs** [comment]
Судя по всему guardian в основном для jwt, а вот ueberauth уже oauth поддерживает, что нам и надо.

**Comment by imamatory** [comment]
Думаю это ключ
>Ueberauth provides only the initial authentication challenge, (initial OAuth flow, collecting the information from a login form, etc). It does not authenticate each request, that's up to your application

**Comment by antonshwab** [comment]
Объясните, пжлста, почему нам нужен OAuth, а не JWT?

**Comment by staskjs** [comment]
Они решают разные проблемы. Oauth это протокол для авторизации, который, например, может включать в себя использование jwt. Но этот протокол похоже реализуется только в ueberauth

**Comment by staskjs** [comment]
Займцсь этим

**Comment by antonshwab** [comment]
окей

**Comment by antonshwab** [comment]
`Займцсь этим` = Займусь или Займись? )

**Comment by staskjs** [comment]
Исправил
