### ISSUE TITLE
Странный результат вывода тестов

### ISSUE THREAD

**Issue by Melodyn** [hexlet-codebattle/codebattle#407]
![image](https://user-images.githubusercontent.com/26752238/51089125-2faf2580-1779-11e9-8be1-5df550fc85d1.png)

В result, предположительно, лишние буквы, в надписи либо убрать единицы, либо разбавить их знаками восклицания!!!1!11!
http://codebattle.hexlet.io/games/2300

**Comment by krivtsov** [comment]
> ![image](https://user-images.githubusercontent.com/26752238/51089125-2faf2580-1779-11e9-8be1-5df550fc85d1.png)
> 
> В result, предположительно, лишние буквы, в надписи либо убрать единицы, либо разбавить их знаками восклицания!!!1!11!
> http://codebattle.hexlet.io/games/2300

Это фича!!111

**Comment by Melodyn** [comment]
Ну тыгдык ладно!!!!11!!!1!!1!1!! Но result всё равно надо бы проверить!11!1!
