### ISSUE TITLE
Вся верстка летит!!! Дима, ты дурак?!?!??! Ишью объявляется открытым

### ISSUE THREAD

**Issue by deadit** [hexlet-codebattle/codebattle#412]
Пишите доработки верстки сюда максимально точно. Старайтесь не повторяться
1. Исправить цвет фона.
2. Обновить лэндинг

**Comment by vtm9** [comment]
Суровое название

**Comment by vtm9** [comment]
Хедер в игре вернуть как был

**Comment by amshkv** [comment]
Таблица юзеров стала скакать из-за иконок побед\сдач, это уже было, думали место зарезервивровать под иконки, может есть лучше решение

**Comment by skhrv** [comment]
Подправить отступы в чате и заодно удали плиз Online Users

**Comment by deadit** [comment]
> Подправить отступы в чате и заодно удали плиз Online Users

почему удалить онлайн юзерс?

**Comment by skhrv** [comment]
не нужная информация, место занимает

**Comment by deadit** [comment]
> не нужная информация, место занимает

да мне кажется там хватает места для 5-6 юзеров и этого достаточно. А надпись говорит о том, что это блок юзеров. Так он просто в воздухе висеть будет

**Comment by krivtsov** [comment]
Сильный переход в цвете фона игрового процесса, смотрится, как 4 островка. Нет связанности интерфейса. Большие отступы, над хедером и между редакторами.

**Comment by vtm9** [comment]
расширь контейнер с таблицей, там не очевидно, что внизу скролл не видно кнопку show

**Comment by fey** [comment]
![default](https://user-images.githubusercontent.com/697178/52061772-e9d3c900-2590-11e9-8d0c-5c5a463be054.PNG)
Длинная строка в поле ввода текста не влезает.
