### ISSUE TITLE
User statistic info

### ISSUE THREAD

**Issue by puku** [hexlet-codebattle/codebattle#416]
The idea is to add a new column to the list of users and to the user's profile with the information about the number of games user win/lost or gave up.

The new column should contain 3 numbers separated by `/`. For example `7/3/2`.
The first number represents amount of games user won, the second number - the amount of games user lost and the last number - the amount of games user gave up.

**Comment by vtm9** [comment]
посмотри еще как на lichess.org сделали всплывашку с профилем игрока.

**Comment by puku** [comment]
Ок, для всплывашек сделаю отдельную таску

**Comment by vtm9** [comment]
Ну да, для этого как раз можно одно апи сделать. Для профиля. И все на реакте сделать. Как ты хотел)

**Comment by puku** [comment]
As discussed in slack, statistic info should be added only on the user's profile page.
There is no sense to add it to the table, because of the task #437.
