### ISSUE TITLE
Подключить редактор Ace

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#42]
При реализации игрового процесса подключить редактор Ace, чтобы он отображался слева для кода пользователя, а справа - для мониторинга кода соперника. [Сам редактор](https://ace.c9.io) и [Известная либа на реакте](https://github.com/securingsincity/react-ace)

**Comment by PeresvetS** [comment]
Будем реализовать это при работе над вторым прототипом. Текущий прототип - 1.

**Comment by ilyar** [comment]
Предложение: использовать в качестве редактора StackBlitz, онлайн-IDE на основе VS Code для быстрой разработки прототипов React- и Angular-приложений — https://stackblitz.com/

**Comment by PeresvetS** [comment]
Спасибо за предложение. Дело в том, что у на планируется много языков, на которых будут написаны задания, а не только React и Angular. А Ace поддерживает все популярные языки. Ну и он является негласным стандартом, им пользуются Chrome, Firefox, Github  и другие. Полный список его пользователей с 'именем' можно увидеть [здесь](https://ace.c9.io/#nav=production).

**Comment by ilyar** [comment]
@PeresvetS Думаю в StackBlitz важным параметром является "на основе VS Code", просто авторы стартовали свой проект с преднастройкой на популярные технологии. Уверен не будет проблемы подключить другие языки полный список [здесь](https://marketplace.visualstudio.com/VSCode).

Стоит отметить что исходников проекта еще не видел, возможно не все гладко, но сама идея супер.

**Comment by PeresvetS** [comment]
Может быть, в будущем это будет хороший редактор. Но в данный момент у него нет ни API для подключения, ни одной библиотеки на React для того, чтобы прикрутить этот редактор к нам в проект. И их [гитхаб репозиторий](https://github.com/stackblitz/core) вообще пока почти пуст, поэтому невозможно с этим редактором разобраться. Поэтому не вижу смысла придумавать себе новые проблемы, когда есть уже готовое проверенное временем решение, которое  имеет много готовых библиотек для подключения и хорошую документацию.

**Comment by imamatory** [comment]
Начал пилить

**Comment by PeresvetS** [comment]
Closed #136 #141
