### ISSUE TITLE
Add user statistic by language

### ISSUE THREAD

**Issue by puku** [hexlet-codebattle/codebattle#447]
Inside user profile add games statistic by languages

**Comment by MityaDementiy** [comment]
@vtm9, привет. Актуальный issue?

**Comment by vtm9** [comment]
ишуе актуальный, осталось backend доделать)

**Comment by nikkstchv** [comment]
а сейчас еще актуальный?

**Comment by ReDBrother** [comment]
Уже нет, выше есть обновленное ишью и его взяли в разработку.
