### ISSUE TITLE
Удобный старт батла - оповещалка + старт когда все готовы

### ISSUE THREAD

**Issue by zulkris** [hexlet-codebattle/codebattle#456]
Когда создаешь батл и ждешь - это реально нервирует. Спустя несколько минут - уже засыпаешь начинаешь "серфить" интернет, переключаясь по вкладкам.

Предложение - когда заходит второй участник - включить "мигание" favicon дабы визуально отделить вкладку кодебатла от других + звуковой сигнал.

Дополнительно - подобно dota2 сделать старт после 10 секунд "захода" второго юзера. Дабы после мигания+звука было несколько секунд подготовиться, и только после этого, одновременно, показывать задание. Иначе получается нечестно - один уже прочитал задание и погуглил, а второй только зашёл :)

**Comment by vtm9** [comment]
Предлагаю оставить только мигание favico и таймер со звуком.

**Comment by mettled** [comment]
Добрый день
Возьму данное issue в работу.
