### ISSUE TITLE
Добавить возможность отмены батла

### ISSUE THREAD

**Issue by zulkris** [hexlet-codebattle/codebattle#458]
Было бы просто замечательно иметь возможность отменить батл, который ты только что создал.

**Comment by vtm9** [comment]
Можно еще сделать более удобное копирование ссылки

**Comment by vtm9** [comment]
WaitingOpponentInfo.jsx

**Comment by zulkris** [comment]
еще бы такую кнопку на страничке самой игры, а не только в общем списке

**Comment by vtm9** [comment]
@rexemtoxa , похоже это твой case)

**Comment by AnnaTerekhina93** [comment]
нет возможности отмены батла

**Comment by AnnaTerekhina93** [comment]
нет возможности отмены батла 

Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

OS:
Windows 10 64-разрядная операционная система, процессор x64
