### ISSUE TITLE
Сделать лендинг

### ISSUE THREAD

**Issue by nohardcode** [hexlet-codebattle/codebattle#462]
@vtm9 
подробности в студию

**Comment by vtm9** [comment]
На сделать лендинг. Любое творчество приветствуется. Использовать базовые компоненты бутстрапа

**Comment by vtm9** [comment]
Цель дать новому пользователю понять что такое кодебаттл

**Comment by vtm9** [comment]
И сделать кнопку начать игру

**Comment by vtm9** [comment]
И тогда человек попадает 6а окно игры с ботом
