### ISSUE TITLE
Рематч ботов зависает. Нужен механизм автосоглашения

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#479]
![image](https://user-images.githubusercontent.com/16337910/55586006-a0d6f700-5730-11e9-9c3d-647c2a3a67d6.png)

@zipofar , можешь сделать автосоглашение?

**Comment by zipofar** [comment]
Работаю над этим

4 апреля 2019 г. 23:24:54 GMT+03:00, Vitaly <notifications@github.com> пишет:
>![image](https://user-images.githubusercontent.com/16337910/55586006-a0d6f700-5730-11e9-9c3d-647c2a3a67d6.png)>
>>
>>
>@zipofar , можешь сделать автосоглашение?>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/hexlet-codebattle/codebattle/issues/479

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by vtm9** [comment]
Думаю надо просто на бек перенести этот способ создания рематча. А там уже бек сделать
