### ISSUE TITLE
Починить список пользователей в чате

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#480]
![Screenshot at 2019-04-05 16-37-18](https://user-images.githubusercontent.com/24855537/55631691-4cc82300-57c1-11e9-9e3d-7f18d19140aa.png)
Дублируется пользователь в чате. Случай наткнуться будет редким, но лучше исправить.

**Comment by vtm9** [comment]
ХЗ как это исправить)

**Comment by ReDBrother** [comment]
Там фильтрацию нужно поставить не по elo пользователя, а по id.

**Comment by vtm9** [comment]
Ааа, тогда сделай)
