### ISSUE TITLE
Сделать, чтобы всегда была доступна игра с ботом каждого уровня сложности

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#493]
![image](https://user-images.githubusercontent.com/697178/56799564-a2c53f00-6832-11e9-83a9-5b2c4310aedb.png)
Думаю, что такого быть не должно. Если кто-то заходит к боту в игру N сложности, то должна создаться еще одна игра N сложности.

**Comment by vtm9** [comment]
Поддерживаю. Сделаешь ПР?

**Comment by fey** [comment]
Пока не могу, тк не шарю в стеке кодбаттла( @vtm9

**Comment by vtm9** [comment]
Ну так вот он повод разобраться
