### ISSUE TITLE
Убрать ботов из топа

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#494]
https://codebattle.hexlet.io/users

**Comment by vtm9** [comment]
Да пусть будут. Это же прикольно

**Comment by fey** [comment]
Тогда сделать фильтр боты/люди/все

**Comment by vtm9** [comment]
Особо не вижу смысла. Вот сортировку по дате регистрации сделать было бы хорошо

**Comment by vtm9** [comment]
@fey , задачка ждет тебя)
