### ISSUE TITLE
Подумать о том, чтобы подробнее сделать описание задач

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#507]
![image](https://user-images.githubusercontent.com/16337910/59962877-efa45980-94f3-11e9-92c0-60df85428229.png)

Например так

**Comment by vtm9** [comment]
@kaldown , сделаешь?)

**Comment by kaldown** [comment]
@vtm9 da :D

**Comment by kaldown** [comment]
а админка ваще есть?

кстати, не все задачи можно обьяснить текстом, могут быть gif \ image или что по-хуже
наверно тип поля тож придется махнуть

**Comment by vtm9** [comment]
Админки нет.
Ну пока я бы оставил текст, и может просто  больше примеров сделать, или описать текстом

**Comment by kaldown** [comment]
тот пример из литкодаработает совсем просто, кажется можно сразу отформатированный список отдавать, например вот таак выглядит эта штука у литкода, прям с контекста украл, большая часть всеж не картинки, если это постгря, то заменить поле на TEXT (unlimited) и дело в шляпе


"content":"<p>Given an integer array, you need to find one <b>continuous subarray</b> that if you only sort this subarray in ascending order, then the whole array will be sorted in ascending order, too. </p> \r\n\r\n<p>You need to find the <b>shortest</b> such subarray and output its length.</p>\r\n\r\n<p><b>Example 1:</b><br />\r\n<pre>\r\n<b>Input:</b> [2, 6, 4, 8, 10, 9, 15]\r\n<b>Output:</b> 5\r\n<b>Explanation:</b> You need to sort [6, 4, 8, 10, 9] in ascending order to make the whole array sorted in ascending order.\r\n</pre>\r\n</p>\r\n\r\n<p><b>Note:</b><br>\r\n<ol>\r\n<li>Then length of the input array is in range [1, 10,000].</li>\r\n<li>The input array may contain duplicates, so ascending order here means <b><=</b>. </li>\r\n</ol>\r\n</p>"

**Comment by kaldown** [comment]
другое дело как будет выглядеть разметка на маленьких дисплеях, но кажется под описание отдается полэкрана - более чем достаточно

**Comment by vtm9** [comment]
У нас там маркдаун

**Comment by vtm9** [comment]
Можно на нем сделать

**Comment by kaldown** [comment]
да просто задача про "подумать", а там думать нечего - берешь и фигачишь))
надо позыркать в тесткейсы и вывести оттуда пару примерчиков в поле

**Comment by vtm9** [comment]
Ну там. Не так очевидно, как лучше это в коде написать. Ты сделай один пример той задачи. А мы потом по образцу будем

**Comment by kaldown** [comment]
ну ваще вот такой командой можно добавить описание:
`update tasks set description=description || '\n' || {NEW_DESCRIPTION} where name={NAME};`

одно но - изменения спадут при следующем `mix.upload`, так что правки нужно делать непосредсвтенно в [issues](https://github.com/hexlet-codebattle/battle_asserts/tree/master/src/battle_asserts/issues)

или гдето есть миграции? (я просто ваще в этом стеке не шарю)

**Comment by vtm9** [comment]
Круто, давай я попробую, выберу оптимальный вариант

**Comment by kaldown** [comment]
я так понял что `mix.upload` не совсем по честному работает, тоесть он не все записывает и под другими названиями, а значит лучшеб чтоб были миграции
типо однажды выполнил `compose-upload-assert`, и потом накатываешь миграции и у всех все консистентно.
Если же поменять issues => то тот у кого щас старая версия - обломается, и ваще база должна идти вперед.
Ну ты и так все знаешь, мне просто поболтать нескем ;)

**Comment by kaldown** [comment]
https://devhints.io/phoenix-migrations

**Comment by kaldown** [comment]
вижу в deploy.yml такое, пойду повкуриваю

**Comment by vtm9** [comment]
У нас там апсерт по имени таска

**Comment by vtm9** [comment]
Все просто
