### ISSUE TITLE
Make random task query more friendly to users

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#520]
https://github.com/hexlet-codebattle/codebattle/blob/e11edae564d581f95a7435c44b1c8383fb02ed87/services/app/lib/codebattle/game_process/engine/standard.ex#L116

**Comment by vtm9** [comment]
Rewrite sql query to make task query more random

**Comment by vtm9** [comment]
@igor-i 
Hi

**Comment by vtm9** [comment]
функция sql Rand часто не однозначно работает. Поэтому я написал штуку, которая выбирает наименее популярный таск для двух игроков. Но проблема в том, что если добавить новый, то он будет всегда выбираться.

**Comment by vtm9** [comment]
У меня была идея сдлеть отдельны GenServer, который грузит таски и раз в 15 минут перетаыовывает их. И работает как рандомный плейлист. ТОесть по кругу выдает таски по запросу, для каждой сложности свой

**Comment by igor-i** [comment]
то есть каждые 15 минут создаётся новый рандомный плейлист по каждой сложности и оттуда выдаются последовательно задачи без учёта истории конкретных игроков
так?

**Comment by igor-i** [comment]
выглядит просто, но возможны ситуации когда будут повторяться у игроков задания

**Comment by vtm9** [comment]
Ну мжоно не в 15 минут, а как прошел полностью цикл задач для одного уровня сложности.
Идея такая, то нам нужно сделать так, чтобы все задачи выбирались с одинаковой вероятностью, а количество посторений у одного игрока было минимальным

**Comment by vtm9** [comment]
Плейлист кажется прикольной идеей

**Comment by vtm9** [comment]
Можно не делать раз в 15 минут пересборку. А просто делать по истечению плейлиста. Просто List.shuffle

**Comment by igor-i** [comment]
ага, cool, так сделаю - построение нового плейлиста не по таймеру, а по исчерпанию всех задач в текущем плейлисте

**Comment by vtm9** [comment]
Можно сделать один генСервер, который содержит 4 списка, и как только он заканчивается, то перемешивает его заново.

Можно для тестов сдлать так, чтобы выбирался рандомный так, если в генсервере пусто

**Comment by vtm9** [comment]
И надо тесты подумать как написать
