### ISSUE TITLE
Not find lodash in ts

### ISSUE THREAD

**Issue by rocketrussia** [hexlet-codebattle/codebattle#525]
check/checker.ts(3,20): error TS2307: Cannot find module 'lodash'.
check/solution.ts(1,20): error TS2307: Cannot find module 'lodash'.
[Screen](https://ibb.co/gVtSmp3)

**Comment by vtm9** [comment]
fixed

**Comment by vtm9** [comment]
Yay!!!!

**Comment by ReDBrother** [comment]
I'm added tsconfig.json. Now you can upgrade typescript config and add new libs.
