### ISSUE TITLE
Созданная игра не отображается в списке Active

### ISSUE THREAD

**Issue by MityaDementiy** [hexlet-codebattle/codebattle#526]
Созданная игра не отображается в списке Active. И соответственно не получается начать новую игру. ![](https://i.ibb.co/rytdQsj/Deepin-Screenshot-20190801115758.png)

**Comment by vtm9** [comment]
Это которая с другом

**Comment by MityaDementiy** [comment]
да. Она и не должна в Active отображаться?

**Comment by igor-i** [comment]
по идее её должен только создатель игры видеть, до тех пор пока не законнектиться второй участник, после этого становится видна всем

**Comment by MityaDementiy** [comment]
Нет, я ее не вижу в списке Active

**Comment by vtm9** [comment]
Короче надо сделать фикс. Когда ты делаешь запрос на active games надо запросить список, потом его фильтровать на беке, паблик или прайват где ты участник. В сокете лежит ид Карент юзера.

**Comment by vtm9** [comment]
И на фронте убрать все фильтрации

**Comment by vtm9** [comment]
Задача на 15 минут

**Comment by vtm9** [comment]
@rexemtoxa thx

**Comment by vtm9** [comment]
#527
