### ISSUE TITLE
Сделать командный турнир

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#548]
Есть идея сделать турнир, чтобы было две команды с равным количествои игроков. Если игроков не хватает, то можно добавить ботов в одну из команд.

Игроки играют несколько туров например 3,5,7.
Потом считается общий результат. Победа - 3 очка. Ничья -  по одному каждому. 0 - проигравшая сторона.
Можно придумать каак это будет на фронте, за основу можно взять liveView который будет рендерить сетку с турнирами и результатами

**Comment by vtm9** [comment]
С версткой надо попросить помощи у @amshkv

**Comment by imamatory** [comment]
Обговорили механику командного турнира с @vtm9 

Командный турнир - соревнование игроков, распределенных в 2 команды.
При создании турнира можно указать максимальное число участников, по-умолчанию 8.
После созданию группового турнира он становится доступен по ссылке и находится в режиме "ожидание игроков". Пользователь может присоединиться к одной из двух команд по выбору.
До начала турнира игроки могут менять команды по желанию.
Создатель турнира может начать турнир вручную, в таком случае, команда с наименьшим количеством игроков будет дополнена ботами.
