### ISSUE TITLE
Wiki wrong link

### ISSUE THREAD

**Issue by alexxis** [hexlet-codebattle/codebattle#557]
On the page with the address https://github.com/hexlet-codebattle/codebattle/wiki/%D0%9C%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D1%8B-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F we have the wrong link.

In the chapter "Elixir", a link to the book "Études for Elixir" goes to https://www.oreilly.com/

**Comment by vtm9** [comment]
Thanks, I think we will update a lot info at wiki
