### ISSUE TITLE
SEO mistakes

### ISSUE THREAD

**Issue by MityaDementiy** [hexlet-codebattle/codebattle#559]
Проверил Codebattle с помощью SEMRush, это инструмент для анализа SEO сайта. 
По итогам:
— самые серьезные ошибки: нет файла robots.txt и карты сайта в формате xml. Они должны быть доступны по URL https://codebattle.hexlet.io/robots.txt и https://codebattle.hexlet.io/sitemap.xml соотвтетственно;
— на странице https://codebattle.hexlet.io/ мало текста в title. Если там в title только Codebattle, можно добавить «Codebattle: поединки программистов»;
— на странице https://codebattle.hexlet.io/auth/github стоит временный редирект, если возможно, его хорошо заменить на постоянный;
— на этой странице https://codebattle.hexlet.io/ низкое соотношение текста к HTML. Если можно добавить на главную пару абзацев текста, я могу написать;
— на сайте проблема с файлами JS и CSS: они слишком большие и не кэшируются (поисковики любят минимизированные файлы CSS и JS).

**Comment by ReDBrother** [comment]
>на сайте проблема с файлами JS и CSS: они слишком большие и не кэшируются (поисковики любят минимизированные файлы CSS и JS).

C этим не очень понятно, поскольку минификаторы для сss и js у нас есть и они работают. Меньше сделать трудно.

**Comment by ReDBrother** [comment]
>на странице https://codebattle.hexlet.io/auth/github стоит временный редирект, если возможно, его хорошо заменить на постоянный

Тут у нас тоже проблемы, поскольку редирект вводится библиотекой, которая занимается гитхаб аутонтификацией. Тут поменять не получится.
