### ISSUE TITLE
Очистить код от deprecated

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#56]
После перехода на elixir 1.5 появилось много deprecated по типу 
```
warning: String.strip/1 is deprecated, use String.trim/1
  lib/mime.ex:28
```
Нужно это исправить. Полный список предупреждений об устаревшем коде можно увидеть, если исполнить команду `make compose-setup`

**Comment by lazycoder9** [comment]
При запуске make compose-setup видно, что бОльшая часть deprecated кода в либах, надо их обновить. А deprecated в нашем коде либо нет, либо я проглядел

**Comment by PeresvetS** [comment]
Понял тебя! В таком случае таск заключается в обновлении либ)

**Comment by PeresvetS** [comment]
Сторонние библиотеки, возможно, не будут обновляться в нужном нам русле ещё долго. Другие элементы деприкейтед подчищены. Можно пока закрыть этот таст, нет предмета задачи.
