### ISSUE TITLE
Move webPushes from oneSignal to Firebase

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#566]
https://firebase.google.com/docs/cloud-messaging/js/client

https://buddy.works/actions/firebase/integrations/elixir

**Comment by imamatory** [comment]
Why do you want to do that?

**Comment by vtm9** [comment]
We had a lot of problems with OneSignal. It is sometimes not available.
It cannot show only last push and show all pushes in new chrome tabs.
And firebase looks more pretty. And I want to try it.

And what's your opinion on that?

**Comment by imamatory** [comment]
Just wanted to see any reasons. I have been using oneSignal for mobile pushes and it was fine despite  troubles with sdk for react native.

**Comment by imamatory** [comment]
feature/firebase-cm
