### ISSUE TITLE
Обновить версию ноды на проде до 8.х, сейчас 7.х

### ISSUE THREAD

**Issue by imamatory** [hexlet-codebattle/codebattle#57]
У дефолтной версии npm для 8-й ноды проблемы с очисткой пакетов npm/npm/issues/17781 которые скоро должны решиться. После этого можно обновить версию ноды. 
Возможно есть вариант понизить версию npm, но необходимости в этом пока нет.

**Comment by vtm9** [comment]
может `yarn`?

**Comment by imamatory** [comment]
Сейчас разницы нет особой, после появления lock-файла.
Этот таск я создал просто чтобы не забывать. Делать ничего не надо

**Comment by imamatory** [comment]
Думаю поставить yarn, ждать пока npm поставит пакеты нету сил
