### ISSUE TITLE
Add linters for languages

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#578]
And add Makefile ([js](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/dockers/js/Makefile)) command `lint` for linting players solution.
branch: [add_linters](https://github.com/hexlet-codebattle/codebattle/tree/add_linters)
- [x] js
- [x] ts
- [ ] elixir
- [x] c++
- [x] golang
- [x] php
- [ ] haskell
- [x] ~perl~
- [x] ruby
- [x] clojure
- [x] python

**Comment by fey** [comment]
вроде все добавили?
