### ISSUE TITLE
Добавить возможность вернуться на главную страницу в меню после окончания игры

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#597]
![image](https://user-images.githubusercontent.com/16337910/72670782-d72cfb00-3a52-11ea-8d02-cb20b5459867.png)

**Comment by irkinwork** [comment]
И еще наверное, нужно добавить кнопку: New Game with Bot (с выбором уровней).
Потому что играешь с ботом, нажимаешь New Game и создаешь ненужную игру, которую нужно потом идти отменять.

**Comment by vtm9** [comment]
Это кнопка рематч

**Comment by irkinwork** [comment]
Да, но это неинтуитивно, непонятно.
Можно переименовать и добавить выбор уровней.

**Comment by vtm9** [comment]
Согласен, давайте добавим
