### ISSUE TITLE
Поменять momentJs на date-FNS

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#598]
Подробности у Вадима

**Comment by ivan-vdovin** [comment]
Смотрю.
Сделаю до конца недели

**Comment by x0xl0ma** [comment]
Меняю. Активно.

**Comment by konstsem** [comment]
Ишью кто то делает? Хотел бы попробовать сделать.

**Comment by vtm9** [comment]
@x0xl0ma , how are you?

**Comment by x0xl0ma** [comment]
@vtm9 Мы пытались с Димой поменять, там все уперлось в бэк. Поэтому замена повисла в воздухе )

**Comment by x0xl0ma** [comment]
@konstsem я не делаю )
