### ISSUE TITLE
Подсказки для новичков

### ISSUE THREAD

**Issue by irkinwork** [hexlet-codebattle/codebattle#602]
Когда заходишь в первый раз — непонятно, куда нажимать, куда смотреть.

Может быть, стоит при первом заходе пользователя открывать приветственное модальное окно. где объяснять вкратце возможные сценарии поведения и основную информацию по сервису (например, объяснение, как отличить ботов от живых людей).

Так же должна быть возможность скрыть и открыть это модальное окно снова.

Возможно, нужна отдельная страница с вводной информацией о сервисе.

**Comment by ReDBrother** [comment]
@irkinwork Есть обновленное [ишью](https://github.com/hexlet-codebattle/codebattle/issues/816), если есть еще предложения, по этому вопросу, то можем еще накинуть всяких фишек.

**Comment by AnnaTerekhina93** [comment]
нет подсказок для новичков 

Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

OS:
Windows 10 64-разрядная операционная система, процессор x64
