### ISSUE TITLE
Сверстать страницу Profile более красиво

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#605]
![image](https://user-images.githubusercontent.com/16337910/72788180-706e3400-3c42-11ea-9746-614521dced9b.png)

Добавить container-lg и более разумно потратить пространство, внизу можно еще добавить последние n игр игрока

**Comment by vtm9** [comment]
@x0xl0ma , давай тебя освободим от этого таска, так как ты выходишь на стажировку
и передадим в руки @valerr

**Comment by apavlyut** [comment]
"
![hqdefault](https://user-images.githubusercontent.com/69304/132949473-163fe702-afeb-4a38-8576-697336c9e8f9.jpg)
Мы стали более лучше одеваться"
