### ISSUE TITLE
Упростить сетап проекта, расширив readme

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#606]
Есть идея сделать сетап проекта более удобным для новичков.
Можно в REadme после инструкции по установке проекта написать раздел популярных ошибок и что делать, с сылками на полезные ресурсы

Пока я вижу три проблемных участка:
- не поставлен docker/docker-compose, - ссылки на установки
- не добавлен пользователь в группу docker
- и порт 5432 уже занят другой базкой, надо ее стопать или удалять с концами

**Comment by jurassic-period** [comment]
Добавляю инструкцию по установки докера.

**Comment by imamatory** [comment]
@jurassic-period вчера в ридми добавили

**Comment by jurassic-period** [comment]
ок
