### ISSUE TITLE
Дополнить процесс создания игры

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#62]
Пользовать авторизовался и попал на предыигровую страницу https://github.com/hexlet-codebattle/codebattle/issues/64, где есть кнопка `Start game`. 
При нажатии на неё, до записи `id` игры в бд и создания игрового процесса, должен создаваться уникальный `Pid` игры(соответствующий `id` игры), который записывается в память отдельного специального процесса(актора, который нужен именно для хранения данных), в виде части коллекции (`id игры` => `pid`).  Возможно, при реализации данной задачи потребуется [данная библиотека](https://github.com/uwiger/gproc)

**Comment by vtm9** [comment]
Этот функционал частично реализован с помощью `gproc`. Который регестрирует все процессы игр и супервизорит их. Сейчас сначала создается игра в базе, а потом сохраняется по id в `gproc`. Если без id игры сохранять, то либо привязывать пид игры к пользователю, что может вызвать коллизии, либо как-то придумаывать ключ сложнее.

**Comment by vtm9** [comment]
возьму этот таск

**Comment by lazycoder9** [comment]
https://github.com/hexlet-codebattle/codebattle/commit/72c2686b3cbb3cdd69870ec266332945bd24611e
