### ISSUE TITLE
Реализовать общий чат

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#63]
Для реализации чата в игровом процессе, первостепенно нам следует сделать его прототип на странице предъигрового процесса (страница, на которую перебрасывает после авторизации, и где кнопка `start game`). В данном чате могут переписываться все авторизованные пользователи, история пока не стирается и хранится в памяти процесса. Возможно, для данной задачи понадобится   [№1](https://github.com/chrismccord/phoenix_chat_example), [№2](https://medium.com/@Stephanbv/elixir-phoenix-build-a-simple-chat-room-7f20ee8e8f9c), [№3](http://work.stevegrossi.com/2016/07/11/building-a-chat-app-with-elixir-and-phoenix-presence/)

**Comment by lazycoder9** [comment]
https://github.com/hexlet-codebattle/codebattle/commit/26cba2fedee60c347d43c1a2f7ad2f0a0a83adb9
