### ISSUE TITLE
Сделать код раннеры более информативными

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#632]
Добавить в каждый `code runner` новые поля. `expected`, `stdout`, `stderr`, `time`.  Чтобы можно было показать выполнение каждого теста.

**Comment by vtm9** [comment]
![image](https://user-images.githubusercontent.com/16337910/74475046-bd4ad080-4eb7-11ea-97a4-b085a742dd41.png)
![image](https://user-images.githubusercontent.com/16337910/74475067-c6d43880-4eb7-11ea-8087-3a02aa802882.png)

**Comment by eldarik** [comment]
@vtm9 @ReDBrother наверное, это issue можно разбить на несколько по каждому языку?

**Comment by vtm9** [comment]
Всего три типа результатов тестов json   
```
{
          status: :failure,
          result: result,
          output: $stdout.string,
          expected: expected,
          arguments: arguments,
          execution_time: finish - start
        }
        {
          status: :success,
          result: result,
          output: $stdout.string,
          expected: expected,
          arguments: arguments,
          execution_time: finish - start
        }

   {
      status: :error,
      result: e.message
    }
```
Надо их отрендерить

**Comment by vtm9** [comment]
see codewars.com

**Comment by vtm9** [comment]
{"status":"failure","result":[0],"output":"","expected":[4,4],"arguments":[[-1,2,-2,-4,4,-3,-2,-3,0,0,-3,3,4,-2]],"execution_time":0.000041752}
