### ISSUE TITLE
На главной актуализировать список доступных языков

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#639]
![2020-02-20 18 39 50](https://user-images.githubusercontent.com/697178/74938753-6fcae800-5410-11ea-8739-b6ae93c4c481.jpg)
![Снимок экрана 2020-02-20 в 18 37 12](https://user-images.githubusercontent.com/697178/74938756-70fc1500-5410-11ea-9999-7d4571cc1ca8.png)

**Comment by ReDBrother** [comment]
От главной странице вскоре вовсе избавимся.
