### ISSUE TITLE
Показывать список участников турнира в превью

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#642]
![image](https://user-images.githubusercontent.com/16337910/75096696-236bdd80-55b3-11ea-8e8e-fabeea788f19.png)

Можно показывать первых участников или создателя на главной странице.

**Comment by MityaDementiy** [comment]
@vtm9, йоу! Это актуальный issue? Вижу, что создатель турнира показывается.
![](https://imgur.com/lBpJzD3.jpg)

**Comment by vtm9** [comment]
актуальный)

**Comment by vtm9** [comment]
done
