### ISSUE TITLE
Обновления по странице users

### ISSUE THREAD

**Issue by eldarik** [hexlet-codebattle/codebattle#652]
- Исправить баг с несохранением параметров пагинации при сортировке
- Добавить серилазованный query в url-path
- Добавить класс для title столбцов, чтобы при наведении менялся курсор

**Comment by vtm9** [comment]
пока предлагаю разобраться с версткой пагинаций
Добавить стрелочки, например как на Гитхабе

**Comment by vtm9** [comment]
![image](https://user-images.githubusercontent.com/16337910/79574803-65a02f80-80c9-11ea-9c4f-0d9dd22c2010.png)

**Comment by vtm9** [comment]
https://examples.bootstrap-table.com/#welcome.html

**Comment by vtm9** [comment]
1. Сделать верстку стрелочек как на примерах выше.

**Comment by vtm9** [comment]
![image](https://user-images.githubusercontent.com/16337910/81221799-fba1e880-8feb-11ea-97ed-5dc303218801.png)
