### ISSUE TITLE
Реализовать чат для каждой игры

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#66]
Данная задача выполяется уже после завершения задачи https://github.com/hexlet-codebattle/codebattle/issues/63
Теперь чат создаётся  при каждом создании нового игрового процесса.  Чат привязан к `Pid` игрового процесса, и история чата хранится в памяти игрового процесса(до завершения игры). Игрок(и) и спектаторы, которые зашли в игровой процесс, могут переписываться в нём. Дублирую материалы с прошлого таска: [№1](https://github.com/chrismccord/phoenix_chat_example), [№2](https://medium.com/@Stephanbv/elixir-phoenix-build-a-simple-chat-room-7f20ee8e8f9c), [№3](http://work.stevegrossi.com/2016/07/11/building-a-chat-app-with-elixir-and-phoenix-presence/)

**Comment by lazycoder9** [comment]
Done https://github.com/hexlet-codebattle/codebattle/commit/8c180355aeb65d0468ba0e34328efa8246a9c75a
