### ISSUE TITLE
Выводить к задаче её авторов

### ISSUE THREAD

**Issue by amshkv** [hexlet-codebattle/codebattle#666]
Хорошо бы выводить тех, кто принимал участие в составлении задач
За рееренс можно взять кодварс

**Comment by vtm9** [comment]
![image](https://user-images.githubusercontent.com/16337910/81479431-be2b9e00-922b-11ea-8835-2ac4ac9ddaa3.png)

Изучить api github, добавить вывод контрибуторов к задаче на странице игры
