### ISSUE TITLE
Перевести реакт компоненты с классов на функциональные.

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#671]
Бонусом, было бы клёво, если есть несколько логически связанных компонентов, то перевести их в отдельные поддирректории. Например: [UserName](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/assets/js/widgets/components/UserName.jsx), [UserStats](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/assets/js/widgets/components/UserStats.jsx), [UserAchievements](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/assets/js/widgets/components/UserAchievements.jsx)

**Comment by Yoffic** [comment]
Хочу перевести на функциональный компонент RematchButton.

**Comment by Yoffic** [comment]
Беру InputWithEmoji

**Comment by H9ko** [comment]
Беру контейнер RightEditorToolbar

**Comment by Yoffic** [comment]
беру контейнер Heatmap

**Comment by Yoffic** [comment]
CodebattlePlayer пока не получилось перевести. Проблема с обновлением стейта при использовании хука useState.

**Comment by Yoffic** [comment]
беру RatingList контейнер

**Comment by H9ko** [comment]
Беру контейнер LeftEditorToolbar

**Comment by x0xl0ma** [comment]
Я взяла GameList

**Comment by MityaDementiy** [comment]
@ReDBrother, йоу! [NotificationsHandler](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/assets/js/widgets/containers/NotificationsHandler.jsx) можно брать?
