### ISSUE TITLE
Сверстать на панельке кнопку с найстройками проигрывания

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#673]
Добавить шестеренку на панель плейера c выпадающей менюшкой, по примеру youtube
![youtube](https://user-images.githubusercontent.com/24855537/77016004-7dc84600-6987-11ea-84fd-8b37848b03f4.png)

**Comment by jurassic-period** [comment]
Взял таску

**Comment by jurassic-period** [comment]
done
