### ISSUE TITLE
Отрефакторить редьюсеры, добавить слайсы

### ISSUE THREAD

**Issue by irkinwork** [hexlet-codebattle/codebattle#674]
Предлагаю вместо громоздкого разделения редьюсеров и экшнов использовать компактные слайсы.

Пример: https://github.com/hexlet-basics/hexlet_basics/blob/master/services/web/assets/js/lesson/slices/checkInfo.js

Руководствоваться так же можно официальным redux styleguide: https://redux.js.org/style-guide/style-guide/

**Comment by x0xl0ma** [comment]
Я беру!
