### ISSUE TITLE
Починить проверку для нескольких задач уровня easy

### ISSUE THREAD

**Issue by dpetruk** [hexlet-codebattle/codebattle#699]
После нажатия кнопки "Check" возникают лишь визуальные эффекты нажатия (анимация загрузки и "нажатость") и отсутствует сама проверка. 
Было замечено для следующих задач уровня easy: disjoint_sets, the_big_divide, group_multiple_by_occurence, sublist.
Также такое происходило и в случае какой-то задачи на уровне elementary, но ее название уже привести не могу.
Прикладываю скрин.
![Screenshot from 2020-04-04 16-00-41](https://user-images.githubusercontent.com/30505853/78453723-35ee3200-769c-11ea-871d-9fd5488ead1e.png)

**Comment by vtm9** [comment]
@ReDBrother  вроде все задачки пофиксил
