### ISSUE TITLE
Повторяются уже решенные задачи

### ISSUE THREAD

**Issue by dpetruk** [hexlet-codebattle/codebattle#711]
Играя достаточно долго с одним оппонентом можно заметить, что задачи повторяются.
Замечено на уровнях elementary и easy, более высокие уровни не проверялись.

**Comment by dpetruk** [comment]
Повторение задач может быть полезно - если спустя время решать ту же задачу, то можно найти более лаконичное решение. Однако, хорошо было бы иметь возможность выбора между новыми задачами и решенными.

**Comment by vtm9** [comment]
Задач мало, поэтому они повторябтся

**Comment by vtm9** [comment]
В целом их можно добавлять, они в опенсорса. Выбирать задачи смысла нет, тогда суть игры теряется

**Comment by dpetruk** [comment]
Выбор отдельных задач действительно лишает игру чего-то важного. Я не точно выразился. Скорее идея в том, что у пользователя при создании игры была возможность выбирать между двумя состояниями. Первому состоянию соответствует то, которое есть сейчас (задачи могут быть либо уже решенными, либо незнакомыми). Второе состояние - когда игра создается только на множестве незнакомых задач. В случае

**Comment by vtm9** [comment]
Выглядит слишком сложно. Но в целом можно сделать. Если есть желание по Велком, могу рассказать где писать код. Но приоритеты другие у проекта. Если будет спрос на фичу, можно будет добавить. Идея мне нравится. Решать новые задачки
