### ISSUE TITLE
Вывод в консоль (js) идет единой строкой, без переносов

### ISSUE THREAD

**Issue by dpetruk** [hexlet-codebattle/codebattle#721]
При игре на js вывод через console.log не делает переход на другую строку. Из-за этого трудно ориентироваться в выводе при отладке. 
В output встречаются управляющие последовательности (\n).
![Screenshot from 2020-04-15 15-52-04](https://user-images.githubusercontent.com/30505853/79339200-2dfe7f80-7f31-11ea-8e1e-c1e17f5e138d.png)

**Comment by ReDBrother** [comment]
Мы работаем над новым форматом вывод результатов проверки и соответственно того, что выводится в консоль на каждый вызов вашей функции. #632

**Comment by ReDBrother** [comment]
@dpetruk Новый формат был добавлен в проект, ждем ваших замечаний)
