### ISSUE TITLE
Если имя турнира очень длинное ломается верстка.

### ISSUE THREAD

**Issue by v1valasvegan** [hexlet-codebattle/codebattle#727]
https://codebattle.hexlet.io/tournaments
<img width="1436" alt="Screenshot 2020-04-25 at 20 37 33" src="https://user-images.githubusercontent.com/46919813/80286557-c9170680-8734-11ea-998e-2e836a8f517a.png">

**Comment by H9ko** [comment]
vtm ты меня подставил я сделал, а потом увидел что ишью существует и занят...
