### ISSUE TITLE
Вывести результат одного из асертов executionOutput, если есть хотя бы один failed

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#746]
Сделать вывод первого failure теста в любом случае, а потом сделать кнопку more

![image](https://user-images.githubusercontent.com/16337910/81479676-55452580-922d-11ea-8cc3-fd53b3d84bd1.png)

**Comment by vtm9** [comment]
assigned to @nikkstchv

**Comment by vtm9** [comment]
Ждем ответа от @H9ko

**Comment by H9ko** [comment]
Сделал другой пр, тот закрыл, там все сломал
