### ISSUE TITLE
Игры в турнирах умирают в состоянии playing

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#775]
![image](https://user-images.githubusercontent.com/16337910/90672504-e1201200-e25e-11ea-9852-aa00b913ed89.png)
Сделать запись плейбук

**Comment by ReDBrother** [comment]
Возможно уже не актуально. Эти матчи завершались из-за ошибки timeout сервера.

**Comment by ReDBrother** [comment]
Либо можно наконец записывать все игры, которые завершаются по таймауту.
