### ISSUE TITLE
Рефакторинг компонентов LeftEditorToolbar and  RightEditorToolbar.jsx

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#781]
Объединить эти компоненты в EditorToolbar и все зависимости вынести в context
Тулбары должны быть разными для Игрока, опонента и спектатора.
Это сложная задача и требудет погружения и исследования. 
Я бы предложил погрузиться в кот и придумать решение лучше

**Comment by voitd** [comment]
Взял в работу!
