### ISSUE TITLE
Заменить имена переменных в темплейтах, для каждой языковой платформы.

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#787]
![signature](https://user-images.githubusercontent.com/24855537/92770026-381e9000-f3a2-11ea-9a25-6657c123a3db.png)
Именая переменных должны соответствовать стандарту своего языка.
1) Добавить в language.ex формат именования переменных.
2) Переделать генератор, чтобы он учитывал этот формат, при генерации solution по умолчанию.

**Comment by mettled** [comment]
Добрый день
Хочу взять данное issue.
