### ISSUE TITLE
ux - навигация после завершения боя

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#790]
После завершения боя не очень понятно куда идти. Всплывашка появляется один раз и все. 
Если захочется подправить решение, то после нажатия кнопки тестов, всплывашка больше не появится.
Перейти на главную через ссылку слева вверху не очень очевидно.

**Comment by possesion** [comment]
Там есть еще кнопка Back to home.
Если она незаметная, то можно чуть подвинуть

**Comment by fey** [comment]
Ишшус не актуален, тк недавно всплывашка была перенесена в саму страницу.
