### ISSUE TITLE
Убрать нотификейшн из всплывашки и добавить в правый верхний угол над чатом, там же отрисовать все кнопки

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#795]
![image](https://user-images.githubusercontent.com/16337910/93016482-2ae3ea00-f5ca-11ea-8e50-50d5d35e4c23.png)

**Comment by H9ko** [comment]
Попробую сделать

**Comment by H9ko** [comment]
Убираем вообще все нотификейшены в правый верх угол над чатом? или только те которые после окончания игры
