### ISSUE TITLE
Реализовать создание игры с выбором языка

### ISSUE THREAD

**Issue by mokevnin** [hexlet-codebattle/codebattle#8]
на главной проекта должен быть список языков, тыкая на один из которых, создается игра

**Comment by pldin601** [comment]
А где же список языков?

**Comment by PeresvetS** [comment]
Спасибо за внимательность, задача была закрыта по ошибке.

**Comment by AnnaTerekhina93** [comment]
1. при создании игры нет выбора языка 

Browser:
Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

OS:
Windows 10 64-разрядная операционная система, процессор x64
