### ISSUE TITLE
Фильтр селекта языка при наборе с клавиатуры

### ISSUE THREAD

**Issue by Melodyn** [hexlet-codebattle/codebattle#803]
Когда нужно сменить язык по умолчанию, то выбор из выпадающего списка языков сейчас не поддерживает ввод с клавиатуры. Будет круто добавить ему фильтр, чтобы набор имени языка откидывал то, что не совпадает. Можно сделать поддержку подсказок в русской раскладке, если есть способ сделать это.

**Comment by possesion** [comment]
Беру issue
