### ISSUE TITLE
Не работает отладочная печать в PHP

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#811]
При выполнении тестов выводится вывод типа
Receive: null
Expected: [1,3,4,4]
Arguments: [2,[1,2,3,9,4,8,4]]

Функции типа var_dump, print бесполезны((

**Comment by eldarik** [comment]
@vtm9 а для php не сделали работу с stdout и время выполнения?

**Comment by fey** [comment]
бамп. Какое-то время работало, щас нет.
