### ISSUE TITLE
Внедрить небольшой туториал по функциональности игры

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#816]
Если игрок первый раз запускает игру с ботом или другим игроком, мы хотим ознакомить его с возможностями платформы и о том, как устроен игровой процесс. Есть два основных направления, по которым можно провести работу.
1. Полная инструкция.
 - [ ] Добавить одну общую модалку, с полной инструкцией игрового процесса
 - [ ] Накидать во всех ключевых местах своего рода, кнопку info, которая эту модалку расскроет.
 - Bonus. Сделать документацию по проекту. Доступно и подробно описать все возможности, которая предоставляет платформа.

2. Внедрить небольшой туториал, который наглядно подскажет что где находится и как работает, немного расскажет про суть игры и что от игрока требуется (Пример: [screeps tutorial](https://screeps.com/a/#!/sim/tutorial/1)).

- [x] Написать компонент, который будет последовательно наводиться на дом элементы и показывать небольшое окошко с инструкцией. (На первых порах по простому: Что за задачу решаем? Как сменить язык? Где писать решение? Как проверять уже написанное решение?)
- [x] В local storage занести флаг, по которому мы будем определять запускать ли туториал тому или иному пользователю. (Показывать только первый раз, когда игрок запускает битву)
- [x] Наполнить такой компонент контентом

Разработка будет вестись в ветке tutorial. Старое ишью: #602

**Comment by possesion** [comment]
Беру! Не знаю, с чего начать даже, так что быстро результат не выдам)
