### ISSUE TITLE
Добавить превью на страницу с игрой

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#817]
Чтобы не ждать, когда прогрузятся данные с сервера и отрендериться основной контент, мы можем вывести небольшое превью с информацией по игре. Кто играет и т.д

**Comment by enmalafeev** [comment]
Это не тут ты предлагал выводить картинку player 1 vs player 2 вместо лоадера ?

**Comment by ReDBrother** [comment]
Да, к этой ишью её можно отнести.

**Comment by enmalafeev** [comment]
Давай возьму

**Comment by enmalafeev** [comment]
Дима, у этого компонента кастомный дизайн. Куда css компонента складываем ?
