### ISSUE TITLE
Добавить тесты контроллеров.

### ISSUE THREAD

**Issue by PeresvetS** [hexlet-codebattle/codebattle#84]
Сейчас есть только тесты моделей. Нужно добавить тесты контроллеров.

**Comment by PeresvetS** [comment]
@ilyar написал, что попробует с ними разобраться. Я же попробую разобраться с фикстурами в ближайшее время.

**Comment by ilyar** [comment]
@PeresvetS пока получается не очень, не уверен, что успею разобраться, напишу как закончу.

**Comment by PeresvetS** [comment]
Closed #142 #146
