### ISSUE TITLE
При попытке подключиться к игре по ссылке кидает на главную

### ISSUE THREAD

**Issue by imamatory** [hexlet-codebattle/codebattle#852]
**Сценарий**: создать игру и поделиться ссылкой на игру, открыть ссылку незалогиненым пользователем, нажать присоединиться.
**Фактический результат**: редирект на главную
**Ожидаемый результат**: для незарегистрированного пользователя показывать кнопку `sign in to join`, которая ведет на логин, с последующим возвратом на страницу с игрой(query-параметр `next` в auth callback url)

**Comment by ReDBrother** [comment]
Да, да. Новый лендинг не выкидывает флешки, как раньше.

**Comment by imamatory** [comment]
Для этой проблемы норм решение. Однако, стоит прикинуть по времени, проблема есть уже сейчас и можно потерять игроков, ведь разработка страницы входа гораздо сложнее, чем вставить дополнительный текст и кнопку внутрь условия с проверкой авторизации.

Классическую это через email? Я бы рекомендовал добавлять провайдеры oauth. Гораздо легче кучу всего делать просто не нужно. Например, отправлять письма.

**Comment by ReDBrother** [comment]
> Классическую это через email? Я бы рекомендовал добавлять провайдеры oauth. Гораздо легче кучу всего делать просто не нужно. Например, отправлять письма.

Угу, мы с Виталем решили заюзать firebase для этой цели.
