### ISSUE TITLE
Редирект со страницы турнира на лендинг для неавторизованного пользователя

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#853]
Если пользователь не авторизован, то его выкидывает без уведомления на лендинг.

Как воспроизвести
Зайти на страницу турнира, например https://codebattle.hexlet.io/tournaments/114 в режиме гостя 

Возможные решения
1. Показывать страницу турнира пользователю
2. Добавить сообщение об ошибке (что нужно авторизоваться)

**Comment by ReDBrother** [comment]
> Добавить сообщение об ошибке (что нужно авторизоваться)

Вот тут скорее проблема в новом лендинге, она флешки не выкидывает с сообщениями. @vtm9 Фиксанешь?
