### ISSUE TITLE
Добавить форму обратной связи.

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#858]
Есть такая клевая библиотека https://github.com/markmur/react-slack-feedback, которая даст пользователям возможность написать нам про ошибки сразу через сайт. Собственно, кроме формы понадобиться небольшая ручка в компоненте ExecutionOutput, которая раскроет дропдаун, либо модалку с этой формой.

**Comment by MityaDementiy** [comment]
Взял.

**Comment by MityaDementiy** [comment]
JSON c payload: 
`{
   "attachments":[
      {
         "fallback":"Feedback (bug)",
         "author_name":"Diman-2306",
         "color":"danger",
         "title":"bug",
         "title_link":"http://localhost:4000/games/34",
         "text":"test test test",
         "footer":"React Slack Feedback"
      }
   ]
}`
