### ISSUE TITLE
404 при попытке открыть свой профиль до прогрузки фронтенда

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#878]
## Как воспроизвести
Залогинился.
Список игр еще не загрузился.
Жму на свой рейтинг справа вверху
Ссылка ведет на https://codebattle.hexlet.io/35
{"error":"NOT_FOUND"}

Также даже после прогрузки можно нажать ПКМ - открыть в новой вкладке и получить такую е ошибку

## Ожидаемое поведение
Откроется мой профиль

**Comment by MityaDementiy** [comment]
Попробую разобраться

**Comment by MityaDementiy** [comment]
@vtm9, привет! Я тут погорячился, без магии эликсира тут не обойтись. Я правильно понимаю, это выпадающее меню у нас в темлейте https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/lib/codebattle_web/templates/layout/app.html.slime? Не могу понять, откуда там берётся URL https://codebattle.hexlet.io/35 и почему даже после прогрузки при попытке открыть в новой вкладке профиль открывается этот URL с ошибкой? 
![](https://imgur.com/ksB8XPe.jpg)
![](https://imgur.com/WeRPxQ3.jpg)

**Comment by vtm9** [comment]
cannot reproduce
