### ISSUE TITLE
Сделать сортировку на список активных игр

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#894]
Сделать более понятную пользуну сортировку.
1 вначале идут игры, в которых играет текущий пользователь,
2 игры живых людей друг с другом,
3 затем игры с ботами(любой игрок с ботом)
и можно по уровню сложности добавить сортировку в каждую из подгрупп

![image](https://user-images.githubusercontent.com/16337910/102721518-4fa7d600-430c-11eb-98b8-45fd75bdc06a.png)

**Comment by disheg** [comment]
Взял в работу
