### ISSUE TITLE
Сделать мобильную верстку игры более удобной

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#911]
![image](https://user-images.githubusercontent.com/16337910/103140151-3fb93900-46f4-11eb-8e8b-8b25507c0fb6.png)

**Comment by vtm9** [comment]
![image](https://user-images.githubusercontent.com/16337910/115607973-56604d00-a2ee-11eb-844e-29f532962db9.png)
Оставить кнопки на мобильной верстке для рематча и back to home

**Comment by vtm9** [comment]
моргающую клаву убрали, надо поправить чат и вернуть кнопки после завершения игры

**Comment by Rost-is-love** [comment]
Взял в работу
