### ISSUE TITLE
Показывать профиль игрока для неавторизованного пользователя

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#933]
Кейс - нельзя смотреть профиль пользователя, если ты гость - редиректит без флеш сообщения на главную страницу.
Как должно быть
1. РРедирект со флешем (авторизуйтесь типа)
2. Страница всегда доступна для гостя (лучший вариант?)
3. Настройки приватности кому можно смотреть профиль

**Comment by ReDBrother** [comment]
Cделали первый вариант.
