### ISSUE TITLE
Кнопка сброса текущего решения.

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#934]
Рядом с кнопкой проверки решения, нужна кнопка `reset`, которая сбрасывает до дефолтного значения cодержимое в редакторе кода (Для каждого языка уже готова калька функции solution, которую нужно реализовать).
![default](https://user-images.githubusercontent.com/24855537/104187088-67184180-5428-11eb-80b7-c5cba0f9dd22.PNG)

**Comment by GPopov9** [comment]
I'll take it
