### ISSUE TITLE
Кнопка реванш, если бот вышел из игры

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#946]
Бывает, что во время игры бот выходит из матча и кнопка рематча заменяется на то, что игрок вышел.
предлагаю для ботов это игнорировать и разрешать рематч или присуждать автопобеду без очков.

**Comment by ReDBrother** [comment]
Боты не выходят просто так. Скорее всего игра уже умерла.

**Comment by vtm9** [comment]
в целом можно всегда оставить кнопку рематч для ботов. все равно создается новая игра и пользуна туда редиректит

**Comment by vtm9** [comment]
еще проще будет просто с ботами сделать кнопку создания новой игры с таким же уровнем
