### ISSUE TITLE
Поправить ширину контейнеров top boards

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#950]
![image](https://user-images.githubusercontent.com/16337910/106445368-fe087480-648f-11eb-98f4-360e3d05f4d5.png)

**Comment by GPopov9** [comment]
Please, assign. Will take!

**Comment by GPopov9** [comment]
Pls close with this PR 
https://github.com/hexlet-codebattle/codebattle/pull/953
