### ISSUE TITLE
Изменить алгоритм подбора пар игроков и ботов в турнирах

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/codebattle#958]
Сейчас боты и игроки шаффлятся рандомно, может получится ситуация, когда будет пара Человек-Человек и Бот-Бот.
Чтобы было больше интересу предлагаю изменить алгоритм, чтобы по возможности люди не попадались друг другу в первых раундах.
Например брать N игроков, создавать для них игры, добавлять их первыми игроками, далее добавлять оставшихся игроков, остальные места заполнять ботами.

**Comment by vtm9** [comment]
Решили сделать так, что мы берем всех игроков и дополняем ботами до размера 2, 4, 8 , 16 тога этой проблемы просто нет
