### ISSUE TITLE
Rewrite tournament pages from liveview to react

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#963]
Cтартовал процесс перехода: Организована подписка на события турниров, написан основной контейнер на реакте и организован redux store (rtk).
Чтобы окончательно завершить переход, нужно написать набор компонентов для [Tournament.jsx](https://github.com/hexlet-codebattle/codebattle/blob/tournament_react/services/app/assets/js/widgets/containers/Tournament.jsx):

- [x] (Задачу взяли: disheg)Хеадер, с выводом основной информации по турниру и таймером отсчета до его начала. Так же несколько основных ссылок на продолжение текущей битвы и возвращение на основную страницу турниров. Для создателя добавить управление началом турнира или его отменой перед началом. Апи реализовать через мидлвару [Tournament](https://github.com/hexlet-codebattle/codebattle/blob/tournament_react/services/app/assets/js/widgets/middlewares/Tournament.js). 
- [x] (Задачу взяли: karen9999)Компонент, отвечающий за турнирный чат. Вебсокетный канал настроен (мидлвара [Chat](https://github.com/hexlet-codebattle/codebattle/blob/tournament_react/services/app/assets/js/widgets/middlewares/Chat.js)). Отправку сообщений так же нужно производить через сответствующую мидлвару.

На данный момент существуют два вида турниров: Индивидуальный (игроки бьются друг с другом) и Командный (игроки разбиваются на равные команды, до выявления лучшей). Апи реализовать через мидлвару [Tournament](https://github.com/hexlet-codebattle/codebattle/blob/tournament_react/services/app/assets/js/widgets/middlewares/Tournament.js). 

---- Индивидуальный Турнир (ИТ) -----
(За кальку можно взять [эту страницу](https://codebattle.hexlet.io/tournaments/182))

- [x] (Задачу взяли: valerr) Компонент, отвечающий за вывод участников турнира.
- [x] Ему же добавить кнопки управления участия или выхода из турнира.
- [x] Компонент с турнирной сеткой. Сверстать турнирную сетку и вывести промежуточную информацию по каждому матчу и подсветить ключевые игры для пользователя.

---- Командный Турнир (КТ) ---- (Cекцию прорабатывает SergeyKirintsev)
(За кальку можно взять [эту страницу](https://codebattle.hexlet.io/tournaments/174))

- [x] Компонент с панелью. Нас интересуют следующие табы:
- [x] (Задачу взяли: valerr) 1.1 Таба с выводом участников турнира от обоих команд и промежуточный результат турнира
- [x] 1.2 Реализовать управление по выбору команды или выхода из неё. Так же реализовать управление для создателя игры (На данный момент, ограничивается заданием имен команд)
- [x] 2 Таба со статистикой участников турнира
- [x] 3 Таба с общей статистикой турнира (Лучшее время битвы, лучший яп)
- [x] Компонент с выводом результатов каждого раунда. (Тот же подход, что и у турнирной сетки ИТ)

Ветка разработки: [tournament_react](https://github.com/hexlet-codebattle/codebattle/tree/tournament_react).
Оставшиеся задачи можете взять, написав комментарии к ишью.

**Comment by karen9999** [comment]
Взял таску с чатом

**Comment by disheg** [comment]
Взял таску с header

**Comment by SergeyKirintsev** [comment]
беру Командный Турнир (КТ)

**Comment by ReDBrother** [comment]
Всех поздравляю! Мы перешли на реакт) Спустя 2 года)
