### ISSUE TITLE
Пофиксить верстку контейнеров топ бара, надо разобраться чтобы топ бары не  залезали на список игр

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#965]
![image](https://user-images.githubusercontent.com/16337910/109426958-2dfc5680-7a01-11eb-8c31-45fa7ac9be54.png)

поправить чтобы справа все подходило под картинку и слева не закрывались кнопки show

**Comment by FilimonPK** [comment]
#1517
