### ISSUE TITLE
Улучшить табы на странице игры

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#969]
![image](https://user-images.githubusercontent.com/16337910/109427816-35256380-7a05-11eb-9aee-909a73b2563f.png)

1. выделенный таб должен быть белым и с бордером 1px solid black
2. два таба уменьшить и сдвинуть влево
3. Справа добавить таймер, вынести его из вкладки task
4.  При ховере на таб подсвечивать текст красным
5. вторую вкладку переименовать в output

**Comment by patapiks** [comment]
Попробую
