### ISSUE TITLE
Убрать рамки, пока мы не придумаем что-то лучше. Сейчас люди думают что это ошибка при победе и отвлекает от кода

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#971]
![image](https://user-images.githubusercontent.com/16337910/109428241-496a6000-7a07-11eb-87f5-c68784e98282.png)

**Comment by karen9999** [comment]
взял

**Comment by ReDBrother** [comment]
Рамку поменял на золотистую. Проблема очевидности будет еще решена, когда доделают модалку с сообщением о победе/поражении.
