### ISSUE TITLE
Убрать моргающую клавиатуру, ибо людям все что моргает мешает концентрироваться на написании кода, особенно на мобильной верстке

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#973]
![image](https://user-images.githubusercontent.com/16337910/109429269-eb8c4700-7a0b-11eb-91ec-7ddf72cce814.png)

**Comment by vtm9** [comment]
убрать еще синюю рамку при моргании.

**Comment by vtm9** [comment]
Прости @ReDBrother , у нас развивается эпилепсия.
Возможно придумать более плавную анимацию.
Но в целом я бы оставил это на подумать

**Comment by vtm9** [comment]
надо придумать дизайнерское ненавязчивое решение

**Comment by ReDBrother** [comment]
Согласен, это решение было пробным. Попробуем отойти от обратного: Показать не что пишут код, а показать что человек отошел.
Когда у нас есть автоматы на редакторе к этому подойти теперь проще.

**Comment by ReDBrother** [comment]
Автомат бы выглядел так:
idle -> ( typing(никак не обозначаем) <-> waiting(осветлим фон редактора) <-> leave(???) )

**Comment by ReDBrother** [comment]
О так же, на автомат навесим online индикатор.
