### ISSUE TITLE
сделать на главной странице список online игроков

### ISSUE THREAD

**Issue by vtm9** [hexlet-codebattle/codebattle#976]
![image](https://user-images.githubusercontent.com/16337910/109429910-80447400-7a0f-11eb-8090-b8398ebf3655.png)

**Comment by vtm9** [comment]
@ReDBrother , давай вдвоем сделаем

**Comment by ReDBrother** [comment]
Вместе с инвайтами (игры с выбранным оппонентом) пойдут. В рамках разработки инвайтов был разработан общий channel , который будет хранить список активных игроков.

**Comment by vtm9** [comment]
done
