### ISSUE TITLE
Mode vim mode does not work or it works

### ISSUE THREAD

**Issue by ilyar** [hexlet-codebattle/codebattle#993]
The vim mode does not work or it works, but my expectations do not match. I assume this is vim editor emulation mode. At the moment I'm observing that vim switch has no effect on editor's behavior, I checked it in `Google Chrome
Version 89.0.4389.90`.

How should vim mode work?

**Comment by ReDBrother** [comment]
> I assume this is vim editor emulation mode
Yes, we are using https://www.npmjs.com/package/monaco-vim. It only adds keybindings for monaco editor. We will check, thanks.

**Comment by ilyar** [comment]
I checked monaco-vim https://monaco-vim.ilyar.repl.co/ it is ok, but in codebattle editor not same

**Comment by ReDBrother** [comment]
https://github.com/hexlet-codebattle/codebattle/blob/140e5a15833b3a05934be2eb28da59e3ca745bcb/services/app/assets/js/widgets/containers/Editor.jsx#L66

**Comment by ReDBrother** [comment]
Maybe some keybindings are being replaced by custom rules in Editor.jsx

**Comment by vtm9** [comment]
Using vim mode all the time, didn't have any problems.

**Comment by vtm9** [comment]
cannot reproduce

**Comment by Layerex** [comment]
> I checked monaco-vim https://monaco-vim.ilyar.repl.co/ it is ok, but in codebattle editor not same

Same. In codebattle vim mode doesn't work, but it does work in https://monaco-vim.ilyar.repl.co/.

Browser: Chromium 102.

**Comment by vtm9** [comment]
Yeah, it doesn't work
