### ISSUE TITLE
Клан-тэги

### ISSUE THREAD

**Issue by ReDBrother** [hexlet-codebattle/codebattle#995]
Сделать аналог кланов в codewars. Добавить новую позицию в пользовательских настройках, чуть подкорректировать базу пользователей, отобразить тег в играх (добавить новый тип игрока "clanmate" в стейт машину, отвечающую за редактор) и на странице со статистикой игрока.

**Comment by nikkstchv** [comment]
Привет, эта ишью актуальна?

**Comment by ReDBrother** [comment]
Да конечно))

**Comment by Guryanov-Maksim** [comment]
Всем привет! Этой ишью кто-нибудь занимается сейчас?

**Comment by vtm9** [comment]
done
