### ISSUE TITLE
Неожиданное поведение кнопки Create game 

### ISSUE THREAD

**Issue by Melodyn** [hexlet-codebattle/codebattle#999]
При переключении на вкладку Tournaments я ожидал, что кнопка Create game создаст турнир, а она создала парную игру в лобби. При этом кнопка создания турнира выглядит просто как текст, поэтому пришлось плотно подумать как создать турнир.
![image](https://user-images.githubusercontent.com/26752238/114823227-e1f84c00-9dcb-11eb-9d09-cd3f503098c5.png)

Варианты решения:
1. При переключении по вкладкам менять Create game/Create tournament
2. Убрать общую кнопку из хэдера, сделать на каждой вкладке свою кнопку

**Comment by vtm9** [comment]
Да, думаю мы просто уберем кнопку  Create Game, кнопку созания турнира тое подумаем как сделать лучше.

**Comment by vtm9** [comment]
думаю что надо переделать UI, но этот уже не актуален, пока закрою Ишуе, стобы никого не смущать
